const g_Generation8 = Generation(
"====[[Generation VIII]]====",
GAMECOMBO_SWSH_BDSP,
//UniversalTMs https://bulbapedia.bulbagarden.net/w/index.php?search=%22Every+Pok%C3%A9mon+can+learn+this+move+by%22&title=Special%3ASearch&go=Go
[
"Attract",
"Endure",
"Facade",
"Protect",
"Rest",
"Round",
"Sleep Talk",
"Snore"
],
//MonData https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_breeding_attributes https://bulbapedia.bulbagarden.net/wiki/List_of_cross-generational_evolutionary_lines
[
SpeciesInfo("Bulbasaur", "Monster", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Ivysaur", "Monster", "Grass", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Venusaur", "Monster", "Grass", GR_TYPICAL, [], -2, []),
SpeciesInfo("Charmander", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Charmeleon", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Charizard", "Monster", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Squirtle", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Wartortle", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Blastoise", "Monster", "Water 1", GR_TYPICAL, [], -2, []),
SpeciesInfo("Caterpie", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Metapod", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Butterfree", "Bug", "Bug", GR_TYPICAL, [], -2, []),
SpeciesInfo("Pichu", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Pikachu", "Field", "Fairy", GR_TYPICAL, [EvolveData(1, KantonianRaichu)], -1, []),//do not add the evolve for alolan raichu here. you can't evolve a pikachu into alolan raichu in galar.
SpeciesInfo("Raichu", "Field", "Fairy", GR_TYPICAL, [], -2, [KantonianRaichu, AlolanRaichu]),
SpeciesInfo("Sandshrew", "Field", "Field", GR_TYPICAL, [EvolveData(1, KantonianSandslash, KantonianSandshrew), EvolveData(1, AlolanSandslash, AlolanSandshrew)], 0, [KantonianSandshrew, AlolanSandshrew]),
SpeciesInfo("Sandslash", "Field", "Field", GR_TYPICAL, [], -1, [KantonianSandslash, AlolanSandslash]),
SpeciesInfo("Nidoran F", "Monster", "Field", GR_FEMALE_ONLY, [EvolveData(1)], 0, []),
SpeciesInfo("Nidorina", "NED", "NED", GR_FEMALE_ONLY, [EvolveData(1)], -1, []),
SpeciesInfo("Nidoqueen", "NED", "NED", GR_FEMALE_ONLY, [], -2, []),
SpeciesInfo("Nidoran M", "Monster", "Field", GR_MALE_ONLY, [EvolveData(1)], 0, []),
SpeciesInfo("Nidorino", "Monster", "Field", GR_MALE_ONLY, [EvolveData(1)], -1, []),
SpeciesInfo("Nidoking", "Monster", "Field", GR_MALE_ONLY, [], -2, []),
SpeciesInfo("Cleffa", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Clefairy", "Fairy", "Fairy", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Clefable", "Fairy", "Fairy", GR_TYPICAL, [], -2, []),
SpeciesInfo("Vulpix", "Field", "Field", GR_TYPICAL, [EvolveData(1, KantonianNinetales, KantonianVulpix), EvolveData(1, AlolanNinetales, AlolanVulpix)], 0, [KantonianVulpix, AlolanVulpix]),
SpeciesInfo("Ninetales", "Field", "Field", GR_TYPICAL, [], -1, [KantonianNinetales, AlolanNinetales]),
SpeciesInfo("Igglybuff", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Jigglypuff", "Fairy", "Fairy", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Wigglytuff", "Fairy", "Fairy", GR_TYPICAL, [], -2, []),
SpeciesInfo("Zubat", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Golbat", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Crobat", "Flying", "Flying", GR_TYPICAL, [], -2, []),
SpeciesInfo("Oddish", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Gloom", "Grass", "Grass", GR_TYPICAL, [EvolveData(1), EvolveData(2)], -1, []),
SpeciesInfo("Vileplume", "Grass", "Grass", GR_TYPICAL, [], -2, []),
SpeciesInfo("Bellossom", "Grass", "Grass", GR_TYPICAL, [], -3, []),
SpeciesInfo("Diglett", "Field", "Field", GR_TYPICAL, [EvolveData(1, KantonianDugtrio, KantonianDiglett), EvolveData(1, AlolanDugtrio, AlolanDiglett)], 0, [KantonianDiglett, AlolanDiglett]),
SpeciesInfo("Dugtrio", "Field", "Field", GR_TYPICAL, [], -1, [KantonianDugtrio, AlolanDugtrio]),
SpeciesInfo("Meowth", "Field", "Field", GR_TYPICAL, [EvolveData(1, KantonianPersian, KantonianMeowth), EvolveData(1, AlolanPersian, AlolanMeowth), EvolveData(2, null, GalarianMeowth)], 0, [KantonianMeowth, AlolanMeowth, GalarianMeowth]),
SpeciesInfo("Persian", "Field", "Field", GR_TYPICAL, [], -1, [KantonianPersian, AlolanPersian]),
SpeciesInfo("Perrserker", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Psyduck", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Golduck", "Water 1", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Growlithe", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Arcanine", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Poliwag", "Water 1", "Water 1", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Poliwhirl", "Water 1", "Water 1", GR_TYPICAL, [EvolveData(1), EvolveData(2)], -1, []),
SpeciesInfo("Poliwrath", "Water 1", "Water 1", GR_TYPICAL, [], -2, []),
SpeciesInfo("Politoed", "Water 1", "Water 1", GR_TYPICAL, [], -3, []),
SpeciesInfo("Abra", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Kadabra", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Alakazam", "Human-Like", "Human-Like", GR_TYPICAL, [], -2, []),
SpeciesInfo("Machop", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Machoke", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Machamp", "Human-Like", "Human-Like", GR_TYPICAL, [], -2, []),
SpeciesInfo("Tentacool", "Water 3", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Tentacruel", "Water 3", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Ponyta", "Field", "Field", GR_TYPICAL, [EvolveData(1, KantonianRapidash, KantonianPonyta), EvolveData(1, GalarianRapidash, GalarianPonyta)], 0, [KantonianPonyta, GalarianPonyta]),
SpeciesInfo("Rapidash", "Field", "Field", GR_TYPICAL, [], -1, [KantonianRapidash, GalarianRapidash]),
SpeciesInfo("Slowpoke", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1, KantonianSlowbro, KantonianSlowpoke), EvolveData(1, GalarianSlowbro, GalarianSlowpoke), EvolveData(1, JohtonianSlowking, KantonianSlowpoke), EvolveData(1, GalarianSlowking, GalarianSlowpoke)], 0, [KantonianSlowpoke, GalarianSlowpoke]),
SpeciesInfo("Slowbro", "Monster", "Water 1", GR_TYPICAL, [], -1, [KantonianSlowbro, GalarianSlowbro]),
SpeciesInfo("Slowking", "Monster", "Water 1", GR_TYPICAL, [], -2, [JohtonianSlowking, GalarianSlowking]),
SpeciesInfo("Magnemite", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Magneton", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], -1, []),
SpeciesInfo("Magnezone", "Mineral", "Mineral", GR_UNKNOWN, [], -2, []),
SpeciesInfo("Farfetch'd", "Flying", "Field", GR_TYPICAL, [EvolveData(1, null, GalarianFarfetchd)], 0, [KantonianFarfetchd, GalarianFarfetchd]),
SpeciesInfo("Sirfetch'd", "Flying", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Shellder", "Water 3", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Cloyster", "Water 3", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Gastly", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Haunter", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Gengar", "Amorphous", "Amorphous", GR_TYPICAL, [], -2, []),
SpeciesInfo("Onix", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Steelix", "Mineral", "Mineral", GR_TYPICAL, [], -1, []),
SpeciesInfo("Krabby", "Water 3", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Kingler", "Water 3", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Exeggcute", "Grass", "Grass", GR_TYPICAL, [EvolveData(1, KantonianExeggutor)], 0, []),
SpeciesInfo("Exeggutor", "Grass", "Grass", GR_TYPICAL, [], -1, [KantonianExeggutor, AlolanExeggutor]),
SpeciesInfo("Cubone", "Monster", "Monster", GR_TYPICAL, [EvolveData(1, KantonianMarowak)], 0, []),
SpeciesInfo("Marowak", "Monster", "Monster", GR_TYPICAL, [], -1, [KantonianMarowak, AlolanMarowak]),
SpeciesInfo("Tyrogue", "NED", "NED", GR_MALE_ONLY, [EvolveData(1), EvolveData(2), EvolveData(3)], 0, []),
SpeciesInfo("Hitmonlee", "Human-Like", "Human-Like", GR_MALE_ONLY, [], -1, []),
SpeciesInfo("Hitmonchan", "Human-Like", "Human-Like", GR_MALE_ONLY, [], -2, []),
SpeciesInfo("Hitmontop", "Human-Like", "Human-Like", GR_MALE_ONLY, [], -3, []),
SpeciesInfo("Lickitung", "Monster", "Monster", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Lickilicky", "Monster", "Monster", GR_TYPICAL, [], -1, []),
SpeciesInfo("Koffing", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1, KantonianWeezing), EvolveData(1, GalarianWeezing)], 0, []),
SpeciesInfo("Weezing", "Amorphous", "Amorphous", GR_TYPICAL, [], -1, [KantonianWeezing, GalarianWeezing]),
SpeciesInfo("Rhyhorn", "Monster", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Rhydon", "Monster", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Rhyperior", "Monster", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Happiny", "NED", "NED", GR_FEMALE_ONLY, [EvolveData(1)], 0, []),
SpeciesInfo("Chansey", "Fairy", "Fairy", GR_FEMALE_ONLY, [EvolveData(1)], -1, []),
SpeciesInfo("Blissey", "Fairy", "Fairy", GR_FEMALE_ONLY, [], -2, []),
SpeciesInfo("Tangela", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Tangrowth", "Grass", "Grass", GR_TYPICAL, [], -1, []),
SpeciesInfo("Kangaskhan", "Monster", "Monster", GR_FEMALE_ONLY, [], 0, []),
SpeciesInfo("Horsea", "Water 1", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Seadra", "Water 1", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Kingdra", "Water 1", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Goldeen", "Water 2", "Water 2", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Seaking", "Water 2", "Water 2", GR_TYPICAL, [], -1, []),
SpeciesInfo("Staryu", "Water 3", "Water 3", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Starmie", "Water 3", "Water 3", GR_UNKNOWN, [], -1, []),
SpeciesInfo("Mime Jr.", "NED", "NED", GR_TYPICAL, [EvolveData(1, KantonianMrMime), EvolveData(1, GalarianMrMime)], 0, []),
SpeciesInfo("Mr. Mime", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1, null, GalarianMrMime)], 0, [KantonianMrMime, GalarianMrMime]),
SpeciesInfo("Mr. Rime", "Human-Like", "Human-Like", GR_TYPICAL, [], -1, []),
SpeciesInfo("Scyther", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Scizor", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Smoochum", "NED", "NED", GR_FEMALE_ONLY, [EvolveData(1)], 0, []),
SpeciesInfo("Jynx", "Human-Like", "Human-Like", GR_FEMALE_ONLY, [], -1, []),
SpeciesInfo("Elekid", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Electabuzz", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Electivire", "Human-Like", "Human-Like", GR_TYPICAL, [], -2, []),
SpeciesInfo("Magby", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Magmar", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Magmortar", "Human-Like", "Human-Like", GR_TYPICAL, [], -2, []),
SpeciesInfo("Pinsir", "Bug", "Bug", GR_TYPICAL, [], 0, []),
SpeciesInfo("Tauros", "Field", "Field", GR_MALE_ONLY, [], 0, []),
SpeciesInfo("Magikarp", "Water 2", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Gyarados", "Water 2", "Dragon", GR_TYPICAL, [], -1, []),
SpeciesInfo("Lapras", "Monster", "Water 1", GR_TYPICAL, [], 0, []),
SpeciesInfo("Ditto", "Ditto", "Ditto", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Eevee", "Field", "Field", GR_TYPICAL, [EvolveData(1), EvolveData(2), EvolveData(3), EvolveData(4), EvolveData(5), EvolveData(6), EvolveData(7), EvolveData(8)], 0, []),
SpeciesInfo("Vaporeon", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Jolteon", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Flareon", "Field", "Field", GR_TYPICAL, [], -3, []),
SpeciesInfo("Espeon", "Field", "Field", GR_TYPICAL, [], -4, []),
SpeciesInfo("Umbreon", "Field", "Field", GR_TYPICAL, [], -5, []),
SpeciesInfo("Leafeon", "Field", "Field", GR_TYPICAL, [], -6, []),
SpeciesInfo("Glaceon", "Field", "Field", GR_TYPICAL, [], -7, []),
SpeciesInfo("Sylveon", "Field", "Field", GR_TYPICAL, [], -8, []),
SpeciesInfo("Porygon", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Porygon2", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], -1, []),
SpeciesInfo("Porygon-Z", "Mineral", "Mineral", GR_UNKNOWN, [], -2, []),
SpeciesInfo("Omanyte", "Water 1", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Omastar", "Water 1", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Kabuto", "Water 1", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Kabutops", "Water 1", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Aerodactyl", "Flying", "Flying", GR_TYPICAL, [], 0, []),
SpeciesInfo("Munchlax", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Snorlax", "Monster", "Monster", GR_TYPICAL, [], -1, []),
SpeciesInfo("Articuno", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Zapdos", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Moltres", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Dratini", "Water 1", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Dragonair", "Water 1", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Dragonite", "Water 1", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Mewtwo", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Mew", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Hoothoot", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Noctowl", "Flying", "Flying", GR_TYPICAL, [], -1, []),
SpeciesInfo("Chinchou", "Water 2", "Water 2", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Lanturn", "Water 2", "Water 2", GR_TYPICAL, [], -1, []),
SpeciesInfo("Togepi", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Togetic", "Flying", "Fairy", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Togekiss", "Flying", "Fairy", GR_TYPICAL, [], -2, []),
SpeciesInfo("Natu", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Xatu", "Flying", "Flying", GR_TYPICAL, [], -1, []),
SpeciesInfo("Azurill", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Marill", "Water 1", "Fairy", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Azumarill", "Water 1", "Fairy", GR_TYPICAL, [], -2, []),
SpeciesInfo("Bonsly", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Sudowoodo", "Mineral", "Mineral", GR_TYPICAL, [], -1, []),
SpeciesInfo("Wooper", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Quagsire", "Water 1", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Wynaut", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Wobbuffet", "Amorphous", "Amorphous", GR_TYPICAL, [], -1, []),
SpeciesInfo("Dunsparce", "Field", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Qwilfish", "Water 2", "Water 2", GR_TYPICAL, [], 0, []),
SpeciesInfo("Shuckle", "Bug", "Bug", GR_TYPICAL, [], 0, []),
SpeciesInfo("Heracross", "Bug", "Bug", GR_TYPICAL, [], 0, []),
SpeciesInfo("Sneasel", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Weavile", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Swinub", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Piloswine", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Mamoswine", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Corsola", "Water 1", "Water 3", GR_TYPICAL, [EvolveData(1, null, GalarianCorsola)], 0, [KantonianCorsola, GalarianCorsola]),
SpeciesInfo("Cursola", "Water 1", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Remoraid", "Water 1", "Water 2", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Octillery", "Water 1", "Water 2", GR_TYPICAL, [], -1, []),
SpeciesInfo("Delibird", "Water 1", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Mantyke", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Mantine", "Water 1", "Water 1", GR_TYPICAL, [], -1, []),
SpeciesInfo("Skarmory", "Flying", "Flying", GR_TYPICAL, [], 0, []),
SpeciesInfo("Miltank", "Field", "Field", GR_FEMALE_ONLY, [], 0, []),
SpeciesInfo("Raikou", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Entei", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Suicune", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Larvitar", "Monster", "Monster", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Pupitar", "Monster", "Monster", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Tyranitar", "Monster", "Monster", GR_TYPICAL, [], -2, []),
SpeciesInfo("Lugia", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Ho-Oh", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Celebi", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Treecko", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Grovyle", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Sceptile", "Monster", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Torchic", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Combusken", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Blaziken", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Mudkip", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Marshtomp", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Swampert", "Monster", "Water 1", GR_TYPICAL, [], -2, []),
SpeciesInfo("Zigzagoon", "Field", "Field", GR_TYPICAL, [EvolveData(1, HoennianLinoone, HoennianZigzagoon), EvolveData(1, GalarianLinoone, GalarianZigzagoon)], 0, [HoennianZigzagoon, GalarianZigzagoon]),
SpeciesInfo("Linoone", "Field", "Field", GR_TYPICAL, [EvolveData(1, null, GalarianLinoone)], -1, [HoennianLinoone, GalarianLinoone]),
SpeciesInfo("Obstagoon", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Lotad", "Water 1", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Lombre", "Water 1", "Grass", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Ludicolo", "Water 1", "Grass", GR_TYPICAL, [], -2, []),
SpeciesInfo("Seedot", "Field", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Nuzleaf", "Field", "Grass", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Shiftry", "Field", "Grass", GR_TYPICAL, [], -2, []),
SpeciesInfo("Wingull", "Water 1", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Pelipper", "Water 1", "Flying", GR_TYPICAL, [], -1, []),
SpeciesInfo("Ralts", "Human-Like", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Kirlia", "Human-Like", "Amorphous", GR_MALE_ONLY, [EvolveData(1), EvolveData(2)], -1, []),
SpeciesInfo("Gardevoir", "Human-Like", "Amorphous", GR_TYPICAL, [], -2, []),
SpeciesInfo("Gallade", "Human-Like", "Amorphous", GR_MALE_ONLY, [], -3, []),
SpeciesInfo("Nincada", "Bug", "Bug", GR_UNKNOWN, [EvolveData(1), EvolveData(2)], 0, []),
SpeciesInfo("Ninjask", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Shedinja", "Bug", "Bug", GR_UNKNOWN, [], -2, []),
SpeciesInfo("Whismur", "Monster", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Loudred", "Monster", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Exploud", "Monster", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Sableye", "Human-Like", "Human-Like", GR_TYPICAL, [], 0, []),
SpeciesInfo("Mawile", "Field", "Fairy", GR_TYPICAL, [], 0, []),
SpeciesInfo("Aron", "Monster", "Monster", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Lairon", "Monster", "Monster", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Aggron", "Monster", "Monster", GR_TYPICAL, [], -2, []),
SpeciesInfo("Electrike", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Manectric", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Budew", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Roselia", "Fairy", "Grass", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Roserade", "Fairy", "Grass", GR_TYPICAL, [], -2, []),
SpeciesInfo("Carvanha", "Water 2", "Water 2", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Sharpedo", "Water 2", "Water 2", GR_TYPICAL, [], -1, []),
SpeciesInfo("Wailmer", "Field", "Water 2", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Wailord", "Field", "Water 2", GR_TYPICAL, [], -1, []),
SpeciesInfo("Torkoal", "Field", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Trapinch", "Bug", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Vibrava", "Bug", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Flygon", "Bug", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Swablu", "Flying", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Altaria", "Flying", "Dragon", GR_TYPICAL, [], -1, []),
SpeciesInfo("Lunatone", "Mineral", "Mineral", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Solrock", "Mineral", "Mineral", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Barboach", "Water 2", "Water 2", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Whiscash", "Water 2", "Water 2", GR_TYPICAL, [], -1, []),
SpeciesInfo("Corphish", "Water 1", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Crawdaunt", "Water 1", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Baltoy", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Claydol", "Mineral", "Mineral", GR_UNKNOWN, [], -1, []),
SpeciesInfo("Lileep", "Water 3", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Cradily", "Water 3", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Anorith", "Water 3", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Armaldo", "Water 3", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Feebas", "Water 1", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Milotic", "Water 1", "Dragon", GR_TYPICAL, [], -1, []),
SpeciesInfo("Duskull", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Dusclops", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Dusknoir", "Amorphous", "Amorphous", GR_TYPICAL, [], -2, []),
SpeciesInfo("Absol", "Field", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Snorunt", "Fairy", "Mineral", GR_TYPICAL, [EvolveData(1), EvolveData(2)], 0, []),
SpeciesInfo("Glalie", "Fairy", "Mineral", GR_TYPICAL, [], -1, []),
SpeciesInfo("Froslass", "Fairy", "Mineral", GR_FEMALE_ONLY, [], -2, []),
SpeciesInfo("Spheal", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Sealeo", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Walrein", "Water 1", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Relicanth", "Water 1", "Water 2", GR_TYPICAL, [], 0, []),
SpeciesInfo("Bagon", "Dragon", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Shelgon", "Dragon", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Salamence", "Dragon", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Beldum", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Metang", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], -1, []),
SpeciesInfo("Metagross", "Mineral", "Mineral", GR_UNKNOWN, [], -2, []),
SpeciesInfo("Regirock", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Regice", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Registeel", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Latias", "NED", "NED", GR_FEMALE_ONLY, [], 0, []),
SpeciesInfo("Latios", "NED", "NED", GR_MALE_ONLY, [], 0, []),
SpeciesInfo("Kyogre", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Groudon", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Rayquaza", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Jirachi", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Shinx", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Luxio", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Luxray", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Combee", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Vespiquen", "Bug", "Bug", GR_FEMALE_ONLY, [], -1, []),
SpeciesInfo("Cherubi", "Fairy", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Cherrim", "Fairy", "Grass", GR_TYPICAL, [], -1, []),
SpeciesInfo("Shellos", "Water 1", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Gastrodon", "Water 1", "Amorphous", GR_TYPICAL, [], -1, []),
SpeciesInfo("Drifloon", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Drifblim", "Amorphous", "Amorphous", GR_TYPICAL, [], -1, []),
SpeciesInfo("Buneary", "Field", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Lopunny", "Field", "Human-Like", GR_TYPICAL, [], -1, []),
SpeciesInfo("Stunky", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Skuntank", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Bronzor", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Bronzong", "Mineral", "Mineral", GR_UNKNOWN, [], -1, []),
SpeciesInfo("Spiritomb", "Amorphous", "Amorphous", GR_TYPICAL, [], 0, []),
SpeciesInfo("Gible", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Gabite", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Garchomp", "Monster", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Riolu", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Lucario", "Field", "Human-Like", GR_TYPICAL, [], -1, []),
SpeciesInfo("Hippopotas", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Hippowdon", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Skorupi", "Bug", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Drapion", "Bug", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Croagunk", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Toxicroak", "Human-Like", "Human-Like", GR_TYPICAL, [], 0, []),
SpeciesInfo("Snover", "Monster", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Abomasnow", "Monster", "Grass", GR_TYPICAL, [], -1, []),
SpeciesInfo("Rotom", "Amorphous", "Amorphous", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Uxie", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Mesprit", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Azelf", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Dialga", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Palkia", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Heatran", "NED", "NED", GR_TYPICAL, [], 0, []),
SpeciesInfo("Regigigas", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Giratina", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Cresselia", "NED", "NED", GR_FEMALE_ONLY, [], 0, []),
SpeciesInfo("Victini", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Lillipup", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Herdier", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Stoutland", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Purrloin", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Liepard", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Munna", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Musharna", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Pidove", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Tranquill", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Unfezant", "Flying", "Flying", GR_TYPICAL, [], -2, []),
SpeciesInfo("Roggenrola", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Boldore", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Gigalith", "Mineral", "Mineral", GR_TYPICAL, [], -2, []),
SpeciesInfo("Woobat", "Field", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Swoobat", "Field", "Flying", GR_TYPICAL, [], -1, []),
SpeciesInfo("Drilbur", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Excadrill", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Audino", "Fairy", "Fairy", GR_TYPICAL, [], 0, []),
SpeciesInfo("Timburr", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Gurdurr", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Conkeldurr", "Human-Like", "Human-Like", GR_TYPICAL, [], -2, []),
SpeciesInfo("Tympole", "Water 1", "Water 1", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Palpitoad", "Water 1", "Water 1", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Seismitoad", "Water 1", "Water 1", GR_TYPICAL, [], -2, []),
SpeciesInfo("Throh", "Human-Like", "Human-Like", GR_MALE_ONLY, [], 0, []),
SpeciesInfo("Sawk", "Human-Like", "Human-Like", GR_MALE_ONLY, [], 0, []),
SpeciesInfo("Venipede", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Whirlipede", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Scolipede", "Bug", "Bug", GR_TYPICAL, [], -2, []),
SpeciesInfo("Cottonee", "Grass", "Fairy", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Whimsicott", "Grass", "Fairy", GR_FEMALE_ONLY, [], -1, []),
SpeciesInfo("Petilil", "Grass", "Grass", GR_FEMALE_ONLY, [EvolveData(1)], 0, []),
SpeciesInfo("Lilligant", "Grass", "Grass", GR_FEMALE_ONLY, [], -1, []),
SpeciesInfo("Basculin", "Water 2", "Water 2", GR_TYPICAL, [], 0, []),
SpeciesInfo("Sandile", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Krokorok", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Krookodile", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Darumaka", "Field", "Field", GR_TYPICAL, [EvolveData(1, UnovanDarmanitan, UnovanDarumaka), EvolveData(1, GalarianDarmanitan, GalarianDarumaka)], 0, [UnovanDarumaka, GalarianDarumaka]),
SpeciesInfo("Darmanitan", "Field", "Field", GR_TYPICAL, [], -1, [UnovanDarmanitan, GalarianDarmanitan]),
SpeciesInfo("Maractus", "Grass", "Grass", GR_TYPICAL, [], 0, []),
SpeciesInfo("Dwebble", "Bug", "Mineral", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Crustle", "Bug", "Mineral", GR_TYPICAL, [], -1, []),
SpeciesInfo("Scraggy", "Field", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Scrafty", "Field", "Dragon", GR_TYPICAL, [], -1, []),
SpeciesInfo("Sigilyph", "Flying", "Flying", GR_TYPICAL, [], 0, []),
SpeciesInfo("Yamask", "Mineral", "Amorphous", GR_TYPICAL, [EvolveData(1, null, UnovanYamask), EvolveData(2, null, GalarianYamask)], 0, [UnovanYamask, GalarianYamask]),
SpeciesInfo("Cofagrigus", "Mineral", "Amorphous", GR_TYPICAL, [], -1, []),
SpeciesInfo("Runerigus", "Mineral", "Amorphous", GR_TYPICAL, [], -2, []),
SpeciesInfo("Tirtouga", "Water 1", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Carracosta", "Water 1", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Archen", "Flying", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Archeops", "Flying", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Trubbish", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Garbodor", "Mineral", "Mineral", GR_TYPICAL, [], -1, []),
SpeciesInfo("Zorua", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Zoroark", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Minccino", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Cinccino", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Gothita", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Gothorita", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Gothitelle", "Human-Like", "Human-Like", GR_TYPICAL, [], -2, []),
SpeciesInfo("Solosis", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Duosion", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Reuniclus", "Amorphous", "Amorphous", GR_TYPICAL, [], -2, []),
SpeciesInfo("Vanillite", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Vanillish", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Vanilluxe", "Mineral", "Mineral", GR_TYPICAL, [], -2, []),
SpeciesInfo("Emolga", "Field", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Karrablast", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Escavalier", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Foongus", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Amoonguss", "Grass", "Grass", GR_TYPICAL, [], -1, []),
SpeciesInfo("Frillish", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Jellicent", "Amorphous", "Amorphous", GR_TYPICAL, [], -1, []),
SpeciesInfo("Joltik", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Galvantula", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Ferroseed", "Grass", "Mineral", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Ferrothorn", "Grass", "Mineral", GR_TYPICAL, [], -1, []),
SpeciesInfo("Klink", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Klang", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], -1, []),
SpeciesInfo("Klinklang", "Mineral", "Mineral", GR_UNKNOWN, [], -2, []),
SpeciesInfo("Elgyem", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Beheeyem", "Human-Like", "Human-Like", GR_TYPICAL, [], -1, []),
SpeciesInfo("Litwick", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Lampent", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Chandelure", "Amorphous", "Amorphous", GR_TYPICAL, [], -2, []),
SpeciesInfo("Axew", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Fraxure", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Haxorus", "Monster", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Cubchoo", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Beartic", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Cryogonal", "Mineral", "Mineral", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Shelmet", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Accelgor", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Stunfisk", "Water 1", "Amorphous", GR_TYPICAL, [], 0, [UnovanStunfisk, GalarianStunfisk]),
SpeciesInfo("Mienfoo", "Field", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Mienshao", "Field", "Human-Like", GR_TYPICAL, [], -1, []),
SpeciesInfo("Druddigon", "Dragon", "Monster", GR_TYPICAL, [], 0, []),
SpeciesInfo("Golett", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Golurk", "Mineral", "Mineral", GR_UNKNOWN, [], -1, []),
SpeciesInfo("Pawniard", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Bisharp", "Human-Like", "Human-Like", GR_TYPICAL, [], -1, []),
SpeciesInfo("Bouffalant", "Field", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Rufflet", "Flying", "Flying", GR_MALE_ONLY, [EvolveData(1)], 0, []),
SpeciesInfo("Braviary", "Flying", "Flying", GR_MALE_ONLY, [], -1, []),
SpeciesInfo("Vullaby", "Flying", "Flying", GR_FEMALE_ONLY, [EvolveData(1)], 0, []),
SpeciesInfo("Mandibuzz", "Flying", "Flying", GR_FEMALE_ONLY, [], -1, []),
SpeciesInfo("Heatmor", "Field", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Durant", "Bug", "Bug", GR_TYPICAL, [], 0, []),
SpeciesInfo("Deino", "Dragon", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Zweilous", "Dragon", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Hydreigon", "Dragon", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Larvesta", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Volcarona", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Cobalion", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Terrakion", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Virizion", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Tornadus", "NED", "NED", GR_MALE_ONLY, [], 0, []),
SpeciesInfo("Thundurus", "NED", "NED", GR_MALE_ONLY, [], 0, []),
SpeciesInfo("Reshiram", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Zekrom", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Landorus", "NED", "NED", GR_MALE_ONLY, [], 0, []),
SpeciesInfo("Kyurem", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Keldeo", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Genesect", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Bunnelby", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Diggersby", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Fletchling", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Fletchinder", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Talonflame", "Flying", "Flying", GR_TYPICAL, [], -2, []),
SpeciesInfo("Pancham", "Field", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Pangoro", "Field", "Human-Like", GR_TYPICAL, [], -1, []),
SpeciesInfo("Espurr", "Field", "Field", GR_TYPICAL, [EvolveData(1, MaleMeowstic), EvolveData(1, FemaleMeowstic)], 0, []),
SpeciesInfo("Meowstic", "Field", "Field", GR_TYPICAL, [], -1, [MaleMeowstic, FemaleMeowstic]),
SpeciesInfo("Honedge", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Doublade", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Aegislash", "Mineral", "Mineral", GR_TYPICAL, [], -2, []),
SpeciesInfo("Spritzee", "Fairy", "Fairy", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Aromatisse", "Fairy", "Fairy", GR_TYPICAL, [], -1, []),
SpeciesInfo("Swirlix", "Fairy", "Fairy", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Slurpuff", "Fairy", "Fairy", GR_TYPICAL, [], -1, []),
SpeciesInfo("Inkay", "Water 1", "Water 2", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Malamar", "Water 1", "Water 2", GR_TYPICAL, [], -1, []),
SpeciesInfo("Binacle", "Water 3", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Barbaracle", "Water 3", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Skrelp", "Water 1", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Dragalge", "Water 1", "Dragon", GR_TYPICAL, [], -1, []),
SpeciesInfo("Clauncher", "Water 1", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Clawitzer", "Water 1", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Helioptile", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Heliolisk", "Monster", "Dragon", GR_TYPICAL, [], -1, []),
SpeciesInfo("Tyrunt", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Tyrantrum", "Monster", "Dragon", GR_TYPICAL, [], -1, []),
SpeciesInfo("Amaura", "Monster", "Monster", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Aurorus", "Monster", "Monster", GR_TYPICAL, [], -1, []),
SpeciesInfo("Hawlucha", "Flying", "Human-Like", GR_TYPICAL, [], 0, []),
SpeciesInfo("Dedenne", "Field", "Fairy", GR_TYPICAL, [], 0, []),
SpeciesInfo("Carbink", "Fairy", "Mineral", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Goomy", "Dragon", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Sliggoo", "Dragon", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Goodra", "Dragon", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Klefki", "Mineral", "Mineral", GR_TYPICAL, [], 0, []),
SpeciesInfo("Phantump", "Grass", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Trevenant", "Grass", "Amorphous", GR_TYPICAL, [], -1, []),
SpeciesInfo("Pumpkaboo", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Gourgeist", "Amorphous", "Amorphous", GR_TYPICAL, [], -1, []),
SpeciesInfo("Bergmite", "Monster", "Mineral", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Avalugg", "Monster", "Mineral", GR_TYPICAL, [], -1, []),
SpeciesInfo("Noibat", "Flying", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Noivern", "Flying", "Dragon", GR_TYPICAL, [], -1, []),
SpeciesInfo("Xerneas", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Yveltal", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Zygarde", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Diancie", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Volcanion", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Rowlet", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Dartrix", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Decidueye", "Flying", "Flying", GR_TYPICAL, [], -2, []),
SpeciesInfo("Litten", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Torracat", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Incineroar", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Popplio", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Brionne", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Primarina", "Water 1", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Grubbin", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Charjabug", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Vikavolt", "Bug", "Bug", GR_TYPICAL, [], -2, []),
SpeciesInfo("Cutiefly", "Bug", "Fairy", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Ribombee", "Bug", "Fairy", GR_TYPICAL, [], -1, []),
SpeciesInfo("Rockruff", "Field", "Field", GR_TYPICAL, [EvolveData(1, MiddayLycanroc), EvolveData(1, MidnightLycanroc), EvolveData(1, DuskLycanroc)], 0, []),
SpeciesInfo("Lycanroc", "Field", "Field", GR_TYPICAL, [], -1, [MiddayLycanroc, MidnightLycanroc, DuskLycanroc]),
SpeciesInfo("Wishiwashi", "Water 2", "Water 2", GR_TYPICAL, [], 0, []),
SpeciesInfo("Mareanie", "Water 1", "Water 1", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Toxapex", "Water 1", "Water 1", GR_TYPICAL, [], -1, []),
SpeciesInfo("Mudbray", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Mudsdale", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Dewpider", "Water 1", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Araquanid", "Water 1", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Fomantis", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Lurantis", "Grass", "Grass", GR_TYPICAL, [], -1, []),
SpeciesInfo("Morelull", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Shiinotic", "Grass", "Grass", GR_TYPICAL, [], -1, []),
SpeciesInfo("Salandit", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Salazzle", "Monster", "Dragon", GR_FEMALE_ONLY, [], -1, []),
SpeciesInfo("Stufful", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Bewear", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Bounsweet", "Grass", "Grass", GR_FEMALE_ONLY, [EvolveData(1)], 0, []),
SpeciesInfo("Steenee", "Grass", "Grass", GR_FEMALE_ONLY, [EvolveData(1)], -1, []),
SpeciesInfo("Tsareena", "Grass", "Grass", GR_FEMALE_ONLY, [], -2, []),
SpeciesInfo("Comfey", "Grass", "Grass", GR_TYPICAL, [], 0, []),
SpeciesInfo("Oranguru", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Passimian", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Wimpod", "Bug", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Golisopod", "Bug", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Sandygast", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Palossand", "Amorphous", "Amorphous", GR_TYPICAL, [], -1, []),
SpeciesInfo("Pyukumuku", "Water 1", "Water 1", GR_TYPICAL, [], 0, []),
SpeciesInfo("Type: Null", "NED", "NED", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Silvally", "NED", "NED", GR_UNKNOWN, [], -1, []),
SpeciesInfo("Turtonator", "Monster", "Dragon", GR_TYPICAL, [], 0, []),
SpeciesInfo("Togedemaru", "Field", "Fairy", GR_TYPICAL, [], 0, []),
SpeciesInfo("Mimikyu", "Amorphous", "Amorphous", GR_TYPICAL, [], 0, []),
SpeciesInfo("Drampa", "Monster", "Dragon", GR_TYPICAL, [], 0, []),
SpeciesInfo("Dhelmise", "Mineral", "Mineral", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Jangmo-o", "Dragon", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Hakamo-o", "Dragon", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Kommo-o", "Dragon", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Tapu Koko", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Tapu Lele", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Tapu Bulu", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Tapu Fini", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Cosmog", "NED", "NED", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Cosmoem", "NED", "NED", GR_UNKNOWN, [EvolveData(1), EvolveData(2)], -1, []),
SpeciesInfo("Solgaleo", "NED", "NED", GR_UNKNOWN, [], -2, []),
SpeciesInfo("Lunala", "NED", "NED", GR_UNKNOWN, [], -3, []),
SpeciesInfo("Nihilego", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Buzzwole", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Pheromosa", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Xurkitree", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Celesteela", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Kartana", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Guzzlord", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Necrozma", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Magearna", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Marshadow", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Poipole", "NED", "NED", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Naganadel", "NED", "NED", GR_UNKNOWN, [], -1, []),
SpeciesInfo("Stakataka", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Blacephalon", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Zeraora", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Meltan", "NED", "NED", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Melmetal", "NED", "NED", GR_UNKNOWN, [], -1, []),
SpeciesInfo("Grookey", "Field", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Thwackey", "Field", "Grass", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Rillaboom", "Field", "Grass", GR_TYPICAL, [], -2, []),
SpeciesInfo("Scorbunny", "Field", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Raboot", "Field", "Human-Like", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Cinderace", "Field", "Human-Like", GR_TYPICAL, [], -2, []),
SpeciesInfo("Sobble", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Drizzile", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Inteleon", "Water 1", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Skwovet", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Greedent", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Rookidee", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Corvisquire", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Corviknight", "Flying", "Flying", GR_TYPICAL, [], -2, []),
SpeciesInfo("Blipbug", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Dottler", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Orbeetle", "Bug", "Bug", GR_TYPICAL, [], -2, []),
SpeciesInfo("Nickit", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Thievul", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Gossifleur", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Eldegoss", "Grass", "Grass", GR_TYPICAL, [], -1, []),
SpeciesInfo("Wooloo", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Dubwool", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Chewtle", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Drednaw", "Monster", "Water 1", GR_TYPICAL, [], -1, []),
SpeciesInfo("Yamper", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Boltund", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Rolycoly", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Carkol", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Coalossal", "Mineral", "Mineral", GR_TYPICAL, [], -2, []),
SpeciesInfo("Applin", "Grass", "Dragon", GR_TYPICAL, [EvolveData(1), EvolveData(2)], 0, []),
SpeciesInfo("Flapple", "Grass", "Dragon", GR_TYPICAL, [], -1, []),
SpeciesInfo("Appletun", "Grass", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Silicobra", "Field", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Sandaconda", "Field", "Dragon", GR_TYPICAL, [], -1, []),
SpeciesInfo("Cramorant", "Water 1", "Flying", GR_TYPICAL, [], 0, []),
SpeciesInfo("Arrokuda", "Water 2", "Water 2", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Barraskewda", "Water 2", "Water 2", GR_TYPICAL, [], -1, []),
SpeciesInfo("Toxel", "NED", "NED", GR_TYPICAL, [EvolveData(1, AmpedToxtricity), EvolveData(1, LowKeyToxtricity)], 0, []),
SpeciesInfo("Toxtricity", "Human-Like", "Human-Like", GR_TYPICAL, [], -1, [AmpedToxtricity, LowKeyToxtricity]),
SpeciesInfo("Sizzlipede", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Centiskorch", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Clobbopus", "Water 1", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Grapploct", "Water 1", "Human-Like", GR_TYPICAL, [], -1, []),
SpeciesInfo("Sinistea", "Mineral", "Amorphous", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Polteageist", "Mineral", "Amorphous", GR_UNKNOWN, [], -1, []),
SpeciesInfo("Hatenna", "Fairy", "Fairy", GR_FEMALE_ONLY, [EvolveData(1)], 0, []),
SpeciesInfo("Hattrem", "Fairy", "Fairy", GR_FEMALE_ONLY, [EvolveData(1)], -1, []),
SpeciesInfo("Hatterene", "Fairy", "Fairy", GR_FEMALE_ONLY, [], -2, []),
SpeciesInfo("Impidimp", "Fairy", "Human-Like", GR_MALE_ONLY, [EvolveData(1)], 0, []),
SpeciesInfo("Morgrem", "Fairy", "Human-Like", GR_MALE_ONLY, [EvolveData(1)], -1, []),
SpeciesInfo("Grimmsnarl", "Fairy", "Human-Like", GR_MALE_ONLY, [], -2, []),
SpeciesInfo("Milcery", "Fairy", "Amorphous", GR_FEMALE_ONLY, [EvolveData(1)], 0, []),
SpeciesInfo("Alcremie", "Fairy", "Amorphous", GR_FEMALE_ONLY, [], -1, []),
SpeciesInfo("Falinks", "Fairy", "Mineral", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Pincurchin", "Water 1", "Amorphous", GR_TYPICAL, [], 0, []),
SpeciesInfo("Snom", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Frosmoth", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Stonjourner", "Mineral", "Mineral", GR_TYPICAL, [], 0, []),
SpeciesInfo("Eiscue", "Water 1", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Indeedee", "Fairy", "Fairy", GR_TYPICAL, [], 0, [MaleIndeedee, FemaleIndeedee]),
SpeciesInfo("Morpeko", "Field", "Fairy", GR_TYPICAL, [], 0, []),
SpeciesInfo("Cufant", "Field", "Mineral", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Copperajah", "Field", "Mineral", GR_TYPICAL, [], -1, []),
SpeciesInfo("Dracozolt", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Arctozolt", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Dracovish", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Arctovish", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Duraludon", "Mineral", "Dragon", GR_TYPICAL, [], 0, []),
SpeciesInfo("Dreepy", "Amorphous", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Drakloak", "Amorphous", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Dragapult", "Amorphous", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Zacian", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Zamazenta", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Eternatus", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Kubfu", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Urshifu", "NED", "NED", GR_TYPICAL, [], -1, []),
SpeciesInfo("Zarude", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Regieleki", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Regidrago", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Glastrier", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Spectrier", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Calyrex", "NED", "NED", GR_UNKNOWN, [], 0, [])
//SpeciesInfo("Enamorus", "NED", "NED", GR_FEMALE_ONLY, [], 0, []),//officially gen 8, but not in any relevant game until gen 9
]
);