const g_Generation8 = Generation(
"====[[Generation VIII]]====",
GAMECOMBO_SWSH_BDSP,
//UniversalTMs https://bulbapedia.bulbagarden.net/w/index.php?search=%22Every+Pok%C3%A9mon+can+learn+this+move+by%22&title=Special%3ASearch&go=Go
[
"Attract",
"Endure",
"Facade",
"Protect",
"Rest",
"Round",
"Sleep Talk",
"Snore"
],
//MonData https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_breeding_attributes https://bulbapedia.bulbagarden.net/wiki/List_of_cross-generational_evolutionary_lines
[
SpeciesInfo("Bulbasaur", "Monster", "Grass", GR_TYPICAL, ["Ivysaur"]),
SpeciesInfo("Ivysaur", "Monster", "Grass", GR_TYPICAL, ["Venusaur"]),
SpeciesInfo("Venusaur", "Monster", "Grass", GR_TYPICAL, []),
SpeciesInfo("Charmander", "Monster", "Dragon", GR_TYPICAL, ["Charmeleon"]),
SpeciesInfo("Charmeleon", "Monster", "Dragon", GR_TYPICAL, ["Charizard"]),
SpeciesInfo("Charizard", "Monster", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Squirtle", "Monster", "Water 1", GR_TYPICAL, ["Wartortle"]),
SpeciesInfo("Wartortle", "Monster", "Water 1", GR_TYPICAL, ["Blastoise"]),
SpeciesInfo("Blastoise", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Caterpie", "Bug", "Bug", GR_TYPICAL, ["Metapod"]),
SpeciesInfo("Metapod", "Bug", "Bug", GR_TYPICAL, ["Butterfree"]),
SpeciesInfo("Butterfree", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Pichu", "NED", "NED", GR_TYPICAL, ["Pikachu"]),
SpeciesInfo("Pikachu", "Field", "Fairy", GR_TYPICAL, ["Raichu"]),
SpeciesInfo("Raichu", "Field", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Sandshrew", "Field", "Field", GR_TYPICAL, ["Sandslash"]),
SpeciesInfo("Sandslash", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Nidoran F", "Monster", "Field", GR_FEMALE_ONLY, ["Nidorina"]),
SpeciesInfo("Nidorina", "NED", "NED", GR_FEMALE_ONLY, ["Nidoqueen"]),
SpeciesInfo("Nidoqueen", "NED", "NED", GR_FEMALE_ONLY, []),
SpeciesInfo("Nidoran M", "Monster", "Field", GR_MALE_ONLY, ["Nidorino"]),
SpeciesInfo("Nidorino", "Monster", "Field", GR_MALE_ONLY, ["Nidoking"]),
SpeciesInfo("Nidoking", "Monster", "Field", GR_MALE_ONLY, []),
SpeciesInfo("Cleffa", "NED", "NED", GR_TYPICAL, ["Clefairy"]),
SpeciesInfo("Clefairy", "Fairy", "Fairy", GR_TYPICAL, ["Clefable"]),
SpeciesInfo("Clefable", "Fairy", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Vulpix", "Field", "Field", GR_TYPICAL, ["Ninetales"]),
SpeciesInfo("Ninetales", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Igglybuff", "NED", "NED", GR_TYPICAL, ["Jigglypuff"]),
SpeciesInfo("Jigglypuff", "Fairy", "Fairy", GR_TYPICAL, ["Wigglytuff"]),
SpeciesInfo("Wigglytuff", "Fairy", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Zubat", "Flying", "Flying", GR_TYPICAL, ["Golbat"]),
SpeciesInfo("Golbat", "Flying", "Flying", GR_TYPICAL, ["Crobat"]),
SpeciesInfo("Crobat", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Oddish", "Grass", "Grass", GR_TYPICAL, ["Gloom"]),
SpeciesInfo("Gloom", "Grass", "Grass", GR_TYPICAL, ["Vileplume", "Bellossom"]),
SpeciesInfo("Vileplume", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Bellossom", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Diglett", "Field", "Field", GR_TYPICAL, ["Dugtrio"]),
SpeciesInfo("Dugtrio", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Meowth", "Field", "Field", GR_TYPICAL, ["Persian", "Perrserker"]),
SpeciesInfo("Persian", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Perrserker", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Psyduck", "Water 1", "Field", GR_TYPICAL, ["Golduck"]),
SpeciesInfo("Golduck", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Growlithe", "Field", "Field", GR_TYPICAL, ["Arcanine"]),
SpeciesInfo("Arcanine", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Poliwag", "Water 1", "Water 1", GR_TYPICAL, ["Poliwhirl"]),
SpeciesInfo("Poliwhirl", "Water 1", "Water 1", GR_TYPICAL, ["Poliwrath", "Politoed"]),
SpeciesInfo("Poliwrath", "Water 1", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Politoed", "Water 1", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Abra", "Human-Like", "Human-Like", GR_TYPICAL, ["Kadabra"]),
SpeciesInfo("Kadabra", "Human-Like", "Human-Like", GR_TYPICAL, ["Alakazam"]),
SpeciesInfo("Alakazam", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Machop", "Human-Like", "Human-Like", GR_TYPICAL, ["Machoke"]),
SpeciesInfo("Machoke", "Human-Like", "Human-Like", GR_TYPICAL, ["Machamp"]),
SpeciesInfo("Machamp", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Tentacool", "Water 3", "Water 3", GR_TYPICAL, ["Tentacruel"]),
SpeciesInfo("Tentacruel", "Water 3", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Ponyta", "Field", "Field", GR_TYPICAL, ["Rapidash"]),
SpeciesInfo("Rapidash", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Slowpoke", "Monster", "Water 1", GR_TYPICAL, ["Slowbro", "Slowking"]),
SpeciesInfo("Slowbro", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Slowking", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Magnemite", "Mineral", "Mineral", GR_UNKNOWN, ["Magneton"]),
SpeciesInfo("Magneton", "Mineral", "Mineral", GR_UNKNOWN, ["Magnezone"]),
SpeciesInfo("Magnezone", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Farfetch'd", "Flying", "Field", GR_TYPICAL, ["Sirfetch'd"]),
SpeciesInfo("Sirfetch'd", "Flying", "Field", GR_TYPICAL, []),
SpeciesInfo("Shellder", "Water 3", "Water 3", GR_TYPICAL, ["Cloyster"]),
SpeciesInfo("Cloyster", "Water 3", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Gastly", "Amorphous", "Amorphous", GR_TYPICAL, ["Haunter"]),
SpeciesInfo("Haunter", "Amorphous", "Amorphous", GR_TYPICAL, ["Gengar"]),
SpeciesInfo("Gengar", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Onix", "Mineral", "Mineral", GR_TYPICAL, ["Steelix"]),
SpeciesInfo("Steelix", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Krabby", "Water 3", "Water 3", GR_TYPICAL, ["Kingler"]),
SpeciesInfo("Kingler", "Water 3", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Exeggcute", "Grass", "Grass", GR_TYPICAL, ["Exeggutor"]),
SpeciesInfo("Exeggutor", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Cubone", "Monster", "Monster", GR_TYPICAL, ["Marowak"]),
SpeciesInfo("Marowak", "Monster", "Monster", GR_TYPICAL, []),
SpeciesInfo("Tyrogue", "NED", "NED", GR_MALE_ONLY, ["Hitmonlee", "Hitmonchan", "Hitmontop"]),
SpeciesInfo("Hitmonlee", "Human-Like", "Human-Like", GR_MALE_ONLY, []),
SpeciesInfo("Hitmonchan", "Human-Like", "Human-Like", GR_MALE_ONLY, []),
SpeciesInfo("Hitmontop", "Human-Like", "Human-Like", GR_MALE_ONLY, []),
SpeciesInfo("Lickitung", "Monster", "Monster", GR_TYPICAL, ["Lickilicky"]),
SpeciesInfo("Lickilicky", "Monster", "Monster", GR_TYPICAL, []),
SpeciesInfo("Koffing", "Amorphous", "Amorphous", GR_TYPICAL, ["Weezing"]),
SpeciesInfo("Weezing", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Rhyhorn", "Monster", "Field", GR_TYPICAL, ["Rhydon"]),
SpeciesInfo("Rhydon", "Monster", "Field", GR_TYPICAL, ["Rhyperior"]),
SpeciesInfo("Rhyperior", "Monster", "Field", GR_TYPICAL, []),
SpeciesInfo("Happiny", "NED", "NED", GR_FEMALE_ONLY, ["Chansey"]),
SpeciesInfo("Chansey", "Fairy", "Fairy", GR_FEMALE_ONLY, ["Blissey"]),
SpeciesInfo("Blissey", "Fairy", "Fairy", GR_FEMALE_ONLY, []),
SpeciesInfo("Tangela", "Grass", "Grass", GR_TYPICAL, ["Tangrowth"]),
SpeciesInfo("Tangrowth", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Kangaskhan", "Monster", "Monster", GR_FEMALE_ONLY, []),
SpeciesInfo("Horsea", "Water 1", "Dragon", GR_TYPICAL, ["Seadra"]),
SpeciesInfo("Seadra", "Water 1", "Dragon", GR_TYPICAL, ["Kingdra"]),
SpeciesInfo("Kingdra", "Water 1", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Goldeen", "Water 2", "Water 2", GR_TYPICAL, ["Seaking"]),
SpeciesInfo("Seaking", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Staryu", "Water 3", "Water 3", GR_UNKNOWN, ["Starmie"]),
SpeciesInfo("Starmie", "Water 3", "Water 3", GR_UNKNOWN, []),
SpeciesInfo("Mime Jr.", "NED", "NED", GR_TYPICAL, ["Mr. Mime"]),
SpeciesInfo("Mr. Mime", "Human-Like", "Human-Like", GR_TYPICAL, ["Mr. Rime"]),
SpeciesInfo("Mr. Rime", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Scyther", "Bug", "Bug", GR_TYPICAL, ["Scizor"]),
SpeciesInfo("Scizor", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Smoochum", "NED", "NED", GR_FEMALE_ONLY, ["Jynx"]),
SpeciesInfo("Jynx", "Human-Like", "Human-Like", GR_FEMALE_ONLY, []),
SpeciesInfo("Elekid", "NED", "NED", GR_TYPICAL, ["Electabuzz"]),
SpeciesInfo("Electabuzz", "Human-Like", "Human-Like", GR_TYPICAL, ["Electivire"]),
SpeciesInfo("Electivire", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Magby", "NED", "NED", GR_TYPICAL, ["Magmar"]),
SpeciesInfo("Magmar", "Human-Like", "Human-Like", GR_TYPICAL, ["Magmortar"]),
SpeciesInfo("Magmortar", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Pinsir", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Tauros", "Field", "Field", GR_MALE_ONLY, []),
SpeciesInfo("Magikarp", "Water 2", "Dragon", GR_TYPICAL, ["Gyarados"]),
SpeciesInfo("Gyarados", "Water 2", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Lapras", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Ditto", "Ditto", "Ditto", GR_UNKNOWN, []),
SpeciesInfo("Eevee", "Field", "Field", GR_TYPICAL, ["Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon", "Leafeon", "Glaceon", "Sylveon"]),
SpeciesInfo("Vaporeon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Jolteon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Flareon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Espeon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Umbreon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Leafeon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Glaceon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Sylveon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Porygon", "Mineral", "Mineral", GR_UNKNOWN, ["Porygon2"]),
SpeciesInfo("Porygon2", "Mineral", "Mineral", GR_UNKNOWN, ["Porygon-Z"]),
SpeciesInfo("Porygon-Z", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Omanyte", "Water 1", "Water 3", GR_TYPICAL, ["Omastar"]),
SpeciesInfo("Omastar", "Water 1", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Kabuto", "Water 1", "Water 3", GR_TYPICAL, ["Kabutops"]),
SpeciesInfo("Kabutops", "Water 1", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Aerodactyl", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Munchlax", "NED", "NED", GR_TYPICAL, ["Snorlax"]),
SpeciesInfo("Snorlax", "Monster", "Monster", GR_TYPICAL, []),
SpeciesInfo("Articuno", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Zapdos", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Moltres", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Dratini", "Water 1", "Dragon", GR_TYPICAL, ["Dragonair"]),
SpeciesInfo("Dragonair", "Water 1", "Dragon", GR_TYPICAL, ["Dragonite"]),
SpeciesInfo("Dragonite", "Water 1", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Mewtwo", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Mew", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Hoothoot", "Flying", "Flying", GR_TYPICAL, ["Noctowl"]),
SpeciesInfo("Noctowl", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Chinchou", "Water 2", "Water 2", GR_TYPICAL, ["Lanturn"]),
SpeciesInfo("Lanturn", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Togepi", "NED", "NED", GR_TYPICAL, ["Togetic"]),
SpeciesInfo("Togetic", "Flying", "Fairy", GR_TYPICAL, ["Togekiss"]),
SpeciesInfo("Togekiss", "Flying", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Natu", "Flying", "Flying", GR_TYPICAL, ["Xatu"]),
SpeciesInfo("Xatu", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Azurill", "NED", "NED", GR_TYPICAL, ["Marill"]),
SpeciesInfo("Marill", "Water 1", "Fairy", GR_TYPICAL, ["Azumarill"]),
SpeciesInfo("Azumarill", "Water 1", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Bonsly", "NED", "NED", GR_TYPICAL, ["Sudowoodo"]),
SpeciesInfo("Sudowoodo", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Wooper", "Water 1", "Field", GR_TYPICAL, ["Quagsire"]),
SpeciesInfo("Quagsire", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Wynaut", "NED", "NED", GR_TYPICAL, ["Wobbuffet"]),
SpeciesInfo("Wobbuffet", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Dunsparce", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Qwilfish", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Shuckle", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Heracross", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Sneasel", "Field", "Field", GR_TYPICAL, ["Weavile"]),
SpeciesInfo("Weavile", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Swinub", "Field", "Field", GR_TYPICAL, ["Piloswine"]),
SpeciesInfo("Piloswine", "Field", "Field", GR_TYPICAL, ["Mamoswine"]),
SpeciesInfo("Mamoswine", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Corsola", "Water 1", "Water 3", GR_TYPICAL, ["Cursola"]),
SpeciesInfo("Cursola", "Water 1", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Remoraid", "Water 1", "Water 2", GR_TYPICAL, ["Octillery"]),
SpeciesInfo("Octillery", "Water 1", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Delibird", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Mantyke", "NED", "NED", GR_TYPICAL, ["Mantine"]),
SpeciesInfo("Mantine", "Water 1", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Skarmory", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Miltank", "Field", "Field", GR_FEMALE_ONLY, []),
SpeciesInfo("Raikou", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Entei", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Suicune", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Larvitar", "Monster", "Monster", GR_TYPICAL, ["Pupitar"]),
SpeciesInfo("Pupitar", "Monster", "Monster", GR_TYPICAL, ["Tyranitar"]),
SpeciesInfo("Tyranitar", "Monster", "Monster", GR_TYPICAL, []),
SpeciesInfo("Lugia", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Ho-Oh", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Celebi", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Treecko", "Monster", "Dragon", GR_TYPICAL, ["Grovyle"]),
SpeciesInfo("Grovyle", "Monster", "Dragon", GR_TYPICAL, ["Sceptile"]),
SpeciesInfo("Sceptile", "Monster", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Torchic", "Field", "Field", GR_TYPICAL, ["Combusken"]),
SpeciesInfo("Combusken", "Field", "Field", GR_TYPICAL, ["Blaziken"]),
SpeciesInfo("Blaziken", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Mudkip", "Monster", "Water 1", GR_TYPICAL, ["Marshtomp"]),
SpeciesInfo("Marshtomp", "Monster", "Water 1", GR_TYPICAL, ["Swampert"]),
SpeciesInfo("Swampert", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Zigzagoon", "Field", "Field", GR_TYPICAL, ["Linoone"]),
SpeciesInfo("Linoone", "Field", "Field", GR_TYPICAL, ["Obstagoon"]),
SpeciesInfo("Obstagoon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Lotad", "Water 1", "Grass", GR_TYPICAL, ["Lombre"]),
SpeciesInfo("Lombre", "Water 1", "Grass", GR_TYPICAL, ["Ludicolo"]),
SpeciesInfo("Ludicolo", "Water 1", "Grass", GR_TYPICAL, []),
SpeciesInfo("Seedot", "Field", "Grass", GR_TYPICAL, ["Nuzleaf"]),
SpeciesInfo("Nuzleaf", "Field", "Grass", GR_TYPICAL, ["Shiftry"]),
SpeciesInfo("Shiftry", "Field", "Grass", GR_TYPICAL, []),
SpeciesInfo("Wingull", "Water 1", "Flying", GR_TYPICAL, ["Pelipper"]),
SpeciesInfo("Pelipper", "Water 1", "Flying", GR_TYPICAL, []),
SpeciesInfo("Ralts", "Human-Like", "Amorphous", GR_TYPICAL, ["Kirlia"]),
SpeciesInfo("Kirlia", "Human-Like", "Amorphous", GR_MALE_ONLY, ["Gardevoir", "Gallade"]),
SpeciesInfo("Gardevoir", "Human-Like", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Gallade", "Human-Like", "Amorphous", GR_MALE_ONLY, []),
SpeciesInfo("Nincada", "Bug", "Bug", GR_UNKNOWN, ["Ninjask", "Shedinja"]),
SpeciesInfo("Ninjask", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Shedinja", "Bug", "Bug", GR_UNKNOWN, []),
SpeciesInfo("Whismur", "Monster", "Field", GR_TYPICAL, ["Loudred"]),
SpeciesInfo("Loudred", "Monster", "Field", GR_TYPICAL, ["Exploud"]),
SpeciesInfo("Exploud", "Monster", "Field", GR_TYPICAL, []),
SpeciesInfo("Sableye", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Mawile", "Field", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Aron", "Monster", "Monster", GR_TYPICAL, ["Lairon"]),
SpeciesInfo("Lairon", "Monster", "Monster", GR_TYPICAL, ["Aggron"]),
SpeciesInfo("Aggron", "Monster", "Monster", GR_TYPICAL, []),
SpeciesInfo("Electrike", "Field", "Field", GR_TYPICAL, ["Manectric"]),
SpeciesInfo("Manectric", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Budew", "NED", "NED", GR_TYPICAL, ["Roselia"]),
SpeciesInfo("Roselia", "Fairy", "Grass", GR_TYPICAL, ["Roserade"]),
SpeciesInfo("Roserade", "Fairy", "Grass", GR_TYPICAL, []),
SpeciesInfo("Carvanha", "Water 2", "Water 2", GR_TYPICAL, ["Sharpedo"]),
SpeciesInfo("Sharpedo", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Wailmer", "Field", "Water 2", GR_TYPICAL, ["Wailord"]),
SpeciesInfo("Wailord", "Field", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Torkoal", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Trapinch", "Bug", "Dragon", GR_TYPICAL, ["Vibrava"]),
SpeciesInfo("Vibrava", "Bug", "Dragon", GR_TYPICAL, ["Flygon"]),
SpeciesInfo("Flygon", "Bug", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Swablu", "Flying", "Dragon", GR_TYPICAL, ["Altaria"]),
SpeciesInfo("Altaria", "Flying", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Lunatone", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Solrock", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Barboach", "Water 2", "Water 2", GR_TYPICAL, ["Whiscash"]),
SpeciesInfo("Whiscash", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Corphish", "Water 1", "Water 3", GR_TYPICAL, ["Crawdaunt"]),
SpeciesInfo("Crawdaunt", "Water 1", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Baltoy", "Mineral", "Mineral", GR_UNKNOWN, ["Claydol"]),
SpeciesInfo("Claydol", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Lileep", "Water 3", "Water 3", GR_TYPICAL, ["Cradily"]),
SpeciesInfo("Cradily", "Water 3", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Anorith", "Water 3", "Water 3", GR_TYPICAL, ["Armaldo"]),
SpeciesInfo("Armaldo", "Water 3", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Feebas", "Water 1", "Dragon", GR_TYPICAL, ["Milotic"]),
SpeciesInfo("Milotic", "Water 1", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Duskull", "Amorphous", "Amorphous", GR_TYPICAL, ["Dusclops"]),
SpeciesInfo("Dusclops", "Amorphous", "Amorphous", GR_TYPICAL, ["Dusknoir"]),
SpeciesInfo("Dusknoir", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Absol", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Snorunt", "Fairy", "Mineral", GR_FEMALE_ONLY, ["Glalie", "Froslass"]),
SpeciesInfo("Glalie", "Fairy", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Froslass", "Fairy", "Mineral", GR_FEMALE_ONLY, []),
SpeciesInfo("Spheal", "Water 1", "Field", GR_TYPICAL, ["Sealeo"]),
SpeciesInfo("Sealeo", "Water 1", "Field", GR_TYPICAL, ["Walrein"]),
SpeciesInfo("Walrein", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Relicanth", "Water 1", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Bagon", "Dragon", "Dragon", GR_TYPICAL, ["Shelgon"]),
SpeciesInfo("Shelgon", "Dragon", "Dragon", GR_TYPICAL, ["Salamence"]),
SpeciesInfo("Salamence", "Dragon", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Beldum", "Mineral", "Mineral", GR_UNKNOWN, ["Metang"]),
SpeciesInfo("Metang", "Mineral", "Mineral", GR_UNKNOWN, ["Metagross"]),
SpeciesInfo("Metagross", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Regirock", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Regice", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Registeel", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Latias", "NED", "NED", GR_FEMALE_ONLY, []),
SpeciesInfo("Latios", "NED", "NED", GR_MALE_ONLY, []),
SpeciesInfo("Kyogre", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Groudon", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Rayquaza", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Jirachi", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Shinx", "Field", "Field", GR_TYPICAL, ["Luxio"]),
SpeciesInfo("Luxio", "Field", "Field", GR_TYPICAL, ["Luxray"]),
SpeciesInfo("Luxray", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Combee", "Bug", "Bug", GR_FEMALE_ONLY, ["Vespiquen"]),
SpeciesInfo("Vespiquen", "Bug", "Bug", GR_FEMALE_ONLY, []),
SpeciesInfo("Cherubi", "Fairy", "Grass", GR_TYPICAL, ["Cherrim"]),
SpeciesInfo("Cherrim", "Fairy", "Grass", GR_TYPICAL, []),
SpeciesInfo("Shellos", "Water 1", "Amorphous", GR_TYPICAL, ["Gastrodon"]),
SpeciesInfo("Gastrodon", "Water 1", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Drifloon", "Amorphous", "Amorphous", GR_TYPICAL, ["Drifblim"]),
SpeciesInfo("Drifblim", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Buneary", "Field", "Human-Like", GR_TYPICAL, ["Lopunny"]),
SpeciesInfo("Lopunny", "Field", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Stunky", "Field", "Field", GR_TYPICAL, ["Skuntank"]),
SpeciesInfo("Skuntank", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Bronzor", "Mineral", "Mineral", GR_UNKNOWN, ["Bronzong"]),
SpeciesInfo("Bronzong", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Spiritomb", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Gible", "Monster", "Dragon", GR_TYPICAL, ["Gabite"]),
SpeciesInfo("Gabite", "Monster", "Dragon", GR_TYPICAL, ["Garchomp"]),
SpeciesInfo("Garchomp", "Monster", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Riolu", "NED", "NED", GR_TYPICAL, ["Lucario"]),
SpeciesInfo("Lucario", "Field", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Hippopotas", "Field", "Field", GR_TYPICAL, ["Hippowdon"]),
SpeciesInfo("Hippowdon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Skorupi", "Bug", "Water 3", GR_TYPICAL, ["Drapion"]),
SpeciesInfo("Drapion", "Bug", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Croagunk", "Human-Like", "Human-Like", GR_TYPICAL, ["Toxicroak"]),
SpeciesInfo("Toxicroak", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Snover", "Monster", "Grass", GR_TYPICAL, ["Abomasnow"]),
SpeciesInfo("Abomasnow", "Monster", "Grass", GR_TYPICAL, []),
SpeciesInfo("Rotom", "Amorphous", "Amorphous", GR_UNKNOWN, []),
SpeciesInfo("Uxie", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Mesprit", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Azelf", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Dialga", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Palkia", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Heatran", "NED", "NED", GR_TYPICAL, []),
SpeciesInfo("Regigigas", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Giratina", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Cresselia", "NED", "NED", GR_FEMALE_ONLY, []),
SpeciesInfo("Victini", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Lillipup", "Field", "Field", GR_TYPICAL, ["Herdier"]),
SpeciesInfo("Herdier", "Field", "Field", GR_TYPICAL, ["Stoutland"]),
SpeciesInfo("Stoutland", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Purrloin", "Field", "Field", GR_TYPICAL, ["Liepard"]),
SpeciesInfo("Liepard", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Munna", "Field", "Field", GR_TYPICAL, ["Musharna"]),
SpeciesInfo("Musharna", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Pidove", "Flying", "Flying", GR_TYPICAL, ["Tranquill"]),
SpeciesInfo("Tranquill", "Flying", "Flying", GR_TYPICAL, ["Unfezant"]),
SpeciesInfo("Unfezant", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Roggenrola", "Mineral", "Mineral", GR_TYPICAL, ["Boldore"]),
SpeciesInfo("Boldore", "Mineral", "Mineral", GR_TYPICAL, ["Gigalith"]),
SpeciesInfo("Gigalith", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Woobat", "Field", "Flying", GR_TYPICAL, ["Swoobat"]),
SpeciesInfo("Swoobat", "Field", "Flying", GR_TYPICAL, []),
SpeciesInfo("Drilbur", "Field", "Field", GR_TYPICAL, ["Excadrill"]),
SpeciesInfo("Excadrill", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Audino", "Fairy", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Timburr", "Human-Like", "Human-Like", GR_TYPICAL, ["Gurdurr"]),
SpeciesInfo("Gurdurr", "Human-Like", "Human-Like", GR_TYPICAL, ["Conkeldurr"]),
SpeciesInfo("Conkeldurr", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Tympole", "Water 1", "Water 1", GR_TYPICAL, ["Palpitoad"]),
SpeciesInfo("Palpitoad", "Water 1", "Water 1", GR_TYPICAL, ["Seismitoad"]),
SpeciesInfo("Seismitoad", "Water 1", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Throh", "Human-Like", "Human-Like", GR_MALE_ONLY, []),
SpeciesInfo("Sawk", "Human-Like", "Human-Like", GR_MALE_ONLY, []),
SpeciesInfo("Venipede", "Bug", "Bug", GR_TYPICAL, ["Whirlipede"]),
SpeciesInfo("Whirlipede", "Bug", "Bug", GR_TYPICAL, ["Scolipede"]),
SpeciesInfo("Scolipede", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Cottonee", "Grass", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Whimsicott", "Grass", "Fairy", GR_FEMALE_ONLY, ["Petilil"]),
SpeciesInfo("Petilil", "Grass", "Grass", GR_FEMALE_ONLY, ["Lilligant"]),
SpeciesInfo("Lilligant", "Grass", "Grass", GR_FEMALE_ONLY, []),
SpeciesInfo("Basculin", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Sandile", "Field", "Field", GR_TYPICAL, ["Krokorok"]),
SpeciesInfo("Krokorok", "Field", "Field", GR_TYPICAL, ["Krookodile"]),
SpeciesInfo("Krookodile", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Darumaka", "Field", "Field", GR_TYPICAL, ["Darmanitan"]),
SpeciesInfo("Darmanitan", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Maractus", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Dwebble", "Bug", "Mineral", GR_TYPICAL, ["Crustle"]),
SpeciesInfo("Crustle", "Bug", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Scraggy", "Field", "Dragon", GR_TYPICAL, ["Scrafty"]),
SpeciesInfo("Scrafty", "Field", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Sigilyph", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Yamask", "Mineral", "Amorphous", GR_TYPICAL, ["Cofagrigus", "Runerigus"]),
SpeciesInfo("Cofagrigus", "Mineral", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Runerigus", "Mineral", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Tirtouga", "Water 1", "Water 3", GR_TYPICAL, ["Carracosta"]),
SpeciesInfo("Carracosta", "Water 1", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Archen", "Flying", "Water 3", GR_TYPICAL, ["Archeops"]),
SpeciesInfo("Archeops", "Flying", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Trubbish", "Mineral", "Mineral", GR_TYPICAL, ["Garbodor"]),
SpeciesInfo("Garbodor", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Zorua", "Field", "Field", GR_TYPICAL, ["Zoroark"]),
SpeciesInfo("Zoroark", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Minccino", "Field", "Field", GR_TYPICAL, ["Cinccino"]),
SpeciesInfo("Cinccino", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Gothita", "Human-Like", "Human-Like", GR_TYPICAL, ["Gothorita"]),
SpeciesInfo("Gothorita", "Human-Like", "Human-Like", GR_TYPICAL, ["Gothitelle"]),
SpeciesInfo("Gothitelle", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Solosis", "Amorphous", "Amorphous", GR_TYPICAL, ["Duosion"]),
SpeciesInfo("Duosion", "Amorphous", "Amorphous", GR_TYPICAL, ["Reuniclus"]),
SpeciesInfo("Reuniclus", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Vanillite", "Mineral", "Mineral", GR_TYPICAL, ["Vanillish"]),
SpeciesInfo("Vanillish", "Mineral", "Mineral", GR_TYPICAL, ["Vanilluxe"]),
SpeciesInfo("Vanilluxe", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Emolga", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Karrablast", "Bug", "Bug", GR_TYPICAL, ["Escavalier"]),
SpeciesInfo("Escavalier", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Foongus", "Grass", "Grass", GR_TYPICAL, ["Amoonguss"]),
SpeciesInfo("Amoonguss", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Frillish", "Amorphous", "Amorphous", GR_TYPICAL, ["Jellicent"]),
SpeciesInfo("Jellicent", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Joltik", "Bug", "Bug", GR_TYPICAL, ["Galvantula"]),
SpeciesInfo("Galvantula", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Ferroseed", "Grass", "Mineral", GR_TYPICAL, ["Ferrothorn"]),
SpeciesInfo("Ferrothorn", "Grass", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Klink", "Mineral", "Mineral", GR_UNKNOWN, ["Klang"]),
SpeciesInfo("Klang", "Mineral", "Mineral", GR_UNKNOWN, ["Klinklang"]),
SpeciesInfo("Klinklang", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Elgyem", "Human-Like", "Human-Like", GR_TYPICAL, ["Beheeyem"]),
SpeciesInfo("Beheeyem", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Litwick", "Amorphous", "Amorphous", GR_TYPICAL, ["Lampent"]),
SpeciesInfo("Lampent", "Amorphous", "Amorphous", GR_TYPICAL, ["Chandelure"]),
SpeciesInfo("Chandelure", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Axew", "Monster", "Dragon", GR_TYPICAL, ["Fraxure"]),
SpeciesInfo("Fraxure", "Monster", "Dragon", GR_TYPICAL, ["Haxorus"]),
SpeciesInfo("Haxorus", "Monster", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Cubchoo", "Field", "Field", GR_TYPICAL, ["Beartic"]),
SpeciesInfo("Beartic", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Cryogonal", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Shelmet", "Bug", "Bug", GR_TYPICAL, ["Accelgor"]),
SpeciesInfo("Accelgor", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Stunfisk", "Water 1", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Mienfoo", "Field", "Human-Like", GR_TYPICAL, ["Mienshao"]),
SpeciesInfo("Mienshao", "Field", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Druddigon", "Dragon", "Monster", GR_TYPICAL, []),
SpeciesInfo("Golett", "Mineral", "Mineral", GR_UNKNOWN, ["Golurk"]),
SpeciesInfo("Golurk", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Pawniard", "Human-Like", "Human-Like", GR_TYPICAL, ["Bisharp"]),
SpeciesInfo("Bisharp", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Bouffalant", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Rufflet", "Flying", "Flying", GR_MALE_ONLY, ["Braviary"]),
SpeciesInfo("Braviary", "Flying", "Flying", GR_MALE_ONLY, []),
SpeciesInfo("Vullaby", "Flying", "Flying", GR_FEMALE_ONLY, ["Mandibuzz"]),
SpeciesInfo("Mandibuzz", "Flying", "Flying", GR_FEMALE_ONLY, []),
SpeciesInfo("Heatmor", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Durant", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Deino", "Dragon", "Dragon", GR_TYPICAL, ["Zweilous"]),
SpeciesInfo("Zweilous", "Dragon", "Dragon", GR_TYPICAL, ["Hydreigon"]),
SpeciesInfo("Hydreigon", "Dragon", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Larvesta", "Bug", "Bug", GR_TYPICAL, ["Volcarona"]),
SpeciesInfo("Volcarona", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Cobalion", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Terrakion", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Virizion", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Tornadus", "NED", "NED", GR_MALE_ONLY, []),
SpeciesInfo("Thundurus", "NED", "NED", GR_MALE_ONLY, []),
SpeciesInfo("Reshiram", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Zekrom", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Landorus", "NED", "NED", GR_MALE_ONLY, []),
SpeciesInfo("Kyurem", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Keldeo", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Genesect", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Bunnelby", "Field", "Field", GR_TYPICAL, ["Diggersby"]),
SpeciesInfo("Diggersby", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Fletchling", "Flying", "Flying", GR_TYPICAL, ["Fletchinder"]),
SpeciesInfo("Fletchinder", "Flying", "Flying", GR_TYPICAL, ["Talonflame"]),
SpeciesInfo("Talonflame", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Pancham", "Field", "Human-Like", GR_TYPICAL, ["Pangoro"]),
SpeciesInfo("Pangoro", "Field", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Espurr", "Field", "Field", GR_TYPICAL, ["Meowstic"]),
SpeciesInfo("Meowstic", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Honedge", "Mineral", "Mineral", GR_TYPICAL, ["Doublade"]),
SpeciesInfo("Doublade", "Mineral", "Mineral", GR_TYPICAL, ["Aegislash"]),
SpeciesInfo("Aegislash", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Spritzee", "Fairy", "Fairy", GR_TYPICAL, ["Aromatisse"]),
SpeciesInfo("Aromatisse", "Fairy", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Swirlix", "Fairy", "Fairy", GR_TYPICAL, ["Slurpuff"]),
SpeciesInfo("Slurpuff", "Fairy", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Inkay", "Water 1", "Water 2", GR_TYPICAL, ["Malamar"]),
SpeciesInfo("Malamar", "Water 1", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Binacle", "Water 3", "Water 3", GR_TYPICAL, ["Barbaracle"]),
SpeciesInfo("Barbaracle", "Water 3", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Skrelp", "Water 1", "Dragon", GR_TYPICAL, ["Dragalge"]),
SpeciesInfo("Dragalge", "Water 1", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Clauncher", "Water 1", "Water 3", GR_TYPICAL, ["Clawitzer"]),
SpeciesInfo("Clawitzer", "Water 1", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Helioptile", "Monster", "Dragon", GR_TYPICAL, ["Heliolisk"]),
SpeciesInfo("Heliolisk", "Monster", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Tyrunt", "Monster", "Dragon", GR_TYPICAL, ["Tyrantrum"]),
SpeciesInfo("Tyrantrum", "Monster", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Amaura", "Monster", "Monster", GR_TYPICAL, ["Aurorus"]),
SpeciesInfo("Aurorus", "Monster", "Monster", GR_TYPICAL, []),
SpeciesInfo("Hawlucha", "Flying", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Dedenne", "Field", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Carbink", "Fairy", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Goomy", "Dragon", "Dragon", GR_TYPICAL, ["Sliggoo"]),
SpeciesInfo("Sliggoo", "Dragon", "Dragon", GR_TYPICAL, ["Goodra"]),
SpeciesInfo("Goodra", "Dragon", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Klefki", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Phantump", "Grass", "Amorphous", GR_TYPICAL, ["Trevenant"]),
SpeciesInfo("Trevenant", "Grass", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Pumpkaboo", "Amorphous", "Amorphous", GR_TYPICAL, ["Gourgeist"]),
SpeciesInfo("Gourgeist", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Bergmite", "Monster", "Mineral", GR_TYPICAL, ["Avalugg"]),
SpeciesInfo("Avalugg", "Monster", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Noibat", "Flying", "Dragon", GR_TYPICAL, ["Noivern"]),
SpeciesInfo("Noivern", "Flying", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Xerneas", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Yveltal", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Zygarde", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Diancie", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Volcanion", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Rowlet", "Flying", "Flying", GR_TYPICAL, ["Dartrix"]),
SpeciesInfo("Dartrix", "Flying", "Flying", GR_TYPICAL, ["Decidueye"]),
SpeciesInfo("Decidueye", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Litten", "Field", "Field", GR_TYPICAL, ["Torracat"]),
SpeciesInfo("Torracat", "Field", "Field", GR_TYPICAL, ["Incineroar"]),
SpeciesInfo("Incineroar", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Popplio", "Water 1", "Field", GR_TYPICAL, ["Brionne"]),
SpeciesInfo("Brionne", "Water 1", "Field", GR_TYPICAL, ["Primarina"]),
SpeciesInfo("Primarina", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Grubbin", "Bug", "Bug", GR_TYPICAL, ["Charjabug"]),
SpeciesInfo("Charjabug", "Bug", "Bug", GR_TYPICAL, ["Vikavolt"]),
SpeciesInfo("Vikavolt", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Cutiefly", "Bug", "Fairy", GR_TYPICAL, ["Ribombee"]),
SpeciesInfo("Ribombee", "Bug", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Rockruff", "Field", "Field", GR_TYPICAL, ["Lycanroc"]),
SpeciesInfo("Lycanroc", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Wishiwashi", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Mareanie", "Water 1", "Water 1", GR_TYPICAL, ["Toxapex"]),
SpeciesInfo("Toxapex", "Water 1", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Mudbray", "Field", "Field", GR_TYPICAL, ["Mudsdale"]),
SpeciesInfo("Mudsdale", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Dewpider", "Water 1", "Bug", GR_TYPICAL, ["Araquanid"]),
SpeciesInfo("Araquanid", "Water 1", "Bug", GR_TYPICAL, []),
SpeciesInfo("Fomantis", "Grass", "Grass", GR_TYPICAL, ["Lurantis"]),
SpeciesInfo("Lurantis", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Morelull", "Grass", "Grass", GR_TYPICAL, ["Shiinotic"]),
SpeciesInfo("Shiinotic", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Salandit", "Monster", "Dragon", GR_FEMALE_ONLY, ["Salazzle"]),
SpeciesInfo("Salazzle", "Monster", "Dragon", GR_FEMALE_ONLY, []),
SpeciesInfo("Stufful", "Field", "Field", GR_TYPICAL, ["Bewear"]),
SpeciesInfo("Bewear", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Bounsweet", "Grass", "Grass", GR_FEMALE_ONLY, ["Steenee"]),
SpeciesInfo("Steenee", "Grass", "Grass", GR_FEMALE_ONLY, ["Tsareena"]),
SpeciesInfo("Tsareena", "Grass", "Grass", GR_FEMALE_ONLY, []),
SpeciesInfo("Comfey", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Oranguru", "Field", "Field", GR_TYPICAL, ["Passimian"]),
SpeciesInfo("Passimian", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Wimpod", "Bug", "Water 3", GR_TYPICAL, ["Golisopod"]),
SpeciesInfo("Golisopod", "Bug", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Sandygast", "Amorphous", "Amorphous", GR_TYPICAL, ["Palossand"]),
SpeciesInfo("Palossand", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Pyukumuku", "Water 1", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Type: Null", "NED", "NED", GR_UNKNOWN, ["Silvally"]),
SpeciesInfo("Silvally", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Turtonator", "Monster", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Togedemaru", "Field", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Mimikyu", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Drampa", "Monster", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Dhelmise", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Jangmo-o", "Dragon", "Dragon", GR_TYPICAL, ["Hakamo-o"]),
SpeciesInfo("Hakamo-o", "Dragon", "Dragon", GR_TYPICAL, ["Kommo-o"]),
SpeciesInfo("Kommo-o", "Dragon", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Tapu Koko", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Tapu Lele", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Tapu Bulu", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Tapu Fini", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Cosmog", "NED", "NED", GR_UNKNOWN, ["Cosmoem"]),
SpeciesInfo("Cosmoem", "NED", "NED", GR_UNKNOWN, ["Solgaleo", "Lunala"]),
SpeciesInfo("Solgaleo", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Lunala", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Nihilego", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Buzzwole", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Pheromosa", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Xurkitree", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Celesteela", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Kartana", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Guzzlord", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Necrozma", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Magearna", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Marshadow", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Poipole", "NED", "NED", GR_UNKNOWN, ["Naganadel"]),
SpeciesInfo("Naganadel", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Stakataka", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Blacephalon", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Zeraora", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Meltan", "NED", "NED", GR_UNKNOWN, ["Melmetal"]),
SpeciesInfo("Melmetal", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Grookey", "Field", "Grass", GR_TYPICAL, ["Thwackey"]),
SpeciesInfo("Thwackey", "Field", "Grass", GR_TYPICAL, ["Rillaboom"]),
SpeciesInfo("Rillaboom", "Field", "Grass", GR_TYPICAL, []),
SpeciesInfo("Scorbunny", "Field", "Human-Like", GR_TYPICAL, ["Raboot"]),
SpeciesInfo("Raboot", "Field", "Human-Like", GR_TYPICAL, ["Cinderace"]),
SpeciesInfo("Cinderace", "Field", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Sobble", "Water 1", "Field", GR_TYPICAL, ["Drizzile"]),
SpeciesInfo("Drizzile", "Water 1", "Field", GR_TYPICAL, ["Inteleon"]),
SpeciesInfo("Inteleon", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Skwovet", "Field", "Field", GR_TYPICAL, ["Greedent"]),
SpeciesInfo("Greedent", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Rookidee", "Flying", "Flying", GR_TYPICAL, ["Corvisquire"]),
SpeciesInfo("Corvisquire", "Flying", "Flying", GR_TYPICAL, ["Corviknight"]),
SpeciesInfo("Corviknight", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Blipbug", "Bug", "Bug", GR_TYPICAL, ["Dottler"]),
SpeciesInfo("Dottler", "Bug", "Bug", GR_TYPICAL, ["Orbeetle"]),
SpeciesInfo("Orbeetle", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Nickit", "Field", "Field", GR_TYPICAL, ["Thievul"]),
SpeciesInfo("Thievul", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Gossifleur", "Grass", "Grass", GR_TYPICAL, ["Eldegoss"]),
SpeciesInfo("Eldegoss", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Wooloo", "Field", "Field", GR_TYPICAL, ["Dubwool"]),
SpeciesInfo("Dubwool", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Chewtle", "Monster", "Water 1", GR_TYPICAL, ["Drednaw"]),
SpeciesInfo("Drednaw", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Yamper", "Field", "Field", GR_TYPICAL, ["Boltund"]),
SpeciesInfo("Boltund", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Rolycoly", "Mineral", "Mineral", GR_TYPICAL, ["Carkol"]),
SpeciesInfo("Carkol", "Mineral", "Mineral", GR_TYPICAL, ["Coalossal"]),
SpeciesInfo("Coalossal", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Applin", "Grass", "Dragon", GR_TYPICAL, ["Flapple", "Appletun"]),
SpeciesInfo("Flapple", "Grass", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Appletun", "Grass", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Silicobra", "Field", "Dragon", GR_TYPICAL, ["Sandaconda"]),
SpeciesInfo("Sandaconda", "Field", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Cramorant", "Water 1", "Flying", GR_TYPICAL, []),
SpeciesInfo("Arrokuda", "Water 2", "Water 2", GR_TYPICAL, ["Barraskewda"]),
SpeciesInfo("Barraskewda", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Toxel", "NED", "NED", GR_TYPICAL, ["Toxtricity"]),
SpeciesInfo("Toxtricity", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Sizzlipede", "Bug", "Bug", GR_TYPICAL, ["Centiskorch"]),
SpeciesInfo("Centiskorch", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Clobbopus", "Water 1", "Human-Like", GR_TYPICAL, ["Grapploct"]),
SpeciesInfo("Grapploct", "Water 1", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Sinistea", "Mineral", "Amorphous", GR_UNKNOWN, ["Polteageist"]),
SpeciesInfo("Polteageist", "Mineral", "Amorphous", GR_UNKNOWN, []),
SpeciesInfo("Hatenna", "Fairy", "Fairy", GR_FEMALE_ONLY, ["Hattrem"]),
SpeciesInfo("Hattrem", "Fairy", "Fairy", GR_FEMALE_ONLY, ["Hatterene"]),
SpeciesInfo("Hatterene", "Fairy", "Fairy", GR_FEMALE_ONLY, []),
SpeciesInfo("Impidimp", "Fairy", "Human-Like", GR_MALE_ONLY, ["Morgrem"]),
SpeciesInfo("Morgrem", "Fairy", "Human-Like", GR_MALE_ONLY, ["Grimmsnarl"]),
SpeciesInfo("Grimmsnarl", "Fairy", "Human-Like", GR_MALE_ONLY, []),
SpeciesInfo("Milcery", "Fairy", "Amorphous", GR_FEMALE_ONLY, ["Alcremie"]),
SpeciesInfo("Alcremie", "Fairy", "Amorphous", GR_FEMALE_ONLY, []),
SpeciesInfo("Falinks", "Fairy", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Pincurchin", "Water 1", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Snom", "Bug", "Bug", GR_TYPICAL, ["Frosmoth"]),
SpeciesInfo("Frosmoth", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Stonjourner", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Eiscue", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Indeedee", "Fairy", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Morpeko", "Field", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Cufant", "Field", "Mineral", GR_TYPICAL, ["Copperajah"]),
SpeciesInfo("Copperajah", "Field", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Dracozolt", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Arctozolt", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Dracovish", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Arctovish", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Duraludon", "Mineral", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Dreepy", "Amorphous", "Dragon", GR_TYPICAL, ["Drakloak"]),
SpeciesInfo("Drakloak", "Amorphous", "Dragon", GR_TYPICAL, ["Dragapult"]),
SpeciesInfo("Dragapult", "Amorphous", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Zacian", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Zamazenta", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Eternatus", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Kubfu", "NED", "NED", GR_TYPICAL, ["Urshifu"]),
SpeciesInfo("Urshifu", "NED", "NED", GR_TYPICAL, []),
SpeciesInfo("Zarude", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Regieleki", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Regidrago", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Glastrier", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Spectrier", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Calyrex", "NED", "NED", GR_UNKNOWN, [])
]
);