const g_Generation9 = Generation(
"====[[Generation IX]]====",
GAME_SCARLET_VIOLET,
//UniversalTMs https://bulbapedia.bulbagarden.net/w/index.php?search=%22Every+Pok%C3%A9mon+can+learn+this+move+by%22&title=Special%3ASearch&go=Go
[
	"Endure",
	"Facade",
	"Protect",
	"Rest",
	"Sleep Talk",
	"Tera Blast"
],
//MonData https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_breeding_attributes https://bulbapedia.bulbagarden.net/wiki/List_of_cross-generational_evolutionary_lines
[
SpeciesInfo("Bulbasaur", "Monster", "Grass", GR_TYPICAL, ["Ivysaur"]),
SpeciesInfo("Ivysaur", "Monster", "Grass", GR_TYPICAL, ["Venusaur"]),
SpeciesInfo("Venusaur", "Monster", "Grass", GR_TYPICAL, []),
SpeciesInfo("Charmander", "Monster", "Dragon", GR_TYPICAL, ["Charmeleon"]),
SpeciesInfo("Charmeleon", "Monster", "Dragon", GR_TYPICAL, ["Charizard"]),
SpeciesInfo("Charizard", "Monster", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Squirtle", "Monster", "Water 1", GR_TYPICAL, ["Wartortle"]),
SpeciesInfo("Wartortle", "Monster", "Water 1", GR_TYPICAL, ["Blastoise"]),
SpeciesInfo("Blastoise", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Ekans", "Field", "Dragon", GR_TYPICAL, ["Arbok"]),
SpeciesInfo("Arbok", "Field", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Pichu", "NED", "NED", GR_TYPICAL, ["Pikachu"]),
SpeciesInfo("Pikachu", "Field", "Fairy", GR_TYPICAL, ["Raichu"]),
SpeciesInfo("Raichu", "Field", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Sandshrew", "Field", "Field", GR_TYPICAL, ["Sandslash"]),
SpeciesInfo("Sandslash", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Cleffa", "NED", "NED", GR_TYPICAL, ["Clefairy"]),
SpeciesInfo("Clefairy", "Fairy", "Fairy", GR_TYPICAL, ["Clefable"]),
SpeciesInfo("Clefable", "Fairy", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Vulpix", "Field", "Field", GR_TYPICAL, ["Ninetales"]),
SpeciesInfo("Ninetales", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Igglybuff", "NED", "NED", GR_TYPICAL, ["Jigglypuff"]),
SpeciesInfo("Jigglypuff", "Fairy", "Fairy", GR_TYPICAL, ["Wigglytuff"]),
SpeciesInfo("Wigglytuff", "Fairy", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Oddish", "Grass", "Grass", GR_TYPICAL, ["Gloom"]),
SpeciesInfo("Gloom", "Grass", "Grass", GR_TYPICAL, ["Vileplume", "Bellossom"]),
SpeciesInfo("Vileplume", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Bellossom", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Venonat", "Bug", "Bug", GR_TYPICAL, ["Venomoth"]),
SpeciesInfo("Venomoth", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Diglett", "Field", "Field", GR_TYPICAL, ["Dugtrio"]),
SpeciesInfo("Dugtrio", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Meowth", "Field", "Field", GR_TYPICAL, ["Persian"]),
SpeciesInfo("Persian", "Field", "Field", GR_TYPICAL, ["Perrserker"]),
SpeciesInfo("Perrserker", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Psyduck", "Water 1", "Field", GR_TYPICAL, ["Golduck"]),
SpeciesInfo("Golduck", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Mankey", "Field", "Field", GR_TYPICAL, ["Primeape"]),
SpeciesInfo("Primeape", "Field", "Field", GR_TYPICAL, ["Annihilape"]),
SpeciesInfo("Annihilape", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Growlithe", "Field", "Field", GR_TYPICAL, ["Arcanine"]),
SpeciesInfo("Arcanine", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Poliwag", "Water 1", "Water 1", GR_TYPICAL, ["Poliwhirl"]),
SpeciesInfo("Poliwhirl", "Water 1", "Water 1", GR_TYPICAL, ["Poliwrath", "Politoed"]),
SpeciesInfo("Poliwrath", "Water 1", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Politoed", "Water 1", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Bellsprout", "Grass", "Grass", GR_TYPICAL, ["Weepinbell"]),
SpeciesInfo("Weepinbell", "Grass", "Grass", GR_TYPICAL, ["Victreebel"]),
SpeciesInfo("Victreebel", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Tentacool", "Water 3", "Water 3", GR_TYPICAL, ["Tentacruel"]),
SpeciesInfo("Tentacruel", "Water 3", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Geodude", "Mineral", "Mineral", GR_TYPICAL, ["Graveler"]),
SpeciesInfo("Graveler", "Mineral", "Mineral", GR_TYPICAL, ["Golem"]),
SpeciesInfo("Golem", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Slowpoke", "Monster", "Water 1", GR_TYPICAL, ["Slowbro", "Slowking"]),
SpeciesInfo("Slowbro", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Slowking", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Magnemite", "Mineral", "Mineral", GR_UNKNOWN, ["Magneton"]),
SpeciesInfo("Magneton", "Mineral", "Mineral", GR_UNKNOWN, ["Magnezone"]),
SpeciesInfo("Magnezone", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Doduo", "Flying", "Flying", GR_TYPICAL, ["Dodrio"]),
SpeciesInfo("Dodrio", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Seel", "Water 1", "Field", GR_TYPICAL, ["Dewgong"]),
SpeciesInfo("Dewgong", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Grimer", "Amorphous", "Amorphous", GR_TYPICAL, ["Muk"]),
SpeciesInfo("Muk", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Shellder", "Water 3", "Water 3", GR_TYPICAL, ["Cloyster"]),
SpeciesInfo("Cloyster", "Water 3", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Gastly", "Amorphous", "Amorphous", GR_TYPICAL, ["Haunter"]),
SpeciesInfo("Haunter", "Amorphous", "Amorphous", GR_TYPICAL, ["Gengar"]),
SpeciesInfo("Gengar", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Drowzee", "Human-Like", "Human-Like", GR_TYPICAL, ["Hypno"]),
SpeciesInfo("Hypno", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Voltorb", "Mineral", "Mineral", GR_UNKNOWN, ["Electrode"]),
SpeciesInfo("Electrode", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Exeggcute", "Grass", "Grass", GR_TYPICAL, ["Exeggutor"]),
SpeciesInfo("Exeggutor", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Tyrogue", "NED", "NED", GR_MALE_ONLY, ["Hitmonlee", "Hitmonchan", "Hitmontop"]),
SpeciesInfo("Hitmonlee", "Human-Like", "Human-Like", GR_MALE_ONLY, []),
SpeciesInfo("Hitmonchan", "Human-Like", "Human-Like", GR_MALE_ONLY, []),
SpeciesInfo("Hitmontop", "Human-Like", "Human-Like", GR_MALE_ONLY, []),
SpeciesInfo("Koffing", "Amorphous", "Amorphous", GR_TYPICAL, ["Weezing"]),
SpeciesInfo("Weezing", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Rhyhorn", "Monster", "Field", GR_TYPICAL, ["Rhydon"]),
SpeciesInfo("Rhydon", "Monster", "Field", GR_TYPICAL, ["Rhyperior"]),
SpeciesInfo("Rhyperior", "Monster", "Field", GR_TYPICAL, []),
SpeciesInfo("Happiny", "NED", "NED", GR_FEMALE_ONLY, ["Chansey"]),
SpeciesInfo("Chansey", "Fairy", "Fairy", GR_FEMALE_ONLY, ["Blissey"]),
SpeciesInfo("Blissey", "Fairy", "Fairy", GR_FEMALE_ONLY, []),
SpeciesInfo("Horsea", "Water 1", "Dragon", GR_TYPICAL, ["Seadra"]),
SpeciesInfo("Seadra", "Water 1", "Dragon", GR_TYPICAL, ["Kingdra"]),
SpeciesInfo("Kingdra", "Water 1", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Scyther", "Bug", "Bug", GR_TYPICAL, ["Scizor", "Kleavor"]),
SpeciesInfo("Scizor", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Kleavor", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Elekid", "NED", "NED", GR_TYPICAL, ["Electabuzz"]),
SpeciesInfo("Electabuzz", "Human-Like", "Human-Like", GR_TYPICAL, ["Electivire"]),
SpeciesInfo("Electivire", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Magby", "NED", "NED", GR_TYPICAL, ["Magmar"]),
SpeciesInfo("Magmar", "Human-Like", "Human-Like", GR_TYPICAL, ["Magmortar"]),
SpeciesInfo("Magmortar", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Tauros", "Field", "Field", GR_MALE_ONLY, []),
SpeciesInfo("Magikarp", "Water 2", "Dragon", GR_TYPICAL, ["Gyarados"]),
SpeciesInfo("Gyarados", "Water 2", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Lapras", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Ditto", "Ditto", "Ditto", GR_UNKNOWN, []),
SpeciesInfo("Eevee", "Field", "Field", GR_TYPICAL, ["Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon", "Leafeon", "Glaceon", "Sylveon"]),
SpeciesInfo("Vaporeon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Jolteon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Flareon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Espeon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Umbreon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Leafeon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Glaceon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Sylveon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Porygon", "Mineral", "Mineral", GR_UNKNOWN, ["Porygon2"]),
SpeciesInfo("Porygon2", "Mineral", "Mineral", GR_UNKNOWN, ["Porygon-Z"]),
SpeciesInfo("Porygon-Z", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Munchlax", "NED", "NED", GR_TYPICAL, ["Snorlax"]),
SpeciesInfo("Snorlax", "Monster", "Monster", GR_TYPICAL, []),
SpeciesInfo("Articuno", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Zapdos", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Moltres", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Dratini", "Water 1", "Dragon", GR_TYPICAL, ["Dragonair"]),
SpeciesInfo("Dragonair", "Water 1", "Dragon", GR_TYPICAL, ["Dragonite"]),
SpeciesInfo("Dragonite", "Water 1", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Mewtwo", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Mew", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Chikorita", "Monster", "Grass", GR_TYPICAL, ["Bayleef"]),
SpeciesInfo("Bayleef", "Monster", "Grass", GR_TYPICAL, ["Meganium"]),
SpeciesInfo("Meganium", "Monster", "Grass", GR_TYPICAL, []),
SpeciesInfo("Cyndaquil", "Field", "Field", GR_TYPICAL, ["Quilava"]),
SpeciesInfo("Quilava", "Field", "Field", GR_TYPICAL, ["Typhlosion"]),
SpeciesInfo("Typhlosion", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Totodile", "Monster", "Water 1", GR_TYPICAL, ["Croconaw"]),
SpeciesInfo("Croconaw", "Monster", "Water 1", GR_TYPICAL, ["Feraligatr"]),
SpeciesInfo("Feraligatr", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Sentret", "Field", "Field", GR_TYPICAL, ["Furret"]),
SpeciesInfo("Furret", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Hoothoot", "Flying", "Flying", GR_TYPICAL, ["Noctowl"]),
SpeciesInfo("Noctowl", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Spinarak", "Bug", "Bug", GR_TYPICAL, ["Ariados"]),
SpeciesInfo("Ariados", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Chinchou", "Water 2", "Water 2", GR_TYPICAL, ["Lanturn"]),
SpeciesInfo("Lanturn", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Mareep", "Monster", "Field", GR_TYPICAL, ["Flaaffy"]),
SpeciesInfo("Flaaffy", "Monster", "Field", GR_TYPICAL, ["Ampharos"]),
SpeciesInfo("Ampharos", "Monster", "Field", GR_TYPICAL, []),
SpeciesInfo("Azurill", "NED", "NED", GR_TYPICAL, ["Marill"]),
SpeciesInfo("Marill", "Water 1", "Fairy", GR_TYPICAL, ["Azumarill"]),
SpeciesInfo("Azumarill", "Water 1", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Bonsly", "NED", "NED", GR_TYPICAL, ["Sudowoodo"]),
SpeciesInfo("Sudowoodo", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Hoppip", "Fairy", "Grass", GR_TYPICAL, ["Skiploom"]),
SpeciesInfo("Skiploom", "Fairy", "Grass", GR_TYPICAL, ["Jumpluff"]),
SpeciesInfo("Jumpluff", "Fairy", "Grass", GR_TYPICAL, []),
SpeciesInfo("Aipom", "Field", "Field", GR_TYPICAL, ["Ambipom"]),
SpeciesInfo("Ambipom", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Sunkern", "Grass", "Grass", GR_TYPICAL, ["Sunflora"]),
SpeciesInfo("Sunflora", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Yanma", "Bug", "Bug", GR_TYPICAL, ["Yanmega"]),
SpeciesInfo("Yanmega", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Wooper", "Water 1", "Field", GR_TYPICAL, ["Quagsire", "Clodsire"]),
SpeciesInfo("Quagsire", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Clodsire", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Murkrow", "Flying", "Flying", GR_TYPICAL, ["Honchkrow"]),
SpeciesInfo("Honchkrow", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Misdreavus", "Amorphous", "Amorphous", GR_TYPICAL, ["Mismagius"]),
SpeciesInfo("Mismagius", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Girafarig", "Field", "Field", GR_TYPICAL, ["Farigiraf"]),
SpeciesInfo("Farigiraf", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Pineco", "Bug", "Bug", GR_TYPICAL, ["Forretress"]),
SpeciesInfo("Forretress", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Dunsparce", "Field", "Field", GR_TYPICAL, ["Dudunsparce"]),
SpeciesInfo("Dudunsparce", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Gligar", "Bug", "Bug", GR_TYPICAL, ["Gliscor"]),
SpeciesInfo("Gliscor", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Snubbull", "Field", "Fairy", GR_TYPICAL, ["Granbull"]),
SpeciesInfo("Granbull", "Field", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Qwilfish", "Water 2", "Water 2", GR_TYPICAL, ["Overqwil"]),
SpeciesInfo("Overqwil", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Heracross", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Sneasel", "Field", "Field", GR_TYPICAL, ["Weavile", "Sneasler"]),
SpeciesInfo("Weavile", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Sneasler", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Teddiursa", "Field", "Field", GR_TYPICAL, ["Ursaring"]),
SpeciesInfo("Ursaring", "Field", "Field", GR_TYPICAL, ["Ursaluna"]),
SpeciesInfo("Ursaluna", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Slugma", "Amorphous", "Amorphous", GR_TYPICAL, ["Magcargo"]),
SpeciesInfo("Magcargo", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Swinub", "Field", "Field", GR_TYPICAL, ["Piloswine"]),
SpeciesInfo("Piloswine", "Field", "Field", GR_TYPICAL, ["Mamoswine"]),
SpeciesInfo("Mamoswine", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Delibird", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Skarmory", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Houndour", "Field", "Field", GR_TYPICAL, ["Houndoom"]),
SpeciesInfo("Houndoom", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Phanpy", "Field", "Field", GR_TYPICAL, ["Donphan"]),
SpeciesInfo("Donphan", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Stantler", "Field", "Field", GR_TYPICAL, ["Wyrdeer"]),
SpeciesInfo("Wyrdeer", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Smeargle", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Raikou", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Entei", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Suicune", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Larvitar", "Monster", "Monster", GR_TYPICAL, ["Pupitar"]),
SpeciesInfo("Pupitar", "Monster", "Monster", GR_TYPICAL, ["Tyranitar"]),
SpeciesInfo("Tyranitar", "Monster", "Monster", GR_TYPICAL, []),
SpeciesInfo("Lugia", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Ho-Oh", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Treecko", "Monster", "Dragon", GR_TYPICAL, ["Grovyle"]),
SpeciesInfo("Grovyle", "Monster", "Dragon", GR_TYPICAL, ["Sceptile"]),
SpeciesInfo("Sceptile", "Monster", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Torchic", "Field", "Field", GR_TYPICAL, ["Combusken"]),
SpeciesInfo("Combusken", "Field", "Field", GR_TYPICAL, ["Blaziken"]),
SpeciesInfo("Blaziken", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Mudkip", "Monster", "Water 1", GR_TYPICAL, ["Marshtomp"]),
SpeciesInfo("Marshtomp", "Monster", "Water 1", GR_TYPICAL, ["Swampert"]),
SpeciesInfo("Swampert", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Poochyena", "Field", "Field", GR_TYPICAL, ["Mightyena"]),
SpeciesInfo("Mightyena", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Lotad", "Water 1", "Grass", GR_TYPICAL, ["Lombre"]),
SpeciesInfo("Lombre", "Water 1", "Grass", GR_TYPICAL, ["Ludicolo"]),
SpeciesInfo("Ludicolo", "Water 1", "Grass", GR_TYPICAL, []),
SpeciesInfo("Seedot", "Field", "Grass", GR_TYPICAL, ["Nuzleaf"]),
SpeciesInfo("Nuzleaf", "Field", "Grass", GR_TYPICAL, ["Shiftry"]),
SpeciesInfo("Shiftry", "Field", "Grass", GR_TYPICAL, []),
SpeciesInfo("Wingull", "Water 1", "Flying", GR_TYPICAL, ["Pelipper"]),
SpeciesInfo("Pelipper", "Water 1", "Flying", GR_TYPICAL, []),
SpeciesInfo("Ralts", "Human-Like", "Amorphous", GR_TYPICAL, ["Kirlia"]),
SpeciesInfo("Kirlia", "Human-Like", "Amorphous", GR_MALE_ONLY, ["Gardevoir", "Gallade"]),
SpeciesInfo("Gardevoir", "Human-Like", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Gallade", "Human-Like", "Amorphous", GR_MALE_ONLY, []),
SpeciesInfo("Surskit", "Water 1", "Bug", GR_TYPICAL, ["Masquerain"]),
SpeciesInfo("Masquerain", "Water 1", "Bug", GR_TYPICAL, []),
SpeciesInfo("Shroomish", "Fairy", "Grass", GR_TYPICAL, ["Breloom"]),
SpeciesInfo("Breloom", "Fairy", "Grass", GR_TYPICAL, []),
SpeciesInfo("Slakoth", "Field", "Field", GR_TYPICAL, ["Vigoroth"]),
SpeciesInfo("Vigoroth", "Field", "Field", GR_TYPICAL, ["Slaking"]),
SpeciesInfo("Slaking", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Makuhita", "Human-Like", "Human-Like", GR_TYPICAL, ["Hariyama"]),
SpeciesInfo("Hariyama", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Nosepass", "Mineral", "Mineral", GR_TYPICAL, ["Probopass"]),
SpeciesInfo("Probopass", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Sableye", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Meditite", "Human-Like", "Human-Like", GR_TYPICAL, ["Medicham"]),
SpeciesInfo("Medicham", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Plusle", "Fairy", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Minun", "Fairy", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Volbeat", "Bug", "Human-Like", GR_MALE_ONLY, []),
SpeciesInfo("Illumise", "Bug", "Human-Like", GR_FEMALE_ONLY, []),
SpeciesInfo("Gulpin", "Amorphous", "Amorphous", GR_TYPICAL, ["Swalot"]),
SpeciesInfo("Swalot", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Numel", "Field", "Field", GR_TYPICAL, ["Camerupt"]),
SpeciesInfo("Camerupt", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Torkoal", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Spoink", "Field", "Field", GR_TYPICAL, ["Grumpig"]),
SpeciesInfo("Grumpig", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Trapinch", "Bug", "Dragon", GR_TYPICAL, ["Vibrava"]),
SpeciesInfo("Vibrava", "Bug", "Dragon", GR_TYPICAL, ["Flygon"]),
SpeciesInfo("Flygon", "Bug", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Cacnea", "Grass", "Human-Like", GR_TYPICAL, ["Cacturne"]),
SpeciesInfo("Cacturne", "Grass", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Swablu", "Flying", "Dragon", GR_TYPICAL, ["Altaria"]),
SpeciesInfo("Altaria", "Flying", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Zangoose", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Seviper", "Field", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Barboach", "Water 2", "Water 2", GR_TYPICAL, ["Whiscash"]),
SpeciesInfo("Whiscash", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Corphish", "Water 1", "Water 3", GR_TYPICAL, ["Crawdaunt"]),
SpeciesInfo("Crawdaunt", "Water 1", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Feebas", "Water 1", "Dragon", GR_TYPICAL, ["Milotic"]),
SpeciesInfo("Milotic", "Water 1", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Shuppet", "Amorphous", "Amorphous", GR_TYPICAL, ["Banette"]),
SpeciesInfo("Banette", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Duskull", "Amorphous", "Amorphous", GR_TYPICAL, ["Dusclops"]),
SpeciesInfo("Dusclops", "Amorphous", "Amorphous", GR_TYPICAL, ["Dusknoir"]),
SpeciesInfo("Dusknoir", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Tropius", "Monster", "Grass", GR_TYPICAL, []),
SpeciesInfo("Chingling", "NED", "NED", GR_TYPICAL, ["Chimecho"]),
SpeciesInfo("Chimecho", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Snorunt", "Fairy", "Mineral", GR_FEMALE_ONLY, ["Glalie", "Froslass"]),
SpeciesInfo("Glalie", "Fairy", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Froslass", "Fairy", "Mineral", GR_FEMALE_ONLY, []),
SpeciesInfo("Luvdisc", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Bagon", "Dragon", "Dragon", GR_TYPICAL, ["Shelgon"]),
SpeciesInfo("Shelgon", "Dragon", "Dragon", GR_TYPICAL, ["Salamence"]),
SpeciesInfo("Salamence", "Dragon", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Beldum", "Mineral", "Mineral", GR_UNKNOWN, ["Metang"]),
SpeciesInfo("Metang", "Mineral", "Mineral", GR_UNKNOWN, ["Metagross"]),
SpeciesInfo("Metagross", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Regirock", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Regice", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Registeel", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Latias", "NED", "NED", GR_FEMALE_ONLY, []),
SpeciesInfo("Latios", "NED", "NED", GR_MALE_ONLY, []),
SpeciesInfo("Kyogre", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Groudon", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Rayquaza", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Jirachi", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Deoxys", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Turtwig", "Monster", "Grass", GR_TYPICAL, ["Grotle"]),
SpeciesInfo("Grotle", "Monster", "Grass", GR_TYPICAL, ["Torterra"]),
SpeciesInfo("Torterra", "Monster", "Grass", GR_TYPICAL, []),
SpeciesInfo("Chimchar", "Field", "Human-Like", GR_TYPICAL, ["Monferno"]),
SpeciesInfo("Monferno", "Field", "Human-Like", GR_TYPICAL, ["Infernape"]),
SpeciesInfo("Infernape", "Field", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Piplup", "Water 1", "Field", GR_TYPICAL, ["Prinplup"]),
SpeciesInfo("Prinplup", "Water 1", "Field", GR_TYPICAL, ["Empoleon"]),
SpeciesInfo("Empoleon", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Starly", "Flying", "Flying", GR_TYPICAL, ["Staravia"]),
SpeciesInfo("Staravia", "Flying", "Flying", GR_TYPICAL, ["Staraptor"]),
SpeciesInfo("Staraptor", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Kricketot", "Bug", "Bug", GR_TYPICAL, ["Kricketune"]),
SpeciesInfo("Kricketune", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Shinx", "Field", "Field", GR_TYPICAL, ["Luxio"]),
SpeciesInfo("Luxio", "Field", "Field", GR_TYPICAL, ["Luxray"]),
SpeciesInfo("Luxray", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Cranidos", "Monster", "Monster", GR_TYPICAL, ["Rampardos"]),
SpeciesInfo("Rampardos", "Monster", "Monster", GR_TYPICAL, []),
SpeciesInfo("Shieldon", "Monster", "Monster", GR_TYPICAL, ["Bastiodon"]),
SpeciesInfo("Bastiodon", "Monster", "Monster", GR_TYPICAL, []),
SpeciesInfo("Combee", "Bug", "Bug", GR_FEMALE_ONLY, ["Vespiquen"]),
SpeciesInfo("Vespiquen", "Bug", "Bug", GR_FEMALE_ONLY, []),
SpeciesInfo("Pachirisu", "Field", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Buizel", "Water 1", "Field", GR_TYPICAL, ["Floatzel"]),
SpeciesInfo("Floatzel", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Shellos", "Water 1", "Amorphous", GR_TYPICAL, ["Gastrodon"]),
SpeciesInfo("Gastrodon", "Water 1", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Drifloon", "Amorphous", "Amorphous", GR_TYPICAL, ["Drifblim"]),
SpeciesInfo("Drifblim", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Stunky", "Field", "Field", GR_TYPICAL, ["Skuntank"]),
SpeciesInfo("Skuntank", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Bronzor", "Mineral", "Mineral", GR_UNKNOWN, ["Bronzong"]),
SpeciesInfo("Bronzong", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Spiritomb", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Gible", "Monster", "Dragon", GR_TYPICAL, ["Gabite"]),
SpeciesInfo("Gabite", "Monster", "Dragon", GR_TYPICAL, ["Garchomp"]),
SpeciesInfo("Garchomp", "Monster", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Riolu", "NED", "NED", GR_TYPICAL, ["Lucario"]),
SpeciesInfo("Lucario", "Field", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Hippopotas", "Field", "Field", GR_TYPICAL, ["Hippowdon"]),
SpeciesInfo("Hippowdon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Croagunk", "Human-Like", "Human-Like", GR_TYPICAL, ["Toxicroak"]),
SpeciesInfo("Toxicroak", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Finneon", "Water 2", "Water 2", GR_TYPICAL, ["Lumineon"]),
SpeciesInfo("Lumineon", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Snover", "Monster", "Grass", GR_TYPICAL, ["Abomasnow"]),
SpeciesInfo("Abomasnow", "Monster", "Grass", GR_TYPICAL, []),
SpeciesInfo("Rotom", "Amorphous", "Amorphous", GR_UNKNOWN, []),
SpeciesInfo("Uxie", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Mesprit", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Azelf", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Dialga", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Palkia", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Heatran", "NED", "NED", GR_TYPICAL, []),
SpeciesInfo("Regigigas", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Giratina", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Cresselia", "NED", "NED", GR_FEMALE_ONLY, []),
SpeciesInfo("Phione", "Water 1", "Fairy", GR_UNKNOWN, []),
SpeciesInfo("Manaphy", "Water 1", "Fairy", GR_UNKNOWN, []),
SpeciesInfo("Darkrai", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Shaymin", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Arceus", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Snivy", "Field", "Grass", GR_TYPICAL, ["Servine"]),
SpeciesInfo("Servine", "Field", "Grass", GR_TYPICAL, ["Serperior"]),
SpeciesInfo("Serperior", "Field", "Grass", GR_TYPICAL, []),
SpeciesInfo("Tepig", "Field", "Field", GR_TYPICAL, ["Pignite"]),
SpeciesInfo("Pignite", "Field", "Field", GR_TYPICAL, ["Emboar"]),
SpeciesInfo("Emboar", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Oshawott", "Field", "Field", GR_TYPICAL, ["Dewott"]),
SpeciesInfo("Dewott", "Field", "Field", GR_TYPICAL, ["Samurott"]),
SpeciesInfo("Samurott", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Blitzle", "Field", "Field", GR_TYPICAL, ["Zebstrika"]),
SpeciesInfo("Zebstrika", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Drilbur", "Field", "Field", GR_TYPICAL, ["Excadrill"]),
SpeciesInfo("Excadrill", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Timburr", "Human-Like", "Human-Like", GR_TYPICAL, ["Gurdurr"]),
SpeciesInfo("Gurdurr", "Human-Like", "Human-Like", GR_TYPICAL, ["Conkeldurr"]),
SpeciesInfo("Conkeldurr", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Sewaddle", "Bug", "Bug", GR_TYPICAL, ["Swadloon"]),
SpeciesInfo("Swadloon", "Bug", "Bug", GR_TYPICAL, ["Leavanny"]),
SpeciesInfo("Leavanny", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Cottonee", "Grass", "Fairy", GR_TYPICAL, ["Whimsicott"]),
SpeciesInfo("Whimsicott", "Grass", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Petilil", "Grass", "Grass", GR_FEMALE_ONLY, ["Lilligant"]),
SpeciesInfo("Lilligant", "Grass", "Grass", GR_FEMALE_ONLY, []),
SpeciesInfo("Basculin", "Water 2", "Water 2", GR_TYPICAL, ["Basculegion"]),
SpeciesInfo("Basculegion", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Sandile", "Field", "Field", GR_TYPICAL, ["Krokorok"]),
SpeciesInfo("Krokorok", "Field", "Field", GR_TYPICAL, ["Krookodile"]),
SpeciesInfo("Krookodile", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Scraggy", "Field", "Dragon", GR_TYPICAL, ["Scrafty"]),
SpeciesInfo("Scrafty", "Field", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Zorua", "Field", "Field", GR_TYPICAL, ["Zoroark"]),
SpeciesInfo("Zoroark", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Minccino", "Field", "Field", GR_TYPICAL, ["Cinccino"]),
SpeciesInfo("Cinccino", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Gothita", "Human-Like", "Human-Like", GR_TYPICAL, ["Gothorita"]),
SpeciesInfo("Gothorita", "Human-Like", "Human-Like", GR_TYPICAL, ["Gothitelle"]),
SpeciesInfo("Gothitelle", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Solosis", "Amorphous", "Amorphous", GR_TYPICAL, ["Duosion"]),
SpeciesInfo("Duosion", "Amorphous", "Amorphous", GR_TYPICAL, ["Reuniclus"]),
SpeciesInfo("Reuniclus", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Ducklett", "Water 1", "Flying", GR_TYPICAL, ["Swanna"]),
SpeciesInfo("Swanna", "Water 1", "Flying", GR_TYPICAL, []),
SpeciesInfo("Deerling", "Field", "Field", GR_TYPICAL, ["Sawsbuck"]),
SpeciesInfo("Sawsbuck", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Foongus", "Grass", "Grass", GR_TYPICAL, ["Amoonguss"]),
SpeciesInfo("Amoonguss", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Alomomola", "Water 1", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Joltik", "Bug", "Bug", GR_TYPICAL, ["Galvantula"]),
SpeciesInfo("Galvantula", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Tynamo", "Amorphous", "Amorphous", GR_TYPICAL, ["Eelektrik"]),
SpeciesInfo("Eelektrik", "Amorphous", "Amorphous", GR_TYPICAL, ["Eelektross"]),
SpeciesInfo("Eelektross", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Litwick", "Amorphous", "Amorphous", GR_TYPICAL, ["Lampent"]),
SpeciesInfo("Lampent", "Amorphous", "Amorphous", GR_TYPICAL, ["Chandelure"]),
SpeciesInfo("Chandelure", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Axew", "Monster", "Dragon", GR_TYPICAL, ["Fraxure"]),
SpeciesInfo("Fraxure", "Monster", "Dragon", GR_TYPICAL, ["Haxorus"]),
SpeciesInfo("Haxorus", "Monster", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Cubchoo", "Field", "Field", GR_TYPICAL, ["Beartic"]),
SpeciesInfo("Beartic", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Cryogonal", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Mienfoo", "Field", "Human-Like", GR_TYPICAL, ["Mienshao"]),
SpeciesInfo("Mienshao", "Field", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Golett", "Mineral", "Mineral", GR_UNKNOWN, ["Golurk"]),
SpeciesInfo("Golurk", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Pawniard", "Human-Like", "Human-Like", GR_TYPICAL, ["Bisharp"]),
SpeciesInfo("Bisharp", "Human-Like", "Human-Like", GR_TYPICAL, ["Kingambit"]),
SpeciesInfo("Kingambit", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Rufflet", "Flying", "Flying", GR_MALE_ONLY, ["Braviary"]),
SpeciesInfo("Braviary", "Flying", "Flying", GR_MALE_ONLY, []),
SpeciesInfo("Vullaby", "Flying", "Flying", GR_FEMALE_ONLY, ["Mandibuzz"]),
SpeciesInfo("Mandibuzz", "Flying", "Flying", GR_FEMALE_ONLY, []),
SpeciesInfo("Deino", "Dragon", "Dragon", GR_TYPICAL, ["Zweilous"]),
SpeciesInfo("Zweilous", "Dragon", "Dragon", GR_TYPICAL, ["Hydreigon"]),
SpeciesInfo("Hydreigon", "Dragon", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Larvesta", "Bug", "Bug", GR_TYPICAL, ["Volcarona"]),
SpeciesInfo("Volcarona", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Cobalion", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Terrakion", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Virizion", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Tornadus", "NED", "NED", GR_MALE_ONLY, []),
SpeciesInfo("Thundurus", "NED", "NED", GR_MALE_ONLY, []),
SpeciesInfo("Reshiram", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Zekrom", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Landorus", "NED", "NED", GR_MALE_ONLY, []),
SpeciesInfo("Kyurem", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Keldeo", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Meloetta", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Chespin", "Field", "Field", GR_TYPICAL, ["Quilladin"]),
SpeciesInfo("Quilladin", "Field", "Field", GR_TYPICAL, ["Chesnaught"]),
SpeciesInfo("Chesnaught", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Fennekin", "Field", "Field", GR_TYPICAL, ["Braixen"]),
SpeciesInfo("Braixen", "Field", "Field", GR_TYPICAL, ["Delphox"]),
SpeciesInfo("Delphox", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Froakie", "Water 1", "Water 1", GR_TYPICAL, ["Frogadier"]),
SpeciesInfo("Frogadier", "Water 1", "Water 1", GR_TYPICAL, ["Greninja"]),
SpeciesInfo("Greninja", "Water 1", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Fletchling", "Flying", "Flying", GR_TYPICAL, ["Fletchinder"]),
SpeciesInfo("Fletchinder", "Flying", "Flying", GR_TYPICAL, ["Talonflame"]),
SpeciesInfo("Talonflame", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Scatterbug", "Bug", "Bug", GR_TYPICAL, ["Spewpa"]),
SpeciesInfo("Spewpa", "Bug", "Bug", GR_TYPICAL, ["Vivillon"]),
SpeciesInfo("Vivillon", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Litleo", "Field", "Field", GR_TYPICAL, ["Pyroar"]),
SpeciesInfo("Pyroar", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Flabebe", "Fairy", "Fairy", GR_FEMALE_ONLY, ["Floette"]),
SpeciesInfo("Floette", "Fairy", "Fairy", GR_FEMALE_ONLY, ["Florges"]),
SpeciesInfo("Florges", "Fairy", "Fairy", GR_FEMALE_ONLY, []),
SpeciesInfo("Skiddo", "Field", "Field", GR_TYPICAL, ["Gogoat"]),
SpeciesInfo("Gogoat", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Espurr", "Field", "Field", GR_TYPICAL, ["Meowstic"]),
SpeciesInfo("Meowstic", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Inkay", "Water 1", "Water 2", GR_TYPICAL, ["Malamar"]),
SpeciesInfo("Malamar", "Water 1", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Skrelp", "Water 1", "Dragon", GR_TYPICAL, ["Dragalge"]),
SpeciesInfo("Dragalge", "Water 1", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Clauncher", "Water 1", "Water 3", GR_TYPICAL, ["Clawitzer"]),
SpeciesInfo("Clawitzer", "Water 1", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Hawlucha", "Flying", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Dedenne", "Field", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Carbink", "Fairy", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Goomy", "Dragon", "Dragon", GR_TYPICAL, ["Sliggoo"]),
SpeciesInfo("Sliggoo", "Dragon", "Dragon", GR_TYPICAL, ["Goodra"]),
SpeciesInfo("Goodra", "Dragon", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Klefki", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Phantump", "Grass", "Amorphous", GR_TYPICAL, ["Trevenant"]),
SpeciesInfo("Trevenant", "Grass", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Bergmite", "Monster", "Mineral", GR_TYPICAL, ["Avalugg"]),
SpeciesInfo("Avalugg", "Monster", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Noibat", "Flying", "Dragon", GR_TYPICAL, ["Noivern"]),
SpeciesInfo("Noivern", "Flying", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Diancie", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Hoopa", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Volcanion", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Rowlet", "Flying", "Flying", GR_TYPICAL, ["Dartrix"]),
SpeciesInfo("Dartrix", "Flying", "Flying", GR_TYPICAL, ["Decidueye"]),
SpeciesInfo("Decidueye", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Litten", "Field", "Field", GR_TYPICAL, ["Torracat"]),
SpeciesInfo("Torracat", "Field", "Field", GR_TYPICAL, ["Incineroar"]),
SpeciesInfo("Incineroar", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Popplio", "Water 1", "Field", GR_TYPICAL, ["Brionne"]),
SpeciesInfo("Brionne", "Water 1", "Field", GR_TYPICAL, ["Primarina"]),
SpeciesInfo("Primarina", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Pikipek", "Flying", "Flying", GR_TYPICAL, ["Trumbeak"]),
SpeciesInfo("Trumbeak", "Flying", "Flying", GR_TYPICAL, ["Toucannon"]),
SpeciesInfo("Toucannon", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Yungoos", "Field", "Field", GR_TYPICAL, ["Gumshoos"]),
SpeciesInfo("Gumshoos", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Grubbin", "Bug", "Bug", GR_TYPICAL, ["Charjabug"]),
SpeciesInfo("Charjabug", "Bug", "Bug", GR_TYPICAL, ["Vikavolt"]),
SpeciesInfo("Vikavolt", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Crabrawler", "Water 3", "Water 3", GR_TYPICAL, ["Crabominable"]),
SpeciesInfo("Crabominable", "Water 3", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Oricorio", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Cutiefly", "Bug", "Fairy", GR_TYPICAL, ["Ribombee"]),
SpeciesInfo("Ribombee", "Bug", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Rockruff", "Field", "Field", GR_TYPICAL, ["Lycanroc"]),
SpeciesInfo("Lycanroc", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Mareanie", "Water 1", "Water 1", GR_TYPICAL, ["Toxapex"]),
SpeciesInfo("Toxapex", "Water 1", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Mudbray", "Field", "Field", GR_TYPICAL, ["Mudsdale"]),
SpeciesInfo("Mudsdale", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Dewpider", "Water 1", "Bug", GR_TYPICAL, ["Araquanid"]),
SpeciesInfo("Araquanid", "Water 1", "Bug", GR_TYPICAL, []),
SpeciesInfo("Fomantis", "Grass", "Grass", GR_TYPICAL, ["Lurantis"]),
SpeciesInfo("Lurantis", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Salandit", "Monster", "Dragon", GR_FEMALE_ONLY, ["Salazzle"]),
SpeciesInfo("Salazzle", "Monster", "Dragon", GR_FEMALE_ONLY, []),
SpeciesInfo("Bounsweet", "Grass", "Grass", GR_FEMALE_ONLY, ["Steenee"]),
SpeciesInfo("Steenee", "Grass", "Grass", GR_FEMALE_ONLY, ["Tsareena"]),
SpeciesInfo("Tsareena", "Grass", "Grass", GR_FEMALE_ONLY, []),
SpeciesInfo("Comfey", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Oranguru", "Field", "Field", GR_TYPICAL, ["Passimian"]),
SpeciesInfo("Passimian", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Sandygast", "Amorphous", "Amorphous", GR_TYPICAL, ["Palossand"]),
SpeciesInfo("Palossand", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Minior", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Komala", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Mimikyu", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Bruxish", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Jangmo-o", "Dragon", "Dragon", GR_TYPICAL, ["Hakamo-o"]),
SpeciesInfo("Hakamo-o", "Dragon", "Dragon", GR_TYPICAL, ["Kommo-o"]),
SpeciesInfo("Kommo-o", "Dragon", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Cosmog", "NED", "NED", GR_UNKNOWN, ["Cosmoem"]),
SpeciesInfo("Cosmoem", "NED", "NED", GR_UNKNOWN, ["Solgaleo", "Lunala"]),
SpeciesInfo("Solgaleo", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Lunala", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Necrozma", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Magearna", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Grookey", "Field", "Grass", GR_TYPICAL, ["Thwackey"]),
SpeciesInfo("Thwackey", "Field", "Grass", GR_TYPICAL, ["Rillaboom"]),
SpeciesInfo("Rillaboom", "Field", "Grass", GR_TYPICAL, []),
SpeciesInfo("Scorbunny", "Field", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Raboot", "Field", "Human-Like", GR_TYPICAL, ["Cinderace"]),
SpeciesInfo("Cinderace", "Field", "Human-Like", GR_TYPICAL, ["Sobble"]),
SpeciesInfo("Sobble", "Water 1", "Field", GR_TYPICAL, ["Drizzile"]),
SpeciesInfo("Drizzile", "Water 1", "Field", GR_TYPICAL, ["Inteleon"]),
SpeciesInfo("Inteleon", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Skwovet", "Field", "Field", GR_TYPICAL, ["Greedent"]),
SpeciesInfo("Greedent", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Rookidee", "Flying", "Flying", GR_TYPICAL, ["Corvisquire"]),
SpeciesInfo("Corvisquire", "Flying", "Flying", GR_TYPICAL, ["Corviknight"]),
SpeciesInfo("Corviknight", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Chewtle", "Monster", "Water 1", GR_TYPICAL, ["Drednaw"]),
SpeciesInfo("Drednaw", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Rolycoly", "Mineral", "Mineral", GR_TYPICAL, ["Carkol"]),
SpeciesInfo("Carkol", "Mineral", "Mineral", GR_TYPICAL, ["Coalossal"]),
SpeciesInfo("Coalossal", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Applin", "Grass", "Dragon", GR_TYPICAL, ["Flapple", "Appletun", "Dipplin"]),
SpeciesInfo("Flapple", "Grass", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Appletun", "Grass", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Dipplin", "Grass", "Dragon", GR_TYPICAL, ["Hydrapple"]),
SpeciesInfo("Hydrapple", "Grass", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Silicobra", "Field", "Dragon", GR_TYPICAL, ["Sandaconda"]),
SpeciesInfo("Sandaconda", "Field", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Cramorant", "Water 1", "Flying", GR_TYPICAL, []),
SpeciesInfo("Arrokuda", "Water 2", "Water 2", GR_TYPICAL, ["Barraskewda"]),
SpeciesInfo("Barraskewda", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Toxel", "NED", "NED", GR_TYPICAL, ["Toxtricity"]),
SpeciesInfo("Toxtricity", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Sinistea", "Mineral", "Amorphous", GR_UNKNOWN, ["Polteageist"]),
SpeciesInfo("Polteageist", "Mineral", "Amorphous", GR_UNKNOWN, []),
SpeciesInfo("Hatenna", "Fairy", "Fairy", GR_FEMALE_ONLY, ["Hattrem"]),
SpeciesInfo("Hattrem", "Fairy", "Fairy", GR_FEMALE_ONLY, ["Hatterene"]),
SpeciesInfo("Hatterene", "Fairy", "Fairy", GR_FEMALE_ONLY, []),
SpeciesInfo("Impidimp", "Fairy", "Human-Like", GR_MALE_ONLY, ["Morgrem"]),
SpeciesInfo("Morgrem", "Fairy", "Human-Like", GR_MALE_ONLY, ["Grimmsnarl"]),
SpeciesInfo("Grimmsnarl", "Fairy", "Human-Like", GR_MALE_ONLY, []),
SpeciesInfo("Milcery", "Fairy", "Amorphous", GR_FEMALE_ONLY, ["Alcremie"]),
SpeciesInfo("Alcremie", "Fairy", "Amorphous", GR_FEMALE_ONLY, []),
SpeciesInfo("Falinks", "Fairy", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Pincurchin", "Water 1", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Snom", "Bug", "Bug", GR_TYPICAL, ["Frosmoth"]),
SpeciesInfo("Frosmoth", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Stonjourner", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Eiscue", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Indeedee", "Fairy", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Morpeko", "Field", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Cufant", "Field", "Mineral", GR_TYPICAL, ["Copperajah"]),
SpeciesInfo("Copperajah", "Field", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Duraludon", "Mineral", "Dragon", GR_TYPICAL, ["Archaludon"]),
SpeciesInfo("Archaludon", "Mineral", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Dreepy", "Amorphous", "Dragon", GR_TYPICAL, ["Drakloak"]),
SpeciesInfo("Drakloak", "Amorphous", "Dragon", GR_TYPICAL, ["Dragapult"]),
SpeciesInfo("Dragapult", "Amorphous", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Zacian", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Zamazenta", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Eternatus", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Kubfu", "NED", "NED", GR_TYPICAL, ["Urshifu"]),
SpeciesInfo("Urshifu", "NED", "NED", GR_TYPICAL, []),
SpeciesInfo("Zarude", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Regieleki", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Regidrago", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Glastrier", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Spectrier", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Calyrex", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Enamorus", "NED", "NED", GR_FEMALE_ONLY, []),
SpeciesInfo("Sprigatito", "Field", "Grass", GR_TYPICAL, ["Floragato"]),
SpeciesInfo("Floragato", "Field", "Grass", GR_TYPICAL, ["Meowscarada"]),
SpeciesInfo("Meowscarada", "Field", "Grass", GR_TYPICAL, []),
SpeciesInfo("Fuecoco", "Field", "Field", GR_TYPICAL, ["Crocalor"]),
SpeciesInfo("Crocalor", "Field", "Field", GR_TYPICAL, ["Skeledirge"]),
SpeciesInfo("Skeledirge", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Quaxly", "Flying", "Water 1", GR_TYPICAL, ["Quaxwell"]),
SpeciesInfo("Quaxwell", "Flying", "Water 1", GR_TYPICAL, ["Quaquaval"]),
SpeciesInfo("Quaquaval", "Flying", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Lechonk", "Field", "Field", GR_TYPICAL, ["Oinkologne"]),
SpeciesInfo("Oinkologne", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Tarountula", "Bug", "Bug", GR_TYPICAL, ["Spidops"]),
SpeciesInfo("Spidops", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Nymble", "Bug", "Bug", GR_TYPICAL, ["Lokix"]),
SpeciesInfo("Lokix", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Pawmi", "Field", "Field", GR_TYPICAL, ["Pawmo"]),
SpeciesInfo("Pawmo", "Field", "Field", GR_TYPICAL, ["Pawmot"]),
SpeciesInfo("Pawmot", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Tandemaus", "Field", "Fairy", GR_UNKNOWN, ["Maushold"]),
SpeciesInfo("Maushold", "Field", "Fairy", GR_UNKNOWN, []),
SpeciesInfo("Fidough", "Field", "Mineral", GR_TYPICAL, ["Dachsbun"]),
SpeciesInfo("Dachsbun", "Field", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Smoliv", "Grass", "Grass", GR_TYPICAL, ["Dolliv"]),
SpeciesInfo("Dolliv", "Grass", "Grass", GR_TYPICAL, ["Arboliva"]),
SpeciesInfo("Arboliva", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Squawkabilly", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Nacli", "Mineral", "Mineral", GR_TYPICAL, ["Naclstack"]),
SpeciesInfo("Naclstack", "Mineral", "Mineral", GR_TYPICAL, ["Garganacl"]),
SpeciesInfo("Garganacl", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Charcadet", "Human-Like", "Human-Like", GR_TYPICAL, ["Armarouge", "Ceruledge"]),
SpeciesInfo("Armarouge", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Ceruledge", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Tadbulb", "Water 1", "Water 1", GR_TYPICAL, ["Bellibolt"]),
SpeciesInfo("Bellibolt", "Water 1", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Wattrel", "Water 1", "Flying", GR_TYPICAL, ["Kilowattrel"]),
SpeciesInfo("Kilowattrel", "Water 1", "Flying", GR_TYPICAL, []),
SpeciesInfo("Maschiff", "Field", "Field", GR_TYPICAL, ["Mabosstiff"]),
SpeciesInfo("Mabosstiff", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Shroodle", "Field", "Field", GR_TYPICAL, ["Grafaiai"]),
SpeciesInfo("Grafaiai", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Bramblin", "Grass", "Grass", GR_TYPICAL, ["Brambleghast"]),
SpeciesInfo("Brambleghast", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Toedscool", "Grass", "Grass", GR_TYPICAL, ["Toedscruel"]),
SpeciesInfo("Toedscruel", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Klawf", "Water 3", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Capsakid", "Grass", "Grass", GR_TYPICAL, ["Scovillain"]),
SpeciesInfo("Scovillain", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Rellor", "Bug", "Bug", GR_TYPICAL, ["Rabsca"]),
SpeciesInfo("Rabsca", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Flittle", "Flying", "Flying", GR_TYPICAL, ["Espathra"]),
SpeciesInfo("Espathra", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Tinkatink", "Fairy", "Fairy", GR_FEMALE_ONLY, ["Tinkatuff"]),
SpeciesInfo("Tinkatuff", "Fairy", "Fairy", GR_FEMALE_ONLY, ["Tinkaton"]),
SpeciesInfo("Tinkaton", "Fairy", "Fairy", GR_FEMALE_ONLY, []),
SpeciesInfo("Wiglett", "Water 3", "Water 3", GR_TYPICAL, ["Wugtrio"]),
SpeciesInfo("Wugtrio", "Water 3", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Bombirdier", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Finizen", "Field", "Water 2", GR_TYPICAL, ["Palafin"]),
SpeciesInfo("Palafin", "Field", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Varoom", "Mineral", "Mineral", GR_TYPICAL, ["Revavroom"]),
SpeciesInfo("Revavroom", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Cyclizar", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Orthworm", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Glimmet", "Mineral", "Mineral", GR_TYPICAL, ["Glimmora"]),
SpeciesInfo("Glimmora", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Greavard", "Field", "Field", GR_TYPICAL, ["Houndstone"]),
SpeciesInfo("Houndstone", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Flamigo", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Cetoddle", "Field", "Field", GR_TYPICAL, ["Cetitan"]),
SpeciesInfo("Cetitan", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Veluza", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Dondozo", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Tatsugiri", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Great Tusk", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Scream Tail", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Brute Bonnet", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Flutter Mane", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Slither Wing", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Sandy Shocks", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Iron Treads", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Iron Bundle", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Iron Hands", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Iron Jugulis", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Iron Moth", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Iron Thorns", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Frigibax", "Dragon", "Mineral", GR_TYPICAL, ["Arctibax"]),
SpeciesInfo("Arctibax", "Dragon", "Mineral", GR_TYPICAL, ["Baxcalibur"]),
SpeciesInfo("Baxcalibur", "Dragon", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Gimmighoul", "NED", "NED", GR_UNKNOWN, ["Gholdengo"]),
SpeciesInfo("Gholdengo", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Wo-Chien", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Chien-Pao", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Ting-Lu", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Chi-Yu", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Roaring Moon", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Iron Valiant", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Koraidon", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Miraidon", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Walking Wake", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Iron Leaves", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Poltchageist", "Mineral", "Amorphous", GR_UNKNOWN, ["Sinistcha"]),
SpeciesInfo("Sinistcha", "Mineral", "Amorphous", GR_UNKNOWN, []),
SpeciesInfo("Okidogi", "NED", "NED", GR_MALE_ONLY, []),
SpeciesInfo("Munkidori", "NED", "NED", GR_MALE_ONLY, []),
SpeciesInfo("Fezandipiti", "NED", "NED", GR_MALE_ONLY, []),
SpeciesInfo("Ogerpon", "NED", "NED", GR_FEMALE_ONLY, []),
SpeciesInfo("Gouging Fire", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Raging Bolt", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Iron Boulder", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Iron Crown", "NED", "NED", GR_UNKNOWN, []),
SpeciesInfo("Terapagos", "NED", "NED", GR_TYPICAL, []),
SpeciesInfo("Pecharunt", "NED", "NED", GR_UNKNOWN, [])
]
);