const g_Generation1 = Generation(
"====[[Generation I]]====",
GAMECOMBO_ALL_GEN1,
//UniversalTMs
[
"Bide",
"Double Team",
"Rage",
"Rest",
"Toxic"
],
//MonData
[
SpeciesInfo("Bulbasaur", "Monster", "Grass", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Ivysaur", "Monster", "Grass", GR_UNKNOWN, [EvolveData(1)], -1),
SpeciesInfo("Venusaur", "Monster", "Grass", GR_UNKNOWN, [], -2),
SpeciesInfo("Charmander", "Monster", "Dragon", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Charmeleon", "Monster", "Dragon", GR_UNKNOWN, [EvolveData(1)], -1),
SpeciesInfo("Charizard", "Monster", "Dragon", GR_UNKNOWN, [], -2),
SpeciesInfo("Squirtle", "Monster", "Water 1", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Wartortle", "Monster", "Water 1", GR_UNKNOWN, [EvolveData(1)], -1),
SpeciesInfo("Blastoise", "Monster", "Water 1", GR_UNKNOWN, [], -2),
SpeciesInfo("Caterpie", "Bug", "Bug", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Metapod", "Bug", "Bug", GR_UNKNOWN, [EvolveData(1)], -1),
SpeciesInfo("Butterfree", "Bug", "Bug", GR_UNKNOWN, [], -2),
SpeciesInfo("Weedle", "Bug", "Bug", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Kakuna", "Bug", "Bug", GR_UNKNOWN, [EvolveData(1)], -1),
SpeciesInfo("Beedrill", "Bug", "Bug", GR_UNKNOWN, [], -2),
SpeciesInfo("Pidgey", "Flying", "Flying", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Pidgeotto", "Flying", "Flying", GR_UNKNOWN, [EvolveData(1)], -1),
SpeciesInfo("Pidgeot", "Flying", "Flying", GR_UNKNOWN, [], -2),
SpeciesInfo("Rattata", "Field", "Field", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Raticate", "Field", "Field", GR_UNKNOWN, [], -1),
SpeciesInfo("Spearow", "Flying", "Flying", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Fearow", "Flying", "Flying", GR_UNKNOWN, [], -1),
SpeciesInfo("Ekans", "Field", "Dragon", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Arbok", "Field", "Dragon", GR_UNKNOWN, [], -1),
SpeciesInfo("Pikachu", "Field", "Fairy", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Raichu", "Field", "Fairy", GR_UNKNOWN, [], -1),
SpeciesInfo("Sandshrew", "Field", "Field", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Sandslash", "Field", "Field", GR_UNKNOWN, [], -1),
SpeciesInfo("Nidoran F", "Monster", "Field", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Nidorina", "NED", "NED", GR_UNKNOWN, [EvolveData(1)], -1),
SpeciesInfo("Nidoqueen", "NED", "NED", GR_UNKNOWN, [], -2),
SpeciesInfo("Nidoran M", "Monster", "Field", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Nidorino", "Monster", "Field", GR_UNKNOWN, [EvolveData(1)], -1),
SpeciesInfo("Nidoking", "Monster", "Field", GR_UNKNOWN, [], -2),
SpeciesInfo("Clefairy", "Fairy", "Fairy", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Clefable", "Fairy", "Fairy", GR_UNKNOWN, [], -1),
SpeciesInfo("Vulpix", "Field", "Field", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Ninetales", "Field", "Field", GR_UNKNOWN, [], -1),
SpeciesInfo("Jigglypuff", "Fairy", "Fairy", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Wigglytuff", "Fairy", "Fairy", GR_UNKNOWN, [], -1),
SpeciesInfo("Zubat", "Flying", "Flying", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Golbat", "Flying", "Flying", GR_UNKNOWN, [], -1),
SpeciesInfo("Oddish", "Grass", "Grass", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Gloom", "Grass", "Grass", GR_UNKNOWN, [EvolveData(1)], -1),
SpeciesInfo("Vileplume", "Grass", "Grass", GR_UNKNOWN, [], -2),
SpeciesInfo("Paras", "Bug", "Grass", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Parasect", "Bug", "Grass", GR_UNKNOWN, [], -1),
SpeciesInfo("Venonat", "Bug", "Bug", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Venomoth", "Bug", "Bug", GR_UNKNOWN, [], -1),
SpeciesInfo("Diglett", "Field", "Field", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Dugtrio", "Field", "Field", GR_UNKNOWN, [], -1),
SpeciesInfo("Meowth", "Field", "Field", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Persian", "Field", "Field", GR_UNKNOWN, [], -1),
SpeciesInfo("Psyduck", "Water 1", "Field", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Golduck", "Water 1", "Field", GR_UNKNOWN, [], -1),
SpeciesInfo("Mankey", "Field", "Field", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Primeape", "Field", "Field", GR_UNKNOWN, [], -1),
SpeciesInfo("Growlithe", "Field", "Field", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Arcanine", "Field", "Field", GR_UNKNOWN, [], -1),
SpeciesInfo("Poliwag", "Water 1", "Water 1", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Poliwhirl", "Water 1", "Water 1", GR_UNKNOWN, [EvolveData(1)], -1),
SpeciesInfo("Poliwrath", "Water 1", "Water 1", GR_UNKNOWN, [], -2),
SpeciesInfo("Abra", "Human-Like", "Human-Like", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Kadabra", "Human-Like", "Human-Like", GR_UNKNOWN, [EvolveData(1)], -1),
SpeciesInfo("Alakazam", "Human-Like", "Human-Like", GR_UNKNOWN, [], -2),
SpeciesInfo("Machop", "Human-Like", "Human-Like", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Machoke", "Human-Like", "Human-Like", GR_UNKNOWN, [EvolveData(1)], -1),
SpeciesInfo("Machamp", "Human-Like", "Human-Like", GR_UNKNOWN, [], -2),
SpeciesInfo("Bellsprout", "Grass", "Grass", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Weepinbell", "Grass", "Grass", GR_UNKNOWN, [EvolveData(1)], -1),
SpeciesInfo("Victreebel", "Grass", "Grass", GR_UNKNOWN, [], -2),
SpeciesInfo("Tentacool", "Water 3", "Water 3", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Tentacruel", "Water 3", "Water 3", GR_UNKNOWN, [], -1),
SpeciesInfo("Geodude", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Graveler", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], -1),
SpeciesInfo("Golem", "Mineral", "Mineral", GR_UNKNOWN, [], -2),
SpeciesInfo("Ponyta", "Field", "Field", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Rapidash", "Field", "Field", GR_UNKNOWN, [], -1),
SpeciesInfo("Slowpoke", "Monster", "Water 1", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Slowbro", "Monster", "Water 1", GR_UNKNOWN, [], -1),
SpeciesInfo("Magnemite", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Magneton", "Mineral", "Mineral", GR_UNKNOWN, [], -1),
SpeciesInfo("Farfetch'd", "Flying", "Field", GR_UNKNOWN, [], -1),
SpeciesInfo("Doduo", "Flying", "Flying", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Dodrio", "Flying", "Flying", GR_UNKNOWN, [], -1),
SpeciesInfo("Seel", "Water 1", "Field", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Dewgong", "Water 1", "Field", GR_UNKNOWN, [], -1),
SpeciesInfo("Grimer", "Amorphous", "Amorphous", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Muk", "Amorphous", "Amorphous", GR_UNKNOWN, [], -1),
SpeciesInfo("Shellder", "Water 3", "Water 3", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Cloyster", "Water 3", "Water 3", GR_UNKNOWN, [], -1),
SpeciesInfo("Gastly", "Amorphous", "Amorphous", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Haunter", "Amorphous", "Amorphous", GR_UNKNOWN, [EvolveData(1)], -1),
SpeciesInfo("Gengar", "Amorphous", "Amorphous", GR_UNKNOWN, [], -2),
SpeciesInfo("Onix", "Mineral", "Mineral", GR_UNKNOWN, [], 0),
SpeciesInfo("Drowzee", "Human-Like", "Human-Like", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Hypno", "Human-Like", "Human-Like", GR_UNKNOWN, [], -1),
SpeciesInfo("Krabby", "Water 3", "Water 3", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Kingler", "Water 3", "Water 3", GR_UNKNOWN, [], -1),
SpeciesInfo("Voltorb", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Electrode", "Mineral", "Mineral", GR_UNKNOWN, [], -1),
SpeciesInfo("Exeggcute", "Grass", "Grass", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Exeggutor", "Grass", "Grass", GR_UNKNOWN, [], -1),
SpeciesInfo("Cubone", "Monster", "Monster", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Marowak", "Monster", "Monster", GR_UNKNOWN, [], -1),
SpeciesInfo("Hitmonlee", "Human-Like", "Human-Like", GR_UNKNOWN, [], 0),
SpeciesInfo("Hitmonchan", "Human-Like", "Human-Like", GR_UNKNOWN, [], 0),
SpeciesInfo("Lickitung", "Monster", "Monster", GR_UNKNOWN, [], 0),
SpeciesInfo("Koffing", "Amorphous", "Amorphous", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Weezing", "Amorphous", "Amorphous", GR_UNKNOWN, [], -1),
SpeciesInfo("Rhyhorn", "Monster", "Field", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Rhydon", "Monster", "Field", GR_UNKNOWN, [], -1),
SpeciesInfo("Chansey", "Fairy", "Fairy", GR_UNKNOWN, [], 0),
SpeciesInfo("Tangela", "Grass", "Grass", GR_UNKNOWN, [], 0),
SpeciesInfo("Kangaskhan", "Monster", "Monster", GR_UNKNOWN, [], 0),
SpeciesInfo("Horsea", "Water 1", "Dragon", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Seadra", "Water 1", "Dragon", GR_UNKNOWN, [], -1),
SpeciesInfo("Goldeen", "Water 2", "Water 2", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Seaking", "Water 2", "Water 2", GR_UNKNOWN, [], -1),
SpeciesInfo("Staryu", "Water 3", "Water 3", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Starmie", "Water 3", "Water 3", GR_UNKNOWN, [], -1),
SpeciesInfo("Mr. Mime", "Human-Like", "Human-Like", GR_UNKNOWN, [], 0),
SpeciesInfo("Scyther", "Bug", "Bug", GR_UNKNOWN, [], 0),
SpeciesInfo("Jynx", "Human-Like", "Human-Like", GR_UNKNOWN, [], 0),
SpeciesInfo("Electabuzz", "Human-Like", "Human-Like", GR_UNKNOWN, [], 0),
SpeciesInfo("Magmar", "Human-Like", "Human-Like", GR_UNKNOWN, [], 0),
SpeciesInfo("Pinsir", "Bug", "Bug", GR_UNKNOWN, [], 0),
SpeciesInfo("Tauros", "Field", "Field", GR_UNKNOWN, [], 0),
SpeciesInfo("Magikarp", "Water 2", "Dragon", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Gyarados", "Water 2", "Dragon", GR_UNKNOWN, [], -1),
SpeciesInfo("Lapras", "Monster", "Water 1", GR_UNKNOWN, [], 0),
SpeciesInfo("Ditto", "Ditto", "Ditto", GR_UNKNOWN, [], 0),
SpeciesInfo("Eevee", "Field", "Field", GR_UNKNOWN, [EvolveData(1), EvolveData(2), EvolveData(3)], 0),
SpeciesInfo("Vaporeon", "Field", "Field", GR_UNKNOWN, [], -1),
SpeciesInfo("Jolteon", "Field", "Field", GR_UNKNOWN, [], -2),
SpeciesInfo("Flareon", "Field", "Field", GR_UNKNOWN, [], -3),
SpeciesInfo("Porygon", "Mineral", "Mineral", GR_UNKNOWN, [], 0),
SpeciesInfo("Omanyte", "Water 1", "Water 3", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Omastar", "Water 1", "Water 3", GR_UNKNOWN, [], -1),
SpeciesInfo("Kabuto", "Water 1", "Water 3", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Kabutops", "Water 1", "Water 3", GR_UNKNOWN, [], -1),
SpeciesInfo("Aerodactyl", "Flying", "Flying", GR_UNKNOWN, [], 0),
SpeciesInfo("Snorlax", "Monster", "Monster", GR_UNKNOWN, [], 0),
SpeciesInfo("Articuno", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Zapdos", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Moltres", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Dratini", "Water 1", "Dragon", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Dragonair", "Water 1", "Dragon", GR_UNKNOWN, [EvolveData(1)], -1),
SpeciesInfo("Dragonite", "Water 1", "Dragon", GR_UNKNOWN, [], -2),
SpeciesInfo("Mewtwo", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Mew", "NED", "NED", GR_UNKNOWN, [], 0)
]
);