const g_Generation2 = Generation(
"====[[Generation II]]====",
GAMECOMBO_ALL_GEN2,
//UniversalTMs
//NOTE: Curse is technically a universal TM in gen 2, but since Bulbapedia doesn't treat it like one, we don't either
[
"Attract",
"Double Team",
"Endure",
"Frustration",
"Hidden Power",
"Protect",
"Rest",
"Return",
"Sleep Talk",
"Snore",
"Swagger",
"Toxic"
],
//MonData
[
SpeciesInfo("Bulbasaur", "Monster", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Ivysaur", "Monster", "Grass", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Venusaur", "Monster", "Grass", GR_TYPICAL, [], -2, []),
SpeciesInfo("Charmander", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Charmeleon", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Charizard", "Monster", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Squirtle", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Wartortle", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Blastoise", "Monster", "Water 1", GR_TYPICAL, [], -2, []),
SpeciesInfo("Caterpie", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Metapod", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Butterfree", "Bug", "Bug", GR_TYPICAL, [], -2, []),
SpeciesInfo("Weedle", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Kakuna", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Beedrill", "Bug", "Bug", GR_TYPICAL, [], -2, []),
SpeciesInfo("Pidgey", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Pidgeotto", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Pidgeot", "Flying", "Flying", GR_TYPICAL, [], -2, []),
SpeciesInfo("Rattata", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Raticate", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Spearow", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Fearow", "Flying", "Flying", GR_TYPICAL, [], -1, []),
SpeciesInfo("Ekans", "Field", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Arbok", "Field", "Dragon", GR_TYPICAL, [], -1, []),
SpeciesInfo("Pichu", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Pikachu", "Field", "Fairy", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Raichu", "Field", "Fairy", GR_TYPICAL, [], -2, []),
SpeciesInfo("Sandshrew", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Sandslash", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Nidoran F", "Monster", "Field", GR_FEMALE_ONLY, [EvolveData(1)], 0, []),
SpeciesInfo("Nidorina", "NED", "NED", GR_FEMALE_ONLY, [EvolveData(1)], -1, []),
SpeciesInfo("Nidoqueen", "NED", "NED", GR_FEMALE_ONLY, [], -2, []),
SpeciesInfo("Nidoran M", "Monster", "Field", GR_MALE_ONLY, [EvolveData(1)], 0, []),
SpeciesInfo("Nidorino", "Monster", "Field", GR_MALE_ONLY, [EvolveData(1)], -1, []),
SpeciesInfo("Nidoking", "Monster", "Field", GR_MALE_ONLY, [], -2, []),
SpeciesInfo("Cleffa", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Clefairy", "Fairy", "Fairy", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Clefable", "Fairy", "Fairy", GR_TYPICAL, [], -2, []),
SpeciesInfo("Vulpix", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Ninetales", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Igglybuff", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Jigglypuff", "Fairy", "Fairy", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Wigglytuff", "Fairy", "Fairy", GR_TYPICAL, [], -2, []),
SpeciesInfo("Zubat", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Golbat", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Crobat", "Flying", "Flying", GR_TYPICAL, [], -2, []),
SpeciesInfo("Oddish", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Gloom", "Grass", "Grass", GR_TYPICAL, [EvolveData(1), EvolveData(2)], -1, []),
SpeciesInfo("Vileplume", "Grass", "Grass", GR_TYPICAL, [], -2, []),
SpeciesInfo("Bellossom", "Grass", "Grass", GR_TYPICAL, [], -3, []),
SpeciesInfo("Paras", "Bug", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Parasect", "Bug", "Grass", GR_TYPICAL, [], -1, []),
SpeciesInfo("Venonat", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Venomoth", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Diglett", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Dugtrio", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Meowth", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Persian", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Psyduck", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Golduck", "Water 1", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Mankey", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Primeape", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Growlithe", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Arcanine", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Poliwag", "Water 1", "Water 1", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Poliwhirl", "Water 1", "Water 1", GR_TYPICAL, [EvolveData(1), EvolveData(2)], -1, []),
SpeciesInfo("Poliwrath", "Water 1", "Water 1", GR_TYPICAL, [], -2, []),
SpeciesInfo("Politoed", "Water 1", "Water 1", GR_TYPICAL, [], -3, []),
SpeciesInfo("Abra", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Kadabra", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Alakazam", "Human-Like", "Human-Like", GR_TYPICAL, [], -2, []),
SpeciesInfo("Machop", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Machoke", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Machamp", "Human-Like", "Human-Like", GR_TYPICAL, [], -2, []),
SpeciesInfo("Bellsprout", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Weepinbell", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Victreebel", "Grass", "Grass", GR_TYPICAL, [], -2, []),
SpeciesInfo("Tentacool", "Water 3", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Tentacruel", "Water 3", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Geodude", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Graveler", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Golem", "Mineral", "Mineral", GR_TYPICAL, [], -2, []),
SpeciesInfo("Ponyta", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Rapidash", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Slowpoke", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1), EvolveData(2)], 0, []),
SpeciesInfo("Slowbro", "Monster", "Water 1", GR_TYPICAL, [], -1, []),
SpeciesInfo("Slowking", "Monster", "Water 1", GR_TYPICAL, [], -2, []),
SpeciesInfo("Magnemite", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Magneton", "Mineral", "Mineral", GR_UNKNOWN, [], -1, []),
SpeciesInfo("Farfetch'd", "Flying", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Doduo", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Dodrio", "Flying", "Flying", GR_TYPICAL, [], -1, []),
SpeciesInfo("Seel", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Dewgong", "Water 1", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Grimer", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Muk", "Amorphous", "Amorphous", GR_TYPICAL, [], -1, []),
SpeciesInfo("Shellder", "Water 3", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Cloyster", "Water 3", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Gastly", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Haunter", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Gengar", "Amorphous", "Amorphous", GR_TYPICAL, [], -2, []),
SpeciesInfo("Onix", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Steelix", "Mineral", "Mineral", GR_TYPICAL, [], -1, []),
SpeciesInfo("Drowzee", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Hypno", "Human-Like", "Human-Like", GR_TYPICAL, [], -1, []),
SpeciesInfo("Krabby", "Water 3", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Kingler", "Water 3", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Voltorb", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Electrode", "Mineral", "Mineral", GR_UNKNOWN, [], -1, []),
SpeciesInfo("Exeggcute", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Exeggutor", "Grass", "Grass", GR_TYPICAL, [], -1, []),
SpeciesInfo("Cubone", "Monster", "Monster", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Marowak", "Monster", "Monster", GR_TYPICAL, [], -1, []),
SpeciesInfo("Tyrogue", "NED", "NED", GR_MALE_ONLY, [EvolveData(1), EvolveData(2), EvolveData(3)], 0, []),
SpeciesInfo("Hitmonlee", "Human-Like", "Human-Like", GR_MALE_ONLY, [], -1, []),
SpeciesInfo("Hitmonchan", "Human-Like", "Human-Like", GR_MALE_ONLY, [], -2, []),
SpeciesInfo("Hitmontop", "Human-Like", "Human-Like", GR_MALE_ONLY, [], -3, []),
SpeciesInfo("Lickitung", "Monster", "Monster", GR_TYPICAL, [], 0, []),
SpeciesInfo("Koffing", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Weezing", "Amorphous", "Amorphous", GR_TYPICAL, [], -1, []),
SpeciesInfo("Rhyhorn", "Monster", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Rhydon", "Monster", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Chansey", "Fairy", "Fairy", GR_FEMALE_ONLY, [EvolveData(1)], 0, []),
SpeciesInfo("Blissey", "Fairy", "Fairy", GR_FEMALE_ONLY, [], -1, []),
SpeciesInfo("Tangela", "Grass", "Grass", GR_TYPICAL, [], 0, []),
SpeciesInfo("Kangaskhan", "Monster", "Monster", GR_FEMALE_ONLY, [], 0, []),
SpeciesInfo("Horsea", "Water 1", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Seadra", "Water 1", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Kingdra", "Water 1", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Goldeen", "Water 2", "Water 2", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Seaking", "Water 2", "Water 2", GR_TYPICAL, [], -1, []),
SpeciesInfo("Staryu", "Water 3", "Water 3", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Starmie", "Water 3", "Water 3", GR_UNKNOWN, [], -1, []),
SpeciesInfo("Mr. Mime", "Human-Like", "Human-Like", GR_TYPICAL, [], 0, []),
SpeciesInfo("Scyther", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Scizor", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Smoochum", "NED", "NED", GR_FEMALE_ONLY, [EvolveData(1)], 0, []),
SpeciesInfo("Jynx", "Human-Like", "Human-Like", GR_FEMALE_ONLY, [], -1, []),
SpeciesInfo("Elekid", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Electabuzz", "Human-Like", "Human-Like", GR_TYPICAL, [], -1, []),
SpeciesInfo("Magby", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Magmar", "Human-Like", "Human-Like", GR_TYPICAL, [], -1, []),
SpeciesInfo("Pinsir", "Bug", "Bug", GR_TYPICAL, [], 0, []),
SpeciesInfo("Tauros", "Field", "Field", GR_MALE_ONLY, [], 0, []),
SpeciesInfo("Magikarp", "Water 2", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Gyarados", "Water 2", "Dragon", GR_TYPICAL, [], -1, []),
SpeciesInfo("Lapras", "Monster", "Water 1", GR_TYPICAL, [], 0, []),
SpeciesInfo("Ditto", "Ditto", "Ditto", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Eevee", "Field", "Field", GR_TYPICAL, [EvolveData(1), EvolveData(2), EvolveData(3), EvolveData(4), EvolveData(5)], 0, []),
SpeciesInfo("Vaporeon", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Jolteon", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Flareon", "Field", "Field", GR_TYPICAL, [], -3, []),
SpeciesInfo("Espeon", "Field", "Field", GR_TYPICAL, [], -4, []),
SpeciesInfo("Umbreon", "Field", "Field", GR_TYPICAL, [], -5, []),
SpeciesInfo("Porygon", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Porygon2", "Mineral", "Mineral", GR_UNKNOWN, [], -1, []),
SpeciesInfo("Omanyte", "Water 1", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Omastar", "Water 1", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Kabuto", "Water 1", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Kabutops", "Water 1", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Aerodactyl", "Flying", "Flying", GR_TYPICAL, [], 0, []),
SpeciesInfo("Snorlax", "Monster", "Monster", GR_TYPICAL, [], 0, []),
SpeciesInfo("Articuno", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Zapdos", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Moltres", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Dratini", "Water 1", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Dragonair", "Water 1", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Dragonite", "Water 1", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Mewtwo", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Mew", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Chikorita", "Monster", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Bayleef", "Monster", "Grass", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Meganium", "Monster", "Grass", GR_TYPICAL, [], -2, []),
SpeciesInfo("Cyndaquil", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Quilava", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Typhlosion", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Totodile", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Croconaw", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Feraligatr", "Monster", "Water 1", GR_TYPICAL, [], -2, []),
SpeciesInfo("Sentret", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Furret", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Hoothoot", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Noctowl", "Flying", "Flying", GR_TYPICAL, [], -1, []),
SpeciesInfo("Ledyba", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Ledian", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Spinarak", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Ariados", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Chinchou", "Water 2", "Water 2", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Lanturn", "Water 2", "Water 2", GR_TYPICAL, [], -1, []),
SpeciesInfo("Togepi", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Togetic", "Flying", "Fairy", GR_TYPICAL, [], -1, []),
SpeciesInfo("Natu", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Xatu", "Flying", "Flying", GR_TYPICAL, [], -1, []),
SpeciesInfo("Mareep", "Monster", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Flaaffy", "Monster", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Ampharos", "Monster", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Marill", "Water 1", "Fairy", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Azumarill", "Water 1", "Fairy", GR_TYPICAL, [], -1, []),
SpeciesInfo("Sudowoodo", "Mineral", "Mineral", GR_TYPICAL, [], 0, []),
SpeciesInfo("Hoppip", "Fairy", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Skiploom", "Fairy", "Grass", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Jumpluff", "Fairy", "Grass", GR_TYPICAL, [], -2, []),
SpeciesInfo("Aipom", "Field", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Sunkern", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Sunflora", "Grass", "Grass", GR_TYPICAL, [], -1, []),
SpeciesInfo("Yanma", "Bug", "Bug", GR_TYPICAL, [], 0, []),
SpeciesInfo("Wooper", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Quagsire", "Water 1", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Murkrow", "Flying", "Flying", GR_TYPICAL, [], 0, []),
SpeciesInfo("Misdreavus", "Amorphous", "Amorphous", GR_TYPICAL, [], 0, []),
SpeciesInfo("Unown", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Wobbuffet", "Amorphous", "Amorphous", GR_TYPICAL, [], 0, []),
SpeciesInfo("Girafarig", "Field", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Pineco", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Forretress", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Dunsparce", "Field", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Gligar", "Bug", "Bug", GR_TYPICAL, [], 0, []),
SpeciesInfo("Snubbull", "Field", "Fairy", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Granbull", "Field", "Fairy", GR_TYPICAL, [], -1, []),
SpeciesInfo("Qwilfish", "Water 2", "Water 2", GR_TYPICAL, [], 0, []),
SpeciesInfo("Shuckle", "Bug", "Bug", GR_TYPICAL, [], 0, []),
SpeciesInfo("Heracross", "Bug", "Bug", GR_TYPICAL, [], 0, []),
SpeciesInfo("Sneasel", "Field", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Teddiursa", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Ursaring", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Slugma", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Magcargo", "Amorphous", "Amorphous", GR_TYPICAL, [], -1, []),
SpeciesInfo("Swinub", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Piloswine", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Corsola", "Water 1", "Water 3", GR_TYPICAL, [], 0, []),
SpeciesInfo("Remoraid", "Water 1", "Water 2", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Octillery", "Water 1", "Water 2", GR_TYPICAL, [], -1, []),
SpeciesInfo("Delibird", "Water 1", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Mantine", "Water 1", "Water 1", GR_TYPICAL, [], 0, []),
SpeciesInfo("Skarmory", "Flying", "Flying", GR_TYPICAL, [], 0, []),
SpeciesInfo("Houndour", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Houndoom", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Phanpy", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Donphan", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Stantler", "Field", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Smeargle", "Field", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Miltank", "Field", "Field", GR_FEMALE_ONLY, [], 0, []),
SpeciesInfo("Raikou", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Entei", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Suicune", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Larvitar", "Monster", "Monster", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Pupitar", "Monster", "Monster", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Tyranitar", "Monster", "Monster", GR_TYPICAL, [], -2, []),
SpeciesInfo("Lugia", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Ho-Oh", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Celebi", "NED", "NED", GR_UNKNOWN, [], 0, [])
]
);
const g_MovesNewInGen2 =
[
"Sketch",
"Triple Kick",
"Thief",
"Spider Web",
"Mind Reader",
"Nightmare",
"Flame Wheel",
"Snore",
"Curse",
"Flail",
"Conversion 2",
"Aeroblast",
"Cotton Spore",
"Reversal",
"Spite",
"Powder Snow",
"Protect",
"Mach Punch",
"Scary Face",
"Feint Attack",
"Sweet Kiss",
"Belly Drum",
"Sludge Bomb",
"Mud-Slap",
"Octazooka",
"Spikes",
"Zap Cannon",
"Foresight",
"Destiny Bond",
"Perish Song",
"Icy Wind",
"Detect",
"Bone Rush",
"Lock-On",
"Outrage",
"Sandstorm",
"Giga Drain",
"Endure",
"Charm",
"Rollout",
"False Swipe",
"Swagger",
"Milk Drink",
"Spark",
"Fury Cutter",
"Steel Wing",
"Mean Look",
"Attract",
"Sleep Talk",
"Heal Bell",
"Return",
"Present",
"Frustration",
"Safeguard",
"Pain Split",
"Sacred Fire",
"Magnitude",
"Dynamic Punch",
"Megahorn",
"Dragon Breath",
"Baton Pass",
"Encore",
"Pursuit",
"Rapid Spin",
"Sweet Scent",
"Iron Tail",
"Metal Claw",
"Vital Throw",
"Morning Sun",
"Synthesis",
"Moonlight",
"Hidden Power",
"Cross Chop",
"Twister",
"Rain Dance",
"Sunny Day",
"Crunch",
"Mirror Coat",
"Psych Up",
"Extreme Speed",
"Ancient Power",
"Shadow Ball",
"Future Sight",
"Rock Smash",
"Whirlpool",
"Beat Up"
];