const g_Generation2 = Generation(
"====[[Generation II]]====",
GAMECOMBO_ALL_GEN2,
//UniversalTMs
//NOTE: Curse is technically a universal TM in gen 2, but since Bulbapedia doesn't treat it like one, we don't either
[
"Attract",
"Double Team",
"Endure",
"Frustration",
"Hidden Power",
"Protect",
"Rest",
"Return",
"Sleep Talk",
"Snore",
"Swagger",
"Toxic"
],
//MonData
[
SpeciesInfo("Bulbasaur", "Monster", "Grass", GR_TYPICAL, ["Ivysaur"]),
SpeciesInfo("Ivysaur", "Monster", "Grass", GR_TYPICAL, ["Venusaur"]),
SpeciesInfo("Venusaur", "Monster", "Grass", GR_TYPICAL, []),
SpeciesInfo("Charmander", "Monster", "Dragon", GR_TYPICAL, ["Charmeleon"]),
SpeciesInfo("Charmeleon", "Monster", "Dragon", GR_TYPICAL, ["Charizard"]),
SpeciesInfo("Charizard", "Monster", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Squirtle", "Monster", "Water 1", GR_TYPICAL, ["Wartortle"]),
SpeciesInfo("Wartortle", "Monster", "Water 1", GR_TYPICAL, ["Blastoise"]),
SpeciesInfo("Blastoise", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Caterpie", "Bug", "Bug", GR_TYPICAL, ["Metapod"]),
SpeciesInfo("Metapod", "Bug", "Bug", GR_TYPICAL, ["Butterfree"]),
SpeciesInfo("Butterfree", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Weedle", "Bug", "Bug", GR_TYPICAL, ["Kakuna"]),
SpeciesInfo("Kakuna", "Bug", "Bug", GR_TYPICAL, ["Beedrill"]),
SpeciesInfo("Beedrill", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Pidgey", "Flying", "Flying", GR_TYPICAL, ["Pidgeotto"]),
SpeciesInfo("Pidgeotto", "Flying", "Flying", GR_TYPICAL, ["Pidgeot"]),
SpeciesInfo("Pidgeot", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Rattata", "Field", "Field", GR_TYPICAL, ["Raticate"]),
SpeciesInfo("Raticate", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Spearow", "Flying", "Flying", GR_TYPICAL, ["Fearow"]),
SpeciesInfo("Fearow", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Ekans", "Field", "Dragon", GR_TYPICAL, ["Arbok"]),
SpeciesInfo("Arbok", "Field", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Pichu", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, ["Pikachu"]),
SpeciesInfo("Pikachu", "Field", "Fairy", GR_TYPICAL, ["Raichu"]),
SpeciesInfo("Raichu", "Field", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Sandshrew", "Field", "Field", GR_TYPICAL, ["Sandslash"]),
SpeciesInfo("Sandslash", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Nidoran F", "Monster", "Field", GR_FEMALE_ONLY, ["Nidorina"]),
SpeciesInfo("Nidorina", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, ["Nidoqueen"]),
SpeciesInfo("Nidoqueen", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, []),
SpeciesInfo("Nidoran M", "Monster", "Field", GR_MALE_ONLY, ["Nidorino"]),
SpeciesInfo("Nidorino", "Monster", "Field", GR_MALE_ONLY, ["Nidoking"]),
SpeciesInfo("Nidoking", "Monster", "Field", GR_MALE_ONLY, []),
SpeciesInfo("Cleffa", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, ["Clefairy"]),
SpeciesInfo("Clefairy", "Fairy", "Fairy", GR_TYPICAL, ["Clefable"]),
SpeciesInfo("Clefable", "Fairy", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Vulpix", "Field", "Field", GR_TYPICAL, ["Ninetales"]),
SpeciesInfo("Ninetales", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Igglybuff", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, ["Jigglypuff"]),
SpeciesInfo("Jigglypuff", "Fairy", "Fairy", GR_TYPICAL, ["Wigglytuff"]),
SpeciesInfo("Wigglytuff", "Fairy", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Zubat", "Flying", "Flying", GR_TYPICAL, ["Golbat"]),
SpeciesInfo("Golbat", "Flying", "Flying", GR_TYPICAL, ["Crobat"]),
SpeciesInfo("Crobat", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Oddish", "Grass", "Grass", GR_TYPICAL, ["Gloom"]),
SpeciesInfo("Gloom", "Grass", "Grass", GR_TYPICAL, ["Vileplume", "Bellossom"]),
SpeciesInfo("Vileplume", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Bellossom", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Paras", "Bug", "Grass", GR_TYPICAL, ["Parasect"]),
SpeciesInfo("Parasect", "Bug", "Grass", GR_TYPICAL, []),
SpeciesInfo("Venonat", "Bug", "Bug", GR_TYPICAL, ["Venomoth"]),
SpeciesInfo("Venomoth", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Diglett", "Field", "Field", GR_TYPICAL, ["Dugtrio"]),
SpeciesInfo("Dugtrio", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Meowth", "Field", "Field", GR_TYPICAL, ["Persian"]),
SpeciesInfo("Persian", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Psyduck", "Water 1", "Field", GR_TYPICAL, ["Golduck"]),
SpeciesInfo("Golduck", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Mankey", "Field", "Field", GR_TYPICAL, ["Primeape"]),
SpeciesInfo("Primeape", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Growlithe", "Field", "Field", GR_TYPICAL, ["Arcanine"]),
SpeciesInfo("Arcanine", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Poliwag", "Water 1", "Water 1", GR_TYPICAL, ["Poliwhirl"]),
SpeciesInfo("Poliwhirl", "Water 1", "Water 1", GR_TYPICAL, ["Poliwrath", "Politoed"]),
SpeciesInfo("Poliwrath", "Water 1", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Politoed", "Water 1", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Abra", "Human-Like", "Human-Like", GR_TYPICAL, ["Kadabra"]),
SpeciesInfo("Kadabra", "Human-Like", "Human-Like", GR_TYPICAL, ["Alakazam"]),
SpeciesInfo("Alakazam", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Machop", "Human-Like", "Human-Like", GR_TYPICAL, ["Machoke"]),
SpeciesInfo("Machoke", "Human-Like", "Human-Like", GR_TYPICAL, ["Machamp"]),
SpeciesInfo("Machamp", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Bellsprout", "Grass", "Grass", GR_TYPICAL, ["Weepinbell"]),
SpeciesInfo("Weepinbell", "Grass", "Grass", GR_TYPICAL, ["Victreebel"]),
SpeciesInfo("Victreebel", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Tentacool", "Water 3", "Water 3", GR_TYPICAL, ["Tentacruel"]),
SpeciesInfo("Tentacruel", "Water 3", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Geodude", "Mineral", "Mineral", GR_TYPICAL, ["Graveler"]),
SpeciesInfo("Graveler", "Mineral", "Mineral", GR_TYPICAL, ["Golem"]),
SpeciesInfo("Golem", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Ponyta", "Field", "Field", GR_TYPICAL, ["Rapidash"]),
SpeciesInfo("Rapidash", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Slowpoke", "Monster", "Water 1", GR_TYPICAL, ["Slowbro", "Slowking"]),
SpeciesInfo("Slowbro", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Slowking", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Magnemite", "Mineral", "Mineral", GR_UNKNOWN, ["Magneton"]),
SpeciesInfo("Magneton", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Farfetch'd", "Flying", "Field", GR_TYPICAL, []),
SpeciesInfo("Doduo", "Flying", "Flying", GR_TYPICAL, ["Dodrio"]),
SpeciesInfo("Dodrio", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Seel", "Water 1", "Field", GR_TYPICAL, ["Dewgong"]),
SpeciesInfo("Dewgong", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Grimer", "Amorphous", "Amorphous", GR_TYPICAL, ["Muk"]),
SpeciesInfo("Muk", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Shellder", "Water 3", "Water 3", GR_TYPICAL, ["Cloyster"]),
SpeciesInfo("Cloyster", "Water 3", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Gastly", "Amorphous", "Amorphous", GR_TYPICAL, ["Haunter"]),
SpeciesInfo("Haunter", "Amorphous", "Amorphous", GR_TYPICAL, ["Gengar"]),
SpeciesInfo("Gengar", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Onix", "Mineral", "Mineral", GR_TYPICAL, ["Steelix"]),
SpeciesInfo("Steelix", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Drowzee", "Human-Like", "Human-Like", GR_TYPICAL, ["Hypno"]),
SpeciesInfo("Hypno", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Krabby", "Water 3", "Water 3", GR_TYPICAL, ["Kingler"]),
SpeciesInfo("Kingler", "Water 3", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Voltorb", "Mineral", "Mineral", GR_UNKNOWN, ["Electrode"]),
SpeciesInfo("Electrode", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Exeggcute", "Grass", "Grass", GR_TYPICAL, ["Exeggutor"]),
SpeciesInfo("Exeggutor", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Cubone", "Monster", "Monster", GR_TYPICAL, ["Marowak"]),
SpeciesInfo("Marowak", "Monster", "Monster", GR_TYPICAL, []),
SpeciesInfo("Tyrogue", "No Eggs Discovered", "No Eggs Discovered", GR_MALE_ONLY, ["Hitmonlee", "Hitmonchan", "Hitmontop"]),
SpeciesInfo("Hitmonlee", "Human-Like", "Human-Like", GR_MALE_ONLY, []),
SpeciesInfo("Hitmonchan", "Human-Like", "Human-Like", GR_MALE_ONLY, []),
SpeciesInfo("Hitmontop", "Human-Like", "Human-Like", GR_MALE_ONLY, []),
SpeciesInfo("Lickitung", "Monster", "Monster", GR_TYPICAL, []),
SpeciesInfo("Koffing", "Amorphous", "Amorphous", GR_TYPICAL, ["Weezing"]),
SpeciesInfo("Weezing", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Rhyhorn", "Monster", "Field", GR_TYPICAL, ["Rhydon"]),
SpeciesInfo("Rhydon", "Monster", "Field", GR_TYPICAL, []),
SpeciesInfo("Chansey", "Fairy", "Fairy", GR_FEMALE_ONLY, ["Blissey"]),
SpeciesInfo("Blissey", "Fairy", "Fairy", GR_FEMALE_ONLY, []),
SpeciesInfo("Tangela", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Kangaskhan", "Monster", "Monster", GR_FEMALE_ONLY, []),
SpeciesInfo("Horsea", "Water 1", "Dragon", GR_TYPICAL, ["Seadra"]),
SpeciesInfo("Seadra", "Water 1", "Dragon", GR_TYPICAL, ["Kingdra"]),
SpeciesInfo("Kingdra", "Water 1", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Goldeen", "Water 2", "Water 2", GR_TYPICAL, ["Seaking"]),
SpeciesInfo("Seaking", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Staryu", "Water 3", "Water 3", GR_UNKNOWN, ["Starmie"]),
SpeciesInfo("Starmie", "Water 3", "Water 3", GR_UNKNOWN, []),
SpeciesInfo("Mr. Mime", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Scyther", "Bug", "Bug", GR_TYPICAL, ["Scizor"]),
SpeciesInfo("Scizor", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Smoochum", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, ["Jynx"]),
SpeciesInfo("Jynx", "Human-Like", "Human-Like", GR_FEMALE_ONLY, []),
SpeciesInfo("Elekid", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, ["Electabuzz"]),
SpeciesInfo("Electabuzz", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Magby", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, ["Magmar"]),
SpeciesInfo("Magmar", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Pinsir", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Tauros", "Field", "Field", GR_MALE_ONLY, []),
SpeciesInfo("Magikarp", "Water 2", "Dragon", GR_TYPICAL, ["Gyarados"]),
SpeciesInfo("Gyarados", "Water 2", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Lapras", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Ditto", "Ditto", "Ditto", GR_UNKNOWN, []),
SpeciesInfo("Eevee", "Field", "Field", GR_TYPICAL, ["Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon"]),
SpeciesInfo("Vaporeon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Jolteon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Flareon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Espeon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Umbreon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Porygon", "Mineral", "Mineral", GR_UNKNOWN, ["Porygon2"]),
SpeciesInfo("Porygon2", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Omanyte", "Water 1", "Water 3", GR_TYPICAL, ["Omastar"]),
SpeciesInfo("Omastar", "Water 1", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Kabuto", "Water 1", "Water 3", GR_TYPICAL, ["Kabutops"]),
SpeciesInfo("Kabutops", "Water 1", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Aerodactyl", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Snorlax", "Monster", "Monster", GR_TYPICAL, []),
SpeciesInfo("Articuno", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Zapdos", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Moltres", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Dratini", "Water 1", "Dragon", GR_TYPICAL, ["Dragonair"]),
SpeciesInfo("Dragonair", "Water 1", "Dragon", GR_TYPICAL, ["Dragonite"]),
SpeciesInfo("Dragonite", "Water 1", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Mewtwo", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Mew", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Chikorita", "Monster", "Grass", GR_TYPICAL, ["Bayleef"]),
SpeciesInfo("Bayleef", "Monster", "Grass", GR_TYPICAL, ["Meganium"]),
SpeciesInfo("Meganium", "Monster", "Grass", GR_TYPICAL, []),
SpeciesInfo("Cyndaquil", "Field", "Field", GR_TYPICAL, ["Quilava"]),
SpeciesInfo("Quilava", "Field", "Field", GR_TYPICAL, ["Typhlosion"]),
SpeciesInfo("Typhlosion", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Totodile", "Monster", "Water 1", GR_TYPICAL, ["Croconaw"]),
SpeciesInfo("Croconaw", "Monster", "Water 1", GR_TYPICAL, ["Feraligatr"]),
SpeciesInfo("Feraligatr", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Sentret", "Field", "Field", GR_TYPICAL, ["Furret"]),
SpeciesInfo("Furret", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Hoothoot", "Flying", "Flying", GR_TYPICAL, ["Noctowl"]),
SpeciesInfo("Noctowl", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Ledyba", "Bug", "Bug", GR_TYPICAL, ["Ledian"]),
SpeciesInfo("Ledian", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Spinarak", "Bug", "Bug", GR_TYPICAL, ["Ariados"]),
SpeciesInfo("Ariados", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Chinchou", "Water 2", "Water 2", GR_TYPICAL, ["Lanturn"]),
SpeciesInfo("Lanturn", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Togepi", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, ["Togetic"]),
SpeciesInfo("Togetic", "Flying", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Natu", "Flying", "Flying", GR_TYPICAL, ["Xatu"]),
SpeciesInfo("Xatu", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Mareep", "Monster", "Field", GR_TYPICAL, ["Flaaffy"]),
SpeciesInfo("Flaaffy", "Monster", "Field", GR_TYPICAL, ["Ampharos"]),
SpeciesInfo("Ampharos", "Monster", "Field", GR_TYPICAL, []),
SpeciesInfo("Marill", "Water 1", "Fairy", GR_TYPICAL, ["Azumarill"]),
SpeciesInfo("Azumarill", "Water 1", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Sudowoodo", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Hoppip", "Fairy", "Grass", GR_TYPICAL, ["Skiploom"]),
SpeciesInfo("Skiploom", "Fairy", "Grass", GR_TYPICAL, ["Jumpluff"]),
SpeciesInfo("Jumpluff", "Fairy", "Grass", GR_TYPICAL, []),
SpeciesInfo("Aipom", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Sunkern", "Grass", "Grass", GR_TYPICAL, ["Sunflora"]),
SpeciesInfo("Sunflora", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Yanma", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Wooper", "Water 1", "Field", GR_TYPICAL, ["Quagsire"]),
SpeciesInfo("Quagsire", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Murkrow", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Misdreavus", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Unown", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Wobbuffet", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Girafarig", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Pineco", "Bug", "Bug", GR_TYPICAL, ["Forretress"]),
SpeciesInfo("Forretress", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Dunsparce", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Gligar", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Snubbull", "Field", "Fairy", GR_TYPICAL, ["Granbull"]),
SpeciesInfo("Granbull", "Field", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Qwilfish", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Shuckle", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Heracross", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Sneasel", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Teddiursa", "Field", "Field", GR_TYPICAL, ["Ursaring"]),
SpeciesInfo("Ursaring", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Slugma", "Amorphous", "Amorphous", GR_TYPICAL, ["Magcargo"]),
SpeciesInfo("Magcargo", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Swinub", "Field", "Field", GR_TYPICAL, ["Piloswine"]),
SpeciesInfo("Piloswine", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Corsola", "Water 1", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Remoraid", "Water 1", "Water 2", GR_TYPICAL, ["Octillery"]),
SpeciesInfo("Octillery", "Water 1", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Delibird", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Mantine", "Water 1", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Skarmory", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Houndour", "Field", "Field", GR_TYPICAL, ["Houndoom"]),
SpeciesInfo("Houndoom", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Phanpy", "Field", "Field", GR_TYPICAL, ["Donphan"]),
SpeciesInfo("Donphan", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Stantler", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Smeargle", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Miltank", "Field", "Field", GR_FEMALE_ONLY, []),
SpeciesInfo("Raikou", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Entei", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Suicune", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Larvitar", "Monster", "Monster", GR_TYPICAL, ["Pupitar"]),
SpeciesInfo("Pupitar", "Monster", "Monster", GR_TYPICAL, ["Tyranitar"]),
SpeciesInfo("Tyranitar", "Monster", "Monster", GR_TYPICAL, []),
SpeciesInfo("Lugia", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Ho-Oh", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Celebi", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, [])
]
);
const g_MovesNewInGen2 =
[
"Sketch",
"Triple Kick",
"Thief",
"Spider Web",
"Mind Reader",
"Nightmare",
"Flame Wheel",
"Snore",
"Curse",
"Flail",
"Conversion 2",
"Aeroblast",
"Cotton Spore",
"Reversal",
"Spite",
"Powder Snow",
"Protect",
"Mach Punch",
"Scary Face",
"Feint Attack",
"Sweet Kiss",
"Belly Drum",
"Sludge Bomb",
"Mud-Slap",
"Octazooka",
"Spikes",
"Zap Cannon",
"Foresight",
"Destiny Bond",
"Perish Song",
"Icy Wind",
"Detect",
"Bone Rush",
"Lock-On",
"Outrage",
"Sandstorm",
"Giga Drain",
"Endure",
"Charm",
"Rollout",
"False Swipe",
"Swagger",
"Milk Drink",
"Spark",
"Fury Cutter",
"Steel Wing",
"Mean Look",
"Attract",
"Sleep Talk",
"Heal Bell",
"Return",
"Present",
"Frustration",
"Safeguard",
"Pain Split",
"Sacred Fire",
"Magnitude",
"Dynamic Punch",
"Megahorn",
"Dragon Breath",
"Baton Pass",
"Encore",
"Pursuit",
"Rapid Spin",
"Sweet Scent",
"Iron Tail",
"Metal Claw",
"Vital Throw",
"Morning Sun",
"Synthesis",
"Moonlight",
"Hidden Power",
"Cross Chop",
"Twister",
"Rain Dance",
"Sunny Day",
"Crunch",
"Mirror Coat",
"Psych Up",
"Extreme Speed",
"Ancient Power",
"Shadow Ball",
"Future Sight",
"Rock Smash",
"Whirlpool",
"Beat Up"
];