const g_Generation1 = Generation(
"====[[Generation I]]====",
GAMECOMBO_ALL_GEN1,
//UniversalTMs
[
"Bide",
"Double Team",
"Rage",
"Rest",
"Toxic"
],
//MonData
[
SpeciesInfo("Bulbasaur", "Monster", "Grass", GR_UNKNOWN, ["Ivysaur"]),
SpeciesInfo("Ivysaur", "Monster", "Grass", GR_UNKNOWN, ["Venusaur"]),
SpeciesInfo("Venusaur", "Monster", "Grass", GR_UNKNOWN, []),
SpeciesInfo("Charmander", "Monster", "Dragon", GR_UNKNOWN, ["Charmeleon"]),
SpeciesInfo("Charmeleon", "Monster", "Dragon", GR_UNKNOWN, ["Charizard"]),
SpeciesInfo("Charizard", "Monster", "Dragon", GR_UNKNOWN, []),
SpeciesInfo("Squirtle", "Monster", "Water 1", GR_UNKNOWN, ["Wartortle"]),
SpeciesInfo("Wartortle", "Monster", "Water 1", GR_UNKNOWN, ["Blastoise"]),
SpeciesInfo("Blastoise", "Monster", "Water 1", GR_UNKNOWN, []),
SpeciesInfo("Caterpie", "Bug", "Bug", GR_UNKNOWN, ["Metapod"]),
SpeciesInfo("Metapod", "Bug", "Bug", GR_UNKNOWN, ["Butterfree"]),
SpeciesInfo("Butterfree", "Bug", "Bug", GR_UNKNOWN, []),
SpeciesInfo("Weedle", "Bug", "Bug", GR_UNKNOWN, ["Kakuna"]),
SpeciesInfo("Kakuna", "Bug", "Bug", GR_UNKNOWN, ["Beedrill"]),
SpeciesInfo("Beedrill", "Bug", "Bug", GR_UNKNOWN, []),
SpeciesInfo("Pidgey", "Flying", "Flying", GR_UNKNOWN, ["Pidgeotto"]),
SpeciesInfo("Pidgeotto", "Flying", "Flying", GR_UNKNOWN, ["Pidgeot"]),
SpeciesInfo("Pidgeot", "Flying", "Flying", GR_UNKNOWN, []),
SpeciesInfo("Rattata", "Field", "Field", GR_UNKNOWN, ["Raticate"]),
SpeciesInfo("Raticate", "Field", "Field", GR_UNKNOWN, []),
SpeciesInfo("Spearow", "Flying", "Flying", GR_UNKNOWN, ["Fearow"]),
SpeciesInfo("Fearow", "Flying", "Flying", GR_UNKNOWN, []),
SpeciesInfo("Ekans", "Field", "Dragon", GR_UNKNOWN, ["Arbok"]),
SpeciesInfo("Arbok", "Field", "Dragon", GR_UNKNOWN, []),
SpeciesInfo("Pikachu", "Field", "Fairy", GR_UNKNOWN, ["Raichu"]),
SpeciesInfo("Raichu", "Field", "Fairy", GR_UNKNOWN, []),
SpeciesInfo("Sandshrew", "Field", "Field", GR_UNKNOWN, ["Sandslash"]),
SpeciesInfo("Sandslash", "Field", "Field", GR_UNKNOWN, []),
SpeciesInfo("Nidoran F", "Monster", "Field", GR_UNKNOWN, ["Nidorina"]),
SpeciesInfo("Nidorina", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, ["Nidoqueen"]),
SpeciesInfo("Nidoqueen", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Nidoran M", "Monster", "Field", GR_UNKNOWN, ["Nidorino"]),
SpeciesInfo("Nidorino", "Monster", "Field", GR_UNKNOWN, ["Nidoking"]),
SpeciesInfo("Nidoking", "Monster", "Field", GR_UNKNOWN, []),
SpeciesInfo("Clefairy", "Fairy", "Fairy", GR_UNKNOWN, ["Clefable"]),
SpeciesInfo("Clefable", "Fairy", "Fairy", GR_UNKNOWN, []),
SpeciesInfo("Vulpix", "Field", "Field", GR_UNKNOWN, ["Ninetales"]),
SpeciesInfo("Ninetales", "Field", "Field", GR_UNKNOWN, []),
SpeciesInfo("Jigglypuff", "Fairy", "Fairy", GR_UNKNOWN, ["Wigglytuff"]),
SpeciesInfo("Wigglytuff", "Fairy", "Fairy", GR_UNKNOWN, []),
SpeciesInfo("Zubat", "Flying", "Flying", GR_UNKNOWN, ["Golbat"]),
SpeciesInfo("Golbat", "Flying", "Flying", GR_UNKNOWN, []),
SpeciesInfo("Oddish", "Grass", "Grass", GR_UNKNOWN, ["Gloom"]),
SpeciesInfo("Gloom", "Grass", "Grass", GR_UNKNOWN, ["Vileplume"]),
SpeciesInfo("Vileplume", "Grass", "Grass", GR_UNKNOWN, []),
SpeciesInfo("Paras", "Bug", "Grass", GR_UNKNOWN, ["Parasect"]),
SpeciesInfo("Parasect", "Bug", "Grass", GR_UNKNOWN, []),
SpeciesInfo("Venonat", "Bug", "Bug", GR_UNKNOWN, ["Venomoth"]),
SpeciesInfo("Venomoth", "Bug", "Bug", GR_UNKNOWN, []),
SpeciesInfo("Diglett", "Field", "Field", GR_UNKNOWN, ["Dugtrio"]),
SpeciesInfo("Dugtrio", "Field", "Field", GR_UNKNOWN, []),
SpeciesInfo("Meowth", "Field", "Field", GR_UNKNOWN, ["Persian"]),
SpeciesInfo("Persian", "Field", "Field", GR_UNKNOWN, []),
SpeciesInfo("Psyduck", "Water 1", "Field", GR_UNKNOWN, ["Golduck"]),
SpeciesInfo("Golduck", "Water 1", "Field", GR_UNKNOWN, []),
SpeciesInfo("Mankey", "Field", "Field", GR_UNKNOWN, ["Primeape"]),
SpeciesInfo("Primeape", "Field", "Field", GR_UNKNOWN, []),
SpeciesInfo("Growlithe", "Field", "Field", GR_UNKNOWN, ["Arcanine"]),
SpeciesInfo("Arcanine", "Field", "Field", GR_UNKNOWN, []),
SpeciesInfo("Poliwag", "Water 1", "Water 1", GR_UNKNOWN, ["Poliwhirl"]),
SpeciesInfo("Poliwhirl", "Water 1", "Water 1", GR_UNKNOWN, ["Poliwrath"]),
SpeciesInfo("Poliwrath", "Water 1", "Water 1", GR_UNKNOWN, []),
SpeciesInfo("Abra", "Human-Like", "Human-Like", GR_UNKNOWN, ["Kadabra"]),
SpeciesInfo("Kadabra", "Human-Like", "Human-Like", GR_UNKNOWN, ["Alakazam"]),
SpeciesInfo("Alakazam", "Human-Like", "Human-Like", GR_UNKNOWN, []),
SpeciesInfo("Machop", "Human-Like", "Human-Like", GR_UNKNOWN, ["Machoke"]),
SpeciesInfo("Machoke", "Human-Like", "Human-Like", GR_UNKNOWN, ["Machamp"]),
SpeciesInfo("Machamp", "Human-Like", "Human-Like", GR_UNKNOWN, []),
SpeciesInfo("Bellsprout", "Grass", "Grass", GR_UNKNOWN, ["Weepinbell"]),
SpeciesInfo("Weepinbell", "Grass", "Grass", GR_UNKNOWN, ["Victreebel"]),
SpeciesInfo("Victreebel", "Grass", "Grass", GR_UNKNOWN, []),
SpeciesInfo("Tentacool", "Water 3", "Water 3", GR_UNKNOWN, ["Tentacruel"]),
SpeciesInfo("Tentacruel", "Water 3", "Water 3", GR_UNKNOWN, []),
SpeciesInfo("Geodude", "Mineral", "Mineral", GR_UNKNOWN, ["Graveler"]),
SpeciesInfo("Graveler", "Mineral", "Mineral", GR_UNKNOWN, ["Golem"]),
SpeciesInfo("Golem", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Ponyta", "Field", "Field", GR_UNKNOWN, ["Rapidash"]),
SpeciesInfo("Rapidash", "Field", "Field", GR_UNKNOWN, []),
SpeciesInfo("Slowpoke", "Monster", "Water 1", GR_UNKNOWN, ["Slowbro"]),
SpeciesInfo("Slowbro", "Monster", "Water 1", GR_UNKNOWN, []),
SpeciesInfo("Magnemite", "Mineral", "Mineral", GR_UNKNOWN, ["Magneton"]),
SpeciesInfo("Magneton", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Farfetch'd", "Flying", "Field", GR_UNKNOWN, []),
SpeciesInfo("Doduo", "Flying", "Flying", GR_UNKNOWN, ["Dodrio"]),
SpeciesInfo("Dodrio", "Flying", "Flying", GR_UNKNOWN, []),
SpeciesInfo("Seel", "Water 1", "Field", GR_UNKNOWN, ["Dewgong"]),
SpeciesInfo("Dewgong", "Water 1", "Field", GR_UNKNOWN, []),
SpeciesInfo("Grimer", "Amorphous", "Amorphous", GR_UNKNOWN, ["Muk"]),
SpeciesInfo("Muk", "Amorphous", "Amorphous", GR_UNKNOWN, []),
SpeciesInfo("Shellder", "Water 3", "Water 3", GR_UNKNOWN, ["Cloyster"]),
SpeciesInfo("Cloyster", "Water 3", "Water 3", GR_UNKNOWN, []),
SpeciesInfo("Gastly", "Amorphous", "Amorphous", GR_UNKNOWN, ["Haunter"]),
SpeciesInfo("Haunter", "Amorphous", "Amorphous", GR_UNKNOWN, ["Gengar"]),
SpeciesInfo("Gengar", "Amorphous", "Amorphous", GR_UNKNOWN, []),
SpeciesInfo("Onix", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Drowzee", "Human-Like", "Human-Like", GR_UNKNOWN, ["Hypno"]),
SpeciesInfo("Hypno", "Human-Like", "Human-Like", GR_UNKNOWN, []),
SpeciesInfo("Krabby", "Water 3", "Water 3", GR_UNKNOWN, ["Kingler"]),
SpeciesInfo("Kingler", "Water 3", "Water 3", GR_UNKNOWN, []),
SpeciesInfo("Voltorb", "Mineral", "Mineral", GR_UNKNOWN, ["Electrode"]),
SpeciesInfo("Electrode", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Exeggcute", "Grass", "Grass", GR_UNKNOWN, ["Exeggutor"]),
SpeciesInfo("Exeggutor", "Grass", "Grass", GR_UNKNOWN, []),
SpeciesInfo("Cubone", "Monster", "Monster", GR_UNKNOWN, ["Marowak"]),
SpeciesInfo("Marowak", "Monster", "Monster", GR_UNKNOWN, []),
SpeciesInfo("Hitmonlee", "Human-Like", "Human-Like", GR_UNKNOWN, []),
SpeciesInfo("Hitmonchan", "Human-Like", "Human-Like", GR_UNKNOWN, []),
SpeciesInfo("Lickitung", "Monster", "Monster", GR_UNKNOWN, []),
SpeciesInfo("Koffing", "Amorphous", "Amorphous", GR_UNKNOWN, ["Weezing"]),
SpeciesInfo("Weezing", "Amorphous", "Amorphous", GR_UNKNOWN, []),
SpeciesInfo("Rhyhorn", "Monster", "Field", GR_UNKNOWN, ["Rhydon"]),
SpeciesInfo("Rhydon", "Monster", "Field", GR_UNKNOWN, []),
SpeciesInfo("Chansey", "Fairy", "Fairy", GR_UNKNOWN, []),
SpeciesInfo("Tangela", "Grass", "Grass", GR_UNKNOWN, []),
SpeciesInfo("Kangaskhan", "Monster", "Monster", GR_UNKNOWN, []),
SpeciesInfo("Horsea", "Water 1", "Dragon", GR_UNKNOWN, ["Seadra"]),
SpeciesInfo("Seadra", "Water 1", "Dragon", GR_UNKNOWN, []),
SpeciesInfo("Goldeen", "Water 2", "Water 2", GR_UNKNOWN, ["Seaking"]),
SpeciesInfo("Seaking", "Water 2", "Water 2", GR_UNKNOWN, []),
SpeciesInfo("Staryu", "Water 3", "Water 3", GR_UNKNOWN, ["Starmie"]),
SpeciesInfo("Starmie", "Water 3", "Water 3", GR_UNKNOWN, []),
SpeciesInfo("Mr. Mime", "Human-Like", "Human-Like", GR_UNKNOWN, []),
SpeciesInfo("Scyther", "Bug", "Bug", GR_UNKNOWN, []),
SpeciesInfo("Jynx", "Human-Like", "Human-Like", GR_UNKNOWN, []),
SpeciesInfo("Electabuzz", "Human-Like", "Human-Like", GR_UNKNOWN, []),
SpeciesInfo("Magmar", "Human-Like", "Human-Like", GR_UNKNOWN, []),
SpeciesInfo("Pinsir", "Bug", "Bug", GR_UNKNOWN, []),
SpeciesInfo("Tauros", "Field", "Field", GR_UNKNOWN, []),
SpeciesInfo("Magikarp", "Water 2", "Dragon", GR_UNKNOWN, ["Gyarados"]),
SpeciesInfo("Gyarados", "Water 2", "Dragon", GR_UNKNOWN, []),
SpeciesInfo("Lapras", "Monster", "Water 1", GR_UNKNOWN, []),
SpeciesInfo("Ditto", "Ditto", "Ditto", GR_UNKNOWN, []),
SpeciesInfo("Eevee", "Field", "Field", GR_UNKNOWN, ["Vaporeon", "Jolteon", "Flareon"]),
SpeciesInfo("Vaporeon", "Field", "Field", GR_UNKNOWN, []),
SpeciesInfo("Jolteon", "Field", "Field", GR_UNKNOWN, []),
SpeciesInfo("Flareon", "Field", "Field", GR_UNKNOWN, []),
SpeciesInfo("Porygon", "Mineral", "Mineral", GR_UNKNOWN, ["Porygon2"]),
SpeciesInfo("Omanyte", "Water 1", "Water 3", GR_UNKNOWN, ["Omastar"]),
SpeciesInfo("Omastar", "Water 1", "Water 3", GR_UNKNOWN, []),
SpeciesInfo("Kabuto", "Water 1", "Water 3", GR_UNKNOWN, ["Kabutops"]),
SpeciesInfo("Kabutops", "Water 1", "Water 3", GR_UNKNOWN, []),
SpeciesInfo("Aerodactyl", "Flying", "Flying", GR_UNKNOWN, []),
SpeciesInfo("Snorlax", "Monster", "Monster", GR_UNKNOWN, []),
SpeciesInfo("Articuno", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Zapdos", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Moltres", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Dratini", "Water 1", "Dragon", GR_UNKNOWN, ["Dragonair"]),
SpeciesInfo("Dragonair", "Water 1", "Dragon", GR_UNKNOWN, ["Dragonite"]),
SpeciesInfo("Dragonite", "Water 1", "Dragon", GR_UNKNOWN, []),
SpeciesInfo("Mewtwo", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Mew", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, [])
]
);