const g_Generation5 = Generation(
"====[[Generation V]]====",
GAMECOMBO_ALL_GEN5,
//UniversalTMs https://bulbapedia.bulbagarden.net/w/index.php?search=%22Every+Pok%C3%A9mon+can+learn+this+move+by%22&title=Special%3ASearch&go=Go
[
"Attract",
"Double Team",
"Facade",
"Frustration",
"Hidden Power",
"Protect",
"Rest",
"Return",
"Round",
"Swagger",
"Toxic"
],
//MonData https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_breeding_attributes https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_National_Pok%C3%A9dex_number
[
SpeciesInfo("Bulbasaur", "Monster", "Grass", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Ivysaur", "Monster", "Grass", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Venusaur", "Monster", "Grass", GR_TYPICAL, [], -2),
SpeciesInfo("Charmander", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Charmeleon", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Charizard", "Monster", "Dragon", GR_TYPICAL, [], -2),
SpeciesInfo("Squirtle", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Wartortle", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Blastoise", "Monster", "Water 1", GR_TYPICAL, [], -2),
SpeciesInfo("Caterpie", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Metapod", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Butterfree", "Bug", "Bug", GR_TYPICAL, [], -2),
SpeciesInfo("Weedle", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Kakuna", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Beedrill", "Bug", "Bug", GR_TYPICAL, [], -2),
SpeciesInfo("Pidgey", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Pidgeotto", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Pidgeot", "Flying", "Flying", GR_TYPICAL, [], -2),
SpeciesInfo("Rattata", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Raticate", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Spearow", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Fearow", "Flying", "Flying", GR_TYPICAL, [], -1),
SpeciesInfo("Ekans", "Field", "Dragon", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Arbok", "Field", "Dragon", GR_TYPICAL, [], -1),
SpeciesInfo("Pichu", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Pikachu", "Field", "Fairy", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Raichu", "Field", "Fairy", GR_TYPICAL, [], -2),
SpeciesInfo("Sandshrew", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Sandslash", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Nidoran F", "Monster", "Field", GR_FEMALE_ONLY, [EvolveData(1)], 0),
SpeciesInfo("Nidorina", "NED", "NED", GR_FEMALE_ONLY, [EvolveData(1)], -1),
SpeciesInfo("Nidoqueen", "NED", "NED", GR_FEMALE_ONLY, [], -2),
SpeciesInfo("Nidoran M", "Monster", "Field", GR_MALE_ONLY, [EvolveData(1)], 0),
SpeciesInfo("Nidorino", "Monster", "Field", GR_MALE_ONLY, [EvolveData(1)], -1),
SpeciesInfo("Nidoking", "Monster", "Field", GR_MALE_ONLY, [], -2),
SpeciesInfo("Cleffa", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Clefairy", "Fairy", "Fairy", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Clefable", "Fairy", "Fairy", GR_TYPICAL, [], -2),
SpeciesInfo("Vulpix", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Ninetales", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Igglybuff", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Jigglypuff", "Fairy", "Fairy", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Wigglytuff", "Fairy", "Fairy", GR_TYPICAL, [], -2),
SpeciesInfo("Zubat", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Golbat", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Crobat", "Flying", "Flying", GR_TYPICAL, [], -2),
SpeciesInfo("Oddish", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Gloom", "Grass", "Grass", GR_TYPICAL, [EvolveData(1), EvolveData(2)], -1),
SpeciesInfo("Vileplume", "Grass", "Grass", GR_TYPICAL, [], -2),
SpeciesInfo("Bellossom", "Grass", "Grass", GR_TYPICAL, [], -3),
SpeciesInfo("Paras", "Bug", "Grass", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Parasect", "Bug", "Grass", GR_TYPICAL, [], -1),
SpeciesInfo("Venonat", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Venomoth", "Bug", "Bug", GR_TYPICAL, [], -1),
SpeciesInfo("Diglett", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Dugtrio", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Meowth", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Persian", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Psyduck", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Golduck", "Water 1", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Mankey", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Primeape", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Growlithe", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Arcanine", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Poliwag", "Water 1", "Water 1", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Poliwhirl", "Water 1", "Water 1", GR_TYPICAL, [EvolveData(1), EvolveData(2)], -1),
SpeciesInfo("Poliwrath", "Water 1", "Water 1", GR_TYPICAL, [], -2),
SpeciesInfo("Politoed", "Water 1", "Water 1", GR_TYPICAL, [], -3),
SpeciesInfo("Abra", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Kadabra", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Alakazam", "Human-Like", "Human-Like", GR_TYPICAL, [], -2),
SpeciesInfo("Machop", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Machoke", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Machamp", "Human-Like", "Human-Like", GR_TYPICAL, [], -2),
SpeciesInfo("Bellsprout", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Weepinbell", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Victreebel", "Grass", "Grass", GR_TYPICAL, [], -2),
SpeciesInfo("Tentacool", "Water 3", "Water 3", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Tentacruel", "Water 3", "Water 3", GR_TYPICAL, [], -1),
SpeciesInfo("Geodude", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Graveler", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Golem", "Mineral", "Mineral", GR_TYPICAL, [], -2),
SpeciesInfo("Ponyta", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Rapidash", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Slowpoke", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1), EvolveData(2)], 0),
SpeciesInfo("Slowbro", "Monster", "Water 1", GR_TYPICAL, [], -1),
SpeciesInfo("Slowking", "Monster", "Water 1", GR_TYPICAL, [], -2),
SpeciesInfo("Magnemite", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Magneton", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], -1),
SpeciesInfo("Magnezone", "Mineral", "Mineral", GR_UNKNOWN, [], -2),
SpeciesInfo("Farfetch'd", "Flying", "Field", GR_TYPICAL, [], 0),
SpeciesInfo("Doduo", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Dodrio", "Flying", "Flying", GR_TYPICAL, [], -1),
SpeciesInfo("Seel", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Dewgong", "Water 1", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Grimer", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Muk", "Amorphous", "Amorphous", GR_TYPICAL, [], -1),
SpeciesInfo("Shellder", "Water 3", "Water 3", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Cloyster", "Water 3", "Water 3", GR_TYPICAL, [], -1),
SpeciesInfo("Gastly", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Haunter", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Gengar", "Amorphous", "Amorphous", GR_TYPICAL, [], -2),
SpeciesInfo("Onix", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Steelix", "Mineral", "Mineral", GR_TYPICAL, [], -1),
SpeciesInfo("Drowzee", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Hypno", "Human-Like", "Human-Like", GR_TYPICAL, [], -1),
SpeciesInfo("Krabby", "Water 3", "Water 3", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Kingler", "Water 3", "Water 3", GR_TYPICAL, [], -1),
SpeciesInfo("Voltorb", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Electrode", "Mineral", "Mineral", GR_UNKNOWN, [], -1),
SpeciesInfo("Exeggcute", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Exeggutor", "Grass", "Grass", GR_TYPICAL, [], -1),
SpeciesInfo("Cubone", "Monster", "Monster", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Marowak", "Monster", "Monster", GR_TYPICAL, [], -1),
SpeciesInfo("Tyrogue", "NED", "NED", GR_MALE_ONLY, [EvolveData(1), EvolveData(2), EvolveData(3)], 0),
SpeciesInfo("Hitmonlee", "Human-Like", "Human-Like", GR_MALE_ONLY, [], -1),
SpeciesInfo("Hitmonchan", "Human-Like", "Human-Like", GR_MALE_ONLY, [], -2),
SpeciesInfo("Hitmontop", "Human-Like", "Human-Like", GR_MALE_ONLY, [], -3),
SpeciesInfo("Lickitung", "Monster", "Monster", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Lickilicky", "Monster", "Monster", GR_TYPICAL, [], -1),
SpeciesInfo("Koffing", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Weezing", "Amorphous", "Amorphous", GR_TYPICAL, [], -1),
SpeciesInfo("Rhyhorn", "Monster", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Rhydon", "Monster", "Field", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Rhyperior", "Monster", "Field", GR_TYPICAL, [], -2),
SpeciesInfo("Happiny", "NED", "NED", GR_FEMALE_ONLY, [EvolveData(1)], 0),
SpeciesInfo("Chansey", "Fairy", "Fairy", GR_FEMALE_ONLY, [EvolveData(1)], -1),
SpeciesInfo("Blissey", "Fairy", "Fairy", GR_FEMALE_ONLY, [], -2),
SpeciesInfo("Tangela", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Tangrowth", "Grass", "Grass", GR_TYPICAL, [], -1),
SpeciesInfo("Kangaskhan", "Monster", "Monster", GR_FEMALE_ONLY, [], 0),
SpeciesInfo("Horsea", "Water 1", "Dragon", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Seadra", "Water 1", "Dragon", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Kingdra", "Water 1", "Dragon", GR_TYPICAL, [], -2),
SpeciesInfo("Goldeen", "Water 2", "Water 2", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Seaking", "Water 2", "Water 2", GR_TYPICAL, [], -1),
SpeciesInfo("Staryu", "Water 3", "Water 3", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Starmie", "Water 3", "Water 3", GR_UNKNOWN, [], -1),
SpeciesInfo("Mime Jr.", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Mr. Mime", "Human-Like", "Human-Like", GR_TYPICAL, [], -1),
SpeciesInfo("Scyther", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Scizor", "Bug", "Bug", GR_TYPICAL, [], -1),
SpeciesInfo("Smoochum", "NED", "NED", GR_FEMALE_ONLY, [EvolveData(1)], 0),
SpeciesInfo("Jynx", "Human-Like", "Human-Like", GR_FEMALE_ONLY, [], -1),
SpeciesInfo("Elekid", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Electabuzz", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Electivire", "Human-Like", "Human-Like", GR_TYPICAL, [], -2),
SpeciesInfo("Magby", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Magmar", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Magmortar", "Human-Like", "Human-Like", GR_TYPICAL, [], -2),
SpeciesInfo("Pinsir", "Bug", "Bug", GR_TYPICAL, [], 0),
SpeciesInfo("Tauros", "Field", "Field", GR_MALE_ONLY, [], 0),
SpeciesInfo("Magikarp", "Water 2", "Dragon", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Gyarados", "Water 2", "Dragon", GR_TYPICAL, [], -1),
SpeciesInfo("Lapras", "Monster", "Water 1", GR_TYPICAL, [], 0),
SpeciesInfo("Ditto", "Ditto", "Ditto", GR_UNKNOWN, [], 0),
SpeciesInfo("Eevee", "Field", "Field", GR_TYPICAL, [EvolveData(1), EvolveData(2), EvolveData(3), EvolveData(4), EvolveData(5), EvolveData(6), EvolveData(7)], 0),//7 - Glaceon has to look 7 slots back to find Eevee
SpeciesInfo("Vaporeon", "Field", "Field", GR_TYPICAL, [], -1),//6
SpeciesInfo("Jolteon", "Field", "Field", GR_TYPICAL, [], -2),//5
SpeciesInfo("Flareon", "Field", "Field", GR_TYPICAL, [], -3),//4
SpeciesInfo("Espeon", "Field", "Field", GR_TYPICAL, [], -4),//3
SpeciesInfo("Umbreon", "Field", "Field", GR_TYPICAL, [], -5),//2
SpeciesInfo("Leafeon", "Field", "Field", GR_TYPICAL, [], -6),//1
SpeciesInfo("Glaceon", "Field", "Field", GR_TYPICAL, [], -7),//0
SpeciesInfo("Porygon", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Porygon2", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], -1),
SpeciesInfo("Porygon-Z", "Mineral", "Mineral", GR_UNKNOWN, [], -2),
SpeciesInfo("Omanyte", "Water 1", "Water 3", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Omastar", "Water 1", "Water 3", GR_TYPICAL, [], -1),
SpeciesInfo("Kabuto", "Water 1", "Water 3", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Kabutops", "Water 1", "Water 3", GR_TYPICAL, [], -1),
SpeciesInfo("Aerodactyl", "Flying", "Flying", GR_TYPICAL, [], 0),
SpeciesInfo("Munchlax", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Snorlax", "Monster", "Monster", GR_TYPICAL, [], -1),
SpeciesInfo("Articuno", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Zapdos", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Moltres", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Dratini", "Water 1", "Dragon", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Dragonair", "Water 1", "Dragon", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Dragonite", "Water 1", "Dragon", GR_TYPICAL, [], -2),
SpeciesInfo("Mewtwo", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Mew", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Chikorita", "Monster", "Grass", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Bayleef", "Monster", "Grass", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Meganium", "Monster", "Grass", GR_TYPICAL, [], -2),
SpeciesInfo("Cyndaquil", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Quilava", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Typhlosion", "Field", "Field", GR_TYPICAL, [], -2),
SpeciesInfo("Totodile", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Croconaw", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Feraligatr", "Monster", "Water 1", GR_TYPICAL, [], -2),
SpeciesInfo("Sentret", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Furret", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Hoothoot", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Noctowl", "Flying", "Flying", GR_TYPICAL, [], -1),
SpeciesInfo("Ledyba", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Ledian", "Bug", "Bug", GR_TYPICAL, [], -1),
SpeciesInfo("Spinarak", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Ariados", "Bug", "Bug", GR_TYPICAL, [], -1),
SpeciesInfo("Chinchou", "Water 2", "Water 2", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Lanturn", "Water 2", "Water 2", GR_TYPICAL, [], -1),
SpeciesInfo("Togepi", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Togetic", "Flying", "Fairy", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Togekiss", "Flying", "Fairy", GR_TYPICAL, [], -2),
SpeciesInfo("Natu", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Xatu", "Flying", "Flying", GR_TYPICAL, [], -1),
SpeciesInfo("Mareep", "Monster", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Flaaffy", "Monster", "Field", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Ampharos", "Monster", "Field", GR_TYPICAL, [], -2),
SpeciesInfo("Azurill", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Marill", "Water 1", "Fairy", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Azumarill", "Water 1", "Fairy", GR_TYPICAL, [], -2),
SpeciesInfo("Bonsly", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Sudowoodo", "Mineral", "Mineral", GR_TYPICAL, [], -1),
SpeciesInfo("Hoppip", "Fairy", "Grass", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Skiploom", "Fairy", "Grass", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Jumpluff", "Fairy", "Grass", GR_TYPICAL, [], -2),
SpeciesInfo("Aipom", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Ambipom", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Sunkern", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Sunflora", "Grass", "Grass", GR_TYPICAL, [], -1),
SpeciesInfo("Yanma", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Yanmega", "Bug", "Bug", GR_TYPICAL, [], -1),
SpeciesInfo("Wooper", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Quagsire", "Water 1", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Murkrow", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Honchkrow", "Flying", "Flying", GR_TYPICAL, [], -1),
SpeciesInfo("Misdreavus", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Mismagius", "Amorphous", "Amorphous", GR_TYPICAL, [], -1),
SpeciesInfo("Unown", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Wynaut", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Wobbuffet", "Amorphous", "Amorphous", GR_TYPICAL, [], -1),
SpeciesInfo("Girafarig", "Field", "Field", GR_TYPICAL, [], 0),
SpeciesInfo("Pineco", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Forretress", "Bug", "Bug", GR_TYPICAL, [], -1),
SpeciesInfo("Dunsparce", "Field", "Field", GR_TYPICAL, [], 0),
SpeciesInfo("Gligar", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Gliscor", "Bug", "Bug", GR_TYPICAL, [], -1),
SpeciesInfo("Snubbull", "Field", "Fairy", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Granbull", "Field", "Fairy", GR_TYPICAL, [], -1),
SpeciesInfo("Qwilfish", "Water 2", "Water 2", GR_TYPICAL, [], 0),
SpeciesInfo("Shuckle", "Bug", "Bug", GR_TYPICAL, [], 0),
SpeciesInfo("Heracross", "Bug", "Bug", GR_TYPICAL, [], 0),
SpeciesInfo("Sneasel", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Weavile", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Teddiursa", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Ursaring", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Slugma", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Magcargo", "Amorphous", "Amorphous", GR_TYPICAL, [], -1),
SpeciesInfo("Swinub", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Piloswine", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Mamoswine", "Field", "Field", GR_TYPICAL, [], -2),
SpeciesInfo("Corsola", "Water 1", "Water 3", GR_TYPICAL, [], 0),
SpeciesInfo("Remoraid", "Water 1", "Water 2", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Octillery", "Water 1", "Water 2", GR_TYPICAL, [], -1),
SpeciesInfo("Delibird", "Water 1", "Field", GR_TYPICAL, [], 0),
SpeciesInfo("Mantyke", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Mantine", "Water 1", "Water 1", GR_TYPICAL, [], -1),
SpeciesInfo("Skarmory", "Flying", "Flying", GR_TYPICAL, [], 0),
SpeciesInfo("Houndour", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Houndoom", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Phanpy", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Donphan", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Stantler", "Field", "Field", GR_TYPICAL, [], 0),
SpeciesInfo("Smeargle", "Field", "Field", GR_TYPICAL, [], 0),
SpeciesInfo("Miltank", "Field", "Field", GR_FEMALE_ONLY, [], 0),
SpeciesInfo("Raikou", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Entei", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Suicune", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Larvitar", "Monster", "Monster", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Pupitar", "Monster", "Monster", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Tyranitar", "Monster", "Monster", GR_TYPICAL, [], -2),
SpeciesInfo("Lugia", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Ho-Oh", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Celebi", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Treecko", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Grovyle", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Sceptile", "Monster", "Dragon", GR_TYPICAL, [], -2),
SpeciesInfo("Torchic", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Combusken", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Blaziken", "Field", "Field", GR_TYPICAL, [], -2),
SpeciesInfo("Mudkip", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Marshtomp", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Swampert", "Monster", "Water 1", GR_TYPICAL, [], -2),
SpeciesInfo("Poochyena", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Mightyena", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Zigzagoon", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Linoone", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Wurmple", "Bug", "Bug", GR_TYPICAL, [EvolveData(1), EvolveData(3)], 0),
SpeciesInfo("Silcoon", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Beautifly", "Bug", "Bug", GR_TYPICAL, [], -2),
SpeciesInfo("Cascoon", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], -3),
SpeciesInfo("Dustox", "Bug", "Bug", GR_TYPICAL, [], -4),
SpeciesInfo("Lotad", "Water 1", "Grass", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Lombre", "Water 1", "Grass", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Ludicolo", "Water 1", "Grass", GR_TYPICAL, [], -2),
SpeciesInfo("Seedot", "Field", "Grass", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Nuzleaf", "Field", "Grass", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Shiftry", "Field", "Grass", GR_TYPICAL, [], -2),
SpeciesInfo("Taillow", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Swellow", "Flying", "Flying", GR_TYPICAL, [], -1),
SpeciesInfo("Wingull", "Water 1", "Flying", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Pelipper", "Water 1", "Flying", GR_TYPICAL, [], -1),
SpeciesInfo("Ralts", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Kirlia", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1), EvolveData(2)], -1),
SpeciesInfo("Gardevoir", "Amorphous", "Amorphous", GR_TYPICAL, [], -2),
SpeciesInfo("Gallade", "Amorphous", "Amorphous", GR_MALE_ONLY, [], -3),
SpeciesInfo("Surskit", "Water 1", "Bug", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Masquerain", "Water 1", "Bug", GR_TYPICAL, [], -1),
SpeciesInfo("Shroomish", "Fairy", "Grass", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Breloom", "Fairy", "Grass", GR_TYPICAL, [], -1),
SpeciesInfo("Slakoth", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Vigoroth", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Slaking", "Field", "Field", GR_TYPICAL, [], -2),
SpeciesInfo("Nincada", "Bug", "Bug", GR_UNKNOWN, [EvolveData(1), EvolveData(2)], 0),
SpeciesInfo("Ninjask", "Bug", "Bug", GR_TYPICAL, [], -1),
SpeciesInfo("Shedinja", "Bug", "Bug", GR_UNKNOWN, [], -2),
SpeciesInfo("Whismur", "Monster", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Loudred", "Monster", "Field", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Exploud", "Monster", "Field", GR_TYPICAL, [], -2),
SpeciesInfo("Makuhita", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Hariyama", "Human-Like", "Human-Like", GR_TYPICAL, [], -1),
SpeciesInfo("Nosepass", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Probopass", "Mineral", "Mineral", GR_TYPICAL, [], -1),
SpeciesInfo("Skitty", "Field", "Fairy", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Delcatty", "Field", "Fairy", GR_TYPICAL, [], -1),
SpeciesInfo("Sableye", "Human-Like", "Human-Like", GR_TYPICAL, [], 0),
SpeciesInfo("Mawile", "Field", "Fairy", GR_TYPICAL, [], 0),
SpeciesInfo("Aron", "Monster", "Monster", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Lairon", "Monster", "Monster", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Aggron", "Monster", "Monster", GR_TYPICAL, [], -2),
SpeciesInfo("Meditite", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Medicham", "Human-Like", "Human-Like", GR_TYPICAL, [], -1),
SpeciesInfo("Electrike", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Manectric", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Plusle", "Fairy", "Fairy", GR_TYPICAL, [], 0),
SpeciesInfo("Minun", "Fairy", "Fairy", GR_TYPICAL, [], 0),
SpeciesInfo("Volbeat", "Bug", "Human-Like", GR_MALE_ONLY, [], 0),
SpeciesInfo("Illumise", "Bug", "Human-Like", GR_FEMALE_ONLY, [], 0),
SpeciesInfo("Budew", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Roselia", "Fairy", "Grass", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Roserade", "Fairy", "Grass", GR_TYPICAL, [], -2),
SpeciesInfo("Gulpin", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Swalot", "Amorphous", "Amorphous", GR_TYPICAL, [], -1),
SpeciesInfo("Carvanha", "Water 2", "Water 2", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Sharpedo", "Water 2", "Water 2", GR_TYPICAL, [], -1),
SpeciesInfo("Wailmer", "Field", "Water 2", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Wailord", "Field", "Water 2", GR_TYPICAL, [], -1),
SpeciesInfo("Numel", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Camerupt", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Torkoal", "Field", "Field", GR_TYPICAL, [], 0),
SpeciesInfo("Spoink", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Grumpig", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Spinda", "Field", "Human-Like", GR_TYPICAL, [], 0),
SpeciesInfo("Trapinch", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Vibrava", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Flygon", "Bug", "Bug", GR_TYPICAL, [], -2),
SpeciesInfo("Cacnea", "Grass", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Cacturne", "Grass", "Human-Like", GR_TYPICAL, [], -1),
SpeciesInfo("Swablu", "Flying", "Dragon", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Altaria", "Flying", "Dragon", GR_TYPICAL, [], -1),
SpeciesInfo("Zangoose", "Field", "Field", GR_TYPICAL, [], 0),
SpeciesInfo("Seviper", "Field", "Dragon", GR_TYPICAL, [], 0),
SpeciesInfo("Lunatone", "Mineral", "Mineral", GR_UNKNOWN, [], 0),
SpeciesInfo("Solrock", "Mineral", "Mineral", GR_UNKNOWN, [], 0),
SpeciesInfo("Barboach", "Water 2", "Water 2", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Whiscash", "Water 2", "Water 2", GR_TYPICAL, [], -1),
SpeciesInfo("Corphish", "Water 1", "Water 3", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Crawdaunt", "Water 1", "Water 3", GR_TYPICAL, [], -1),
SpeciesInfo("Baltoy", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Claydol", "Mineral", "Mineral", GR_UNKNOWN, [], -1),
SpeciesInfo("Lileep", "Water 3", "Water 3", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Cradily", "Water 3", "Water 3", GR_TYPICAL, [], -1),
SpeciesInfo("Anorith", "Water 3", "Water 3", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Armaldo", "Water 3", "Water 3", GR_TYPICAL, [], -1),
SpeciesInfo("Feebas", "Water 1", "Dragon", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Milotic", "Water 1", "Dragon", GR_TYPICAL, [], -1),
SpeciesInfo("Castform", "Fairy", "Amorphous", GR_TYPICAL, [], 0),
SpeciesInfo("Kecleon", "Field", "Field", GR_TYPICAL, [], 0),
SpeciesInfo("Shuppet", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Banette", "Amorphous", "Amorphous", GR_TYPICAL, [], -1),
SpeciesInfo("Duskull", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Dusclops", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Dusknoir", "Amorphous", "Amorphous", GR_TYPICAL, [], -2),
SpeciesInfo("Tropius", "Monster", "Grass", GR_TYPICAL, [], 0),
SpeciesInfo("Chingling", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Chimecho", "Amorphous", "Amorphous", GR_TYPICAL, [], -1),
SpeciesInfo("Absol", "Field", "Field", GR_TYPICAL, [], 0),
SpeciesInfo("Snorunt", "Fairy", "Mineral", GR_TYPICAL, [EvolveData(1), EvolveData(2)], 0),
SpeciesInfo("Glalie", "Fairy", "Mineral", GR_TYPICAL, [], -1),
SpeciesInfo("Froslass", "Fairy", "Mineral", GR_FEMALE_ONLY, [], -2),
SpeciesInfo("Spheal", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Sealeo", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Walrein", "Water 1", "Field", GR_TYPICAL, [], -2),
SpeciesInfo("Clamperl", "Water 1", "Water 1", GR_TYPICAL, [EvolveData(1), EvolveData(2)], 0),
SpeciesInfo("Huntail", "Water 1", "Water 1", GR_TYPICAL, [], -1),
SpeciesInfo("Gorebyss", "Water 1", "Water 1", GR_TYPICAL, [], -2),
SpeciesInfo("Relicanth", "Water 1", "Water 2", GR_TYPICAL, [], 0),
SpeciesInfo("Luvdisc", "Water 2", "Water 2", GR_TYPICAL, [], 0),
SpeciesInfo("Bagon", "Dragon", "Dragon", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Shelgon", "Dragon", "Dragon", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Salamence", "Dragon", "Dragon", GR_TYPICAL, [], -2),
SpeciesInfo("Beldum", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Metang", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], -1),
SpeciesInfo("Metagross", "Mineral", "Mineral", GR_UNKNOWN, [], -2),
SpeciesInfo("Regirock", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Regice", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Registeel", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Latias", "NED", "NED", GR_FEMALE_ONLY, [], 0),
SpeciesInfo("Latios", "NED", "NED", GR_MALE_ONLY, [], 0),
SpeciesInfo("Kyogre", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Groudon", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Rayquaza", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Jirachi", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Deoxys", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Turtwig", "Monster", "Grass", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Grotle", "Monster", "Grass", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Torterra", "Monster", "Grass", GR_TYPICAL, [], -2),
SpeciesInfo("Chimchar", "Field", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Monferno", "Field", "Human-Like", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Infernape", "Field", "Human-Like", GR_TYPICAL, [], -2),
SpeciesInfo("Piplup", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Prinplup", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Empoleon", "Water 1", "Field", GR_TYPICAL, [], -2),
SpeciesInfo("Starly", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Staravia", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Staraptor", "Flying", "Flying", GR_TYPICAL, [], -2),
SpeciesInfo("Bidoof", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Bibarel", "Water 1", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Kricketot", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Kricketune", "Bug", "Bug", GR_TYPICAL, [], -1),
SpeciesInfo("Shinx", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Luxio", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Luxray", "Field", "Field", GR_TYPICAL, [], -2),
SpeciesInfo("Cranidos", "Monster", "Monster", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Rampardos", "Monster", "Monster", GR_TYPICAL, [], -1),
SpeciesInfo("Shieldon", "Monster", "Monster", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Bastiodon", "Monster", "Monster", GR_TYPICAL, [], -1),
SpeciesInfo("Burmy", "Bug", "Bug", GR_TYPICAL, [EvolveData(1, PlantWormadam), EvolveData(1, SandyWormadam), EvolveData(1, TrashWormadam), EvolveData(2)], 0),
SpeciesInfo("Wormadam", "Bug", "Bug", GR_FEMALE_ONLY, [], -1),
SpeciesInfo("Mothim", "Bug", "Bug", GR_MALE_ONLY, [], -2),
SpeciesInfo("Combee", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Vespiquen", "Bug", "Bug", GR_FEMALE_ONLY, [], -1),
SpeciesInfo("Pachirisu", "Field", "Fairy", GR_TYPICAL, [], 0),
SpeciesInfo("Buizel", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Floatzel", "Water 1", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Cherubi", "Fairy", "Grass", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Cherrim", "Fairy", "Grass", GR_TYPICAL, [], -1),
SpeciesInfo("Shellos", "Water 1", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Gastrodon", "Water 1", "Amorphous", GR_TYPICAL, [], -1),
SpeciesInfo("Drifloon", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Drifblim", "Amorphous", "Amorphous", GR_TYPICAL, [], -1),
SpeciesInfo("Buneary", "Field", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Lopunny", "Field", "Human-Like", GR_TYPICAL, [], -1),
SpeciesInfo("Glameow", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Purugly", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Stunky", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Skuntank", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Bronzor", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Bronzong", "Mineral", "Mineral", GR_UNKNOWN, [], -1),
SpeciesInfo("Chatot", "Flying", "Flying", GR_TYPICAL, [], 0),
SpeciesInfo("Spiritomb", "Amorphous", "Amorphous", GR_TYPICAL, [], 0),
SpeciesInfo("Gible", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Gabite", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Garchomp", "Monster", "Dragon", GR_TYPICAL, [], -2),
SpeciesInfo("Riolu", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Lucario", "Field", "Human-Like", GR_TYPICAL, [], -1),
SpeciesInfo("Hippopotas", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Hippowdon", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Skorupi", "Bug", "Water 3", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Drapion", "Bug", "Water 3", GR_TYPICAL, [], -1),
SpeciesInfo("Croagunk", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Toxicroak", "Human-Like", "Human-Like", GR_TYPICAL, [], 0),
SpeciesInfo("Carnivine", "Grass", "Grass", GR_TYPICAL, [], 0),
SpeciesInfo("Finneon", "Water 2", "Water 2", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Lumineon", "Water 2", "Water 2", GR_TYPICAL, [], -1),
SpeciesInfo("Snover", "Monster", "Grass", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Abomasnow", "Monster", "Grass", GR_TYPICAL, [], -1),
SpeciesInfo("Rotom", "Amorphous", "Amorphous", GR_UNKNOWN, [], 0),
SpeciesInfo("Uxie", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Mesprit", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Azelf", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Dialga", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Palkia", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Heatran", "NED", "NED", GR_TYPICAL, [], 0),
SpeciesInfo("Regigigas", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Giratina", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Cresselia", "NED", "NED", GR_FEMALE_ONLY, [], 0),
SpeciesInfo("Phione", "Water 1", "Fairy", GR_UNKNOWN, [], 0),
SpeciesInfo("Manaphy", "Water 1", "Fairy", GR_UNKNOWN, [], 0),
SpeciesInfo("Darkrai", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Shaymin", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Arceus", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Victini", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Snivy", "Field", "Grass", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Servine", "Field", "Grass", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Serperior", "Field", "Grass", GR_TYPICAL, [], -2),
SpeciesInfo("Tepig", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Pignite", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Emboar", "Field", "Field", GR_TYPICAL, [], -2),
SpeciesInfo("Oshawott", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Dewott", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Samurott", "Field", "Field", GR_TYPICAL, [], -2),
SpeciesInfo("Patrat", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Watchog", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Lillipup", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Herdier", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Stoutland", "Field", "Field", GR_TYPICAL, [], -2),
SpeciesInfo("Purrloin", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Liepard", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Pansage", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Simisage", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Pansear", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Simisear", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Panpour", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Simipour", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Munna", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Musharna", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Pidove", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Tranquill", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Unfezant", "Flying", "Flying", GR_TYPICAL, [], -2),
SpeciesInfo("Blitzle", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Zebstrika", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Roggenrola", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Boldore", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Gigalith", "Mineral", "Mineral", GR_TYPICAL, [], -2),
SpeciesInfo("Woobat", "Field", "Flying", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Swoobat", "Field", "Flying", GR_TYPICAL, [], -1),
SpeciesInfo("Drilbur", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Excadrill", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Audino", "Fairy", "Fairy", GR_TYPICAL, [], 0),
SpeciesInfo("Timburr", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Gurdurr", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Conkeldurr", "Human-Like", "Human-Like", GR_TYPICAL, [], -2),
SpeciesInfo("Tympole", "Water 1", "Water 1", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Palpitoad", "Water 1", "Water 1", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Seismitoad", "Water 1", "Water 1", GR_TYPICAL, [], -2),
SpeciesInfo("Throh", "Human-Like", "Human-Like", GR_MALE_ONLY, [], 0),
SpeciesInfo("Sawk", "Human-Like", "Human-Like", GR_MALE_ONLY, [], 0),
SpeciesInfo("Sewaddle", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Swadloon", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Leavanny", "Bug", "Bug", GR_TYPICAL, [], -2),
SpeciesInfo("Venipede", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Whirlipede", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Scolipede", "Bug", "Bug", GR_TYPICAL, [], -2),
SpeciesInfo("Cottonee", "Grass", "Fairy", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Whimsicott", "Grass", "Fairy", GR_FEMALE_ONLY, [], -1),
SpeciesInfo("Petilil", "Grass", "Grass", GR_FEMALE_ONLY, [EvolveData(1)], 0),
SpeciesInfo("Lilligant", "Grass", "Grass", GR_FEMALE_ONLY, [], -1),
SpeciesInfo("Basculin", "Water 2", "Water 2", GR_TYPICAL, [], 0),
SpeciesInfo("Sandile", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Krokorok", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Krookodile", "Field", "Field", GR_TYPICAL, [], -2),
SpeciesInfo("Darumaka", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Darmanitan", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Maractus", "Grass", "Grass", GR_TYPICAL, [], 0),
SpeciesInfo("Dwebble", "Bug", "Mineral", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Crustle", "Bug", "Mineral", GR_TYPICAL, [], -1),
SpeciesInfo("Scraggy", "Field", "Dragon", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Scrafty", "Field", "Dragon", GR_TYPICAL, [], -1),
SpeciesInfo("Sigilyph", "Flying", "Flying", GR_TYPICAL, [], 0),
SpeciesInfo("Yamask", "Mineral", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Cofagrigus", "Mineral", "Amorphous", GR_TYPICAL, [], -1),
SpeciesInfo("Tirtouga", "Water 1", "Water 3", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Carracosta", "Water 1", "Water 3", GR_TYPICAL, [], -1),
SpeciesInfo("Archen", "Flying", "Water 3", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Archeops", "Flying", "Water 3", GR_TYPICAL, [], -1),
SpeciesInfo("Trubbish", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Garbodor", "Mineral", "Mineral", GR_TYPICAL, [], -1),
SpeciesInfo("Zorua", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Zoroark", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Minccino", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Cinccino", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Gothita", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Gothorita", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Gothitelle", "Human-Like", "Human-Like", GR_TYPICAL, [], -2),
SpeciesInfo("Solosis", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Duosion", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Reuniclus", "Amorphous", "Amorphous", GR_TYPICAL, [], -2),
SpeciesInfo("Ducklett", "Water 1", "Flying", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Swanna", "Water 1", "Flying", GR_TYPICAL, [], -1),
SpeciesInfo("Vanillite", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Vanillish", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Vanilluxe", "Mineral", "Mineral", GR_TYPICAL, [], -2),
SpeciesInfo("Deerling", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Sawsbuck", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Emolga", "Field", "Field", GR_TYPICAL, [], 0),
SpeciesInfo("Karrablast", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Escavalier", "Bug", "Bug", GR_TYPICAL, [], -1),
SpeciesInfo("Foongus", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Amoonguss", "Grass", "Grass", GR_TYPICAL, [], -1),
SpeciesInfo("Frillish", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Jellicent", "Amorphous", "Amorphous", GR_TYPICAL, [], -1),
SpeciesInfo("Alomomola", "Water 1", "Water 2", GR_TYPICAL, [], 0),
SpeciesInfo("Joltik", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Galvantula", "Bug", "Bug", GR_TYPICAL, [], -1),
SpeciesInfo("Ferroseed", "Grass", "Mineral", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Ferrothorn", "Grass", "Mineral", GR_TYPICAL, [], -1),
SpeciesInfo("Klink", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Klang", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], -1),
SpeciesInfo("Klinklang", "Mineral", "Mineral", GR_UNKNOWN, [], -2),
SpeciesInfo("Tynamo", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Eelektrik", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Eelektross", "Amorphous", "Amorphous", GR_TYPICAL, [], -2),
SpeciesInfo("Elgyem", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Beheeyem", "Human-Like", "Human-Like", GR_TYPICAL, [], -1),
SpeciesInfo("Litwick", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Lampent", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Chandelure", "Amorphous", "Amorphous", GR_TYPICAL, [], -2),
SpeciesInfo("Axew", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Fraxure", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Haxorus", "Monster", "Dragon", GR_TYPICAL, [], -2),
SpeciesInfo("Cubchoo", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Beartic", "Field", "Field", GR_TYPICAL, [], -1),
SpeciesInfo("Cryogonal", "Mineral", "Mineral", GR_UNKNOWN, [], 0),
SpeciesInfo("Shelmet", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Accelgor", "Bug", "Bug", GR_TYPICAL, [], -1),
SpeciesInfo("Stunfisk", "Water 1", "Amorphous", GR_TYPICAL, [], 0),
SpeciesInfo("Mienfoo", "Field", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Mienshao", "Field", "Human-Like", GR_TYPICAL, [], -1),
SpeciesInfo("Druddigon", "Dragon", "Monster", GR_TYPICAL, [], 0),
SpeciesInfo("Golett", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0),
SpeciesInfo("Golurk", "Mineral", "Mineral", GR_UNKNOWN, [], -1),
SpeciesInfo("Pawniard", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Bisharp", "Human-Like", "Human-Like", GR_TYPICAL, [], -1),
SpeciesInfo("Bouffalant", "Field", "Field", GR_TYPICAL, [], 0),
SpeciesInfo("Rufflet", "Flying", "Flying", GR_MALE_ONLY, [EvolveData(1)], 0),
SpeciesInfo("Braviary", "Flying", "Flying", GR_MALE_ONLY, [], -1),
SpeciesInfo("Vullaby", "Flying", "Flying", GR_FEMALE_ONLY, [EvolveData(1)], 0),
SpeciesInfo("Mandibuzz", "Flying", "Flying", GR_FEMALE_ONLY, [], -1),
SpeciesInfo("Heatmor", "Field", "Field", GR_TYPICAL, [], 0),
SpeciesInfo("Durant", "Bug", "Bug", GR_TYPICAL, [], 0),
SpeciesInfo("Deino", "Dragon", "Dragon", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Zweilous", "Dragon", "Dragon", GR_TYPICAL, [EvolveData(1)], -1),
SpeciesInfo("Hydreigon", "Dragon", "Dragon", GR_TYPICAL, [], -2),
SpeciesInfo("Larvesta", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0),
SpeciesInfo("Volcarona", "Bug", "Bug", GR_TYPICAL, [], -1),
SpeciesInfo("Cobalion", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Terrakion", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Virizion", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Tornadus", "NED", "NED", GR_MALE_ONLY, [], 0),
SpeciesInfo("Thundurus", "NED", "NED", GR_MALE_ONLY, [], 0),
SpeciesInfo("Reshiram", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Zekrom", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Landorus", "NED", "NED", GR_MALE_ONLY, [], 0),
SpeciesInfo("Kyurem", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Keldeo", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Meloetta", "NED", "NED", GR_UNKNOWN, [], 0),
SpeciesInfo("Genesect", "NED", "NED", GR_UNKNOWN, [], 0)
]
);