const g_Generation9 = Generation(
"====[[Generation IX]]====",
GAME_SCARLET_VIOLET,
//UniversalTMs https://bulbapedia.bulbagarden.net/w/index.php?search=%22Every+Pok%C3%A9mon+can+learn+this+move+by%22&title=Special%3ASearch&go=Go
[
	"Endure",
	"Facade",
	"Protect",
	"Rest",
	"Sleep Talk",
	"Tera Blast"
],
//MonData https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_breeding_attributes https://bulbapedia.bulbagarden.net/wiki/List_of_cross-generational_evolutionary_lines
[
SpeciesInfo("Bulbasaur", "Monster", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Ivysaur", "Monster", "Grass", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Venusaur", "Monster", "Grass", GR_TYPICAL, [], -2, []),
SpeciesInfo("Charmander", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Charmeleon", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Charizard", "Monster", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Squirtle", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Wartortle", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Blastoise", "Monster", "Water 1", GR_TYPICAL, [], -2, []),
SpeciesInfo("Ekans", "Field", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Arbok", "Field", "Dragon", GR_TYPICAL, [], -1, []),
SpeciesInfo("Pichu", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Pikachu", "Field", "Fairy", GR_TYPICAL, [EvolveData(1, KantonianRaichu)], -1, []),
SpeciesInfo("Raichu", "Field", "Fairy", GR_TYPICAL, [], -2, [KantonianRaichu, AlolanRaichu]),
SpeciesInfo("Sandshrew", "Field", "Field", GR_TYPICAL, [EvolveData(1, KantonianSandslash, KantonianSandshrew), EvolveData(1, AlolanSandslash, AlolanSandshrew)], 0, [KantonianSandshrew, AlolanSandshrew]),
SpeciesInfo("Sandslash", "Field", "Field", GR_TYPICAL, [], -1, [KantonianSandslash, AlolanSandslash]),
SpeciesInfo("Cleffa", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Clefairy", "Fairy", "Fairy", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Clefable", "Fairy", "Fairy", GR_TYPICAL, [], -2, []),
SpeciesInfo("Vulpix", "Field", "Field", GR_TYPICAL, [EvolveData(1, KantonianNinetales, KantonianVulpix), EvolveData(1, AlolanNinetales, AlolanVulpix)], 0, [KantonianVulpix, AlolanVulpix]),
SpeciesInfo("Ninetales", "Field", "Field", GR_TYPICAL, [], -1, [KantonianNinetales, AlolanNinetales]),
SpeciesInfo("Igglybuff", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Jigglypuff", "Fairy", "Fairy", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Wigglytuff", "Fairy", "Fairy", GR_TYPICAL, [], -2, []),
SpeciesInfo("Oddish", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Gloom", "Grass", "Grass", GR_TYPICAL, [EvolveData(1), EvolveData(2)], -1, []),
SpeciesInfo("Vileplume", "Grass", "Grass", GR_TYPICAL, [], -2, []),
SpeciesInfo("Bellossom", "Grass", "Grass", GR_TYPICAL, [], -3, []),
SpeciesInfo("Venonat", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Venomoth", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Diglett", "Field", "Field", GR_TYPICAL, [EvolveData(1, KantonianDugtrio, KantonianDiglett), EvolveData(1, AlolanDugtrio, AlolanDiglett)], 0, [KantonianDiglett, AlolanDiglett]),
SpeciesInfo("Dugtrio", "Field", "Field", GR_TYPICAL, [], -1, [KantonianDugtrio, AlolanDugtrio]),
SpeciesInfo("Meowth", "Field", "Field", GR_TYPICAL, [EvolveData(1, KantonianPersian, KantonianMeowth), EvolveData(1, AlolanPersian, AlolanMeowth), EvolveData(2, null, GalarianMeowth)], 0, [KantonianMeowth, AlolanMeowth, GalarianMeowth]),
SpeciesInfo("Persian", "Field", "Field", GR_TYPICAL, [], -1, [KantonianPersian, AlolanPersian]),
SpeciesInfo("Perrserker", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Psyduck", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Golduck", "Water 1", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Mankey", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Primeape", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Annihilape", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Growlithe", "Field", "Field", GR_TYPICAL, [EvolveData(1, KantonianArcanine, KantonianGrowlithe), EvolveData(1, HisuianArcanine, HisuianGrowlithe)], 0, [KantonianGrowlithe, HisuianGrowlithe]),
SpeciesInfo("Arcanine", "Field", "Field", GR_TYPICAL, [], -1, [KantonianArcanine, HisuianArcanine]),
SpeciesInfo("Poliwag", "Water 1", "Water 1", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Poliwhirl", "Water 1", "Water 1", GR_TYPICAL, [EvolveData(1), EvolveData(2)], -1, []),
SpeciesInfo("Poliwrath", "Water 1", "Water 1", GR_TYPICAL, [], -2, []),
SpeciesInfo("Politoed", "Water 1", "Water 1", GR_TYPICAL, [], -3, []),
SpeciesInfo("Bellsprout", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Weepinbell", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Victreebel", "Grass", "Grass", GR_TYPICAL, [], -2, []),
SpeciesInfo("Tentacool", "Water 3", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Tentacruel", "Water 3", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Geodude", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1, KantonianGraveler, KantonianGeodude), EvolveData(1, AlolanGraveler, AlolanGeodude)], 0, [KantonianGeodude, AlolanGeodude]),
SpeciesInfo("Graveler", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1, KantonianGolem, KantonianGraveler), EvolveData(1, AlolanGolem, AlolanGraveler)], -1, [KantonianGraveler, AlolanGraveler]),
SpeciesInfo("Golem", "Mineral", "Mineral", GR_TYPICAL, [], -2, [KantonianGolem, AlolanGolem]),
SpeciesInfo("Slowpoke", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1, KantonianSlowbro, KantonianSlowpoke), EvolveData(1, GalarianSlowbro, GalarianSlowpoke), EvolveData(1, JohtonianSlowking, KantonianSlowpoke), EvolveData(1, GalarianSlowking, GalarianSlowpoke)], 0, [KantonianSlowpoke, GalarianSlowpoke]),
SpeciesInfo("Slowbro", "Monster", "Water 1", GR_TYPICAL, [], -1, [KantonianSlowbro, GalarianSlowbro]),
SpeciesInfo("Slowking", "Monster", "Water 1", GR_TYPICAL, [], -2, [JohtonianSlowking, GalarianSlowking]),
SpeciesInfo("Magnemite", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Magneton", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], -1, []),
SpeciesInfo("Magnezone", "Mineral", "Mineral", GR_UNKNOWN, [], -2, []),
SpeciesInfo("Doduo", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Dodrio", "Flying", "Flying", GR_TYPICAL, [], -1, []),
SpeciesInfo("Seel", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Dewgong", "Water 1", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Grimer", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1, KantonianMuk, KantonianGrimer), EvolveData(1, AlolanMuk, AlolanGrimer)], 0, [KantonianGrimer, AlolanGrimer]),
SpeciesInfo("Muk", "Amorphous", "Amorphous", GR_TYPICAL, [], -1, [KantonianMuk, AlolanMuk]),
SpeciesInfo("Shellder", "Water 3", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Cloyster", "Water 3", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Gastly", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Haunter", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Gengar", "Amorphous", "Amorphous", GR_TYPICAL, [], -2, []),
SpeciesInfo("Drowzee", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Hypno", "Human-Like", "Human-Like", GR_TYPICAL, [], -1, []),
SpeciesInfo("Voltorb", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1, KantonianElectrode, KantonianVoltorb), EvolveData(1, HisuianElectrode, HisuianVoltorb)], 0, [KantonianVoltorb, HisuianVoltorb]),
SpeciesInfo("Electrode", "Mineral", "Mineral", GR_UNKNOWN, [], -1, [KantonianElectrode, HisuianElectrode]),
SpeciesInfo("Exeggcute", "Grass", "Grass", GR_TYPICAL, [EvolveData(1, KantonianExeggutor)], 0, []),
SpeciesInfo("Exeggutor", "Grass", "Grass", GR_TYPICAL, [], -1, [KantonianExeggutor, AlolanExeggutor]),
SpeciesInfo("Tyrogue", "NED", "NED", GR_MALE_ONLY, [EvolveData(1), EvolveData(2), EvolveData(3)], 0, []),
SpeciesInfo("Hitmonlee", "Human-Like", "Human-Like", GR_MALE_ONLY, [], -1, []),
SpeciesInfo("Hitmonchan", "Human-Like", "Human-Like", GR_MALE_ONLY, [], -2, []),
SpeciesInfo("Hitmontop", "Human-Like", "Human-Like", GR_MALE_ONLY, [], -3, []),
SpeciesInfo("Koffing", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Weezing", "Amorphous", "Amorphous", GR_TYPICAL, [], -1, [KantonianWeezing, GalarianWeezing]),
SpeciesInfo("Rhyhorn", "Monster", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Rhydon", "Monster", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Rhyperior", "Monster", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Happiny", "NED", "NED", GR_FEMALE_ONLY, [EvolveData(1)], 0, []),
SpeciesInfo("Chansey", "Fairy", "Fairy", GR_FEMALE_ONLY, [EvolveData(1)], -1, []),
SpeciesInfo("Blissey", "Fairy", "Fairy", GR_FEMALE_ONLY, [], -2, []),
SpeciesInfo("Horsea", "Water 1", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Seadra", "Water 1", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Kingdra", "Water 1", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Scyther", "Bug", "Bug", GR_TYPICAL, [EvolveData(1), EvolveData(2)], 0, []),
SpeciesInfo("Scizor", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Kleavor", "Bug", "Bug", GR_TYPICAL, [], -2, []),
SpeciesInfo("Elekid", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Electabuzz", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Electivire", "Human-Like", "Human-Like", GR_TYPICAL, [], -2, []),
SpeciesInfo("Magby", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Magmar", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Magmortar", "Human-Like", "Human-Like", GR_TYPICAL, [], -2, []),
SpeciesInfo("Tauros", "Field", "Field", GR_MALE_ONLY, [], 0, [KantonianTauros, PaldeanTaurosAqua, PaldeanTaurosBlaze, PaldeanTaurosCombat]),
SpeciesInfo("Magikarp", "Water 2", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Gyarados", "Water 2", "Dragon", GR_TYPICAL, [], -1, []),
SpeciesInfo("Lapras", "Monster", "Water 1", GR_TYPICAL, [], 0, []),
SpeciesInfo("Ditto", "Ditto", "Ditto", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Eevee", "Field", "Field", GR_TYPICAL, [EvolveData(1), EvolveData(2), EvolveData(3), EvolveData(4), EvolveData(5), EvolveData(6), EvolveData(7), EvolveData(8)], 0, []),
SpeciesInfo("Vaporeon", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Jolteon", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Flareon", "Field", "Field", GR_TYPICAL, [], -3, []),
SpeciesInfo("Espeon", "Field", "Field", GR_TYPICAL, [], -4, []),
SpeciesInfo("Umbreon", "Field", "Field", GR_TYPICAL, [], -5, []),
SpeciesInfo("Leafeon", "Field", "Field", GR_TYPICAL, [], -6, []),
SpeciesInfo("Glaceon", "Field", "Field", GR_TYPICAL, [], -7, []),
SpeciesInfo("Sylveon", "Field", "Field", GR_TYPICAL, [], -8, []),
SpeciesInfo("Porygon", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Porygon2", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], -1, []),
SpeciesInfo("Porygon-Z", "Mineral", "Mineral", GR_UNKNOWN, [], -2, []),
SpeciesInfo("Munchlax", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Snorlax", "Monster", "Monster", GR_TYPICAL, [], -1, []),
SpeciesInfo("Articuno", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Zapdos", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Moltres", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Dratini", "Water 1", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Dragonair", "Water 1", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Dragonite", "Water 1", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Mewtwo", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Mew", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Chikorita", "Monster", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Bayleef", "Monster", "Grass", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Meganium", "Monster", "Grass", GR_TYPICAL, [], -2, []),
SpeciesInfo("Cyndaquil", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Quilava", "Field", "Field", GR_TYPICAL, [EvolveData(1, JohtonianTyphlosion), EvolveData(1, HisuianTyphlosion)], -1, []),
SpeciesInfo("Typhlosion", "Field", "Field", GR_TYPICAL, [], -2, [JohtonianTyphlosion, HisuianTyphlosion]),
SpeciesInfo("Totodile", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Croconaw", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Feraligatr", "Monster", "Water 1", GR_TYPICAL, [], -2, []),
SpeciesInfo("Sentret", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Furret", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Hoothoot", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Noctowl", "Flying", "Flying", GR_TYPICAL, [], -1, []),
SpeciesInfo("Spinarak", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Ariados", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Chinchou", "Water 2", "Water 2", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Lanturn", "Water 2", "Water 2", GR_TYPICAL, [], -1, []),
SpeciesInfo("Mareep", "Monster", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Flaaffy", "Monster", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Ampharos", "Monster", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Azurill", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Marill", "Water 1", "Fairy", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Azumarill", "Water 1", "Fairy", GR_TYPICAL, [], -2, []),
SpeciesInfo("Bonsly", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Sudowoodo", "Mineral", "Mineral", GR_TYPICAL, [], -1, []),
SpeciesInfo("Hoppip", "Fairy", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Skiploom", "Fairy", "Grass", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Jumpluff", "Fairy", "Grass", GR_TYPICAL, [], -2, []),
SpeciesInfo("Aipom", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Ambipom", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Sunkern", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Sunflora", "Grass", "Grass", GR_TYPICAL, [], -1, []),
SpeciesInfo("Yanma", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Yanmega", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Wooper", "Water 1", "Field", GR_TYPICAL, [EvolveData(1, null, JohtonianWooper), EvolveData(2, null, PaldeanWooper)], 0, [JohtonianWooper, PaldeanWooper]),
SpeciesInfo("Quagsire", "Water 1", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Clodsire", "Water 1", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Murkrow", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Honchkrow", "Flying", "Flying", GR_TYPICAL, [], -1, []),
SpeciesInfo("Misdreavus", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Mismagius", "Amorphous", "Amorphous", GR_TYPICAL, [], -1, []),
SpeciesInfo("Girafarig", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Farigiraf", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Pineco", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Forretress", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Dunsparce", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Dudunsparce", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Gligar", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Gliscor", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Snubbull", "Field", "Fairy", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Granbull", "Field", "Fairy", GR_TYPICAL, [], -1, []),
SpeciesInfo("Qwilfish", "Water 2", "Water 2", GR_TYPICAL, [EvolveData(1, null, HisuianQwilfish)], 0, [JohtonianQwilfish, HisuianQwilfish]),
SpeciesInfo("Overqwil", "Water 2", "Water 2", GR_TYPICAL, [], -1, []),
SpeciesInfo("Heracross", "Bug", "Bug", GR_TYPICAL, [], 0, []),
SpeciesInfo("Sneasel", "Field", "Field", GR_TYPICAL, [EvolveData(1, null, JohtonianSneasel), EvolveData(2, null, HisuianSneasel)], 0, [JohtonianSneasel, HisuianSneasel]),
SpeciesInfo("Weavile", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Sneasler", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Teddiursa", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Ursaring", "Field", "Field", GR_TYPICAL, [EvolveData(1, NormalUrsaluna)], -1, []),
SpeciesInfo("Ursaluna", "Field", "Field", GR_TYPICAL, [], -2, [NormalUrsaluna, BloodmoonUrsaluna]),
SpeciesInfo("Slugma", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Magcargo", "Amorphous", "Amorphous", GR_TYPICAL, [], -1, []),
SpeciesInfo("Swinub", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Piloswine", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Mamoswine", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Delibird", "Water 1", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Skarmory", "Flying", "Flying", GR_TYPICAL, [], 0, []),
SpeciesInfo("Houndour", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Houndoom", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Phanpy", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Donphan", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Stantler", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Wyrdeer", "Field", "Field", GR_TYPICAL, [] -1, []),
SpeciesInfo("Smeargle", "Field", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Raikou", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Entei", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Suicune", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Larvitar", "Monster", "Monster", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Pupitar", "Monster", "Monster", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Tyranitar", "Monster", "Monster", GR_TYPICAL, [], -2, []),
SpeciesInfo("Lugia", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Ho-Oh", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Treecko", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Grovyle", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Sceptile", "Monster", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Torchic", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Combusken", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Blaziken", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Mudkip", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Marshtomp", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Swampert", "Monster", "Water 1", GR_TYPICAL, [], -2, []),
SpeciesInfo("Poochyena", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Mightyena", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Lotad", "Water 1", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Lombre", "Water 1", "Grass", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Ludicolo", "Water 1", "Grass", GR_TYPICAL, [], -2, []),
SpeciesInfo("Seedot", "Field", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Nuzleaf", "Field", "Grass", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Shiftry", "Field", "Grass", GR_TYPICAL, [], -2, []),
SpeciesInfo("Wingull", "Water 1", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Pelipper", "Water 1", "Flying", GR_TYPICAL, [], -1, []),
SpeciesInfo("Ralts", "Human-Like", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Kirlia", "Human-Like", "Amorphous", GR_MALE_ONLY, [EvolveData(1), EvolveData(2)], -1, []),
SpeciesInfo("Gardevoir", "Human-Like", "Amorphous", GR_TYPICAL, [], -2, []),
SpeciesInfo("Gallade", "Human-Like", "Amorphous", GR_MALE_ONLY, [], -3, []),
SpeciesInfo("Surskit", "Water 1", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Masquerain", "Water 1", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Shroomish", "Fairy", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Breloom", "Fairy", "Grass", GR_TYPICAL, [], -1, []),
SpeciesInfo("Slakoth", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Vigoroth", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Slaking", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Makuhita", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Hariyama", "Human-Like", "Human-Like", GR_TYPICAL, [], -1, []),
SpeciesInfo("Nosepass", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Probopass", "Mineral", "Mineral", GR_TYPICAL, [], -1, []),
SpeciesInfo("Sableye", "Human-Like", "Human-Like", GR_TYPICAL, [], 0, []),
SpeciesInfo("Meditite", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Medicham", "Human-Like", "Human-Like", GR_TYPICAL, [], -1, []),
SpeciesInfo("Plusle", "Fairy", "Fairy", GR_TYPICAL, [], 0, []),
SpeciesInfo("Minun", "Fairy", "Fairy", GR_TYPICAL, [], 0, []),
SpeciesInfo("Volbeat", "Bug", "Human-Like", GR_MALE_ONLY, [], 0, []),
SpeciesInfo("Illumise", "Bug", "Human-Like", GR_FEMALE_ONLY, [], 0, []),
SpeciesInfo("Gulpin", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Swalot", "Amorphous", "Amorphous", GR_TYPICAL, [], -1, []),
SpeciesInfo("Numel", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Camerupt", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Torkoal", "Field", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Spoink", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Grumpig", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Trapinch", "Bug", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Vibrava", "Bug", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Flygon", "Bug", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Cacnea", "Grass", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Cacturne", "Grass", "Human-Like", GR_TYPICAL, [], -1, []),
SpeciesInfo("Swablu", "Flying", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Altaria", "Flying", "Dragon", GR_TYPICAL, [], -1, []),
SpeciesInfo("Zangoose", "Field", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Seviper", "Field", "Dragon", GR_TYPICAL, [], 0, []),
SpeciesInfo("Barboach", "Water 2", "Water 2", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Whiscash", "Water 2", "Water 2", GR_TYPICAL, [], -1, []),
SpeciesInfo("Corphish", "Water 1", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Crawdaunt", "Water 1", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Feebas", "Water 1", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Milotic", "Water 1", "Dragon", GR_TYPICAL, [], -1, []),
SpeciesInfo("Shuppet", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Banette", "Amorphous", "Amorphous", GR_TYPICAL, [], -1, []),
SpeciesInfo("Duskull", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Dusclops", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Dusknoir", "Amorphous", "Amorphous", GR_TYPICAL, [], -2, []),
SpeciesInfo("Tropius", "Monster", "Grass", GR_TYPICAL, [], 0, []),
SpeciesInfo("Chingling", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Chimecho", "Amorphous", "Amorphous", GR_TYPICAL, [], -1, []),
SpeciesInfo("Snorunt", "Fairy", "Mineral", GR_TYPICAL, [EvolveData(1), EvolveData(2)], 0, []),
SpeciesInfo("Glalie", "Fairy", "Mineral", GR_TYPICAL, [], -1, []),
SpeciesInfo("Froslass", "Fairy", "Mineral", GR_FEMALE_ONLY, [], -2, []),
SpeciesInfo("Luvdisc", "Water 2", "Water 2", GR_TYPICAL, [], 0, []),
SpeciesInfo("Bagon", "Dragon", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Shelgon", "Dragon", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Salamence", "Dragon", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Beldum", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Metang", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], -1, []),
SpeciesInfo("Metagross", "Mineral", "Mineral", GR_UNKNOWN, [], -2, []),
SpeciesInfo("Regirock", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Regice", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Registeel", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Latias", "NED", "NED", GR_FEMALE_ONLY, [], 0, []),
SpeciesInfo("Latios", "NED", "NED", GR_MALE_ONLY, [], 0, []),
SpeciesInfo("Kyogre", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Groudon", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Rayquaza", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Jirachi", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Deoxys", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Turtwig", "Monster", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Grotle", "Monster", "Grass", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Torterra", "Monster", "Grass", GR_TYPICAL, [], -2, []),
SpeciesInfo("Chimchar", "Field", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Monferno", "Field", "Human-Like", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Infernape", "Field", "Human-Like", GR_TYPICAL, [], -2, []),
SpeciesInfo("Piplup", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Prinplup", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Empoleon", "Water 1", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Starly", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Staravia", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Staraptor", "Flying", "Flying", GR_TYPICAL, [], -2, []),
SpeciesInfo("Kricketot", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Kricketune", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Shinx", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Luxio", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Luxray", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Cranidos", "Monster", "Monster", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Rampardos", "Monster", "Monster", GR_TYPICAL, [], -1, []),
SpeciesInfo("Shieldon", "Monster", "Monster", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Bastiodon", "Monster", "Monster", GR_TYPICAL, [], -1, []),
SpeciesInfo("Combee", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Vespiquen", "Bug", "Bug", GR_FEMALE_ONLY, [], -1, []),
SpeciesInfo("Pachirisu", "Field", "Fairy", GR_TYPICAL, [], 0, []),
SpeciesInfo("Buizel", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Floatzel", "Water 1", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Shellos", "Water 1", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Gastrodon", "Water 1", "Amorphous", GR_TYPICAL, [], -1, []),
SpeciesInfo("Drifloon", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Drifblim", "Amorphous", "Amorphous", GR_TYPICAL, [], -1, []),
SpeciesInfo("Stunky", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Skuntank", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Bronzor", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Bronzong", "Mineral", "Mineral", GR_UNKNOWN, [], -1, []),
SpeciesInfo("Spiritomb", "Amorphous", "Amorphous", GR_TYPICAL, [], 0, []),
SpeciesInfo("Gible", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Gabite", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Garchomp", "Monster", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Riolu", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Lucario", "Field", "Human-Like", GR_TYPICAL, [], -1, []),
SpeciesInfo("Hippopotas", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Hippowdon", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Croagunk", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Toxicroak", "Human-Like", "Human-Like", GR_TYPICAL, [], 0, []),
SpeciesInfo("Finneon", "Water 2", "Water 2", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Lumineon", "Water 2", "Water 2", GR_TYPICAL, [], -1, []),
SpeciesInfo("Snover", "Monster", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Abomasnow", "Monster", "Grass", GR_TYPICAL, [], -1, []),
SpeciesInfo("Rotom", "Amorphous", "Amorphous", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Uxie", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Mesprit", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Azelf", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Dialga", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Palkia", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Heatran", "NED", "NED", GR_TYPICAL, [], 0, []),
SpeciesInfo("Regigigas", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Giratina", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Cresselia", "NED", "NED", GR_FEMALE_ONLY, [], 0, []),
SpeciesInfo("Phione", "Water 1", "Fairy", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Manaphy", "Water 1", "Fairy", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Darkrai", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Shaymin", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Arceus", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Snivy", "Field", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Servine", "Field", "Grass", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Serperior", "Field", "Grass", GR_TYPICAL, [], -2, []),
SpeciesInfo("Tepig", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Pignite", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Emboar", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Oshawott", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Dewott", "Field", "Field", GR_TYPICAL, [EvolveData(1, UnovanSamurott), EvolveData(1, HisuianSamurott)], -1, []),
SpeciesInfo("Samurott", "Field", "Field", GR_TYPICAL, [], -2, [UnovanSamurott, HisuianSamurott]),
SpeciesInfo("Blitzle", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Zebstrika", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Drilbur", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Excadrill", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Timburr", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Gurdurr", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Conkeldurr", "Human-Like", "Human-Like", GR_TYPICAL, [], -2, []),
SpeciesInfo("Sewaddle", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Swadloon", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Leavanny", "Bug", "Bug", GR_TYPICAL, [], -2, []),
SpeciesInfo("Cottonee", "Grass", "Fairy", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Whimsicott", "Grass", "Fairy", GR_FEMALE_ONLY, [], -1, []),
SpeciesInfo("Petilil", "Grass", "Grass", GR_FEMALE_ONLY, [EvolveData(1, UnovanLilligant), EvolveData(1, HisuianLilligant)], 0, []),
SpeciesInfo("Lilligant", "Grass", "Grass", GR_FEMALE_ONLY, [], -1, [UnovanLilligant, HisuianLilligant]),
SpeciesInfo("Basculin", "Water 2", "Water 2", GR_TYPICAL, [EvolveData(1, null, WhiteStripedBasculin)], 0, [RedBlueStripedBasculin, WhiteStripedBasculin]),
SpeciesInfo("Basculegion", "Water 2", "Water 2", GR_TYPICAL, [], -1, []),
SpeciesInfo("Sandile", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Krokorok", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Krookodile", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Scraggy", "Field", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Scrafty", "Field", "Dragon", GR_TYPICAL, [], -1, []),
SpeciesInfo("Zorua", "Field", "Field", GR_TYPICAL, [EvolveData(1, UnovanZoroark, UnovanZorua), EvolveData(1, HisuianZoroark, HisuianZorua)], 0, [UnovanZorua, HisuianZorua]),
SpeciesInfo("Zoroark", "Field", "Field", GR_TYPICAL, [], -1, [UnovanZoroark, HisuianZoroark]),
SpeciesInfo("Minccino", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Cinccino", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Gothita", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Gothorita", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Gothitelle", "Human-Like", "Human-Like", GR_TYPICAL, [], -2, []),
SpeciesInfo("Solosis", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Duosion", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Reuniclus", "Amorphous", "Amorphous", GR_TYPICAL, [], -2, []),
SpeciesInfo("Ducklett", "Water 1", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Swanna", "Water 1", "Flying", GR_TYPICAL, [], -1, []),
SpeciesInfo("Deerling", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Sawsbuck", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Foongus", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Amoonguss", "Grass", "Grass", GR_TYPICAL, [], -1, []),
SpeciesInfo("Alomomola", "Water 1", "Water 2", GR_TYPICAL, [], 0, []),
SpeciesInfo("Joltik", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Galvantula", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Tynamo", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Eelektrik", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Eelektross", "Amorphous", "Amorphous", GR_TYPICAL, [], -2, []),
SpeciesInfo("Litwick", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Lampent", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Chandelure", "Amorphous", "Amorphous", GR_TYPICAL, [], -2, []),
SpeciesInfo("Axew", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Fraxure", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Haxorus", "Monster", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Cubchoo", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Beartic", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Cryogonal", "Mineral", "Mineral", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Mienfoo", "Field", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Mienshao", "Field", "Human-Like", GR_TYPICAL, [], -1, []),
SpeciesInfo("Golett", "Mineral", "Mineral", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Golurk", "Mineral", "Mineral", GR_UNKNOWN, [], -1, []),
SpeciesInfo("Pawniard", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Bisharp", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Kingambit", "Human-Like", "Human-Like", GR_TYPICAL, [], -2, []),
SpeciesInfo("Rufflet", "Flying", "Flying", GR_MALE_ONLY, [EvolveData(1, UnovanBraviary), EvolveData(1, HisuianBraviary)], 0, []),
SpeciesInfo("Braviary", "Flying", "Flying", GR_MALE_ONLY, [], -1, [UnovanBraviary, HisuianBraviary]),
SpeciesInfo("Vullaby", "Flying", "Flying", GR_FEMALE_ONLY, [EvolveData(1)], 0, []),
SpeciesInfo("Mandibuzz", "Flying", "Flying", GR_FEMALE_ONLY, [], -1, []),
SpeciesInfo("Deino", "Dragon", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Zweilous", "Dragon", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Hydreigon", "Dragon", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Larvesta", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Volcarona", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Cobalion", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Terrakion", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Virizion", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Tornadus", "NED", "NED", GR_MALE_ONLY, [], 0, []),
SpeciesInfo("Thundurus", "NED", "NED", GR_MALE_ONLY, [], 0, []),
SpeciesInfo("Reshiram", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Zekrom", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Landorus", "NED", "NED", GR_MALE_ONLY, [], 0, []),
SpeciesInfo("Kyurem", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Keldeo", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Meloetta", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Chespin", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Quilladin", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Chesnaught", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Fennekin", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Braixen", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Delphox", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Froakie", "Water 1", "Water 1", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Frogadier", "Water 1", "Water 1", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Greninja", "Water 1", "Water 1", GR_TYPICAL, [], -2, []),
SpeciesInfo("Fletchling", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Fletchinder", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Talonflame", "Flying", "Flying", GR_TYPICAL, [], -2, []),
SpeciesInfo("Scatterbug", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Spewpa", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Vivillon", "Bug", "Bug", GR_TYPICAL, [], -2, []),
SpeciesInfo("Litleo", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Pyroar", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Flabebe", "Fairy", "Fairy", GR_FEMALE_ONLY, [EvolveData(1)], 0, []),
SpeciesInfo("Floette", "Fairy", "Fairy", GR_FEMALE_ONLY, [EvolveData(1)], -1, []),
SpeciesInfo("Florges", "Fairy", "Fairy", GR_FEMALE_ONLY, [], -2, []),
SpeciesInfo("Skiddo", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Gogoat", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Espurr", "Field", "Field", GR_TYPICAL, [EvolveData(1, MaleMeowstic), EvolveData(1, FemaleMeowstic)], 0, []),
SpeciesInfo("Meowstic", "Field", "Field", GR_TYPICAL, [], -1, [MaleMeowstic, FemaleMeowstic]),
SpeciesInfo("Inkay", "Water 1", "Water 2", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Malamar", "Water 1", "Water 2", GR_TYPICAL, [], -1, []),
SpeciesInfo("Skrelp", "Water 1", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Dragalge", "Water 1", "Dragon", GR_TYPICAL, [], -1, []),
SpeciesInfo("Clauncher", "Water 1", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Clawitzer", "Water 1", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Hawlucha", "Flying", "Human-Like", GR_TYPICAL, [], 0, []),
SpeciesInfo("Dedenne", "Field", "Fairy", GR_TYPICAL, [], 0, []),
SpeciesInfo("Carbink", "Fairy", "Mineral", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Goomy", "Dragon", "Dragon", GR_TYPICAL, [EvolveData(1, KalosianSliggoo), EvolveData(1, HisuianSliggoo)], 0, []),
SpeciesInfo("Sliggoo", "Dragon", "Dragon", GR_TYPICAL, [EvolveData(1, KalosianGoodra, KalosianSliggoo), EvolveData(1, HisuianGoodra, HisuianSliggoo)], -1, [KalosianSliggoo, HisuianSliggoo]),
SpeciesInfo("Goodra", "Dragon", "Dragon", GR_TYPICAL, [], -2, [KalosianGoodra, HisuianGoodra]),
SpeciesInfo("Klefki", "Mineral", "Mineral", GR_TYPICAL, [], 0, []),
SpeciesInfo("Phantump", "Grass", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Trevenant", "Grass", "Amorphous", GR_TYPICAL, [], -1, []),
SpeciesInfo("Bergmite", "Monster", "Mineral", GR_TYPICAL, [EvolveData(1, KalosianAvalugg), EvolveData(1, HisuianAvalugg)], 0, []),
SpeciesInfo("Avalugg", "Monster", "Mineral", GR_TYPICAL, [], -1, [KalosianAvalugg, HisuianAvalugg]),
SpeciesInfo("Noibat", "Flying", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Noivern", "Flying", "Dragon", GR_TYPICAL, [], -1, []),
SpeciesInfo("Diancie", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Hoopa", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Volcanion", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Rowlet", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Dartrix", "Flying", "Flying", GR_TYPICAL, [EvolveData(1, AlolanDecidueye), EvolveData(1, HisuianDecidueye)], -1, []),
SpeciesInfo("Decidueye", "Flying", "Flying", GR_TYPICAL, [], -2, [AlolanDecidueye, HisuianDecidueye]),
SpeciesInfo("Litten", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Torracat", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Incineroar", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Popplio", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Brionne", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Primarina", "Water 1", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Pikipek", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Trumbeak", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Toucannon", "Flying", "Flying", GR_TYPICAL, [], -2, []),
SpeciesInfo("Yungoos", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Gumshoos", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Grubbin", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Charjabug", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Vikavolt", "Bug", "Bug", GR_TYPICAL, [], -2, []),
SpeciesInfo("Crabrawler", "Water 3", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Crabominable", "Water 3", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Oricorio", "Flying", "Flying", GR_TYPICAL, [], 0, []),
SpeciesInfo("Cutiefly", "Bug", "Fairy", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Ribombee", "Bug", "Fairy", GR_TYPICAL, [], -1, []),
SpeciesInfo("Rockruff", "Field", "Field", GR_TYPICAL, [EvolveData(1, MiddayLycanroc), EvolveData(1, MidnightLycanroc), EvolveData(1, DuskLycanroc)], 0, []),
SpeciesInfo("Lycanroc", "Field", "Field", GR_TYPICAL, [], -1, [MiddayLycanroc, MidnightLycanroc, DuskLycanroc]),
SpeciesInfo("Mareanie", "Water 1", "Water 1", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Toxapex", "Water 1", "Water 1", GR_TYPICAL, [], -1, []),
SpeciesInfo("Mudbray", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Mudsdale", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Dewpider", "Water 1", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Araquanid", "Water 1", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Fomantis", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Lurantis", "Grass", "Grass", GR_TYPICAL, [], -1, []),
SpeciesInfo("Salandit", "Monster", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Salazzle", "Monster", "Dragon", GR_FEMALE_ONLY, [], -1, []),
SpeciesInfo("Bounsweet", "Grass", "Grass", GR_FEMALE_ONLY, [EvolveData(1)], 0, []),
SpeciesInfo("Steenee", "Grass", "Grass", GR_FEMALE_ONLY, [EvolveData(1)], -1, []),
SpeciesInfo("Tsareena", "Grass", "Grass", GR_FEMALE_ONLY, [], -2, []),
SpeciesInfo("Comfey", "Grass", "Grass", GR_TYPICAL, [], 0, []),
SpeciesInfo("Oranguru", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Passimian", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Sandygast", "Amorphous", "Amorphous", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Palossand", "Amorphous", "Amorphous", GR_TYPICAL, [], -1, []),
SpeciesInfo("Minior", "Mineral", "Mineral", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Komala", "Field", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Mimikyu", "Amorphous", "Amorphous", GR_TYPICAL, [], 0, []),
SpeciesInfo("Bruxish", "Water 2", "Water 2", GR_TYPICAL, [], 0, []),
SpeciesInfo("Jangmo-o", "Dragon", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Hakamo-o", "Dragon", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Kommo-o", "Dragon", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Cosmog", "NED", "NED", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Cosmoem", "NED", "NED", GR_UNKNOWN, [EvolveData(1), EvolveData(2)], -1, []),
SpeciesInfo("Solgaleo", "NED", "NED", GR_UNKNOWN, [], -2, []),
SpeciesInfo("Lunala", "NED", "NED", GR_UNKNOWN, [], -3, []),
SpeciesInfo("Necrozma", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Magearna", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Grookey", "Field", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Thwackey", "Field", "Grass", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Rillaboom", "Field", "Grass", GR_TYPICAL, [], -2, []),
SpeciesInfo("Scorbunny", "Field", "Human-Like", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Raboot", "Field", "Human-Like", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Cinderace", "Field", "Human-Like", GR_TYPICAL, [], -2, []),
SpeciesInfo("Sobble", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Drizzile", "Water 1", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Inteleon", "Water 1", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Skwovet", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Greedent", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Rookidee", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Corvisquire", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Corviknight", "Flying", "Flying", GR_TYPICAL, [], -2, []),
SpeciesInfo("Chewtle", "Monster", "Water 1", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Drednaw", "Monster", "Water 1", GR_TYPICAL, [], -1, []),
SpeciesInfo("Rolycoly", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Carkol", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Coalossal", "Mineral", "Mineral", GR_TYPICAL, [], -2, []),
SpeciesInfo("Applin", "Grass", "Dragon", GR_TYPICAL, [EvolveData(1), EvolveData(2), EvolveData(3)], 0, []),
SpeciesInfo("Flapple", "Grass", "Dragon", GR_TYPICAL, [], -1, []),
SpeciesInfo("Appletun", "Grass", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Dipplin", "Grass", "Dragon", GR_TYPICAL, [EvolveData(1)], -3, []),
SpeciesInfo("Hydrapple", "Grass", "Dragon", GR_TYPICAL, [], -4, []),
SpeciesInfo("Silicobra", "Field", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Sandaconda", "Field", "Dragon", GR_TYPICAL, [], -1, []),
SpeciesInfo("Cramorant", "Water 1", "Flying", GR_TYPICAL, [], 0, []),
SpeciesInfo("Arrokuda", "Water 2", "Water 2", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Barraskewda", "Water 2", "Water 2", GR_TYPICAL, [], -1, []),
SpeciesInfo("Toxel", "NED", "NED", GR_TYPICAL, [EvolveData(1, AmpedToxtricity), EvolveData(1, LowKeyToxtricity)], 0, []),
SpeciesInfo("Toxtricity", "Human-Like", "Human-Like", GR_TYPICAL, [], -1, [AmpedToxtricity, LowKeyToxtricity]),
SpeciesInfo("Sinistea", "Mineral", "Amorphous", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Polteageist", "Mineral", "Amorphous", GR_UNKNOWN, [], -1, []),
SpeciesInfo("Hatenna", "Fairy", "Fairy", GR_FEMALE_ONLY, [EvolveData(1)], 0, []),
SpeciesInfo("Hattrem", "Fairy", "Fairy", GR_FEMALE_ONLY, [EvolveData(1)], -1, []),
SpeciesInfo("Hatterene", "Fairy", "Fairy", GR_FEMALE_ONLY, [], -2, []),
SpeciesInfo("Impidimp", "Fairy", "Human-Like", GR_MALE_ONLY, [EvolveData(1)], 0, []),
SpeciesInfo("Morgrem", "Fairy", "Human-Like", GR_MALE_ONLY, [EvolveData(1)], -1, []),
SpeciesInfo("Grimmsnarl", "Fairy", "Human-Like", GR_MALE_ONLY, [], -2, []),
SpeciesInfo("Milcery", "Fairy", "Amorphous", GR_FEMALE_ONLY, [EvolveData(1)], 0, []),
SpeciesInfo("Alcremie", "Fairy", "Amorphous", GR_FEMALE_ONLY, [], -1, []),
SpeciesInfo("Falinks", "Fairy", "Mineral", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Pincurchin", "Water 1", "Amorphous", GR_TYPICAL, [], 0, []),
SpeciesInfo("Snom", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Frosmoth", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Stonjourner", "Mineral", "Mineral", GR_TYPICAL, [], 0, []),
SpeciesInfo("Eiscue", "Water 1", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Indeedee", "Fairy", "Fairy", GR_TYPICAL, [], 0, [MaleIndeedee, FemaleIndeedee]),
SpeciesInfo("Morpeko", "Field", "Fairy", GR_TYPICAL, [], 0, []),
SpeciesInfo("Cufant", "Field", "Mineral", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Copperajah", "Field", "Mineral", GR_TYPICAL, [], -1, []),
SpeciesInfo("Duraludon", "Mineral", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Archaludon", "Mineral", "Dragon", GR_TYPICAL, [], -1, []),
SpeciesInfo("Dreepy", "Amorphous", "Dragon", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Drakloak", "Amorphous", "Dragon", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Dragapult", "Amorphous", "Dragon", GR_TYPICAL, [], -2, []),
SpeciesInfo("Zacian", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Zamazenta", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Eternatus", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Kubfu", "NED", "NED", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Urshifu", "NED", "NED", GR_TYPICAL, [], -1, []),
SpeciesInfo("Zarude", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Regieleki", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Regidrago", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Glastrier", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Spectrier", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Calyrex", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Enamorus", "NED", "NED", GR_FEMALE_ONLY, [], 0, []),
SpeciesInfo("Sprigatito", "Field", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Floragato", "Field", "Grass", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Meowscarada", "Field", "Grass", GR_TYPICAL, [], -2, []),
SpeciesInfo("Fuecoco", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Crocalor", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Skeledirge", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Quaxly", "Flying", "Water 1", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Quaxwell", "Flying", "Water 1", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Quaquaval", "Flying", "Water 1", GR_TYPICAL, [], -2, []),
SpeciesInfo("Lechonk", "Field", "Field", GR_TYPICAL, [EvolveData(1, MaleOinkologne), EvolveData(1, FemaleOinkologne)], 0, []),
SpeciesInfo("Oinkologne", "Field", "Field", GR_TYPICAL, [], -1, [MaleOinkologne, FemaleOinkologne]),
SpeciesInfo("Tarountula", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Spidops", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Nymble", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Lokix", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Pawmi", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Pawmo", "Field", "Field", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Pawmot", "Field", "Field", GR_TYPICAL, [], -2, []),
SpeciesInfo("Tandemaus", "Field", "Fairy", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Maushold", "Field", "Fairy", GR_UNKNOWN, [], -1, []),
SpeciesInfo("Fidough", "Field", "Mineral", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Dachsbun", "Field", "Mineral", GR_TYPICAL, [], -1, []),
SpeciesInfo("Smoliv", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Dolliv", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Arboliva", "Grass", "Grass", GR_TYPICAL, [], -2, []),
SpeciesInfo("Squawkabilly", "Flying", "Flying", GR_TYPICAL, [], 0, []),
SpeciesInfo("Nacli", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Naclstack", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Garganacl", "Mineral", "Mineral", GR_TYPICAL, [], -2, []),
SpeciesInfo("Charcadet", "Human-Like", "Human-Like", GR_TYPICAL, [EvolveData(1), EvolveData(2)], 0, []),
SpeciesInfo("Armarouge", "Human-Like", "Human-Like", GR_TYPICAL, [], -1, []),
SpeciesInfo("Ceruledge", "Human-Like", "Human-Like", GR_TYPICAL, [], -1, []),
SpeciesInfo("Tadbulb", "Water 1", "Water 1", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Bellibolt", "Water 1", "Water 1", GR_TYPICAL, [], -1, []),
SpeciesInfo("Wattrel", "Water 1", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Kilowattrel", "Water 1", "Flying", GR_TYPICAL, [], -1, []),
SpeciesInfo("Maschiff", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Mabosstiff", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Shroodle", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Grafaiai", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Bramblin", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Brambleghast", "Grass", "Grass", GR_TYPICAL, [], -1, []),
SpeciesInfo("Toedscool", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Toedscruel", "Grass", "Grass", GR_TYPICAL, [], -1, []),
SpeciesInfo("Klawf", "Water 3", "Water 3", GR_TYPICAL, [], 0, []),
SpeciesInfo("Capsakid", "Grass", "Grass", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Scovillain", "Grass", "Grass", GR_TYPICAL, [], -1, []),
SpeciesInfo("Rellor", "Bug", "Bug", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Rabsca", "Bug", "Bug", GR_TYPICAL, [], -1, []),
SpeciesInfo("Flittle", "Flying", "Flying", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Espathra", "Flying", "Flying", GR_TYPICAL, [], -1, []),
SpeciesInfo("Tinkatink", "Fairy", "Fairy", GR_FEMALE_ONLY, [EvolveData(1)], 0, []),
SpeciesInfo("Tinkatuff", "Fairy", "Fairy", GR_FEMALE_ONLY, [EvolveData(1)], -1, []),
SpeciesInfo("Tinkaton", "Fairy", "Fairy", GR_FEMALE_ONLY, [], -2, []),
SpeciesInfo("Wiglett", "Water 3", "Water 3", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Wugtrio", "Water 3", "Water 3", GR_TYPICAL, [], -1, []),
SpeciesInfo("Bombirdier", "Flying", "Flying", GR_TYPICAL, [], 0, []),
SpeciesInfo("Finizen", "Field", "Water 2", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Palafin", "Field", "Water 2", GR_TYPICAL, [], -1, []),
SpeciesInfo("Varoom", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Revavroom", "Mineral", "Mineral", GR_TYPICAL, [], -1, []),
SpeciesInfo("Cyclizar", "Field", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Orthworm", "Field", "Field", GR_TYPICAL, [], 0, []),
SpeciesInfo("Glimmet", "Mineral", "Mineral", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Glimmora", "Mineral", "Mineral", GR_TYPICAL, [], -1, []),
SpeciesInfo("Greavard", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Houndstone", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Flamigo", "Flying", "Flying", GR_TYPICAL, [], 0, []),
SpeciesInfo("Cetoddle", "Field", "Field", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Cetitan", "Field", "Field", GR_TYPICAL, [], -1, []),
SpeciesInfo("Veluza", "Water 2", "Water 2", GR_TYPICAL, [], 0, []),
SpeciesInfo("Dondozo", "Water 2", "Water 2", GR_TYPICAL, [], 0, []),
SpeciesInfo("Tatsugiri", "Water 2", "Water 2", GR_TYPICAL, [], 0, []),
SpeciesInfo("Great Tusk", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Scream Tail", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Brute Bonnet", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Flutter Mane", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Slither Wing", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Sandy Shocks", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Iron Treads", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Iron Bundle", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Iron Hands", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Iron Jugulis", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Iron Moth", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Iron Thorns", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Frigibax", "Dragon", "Mineral", GR_TYPICAL, [EvolveData(1)], 0, []),
SpeciesInfo("Arctibax", "Dragon", "Mineral", GR_TYPICAL, [EvolveData(1)], -1, []),
SpeciesInfo("Baxcalibur", "Dragon", "Mineral", GR_TYPICAL, [], -2, []),
SpeciesInfo("Gimmighoul", "NED", "NED", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Gholdengo", "NED", "NED", GR_UNKNOWN, [], -1, []),
SpeciesInfo("Wo-Chien", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Chien-Pao", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Ting-Lu", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Chi-Yu", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Roaring Moon", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Iron Valiant", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Koraidon", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Miraidon", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Walking Wake", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Iron Leaves", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Poltchageist", "Mineral", "Amorphous", GR_UNKNOWN, [EvolveData(1)], 0, []),
SpeciesInfo("Sinistcha", "Mineral", "Amorphous", GR_UNKNOWN, [], -1, []),
SpeciesInfo("Okidogi", "NED", "NED", GR_MALE_ONLY, [], 0, []),
SpeciesInfo("Munkidori", "NED", "NED", GR_MALE_ONLY, [], 0, []),
SpeciesInfo("Fezandipiti", "NED", "NED", GR_MALE_ONLY, [], 0, []),
SpeciesInfo("Ogerpon", "NED", "NED", GR_FEMALE_ONLY, [], 0, []),
SpeciesInfo("Gouging Fire", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Raging Bolt", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Iron Boulder", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Iron Crown", "NED", "NED", GR_UNKNOWN, [], 0, []),
SpeciesInfo("Terapagos", "NED", "NED", GR_TYPICAL, [], 0, []),
SpeciesInfo("Pecharunt", "NED", "NED", GR_UNKNOWN, [], 0, [])
]
);