const g_Generation7 = Generation(
"====[[Generation VII]]====",
GAMECOMBO_SM_USUM,
//UniversalTMs https://bulbapedia.bulbagarden.net/w/index.php?search=%22Every+Pok%C3%A9mon+can+learn+this+move+by%22&title=Special%3ASearch&go=Go
[
"Attract",
"Confide",
"Double Team",
"Frustration",
"Hidden Power",
"Protect",
"Rest",
"Return",
"Round",
"Sleep Talk",
"Swagger",
"Toxic"
],
//MonData https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_breeding_attributes https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_National_Pok%C3%A9dex_number
[
SpeciesInfo("Bulbasaur", "Monster", "Grass", GR_TYPICAL, ["Ivysaur"]),
SpeciesInfo("Ivysaur", "Monster", "Grass", GR_TYPICAL, ["Venusaur"]),
SpeciesInfo("Venusaur", "Monster", "Grass", GR_TYPICAL, []),
SpeciesInfo("Charmander", "Monster", "Dragon", GR_TYPICAL, ["Charmeleon"]),
SpeciesInfo("Charmeleon", "Monster", "Dragon", GR_TYPICAL, ["Charizard"]),
SpeciesInfo("Charizard", "Monster", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Squirtle", "Monster", "Water 1", GR_TYPICAL, ["Wartortle"]),
SpeciesInfo("Wartortle", "Monster", "Water 1", GR_TYPICAL, ["Blastoise"]),
SpeciesInfo("Blastoise", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Caterpie", "Bug", "Bug", GR_TYPICAL, ["Metapod"]),
SpeciesInfo("Metapod", "Bug", "Bug", GR_TYPICAL, ["Butterfree"]),
SpeciesInfo("Butterfree", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Weedle", "Bug", "Bug", GR_TYPICAL, ["Kakuna"]),
SpeciesInfo("Kakuna", "Bug", "Bug", GR_TYPICAL, ["Beedrill"]),
SpeciesInfo("Beedrill", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Pidgey", "Flying", "Flying", GR_TYPICAL, ["Pidgeotto"]),
SpeciesInfo("Pidgeotto", "Flying", "Flying", GR_TYPICAL, ["Pidgeot"]),
SpeciesInfo("Pidgeot", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Rattata", "Field", "Field", GR_TYPICAL, ["Raticate"]),
SpeciesInfo("Raticate", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Spearow", "Flying", "Flying", GR_TYPICAL, ["Fearow"]),
SpeciesInfo("Fearow", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Ekans", "Field", "Dragon", GR_TYPICAL, ["Arbok"]),
SpeciesInfo("Arbok", "Field", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Pichu", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, ["Pikachu"]),
SpeciesInfo("Pikachu", "Field", "Fairy", GR_TYPICAL, ["Raichu"]),
SpeciesInfo("Raichu", "Field", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Sandshrew", "Field", "Field", GR_TYPICAL, ["Sandslash"]),
SpeciesInfo("Sandslash", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Nidoran F", "Monster", "Field", GR_FEMALE_ONLY, ["Nidorina"]),
SpeciesInfo("Nidorina", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, ["Nidoqueen"]),
SpeciesInfo("Nidoqueen", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, []),
SpeciesInfo("Nidoran M", "Monster", "Field", GR_MALE_ONLY, ["Nidorino"]),
SpeciesInfo("Nidorino", "Monster", "Field", GR_MALE_ONLY, ["Nidoking"]),
SpeciesInfo("Nidoking", "Monster", "Field", GR_MALE_ONLY, []),
SpeciesInfo("Cleffa", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, ["Clefairy"]),
SpeciesInfo("Clefairy", "Fairy", "Fairy", GR_TYPICAL, ["Clefable"]),
SpeciesInfo("Clefable", "Fairy", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Vulpix", "Field", "Field", GR_TYPICAL, ["Ninetales"]),
SpeciesInfo("Ninetales", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Igglybuff", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, ["Jigglypuff"]),
SpeciesInfo("Jigglypuff", "Fairy", "Fairy", GR_TYPICAL, ["Wigglytuff"]),
SpeciesInfo("Wigglytuff", "Fairy", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Zubat", "Flying", "Flying", GR_TYPICAL, ["Golbat"]),
SpeciesInfo("Golbat", "Flying", "Flying", GR_TYPICAL, ["Crobat"]),
SpeciesInfo("Crobat", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Oddish", "Grass", "Grass", GR_TYPICAL, ["Gloom"]),
SpeciesInfo("Gloom", "Grass", "Grass", GR_TYPICAL, ["Vileplume", "Bellossom"]),
SpeciesInfo("Vileplume", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Bellossom", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Paras", "Bug", "Grass", GR_TYPICAL, ["Parasect"]),
SpeciesInfo("Parasect", "Bug", "Grass", GR_TYPICAL, []),
SpeciesInfo("Venonat", "Bug", "Bug", GR_TYPICAL, ["Venomoth"]),
SpeciesInfo("Venomoth", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Diglett", "Field", "Field", GR_TYPICAL, ["Dugtrio"]),
SpeciesInfo("Dugtrio", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Meowth", "Field", "Field", GR_TYPICAL, ["Persian"]),
SpeciesInfo("Persian", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Psyduck", "Water 1", "Field", GR_TYPICAL, ["Golduck"]),
SpeciesInfo("Golduck", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Mankey", "Field", "Field", GR_TYPICAL, ["Primeape"]),
SpeciesInfo("Primeape", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Growlithe", "Field", "Field", GR_TYPICAL, ["Arcanine"]),
SpeciesInfo("Arcanine", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Poliwag", "Water 1", "Water 1", GR_TYPICAL, ["Poliwhirl"]),
SpeciesInfo("Poliwhirl", "Water 1", "Water 1", GR_TYPICAL, ["Poliwrath", "Politoed"]),
SpeciesInfo("Poliwrath", "Water 1", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Politoed", "Water 1", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Abra", "Human-Like", "Human-Like", GR_TYPICAL, ["Kadabra"]),
SpeciesInfo("Kadabra", "Human-Like", "Human-Like", GR_TYPICAL, ["Alakazam"]),
SpeciesInfo("Alakazam", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Machop", "Human-Like", "Human-Like", GR_TYPICAL, ["Machoke"]),
SpeciesInfo("Machoke", "Human-Like", "Human-Like", GR_TYPICAL, ["Machamp"]),
SpeciesInfo("Machamp", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Bellsprout", "Grass", "Grass", GR_TYPICAL, ["Weepinbell"]),
SpeciesInfo("Weepinbell", "Grass", "Grass", GR_TYPICAL, ["Victreebel"]),
SpeciesInfo("Victreebel", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Tentacool", "Water 3", "Water 3", GR_TYPICAL, ["Tentacruel"]),
SpeciesInfo("Tentacruel", "Water 3", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Geodude", "Mineral", "Mineral", GR_TYPICAL, ["Graveler"]),
SpeciesInfo("Graveler", "Mineral", "Mineral", GR_TYPICAL, ["Golem"]),
SpeciesInfo("Golem", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Ponyta", "Field", "Field", GR_TYPICAL, ["Rapidash"]),
SpeciesInfo("Rapidash", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Slowpoke", "Monster", "Water 1", GR_TYPICAL, ["Slowbro", "Slowking"]),
SpeciesInfo("Slowbro", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Slowking", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Magnemite", "Mineral", "Mineral", GR_UNKNOWN, ["Magneton"]),
SpeciesInfo("Magneton", "Mineral", "Mineral", GR_UNKNOWN, ["Magnezone"]),
SpeciesInfo("Magnezone", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Farfetch'd", "Flying", "Field", GR_TYPICAL, []),
SpeciesInfo("Doduo", "Flying", "Flying", GR_TYPICAL, ["Dodrio"]),
SpeciesInfo("Dodrio", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Seel", "Water 1", "Field", GR_TYPICAL, ["Dewgong"]),
SpeciesInfo("Dewgong", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Grimer", "Amorphous", "Amorphous", GR_TYPICAL, ["Muk"]),
SpeciesInfo("Muk", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Shellder", "Water 3", "Water 3", GR_TYPICAL, ["Cloyster"]),
SpeciesInfo("Cloyster", "Water 3", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Gastly", "Amorphous", "Amorphous", GR_TYPICAL, ["Haunter"]),
SpeciesInfo("Haunter", "Amorphous", "Amorphous", GR_TYPICAL, ["Gengar"]),
SpeciesInfo("Gengar", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Onix", "Mineral", "Mineral", GR_TYPICAL, ["Steelix"]),
SpeciesInfo("Steelix", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Drowzee", "Human-Like", "Human-Like", GR_TYPICAL, ["Hypno"]),
SpeciesInfo("Hypno", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Krabby", "Water 3", "Water 3", GR_TYPICAL, ["Kingler"]),
SpeciesInfo("Kingler", "Water 3", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Voltorb", "Mineral", "Mineral", GR_UNKNOWN, ["Electrode"]),
SpeciesInfo("Electrode", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Exeggcute", "Grass", "Grass", GR_TYPICAL, ["Exeggutor"]),
SpeciesInfo("Exeggutor", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Cubone", "Monster", "Monster", GR_TYPICAL, ["Marowak"]),
SpeciesInfo("Marowak", "Monster", "Monster", GR_TYPICAL, []),
SpeciesInfo("Tyrogue", "No Eggs Discovered", "No Eggs Discovered", GR_MALE_ONLY, ["Hitmonlee", "Hitmonchan", "Hitmontop"]),
SpeciesInfo("Hitmonlee", "Human-Like", "Human-Like", GR_MALE_ONLY, []),
SpeciesInfo("Hitmonchan", "Human-Like", "Human-Like", GR_MALE_ONLY, []),
SpeciesInfo("Hitmontop", "Human-Like", "Human-Like", GR_MALE_ONLY, []),
SpeciesInfo("Lickitung", "Monster", "Monster", GR_TYPICAL, ["Lickilicky"]),
SpeciesInfo("Lickilicky", "Monster", "Monster", GR_TYPICAL, []),
SpeciesInfo("Koffing", "Amorphous", "Amorphous", GR_TYPICAL, ["Weezing"]),
SpeciesInfo("Weezing", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Rhyhorn", "Monster", "Field", GR_TYPICAL, ["Rhydon"]),
SpeciesInfo("Rhydon", "Monster", "Field", GR_TYPICAL, ["Rhyperior"]),
SpeciesInfo("Rhyperior", "Monster", "Field", GR_TYPICAL, []),
SpeciesInfo("Happiny", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, ["Chansey"]),
SpeciesInfo("Chansey", "Fairy", "Fairy", GR_FEMALE_ONLY, ["Blissey"]),
SpeciesInfo("Blissey", "Fairy", "Fairy", GR_FEMALE_ONLY, []),
SpeciesInfo("Tangela", "Grass", "Grass", GR_TYPICAL, ["Tangrowth"]),
SpeciesInfo("Tangrowth", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Kangaskhan", "Monster", "Monster", GR_FEMALE_ONLY, []),
SpeciesInfo("Horsea", "Water 1", "Dragon", GR_TYPICAL, ["Seadra"]),
SpeciesInfo("Seadra", "Water 1", "Dragon", GR_TYPICAL, ["Kingdra"]),
SpeciesInfo("Kingdra", "Water 1", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Goldeen", "Water 2", "Water 2", GR_TYPICAL, ["Seaking"]),
SpeciesInfo("Seaking", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Staryu", "Water 3", "Water 3", GR_UNKNOWN, ["Starmie"]),
SpeciesInfo("Starmie", "Water 3", "Water 3", GR_UNKNOWN, []),
SpeciesInfo("Mime Jr.", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, ["Mr. Mime"]),
SpeciesInfo("Mr. Mime", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Scyther", "Bug", "Bug", GR_TYPICAL, ["Scizor"]),
SpeciesInfo("Scizor", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Smoochum", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, ["Jynx"]),
SpeciesInfo("Jynx", "Human-Like", "Human-Like", GR_FEMALE_ONLY, []),
SpeciesInfo("Elekid", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, ["Electabuzz"]),
SpeciesInfo("Electabuzz", "Human-Like", "Human-Like", GR_TYPICAL, ["Electivire"]),
SpeciesInfo("Electivire", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Magby", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, ["Magmar"]),
SpeciesInfo("Magmar", "Human-Like", "Human-Like", GR_TYPICAL, ["Magmortar"]),
SpeciesInfo("Magmortar", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Pinsir", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Tauros", "Field", "Field", GR_MALE_ONLY, []),
SpeciesInfo("Magikarp", "Water 2", "Dragon", GR_TYPICAL, ["Gyarados"]),
SpeciesInfo("Gyarados", "Water 2", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Lapras", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Ditto", "Ditto", "Ditto", GR_UNKNOWN, []),
SpeciesInfo("Eevee", "Field", "Field", GR_TYPICAL, ["Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon", "Leafeon", "Glaceon", "Sylveon"]),
SpeciesInfo("Vaporeon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Jolteon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Flareon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Espeon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Umbreon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Leafeon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Glaceon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Sylveon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Porygon", "Mineral", "Mineral", GR_UNKNOWN, ["Porygon2"]),
SpeciesInfo("Porygon2", "Mineral", "Mineral", GR_UNKNOWN, ["Porygon-Z"]),
SpeciesInfo("Porygon-Z", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Omanyte", "Water 1", "Water 3", GR_TYPICAL, ["Omastar"]),
SpeciesInfo("Omastar", "Water 1", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Kabuto", "Water 1", "Water 3", GR_TYPICAL, ["Kabutops"]),
SpeciesInfo("Kabutops", "Water 1", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Aerodactyl", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Munchlax", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, ["Snorlax"]),
SpeciesInfo("Snorlax", "Monster", "Monster", GR_TYPICAL, []),
SpeciesInfo("Articuno", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Zapdos", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Moltres", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Dratini", "Water 1", "Dragon", GR_TYPICAL, ["Dragonair"]),
SpeciesInfo("Dragonair", "Water 1", "Dragon", GR_TYPICAL, ["Dragonite"]),
SpeciesInfo("Dragonite", "Water 1", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Mewtwo", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Mew", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Chikorita", "Monster", "Grass", GR_TYPICAL, ["Bayleef"]),
SpeciesInfo("Bayleef", "Monster", "Grass", GR_TYPICAL, ["Meganium"]),
SpeciesInfo("Meganium", "Monster", "Grass", GR_TYPICAL, []),
SpeciesInfo("Cyndaquil", "Field", "Field", GR_TYPICAL, ["Quilava"]),
SpeciesInfo("Quilava", "Field", "Field", GR_TYPICAL, ["Typhlosion"]),
SpeciesInfo("Typhlosion", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Totodile", "Monster", "Water 1", GR_TYPICAL, ["Croconaw"]),
SpeciesInfo("Croconaw", "Monster", "Water 1", GR_TYPICAL, ["Feraligatr"]),
SpeciesInfo("Feraligatr", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Sentret", "Field", "Field", GR_TYPICAL, ["Furret"]),
SpeciesInfo("Furret", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Hoothoot", "Flying", "Flying", GR_TYPICAL, ["Noctowl"]),
SpeciesInfo("Noctowl", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Ledyba", "Bug", "Bug", GR_TYPICAL, ["Ledian"]),
SpeciesInfo("Ledian", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Spinarak", "Bug", "Bug", GR_TYPICAL, ["Ariados"]),
SpeciesInfo("Ariados", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Chinchou", "Water 2", "Water 2", GR_TYPICAL, ["Lanturn"]),
SpeciesInfo("Lanturn", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Togepi", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, ["Togetic"]),
SpeciesInfo("Togetic", "Flying", "Fairy", GR_TYPICAL, ["Togekiss"]),
SpeciesInfo("Togekiss", "Flying", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Natu", "Flying", "Flying", GR_TYPICAL, ["Xatu"]),
SpeciesInfo("Xatu", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Mareep", "Monster", "Field", GR_TYPICAL, ["Flaaffy"]),
SpeciesInfo("Flaaffy", "Monster", "Field", GR_TYPICAL, ["Ampharos"]),
SpeciesInfo("Ampharos", "Monster", "Field", GR_TYPICAL, []),
SpeciesInfo("Azurill", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, ["Marill"]),
SpeciesInfo("Marill", "Water 1", "Fairy", GR_TYPICAL, ["Azumarill"]),
SpeciesInfo("Azumarill", "Water 1", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Bonsly", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, ["Sudowoodo"]),
SpeciesInfo("Sudowoodo", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Hoppip", "Fairy", "Grass", GR_TYPICAL, ["Skiploom"]),
SpeciesInfo("Skiploom", "Fairy", "Grass", GR_TYPICAL, ["Jumpluff"]),
SpeciesInfo("Jumpluff", "Fairy", "Grass", GR_TYPICAL, []),
SpeciesInfo("Aipom", "Field", "Field", GR_TYPICAL, ["Ambipom"]),
SpeciesInfo("Ambipom", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Sunkern", "Grass", "Grass", GR_TYPICAL, ["Sunflora"]),
SpeciesInfo("Sunflora", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Yanma", "Bug", "Bug", GR_TYPICAL, ["Yanmega"]),
SpeciesInfo("Yanmega", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Wooper", "Water 1", "Field", GR_TYPICAL, ["Quagsire"]),
SpeciesInfo("Quagsire", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Murkrow", "Flying", "Flying", GR_TYPICAL, ["Honchkrow"]),
SpeciesInfo("Honchkrow", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Misdreavus", "Amorphous", "Amorphous", GR_TYPICAL, ["Mismagius"]),
SpeciesInfo("Mismagius", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Unown", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Wynaut", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, ["Wobbuffet"]),
SpeciesInfo("Wobbuffet", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Girafarig", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Pineco", "Bug", "Bug", GR_TYPICAL, ["Forretress"]),
SpeciesInfo("Forretress", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Dunsparce", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Gligar", "Bug", "Bug", GR_TYPICAL, ["Gliscor"]),
SpeciesInfo("Gliscor", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Snubbull", "Field", "Fairy", GR_TYPICAL, ["Granbull"]),
SpeciesInfo("Granbull", "Field", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Qwilfish", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Shuckle", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Heracross", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Sneasel", "Field", "Field", GR_TYPICAL, ["Weavile"]),
SpeciesInfo("Weavile", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Teddiursa", "Field", "Field", GR_TYPICAL, ["Ursaring"]),
SpeciesInfo("Ursaring", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Slugma", "Amorphous", "Amorphous", GR_TYPICAL, ["Magcargo"]),
SpeciesInfo("Magcargo", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Swinub", "Field", "Field", GR_TYPICAL, ["Piloswine"]),
SpeciesInfo("Piloswine", "Field", "Field", GR_TYPICAL, ["Mamoswine"]),
SpeciesInfo("Mamoswine", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Corsola", "Water 1", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Remoraid", "Water 1", "Water 2", GR_TYPICAL, ["Octillery"]),
SpeciesInfo("Octillery", "Water 1", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Delibird", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Mantyke", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, ["Mantine"]),
SpeciesInfo("Mantine", "Water 1", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Skarmory", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Houndour", "Field", "Field", GR_TYPICAL, ["Houndoom"]),
SpeciesInfo("Houndoom", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Phanpy", "Field", "Field", GR_TYPICAL, ["Donphan"]),
SpeciesInfo("Donphan", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Stantler", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Smeargle", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Miltank", "Field", "Field", GR_FEMALE_ONLY, []),
SpeciesInfo("Raikou", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Entei", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Suicune", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Larvitar", "Monster", "Monster", GR_TYPICAL, ["Pupitar"]),
SpeciesInfo("Pupitar", "Monster", "Monster", GR_TYPICAL, ["Tyranitar"]),
SpeciesInfo("Tyranitar", "Monster", "Monster", GR_TYPICAL, []),
SpeciesInfo("Lugia", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Ho-Oh", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Celebi", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Treecko", "Monster", "Dragon", GR_TYPICAL, ["Grovyle"]),
SpeciesInfo("Grovyle", "Monster", "Dragon", GR_TYPICAL, ["Sceptile"]),
SpeciesInfo("Sceptile", "Monster", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Torchic", "Field", "Field", GR_TYPICAL, ["Combusken"]),
SpeciesInfo("Combusken", "Field", "Field", GR_TYPICAL, ["Blaziken"]),
SpeciesInfo("Blaziken", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Mudkip", "Monster", "Water 1", GR_TYPICAL, ["Marshtomp"]),
SpeciesInfo("Marshtomp", "Monster", "Water 1", GR_TYPICAL, ["Swampert"]),
SpeciesInfo("Swampert", "Monster", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Poochyena", "Field", "Field", GR_TYPICAL, ["Mightyena"]),
SpeciesInfo("Mightyena", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Zigzagoon", "Field", "Field", GR_TYPICAL, ["Linoone"]),
SpeciesInfo("Linoone", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Wurmple", "Bug", "Bug", GR_TYPICAL, ["Silcoon", "Cascoon"]),
SpeciesInfo("Silcoon", "Bug", "Bug", GR_TYPICAL, ["Beautifly"]),
SpeciesInfo("Beautifly", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Cascoon", "Bug", "Bug", GR_TYPICAL, ["Dustox"]),
SpeciesInfo("Dustox", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Lotad", "Water 1", "Grass", GR_TYPICAL, ["Lombre"]),
SpeciesInfo("Lombre", "Water 1", "Grass", GR_TYPICAL, ["Ludicolo"]),
SpeciesInfo("Ludicolo", "Water 1", "Grass", GR_TYPICAL, []),
SpeciesInfo("Seedot", "Field", "Grass", GR_TYPICAL, ["Nuzleaf"]),
SpeciesInfo("Nuzleaf", "Field", "Grass", GR_TYPICAL, ["Shiftry"]),
SpeciesInfo("Shiftry", "Field", "Grass", GR_TYPICAL, []),
SpeciesInfo("Taillow", "Flying", "Flying", GR_TYPICAL, ["Swellow"]),
SpeciesInfo("Swellow", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Wingull", "Water 1", "Flying", GR_TYPICAL, ["Pelipper"]),
SpeciesInfo("Pelipper", "Water 1", "Flying", GR_TYPICAL, []),
SpeciesInfo("Ralts", "Amorphous", "Amorphous", GR_TYPICAL, ["Kirlia"]),
SpeciesInfo("Kirlia", "Amorphous", "Amorphous", GR_MALE_ONLY, ["Gardevoir", "Gallade"]),
SpeciesInfo("Gardevoir", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Gallade", "Amorphous", "Amorphous", GR_MALE_ONLY, []),
SpeciesInfo("Surskit", "Water 1", "Bug", GR_TYPICAL, ["Masquerain"]),
SpeciesInfo("Masquerain", "Water 1", "Bug", GR_TYPICAL, []),
SpeciesInfo("Shroomish", "Fairy", "Grass", GR_TYPICAL, ["Breloom"]),
SpeciesInfo("Breloom", "Fairy", "Grass", GR_TYPICAL, []),
SpeciesInfo("Slakoth", "Field", "Field", GR_TYPICAL, ["Vigoroth"]),
SpeciesInfo("Vigoroth", "Field", "Field", GR_TYPICAL, ["Slaking"]),
SpeciesInfo("Slaking", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Nincada", "Bug", "Bug", GR_UNKNOWN, ["Ninjask", "Shedinja"]),
SpeciesInfo("Ninjask", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Shedinja", "Bug", "Bug", GR_UNKNOWN, []),
SpeciesInfo("Whismur", "Monster", "Field", GR_TYPICAL, ["Loudred"]),
SpeciesInfo("Loudred", "Monster", "Field", GR_TYPICAL, ["Exploud"]),
SpeciesInfo("Exploud", "Monster", "Field", GR_TYPICAL, []),
SpeciesInfo("Makuhita", "Human-Like", "Human-Like", GR_TYPICAL, ["Hariyama"]),
SpeciesInfo("Hariyama", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Nosepass", "Mineral", "Mineral", GR_TYPICAL, ["Probopass"]),
SpeciesInfo("Probopass", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Skitty", "Field", "Fairy", GR_TYPICAL, ["Delcatty"]),
SpeciesInfo("Delcatty", "Field", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Sableye", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Mawile", "Field", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Aron", "Monster", "Monster", GR_TYPICAL, ["Lairon"]),
SpeciesInfo("Lairon", "Monster", "Monster", GR_TYPICAL, ["Aggron"]),
SpeciesInfo("Aggron", "Monster", "Monster", GR_TYPICAL, []),
SpeciesInfo("Meditite", "Human-Like", "Human-Like", GR_TYPICAL, ["Medicham"]),
SpeciesInfo("Medicham", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Electrike", "Field", "Field", GR_TYPICAL, ["Manectric"]),
SpeciesInfo("Manectric", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Plusle", "Fairy", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Minun", "Fairy", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Volbeat", "Bug", "Human-Like", GR_MALE_ONLY, []),
SpeciesInfo("Illumise", "Bug", "Human-Like", GR_FEMALE_ONLY, []),
SpeciesInfo("Budew", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, ["Roselia"]),
SpeciesInfo("Roselia", "Fairy", "Grass", GR_TYPICAL, ["Roserade"]),
SpeciesInfo("Roserade", "Fairy", "Grass", GR_TYPICAL, []),
SpeciesInfo("Gulpin", "Amorphous", "Amorphous", GR_TYPICAL, ["Swalot"]),
SpeciesInfo("Swalot", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Carvanha", "Water 2", "Water 2", GR_TYPICAL, ["Sharpedo"]),
SpeciesInfo("Sharpedo", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Wailmer", "Field", "Water 2", GR_TYPICAL, ["Wailord"]),
SpeciesInfo("Wailord", "Field", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Numel", "Field", "Field", GR_TYPICAL, ["Camerupt"]),
SpeciesInfo("Camerupt", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Torkoal", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Spoink", "Field", "Field", GR_TYPICAL, ["Grumpig"]),
SpeciesInfo("Grumpig", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Spinda", "Field", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Trapinch", "Bug", "Bug", GR_TYPICAL, ["Vibrava"]),
SpeciesInfo("Vibrava", "Bug", "Bug", GR_TYPICAL, ["Flygon"]),
SpeciesInfo("Flygon", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Cacnea", "Grass", "Human-Like", GR_TYPICAL, ["Cacturne"]),
SpeciesInfo("Cacturne", "Grass", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Swablu", "Flying", "Dragon", GR_TYPICAL, ["Altaria"]),
SpeciesInfo("Altaria", "Flying", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Zangoose", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Seviper", "Field", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Lunatone", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Solrock", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Barboach", "Water 2", "Water 2", GR_TYPICAL, ["Whiscash"]),
SpeciesInfo("Whiscash", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Corphish", "Water 1", "Water 3", GR_TYPICAL, ["Crawdaunt"]),
SpeciesInfo("Crawdaunt", "Water 1", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Baltoy", "Mineral", "Mineral", GR_UNKNOWN, ["Claydol"]),
SpeciesInfo("Claydol", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Lileep", "Water 3", "Water 3", GR_TYPICAL, ["Cradily"]),
SpeciesInfo("Cradily", "Water 3", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Anorith", "Water 3", "Water 3", GR_TYPICAL, ["Armaldo"]),
SpeciesInfo("Armaldo", "Water 3", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Feebas", "Water 1", "Dragon", GR_TYPICAL, ["Milotic"]),
SpeciesInfo("Milotic", "Water 1", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Castform", "Fairy", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Kecleon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Shuppet", "Amorphous", "Amorphous", GR_TYPICAL, ["Banette"]),
SpeciesInfo("Banette", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Duskull", "Amorphous", "Amorphous", GR_TYPICAL, ["Dusclops"]),
SpeciesInfo("Dusclops", "Amorphous", "Amorphous", GR_TYPICAL, ["Dusknoir"]),
SpeciesInfo("Dusknoir", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Tropius", "Monster", "Grass", GR_TYPICAL, []),
SpeciesInfo("Chingling", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, ["Chimecho"]),
SpeciesInfo("Chimecho", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Absol", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Snorunt", "Fairy", "Mineral", GR_FEMALE_ONLY, ["Glalie", "Froslass"]),
SpeciesInfo("Glalie", "Fairy", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Froslass", "Fairy", "Mineral", GR_FEMALE_ONLY, []),
SpeciesInfo("Spheal", "Water 1", "Field", GR_TYPICAL, ["Sealeo"]),
SpeciesInfo("Sealeo", "Water 1", "Field", GR_TYPICAL, ["Walrein"]),
SpeciesInfo("Walrein", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Clamperl", "Water 1", "Water 1", GR_TYPICAL, ["Huntail", "Gorebyss"]),
SpeciesInfo("Huntail", "Water 1", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Gorebyss", "Water 1", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Relicanth", "Water 1", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Luvdisc", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Bagon", "Dragon", "Dragon", GR_TYPICAL, ["Shelgon"]),
SpeciesInfo("Shelgon", "Dragon", "Dragon", GR_TYPICAL, ["Salamence"]),
SpeciesInfo("Salamence", "Dragon", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Beldum", "Mineral", "Mineral", GR_UNKNOWN, ["Metang"]),
SpeciesInfo("Metang", "Mineral", "Mineral", GR_UNKNOWN, ["Metagross"]),
SpeciesInfo("Metagross", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Regirock", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Regice", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Registeel", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Latias", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, []),
SpeciesInfo("Latios", "No Eggs Discovered", "No Eggs Discovered", GR_MALE_ONLY, []),
SpeciesInfo("Kyogre", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Groudon", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Rayquaza", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Jirachi", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Deoxys", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Turtwig", "Monster", "Grass", GR_TYPICAL, ["Grotle"]),
SpeciesInfo("Grotle", "Monster", "Grass", GR_TYPICAL, ["Torterra"]),
SpeciesInfo("Torterra", "Monster", "Grass", GR_TYPICAL, []),
SpeciesInfo("Chimchar", "Field", "Human-Like", GR_TYPICAL, ["Monferno"]),
SpeciesInfo("Monferno", "Field", "Human-Like", GR_TYPICAL, ["Infernape"]),
SpeciesInfo("Infernape", "Field", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Piplup", "Water 1", "Field", GR_TYPICAL, ["Prinplup"]),
SpeciesInfo("Prinplup", "Water 1", "Field", GR_TYPICAL, ["Empoleon"]),
SpeciesInfo("Empoleon", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Starly", "Flying", "Flying", GR_TYPICAL, ["Staravia"]),
SpeciesInfo("Staravia", "Flying", "Flying", GR_TYPICAL, ["Staraptor"]),
SpeciesInfo("Staraptor", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Bidoof", "Water 1", "Field", GR_TYPICAL, ["Bibarel"]),
SpeciesInfo("Bibarel", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Kricketot", "Bug", "Bug", GR_TYPICAL, ["Kricketune"]),
SpeciesInfo("Kricketune", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Shinx", "Field", "Field", GR_TYPICAL, ["Luxio"]),
SpeciesInfo("Luxio", "Field", "Field", GR_TYPICAL, ["Luxray"]),
SpeciesInfo("Luxray", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Cranidos", "Monster", "Monster", GR_TYPICAL, ["Rampardos"]),
SpeciesInfo("Rampardos", "Monster", "Monster", GR_TYPICAL, []),
SpeciesInfo("Shieldon", "Monster", "Monster", GR_TYPICAL, ["Bastiodon"]),
SpeciesInfo("Bastiodon", "Monster", "Monster", GR_TYPICAL, []),
SpeciesInfo("Burmy", "Bug", "Bug", GR_MALE_ONLY, ["Wormadam", "Mothim"]),
SpeciesInfo("Wormadam", "Bug", "Bug", GR_FEMALE_ONLY, []),
SpeciesInfo("Mothim", "Bug", "Bug", GR_MALE_ONLY, []),
SpeciesInfo("Combee", "Bug", "Bug", GR_FEMALE_ONLY, ["Vespiquen"]),
SpeciesInfo("Vespiquen", "Bug", "Bug", GR_FEMALE_ONLY, []),
SpeciesInfo("Pachirisu", "Field", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Buizel", "Water 1", "Field", GR_TYPICAL, ["Floatzel"]),
SpeciesInfo("Floatzel", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Cherubi", "Fairy", "Grass", GR_TYPICAL, ["Cherrim"]),
SpeciesInfo("Cherrim", "Fairy", "Grass", GR_TYPICAL, []),
SpeciesInfo("Shellos", "Water 1", "Amorphous", GR_TYPICAL, ["Gastrodon"]),
SpeciesInfo("Gastrodon", "Water 1", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Drifloon", "Amorphous", "Amorphous", GR_TYPICAL, ["Drifblim"]),
SpeciesInfo("Drifblim", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Buneary", "Field", "Human-Like", GR_TYPICAL, ["Lopunny"]),
SpeciesInfo("Lopunny", "Field", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Glameow", "Field", "Field", GR_TYPICAL, ["Purugly"]),
SpeciesInfo("Purugly", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Stunky", "Field", "Field", GR_TYPICAL, ["Skuntank"]),
SpeciesInfo("Skuntank", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Bronzor", "Mineral", "Mineral", GR_UNKNOWN, ["Bronzong"]),
SpeciesInfo("Bronzong", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Chatot", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Spiritomb", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Gible", "Monster", "Dragon", GR_TYPICAL, ["Gabite"]),
SpeciesInfo("Gabite", "Monster", "Dragon", GR_TYPICAL, ["Garchomp"]),
SpeciesInfo("Garchomp", "Monster", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Riolu", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, ["Lucario"]),
SpeciesInfo("Lucario", "Field", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Hippopotas", "Field", "Field", GR_TYPICAL, ["Hippowdon"]),
SpeciesInfo("Hippowdon", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Skorupi", "Bug", "Water 3", GR_TYPICAL, ["Drapion"]),
SpeciesInfo("Drapion", "Bug", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Croagunk", "Human-Like", "Human-Like", GR_TYPICAL, ["Toxicroak"]),
SpeciesInfo("Toxicroak", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Carnivine", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Finneon", "Water 2", "Water 2", GR_TYPICAL, ["Lumineon"]),
SpeciesInfo("Lumineon", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Snover", "Monster", "Grass", GR_TYPICAL, ["Abomasnow"]),
SpeciesInfo("Abomasnow", "Monster", "Grass", GR_TYPICAL, []),
SpeciesInfo("Rotom", "Amorphous", "Amorphous", GR_UNKNOWN, []),
SpeciesInfo("Uxie", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Mesprit", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Azelf", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Dialga", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Palkia", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Heatran", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, []),
SpeciesInfo("Regigigas", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Giratina", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Cresselia", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, []),
SpeciesInfo("Phione", "Water 1", "Fairy", GR_UNKNOWN, []),
SpeciesInfo("Manaphy", "Water 1", "Fairy", GR_UNKNOWN, []),
SpeciesInfo("Darkrai", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Shaymin", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Arceus", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Victini", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Snivy", "Field", "Grass", GR_TYPICAL, []),
SpeciesInfo("Servine", "Field", "Grass", GR_TYPICAL, ["Servine"]),
SpeciesInfo("Serperior", "Field", "Grass", GR_TYPICAL, ["Serperior"]),
SpeciesInfo("Tepig", "Field", "Field", GR_TYPICAL, ["Pignite"]),
SpeciesInfo("Pignite", "Field", "Field", GR_TYPICAL, ["Emboar"]),
SpeciesInfo("Emboar", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Oshawott", "Field", "Field", GR_TYPICAL, ["Dewott"]),
SpeciesInfo("Dewott", "Field", "Field", GR_TYPICAL, ["Samurott"]),
SpeciesInfo("Samurott", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Patrat", "Field", "Field", GR_TYPICAL, ["Watchog"]),
SpeciesInfo("Watchog", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Lillipup", "Field", "Field", GR_TYPICAL, ["Herdier"]),
SpeciesInfo("Herdier", "Field", "Field", GR_TYPICAL, ["Stoutland"]),
SpeciesInfo("Stoutland", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Purrloin", "Field", "Field", GR_TYPICAL, ["Liepard"]),
SpeciesInfo("Liepard", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Pansage", "Field", "Field", GR_TYPICAL, ["Simisage"]),
SpeciesInfo("Simisage", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Pansear", "Field", "Field", GR_TYPICAL, ["Simisear"]),
SpeciesInfo("Simisear", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Panpour", "Field", "Field", GR_TYPICAL, ["Simipour"]),
SpeciesInfo("Simipour", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Munna", "Field", "Field", GR_TYPICAL, ["Musharna"]),
SpeciesInfo("Musharna", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Pidove", "Flying", "Flying", GR_TYPICAL, ["Tranquill"]),
SpeciesInfo("Tranquill", "Flying", "Flying", GR_TYPICAL, ["Unfezant"]),
SpeciesInfo("Unfezant", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Blitzle", "Field", "Field", GR_TYPICAL, ["Zebstrika"]),
SpeciesInfo("Zebstrika", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Roggenrola", "Mineral", "Mineral", GR_TYPICAL, ["Boldore"]),
SpeciesInfo("Boldore", "Mineral", "Mineral", GR_TYPICAL, ["Gigalith"]),
SpeciesInfo("Gigalith", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Woobat", "Field", "Flying", GR_TYPICAL, ["Swoobat"]),
SpeciesInfo("Swoobat", "Field", "Flying", GR_TYPICAL, []),
SpeciesInfo("Drilbur", "Field", "Field", GR_TYPICAL, ["Excadrill"]),
SpeciesInfo("Excadrill", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Audino", "Fairy", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Timburr", "Human-Like", "Human-Like", GR_TYPICAL, ["Gurdurr"]),
SpeciesInfo("Gurdurr", "Human-Like", "Human-Like", GR_TYPICAL, ["Conkeldurr"]),
SpeciesInfo("Conkeldurr", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Tympole", "Water 1", "Water 1", GR_TYPICAL, ["Palpitoad"]),
SpeciesInfo("Palpitoad", "Water 1", "Water 1", GR_TYPICAL, ["Seismitoad"]),
SpeciesInfo("Seismitoad", "Water 1", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Throh", "Human-Like", "Human-Like", GR_MALE_ONLY, []),
SpeciesInfo("Sawk", "Human-Like", "Human-Like", GR_MALE_ONLY, []),
SpeciesInfo("Sewaddle", "Bug", "Bug", GR_TYPICAL, ["Swadloon"]),
SpeciesInfo("Swadloon", "Bug", "Bug", GR_TYPICAL, ["Leavanny"]),
SpeciesInfo("Leavanny", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Venipede", "Bug", "Bug", GR_TYPICAL, ["Whirlipede"]),
SpeciesInfo("Whirlipede", "Bug", "Bug", GR_TYPICAL, ["Scolipede"]),
SpeciesInfo("Scolipede", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Cottonee", "Grass", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Whimsicott", "Grass", "Fairy", GR_FEMALE_ONLY, ["Petilil"]),
SpeciesInfo("Petilil", "Grass", "Grass", GR_FEMALE_ONLY, ["Lilligant"]),
SpeciesInfo("Lilligant", "Grass", "Grass", GR_FEMALE_ONLY, []),
SpeciesInfo("Basculin", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Sandile", "Field", "Field", GR_TYPICAL, ["Krokorok"]),
SpeciesInfo("Krokorok", "Field", "Field", GR_TYPICAL, ["Krookodile"]),
SpeciesInfo("Krookodile", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Darumaka", "Field", "Field", GR_TYPICAL, ["Darmanitan"]),
SpeciesInfo("Darmanitan", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Maractus", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Dwebble", "Bug", "Mineral", GR_TYPICAL, ["Crustle"]),
SpeciesInfo("Crustle", "Bug", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Scraggy", "Field", "Dragon", GR_TYPICAL, ["Scrafty"]),
SpeciesInfo("Scrafty", "Field", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Sigilyph", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Yamask", "Mineral", "Amorphous", GR_TYPICAL, ["Cofagrigus"]),
SpeciesInfo("Cofagrigus", "Mineral", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Tirtouga", "Water 1", "Water 3", GR_TYPICAL, ["Carracosta"]),
SpeciesInfo("Carracosta", "Water 1", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Archen", "Flying", "Water 3", GR_TYPICAL, ["Archeops"]),
SpeciesInfo("Archeops", "Flying", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Trubbish", "Mineral", "Mineral", GR_TYPICAL, ["Garbodor"]),
SpeciesInfo("Garbodor", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Zorua", "Field", "Field", GR_TYPICAL, ["Zoroark"]),
SpeciesInfo("Zoroark", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Minccino", "Field", "Field", GR_TYPICAL, ["Cinccino"]),
SpeciesInfo("Cinccino", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Gothita", "Human-Like", "Human-Like", GR_TYPICAL, ["Gothorita"]),
SpeciesInfo("Gothorita", "Human-Like", "Human-Like", GR_TYPICAL, ["Gothitelle"]),
SpeciesInfo("Gothitelle", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Solosis", "Amorphous", "Amorphous", GR_TYPICAL, ["Duosion"]),
SpeciesInfo("Duosion", "Amorphous", "Amorphous", GR_TYPICAL, ["Reuniclus"]),
SpeciesInfo("Reuniclus", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Ducklett", "Water 1", "Flying", GR_TYPICAL, ["Swanna"]),
SpeciesInfo("Swanna", "Water 1", "Flying", GR_TYPICAL, []),
SpeciesInfo("Vanillite", "Mineral", "Mineral", GR_TYPICAL, ["Vanillish"]),
SpeciesInfo("Vanillish", "Mineral", "Mineral", GR_TYPICAL, ["Vanilluxe"]),
SpeciesInfo("Vanilluxe", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Deerling", "Field", "Field", GR_TYPICAL, ["Sawsbuck"]),
SpeciesInfo("Sawsbuck", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Emolga", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Karrablast", "Bug", "Bug", GR_TYPICAL, ["Escavalier"]),
SpeciesInfo("Escavalier", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Foongus", "Grass", "Grass", GR_TYPICAL, ["Amoonguss"]),
SpeciesInfo("Amoonguss", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Frillish", "Amorphous", "Amorphous", GR_TYPICAL, ["Jellicent"]),
SpeciesInfo("Jellicent", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Alomomola", "Water 1", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Joltik", "Bug", "Bug", GR_TYPICAL, ["Galvantula"]),
SpeciesInfo("Galvantula", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Ferroseed", "Grass", "Mineral", GR_TYPICAL, ["Ferrothorn"]),
SpeciesInfo("Ferrothorn", "Grass", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Klink", "Mineral", "Mineral", GR_UNKNOWN, ["Klang"]),
SpeciesInfo("Klang", "Mineral", "Mineral", GR_UNKNOWN, ["Klinklang"]),
SpeciesInfo("Klinklang", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Tynamo", "Amorphous", "Amorphous", GR_TYPICAL, ["Eelektrik"]),
SpeciesInfo("Eelektrik", "Amorphous", "Amorphous", GR_TYPICAL, ["Eelektross"]),
SpeciesInfo("Eelektross", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Elgyem", "Human-Like", "Human-Like", GR_TYPICAL, ["Beheeyem"]),
SpeciesInfo("Beheeyem", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Litwick", "Amorphous", "Amorphous", GR_TYPICAL, ["Lampent"]),
SpeciesInfo("Lampent", "Amorphous", "Amorphous", GR_TYPICAL, ["Chandelure"]),
SpeciesInfo("Chandelure", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Axew", "Monster", "Dragon", GR_TYPICAL, ["Fraxure"]),
SpeciesInfo("Fraxure", "Monster", "Dragon", GR_TYPICAL, ["Haxorus"]),
SpeciesInfo("Haxorus", "Monster", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Cubchoo", "Field", "Field", GR_TYPICAL, ["Beartic"]),
SpeciesInfo("Beartic", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Cryogonal", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Shelmet", "Bug", "Bug", GR_TYPICAL, ["Accelgor"]),
SpeciesInfo("Accelgor", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Stunfisk", "Water 1", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Mienfoo", "Field", "Human-Like", GR_TYPICAL, ["Mienshao"]),
SpeciesInfo("Mienshao", "Field", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Druddigon", "Dragon", "Monster", GR_TYPICAL, []),
SpeciesInfo("Golett", "Mineral", "Mineral", GR_UNKNOWN, ["Golurk"]),
SpeciesInfo("Golurk", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Pawniard", "Human-Like", "Human-Like", GR_TYPICAL, ["Bisharp"]),
SpeciesInfo("Bisharp", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Bouffalant", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Rufflet", "Flying", "Flying", GR_MALE_ONLY, ["Braviary"]),
SpeciesInfo("Braviary", "Flying", "Flying", GR_MALE_ONLY, []),
SpeciesInfo("Vullaby", "Flying", "Flying", GR_FEMALE_ONLY, ["Mandibuzz"]),
SpeciesInfo("Mandibuzz", "Flying", "Flying", GR_FEMALE_ONLY, []),
SpeciesInfo("Heatmor", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Durant", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Deino", "Dragon", "Dragon", GR_TYPICAL, ["Zweilous"]),
SpeciesInfo("Zweilous", "Dragon", "Dragon", GR_TYPICAL, ["Hydreigon"]),
SpeciesInfo("Hydreigon", "Dragon", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Larvesta", "Bug", "Bug", GR_TYPICAL, ["Volcarona"]),
SpeciesInfo("Volcarona", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Cobalion", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Terrakion", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Virizion", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Tornadus", "No Eggs Discovered", "No Eggs Discovered", GR_MALE_ONLY, []),
SpeciesInfo("Thundurus", "No Eggs Discovered", "No Eggs Discovered", GR_MALE_ONLY, []),
SpeciesInfo("Reshiram", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Zekrom", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Landorus", "No Eggs Discovered", "No Eggs Discovered", GR_MALE_ONLY, []),
SpeciesInfo("Kyurem", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Keldeo", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Meloetta", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Genesect", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Chespin", "Field", "Field", GR_TYPICAL, ["Quilladin"]),
SpeciesInfo("Quilladin", "Field", "Field", GR_TYPICAL, ["Chesnaught"]),
SpeciesInfo("Chesnaught", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Fennekin", "Field", "Field", GR_TYPICAL, ["Braixen"]),
SpeciesInfo("Braixen", "Field", "Field", GR_TYPICAL, ["Delphox"]),
SpeciesInfo("Delphox", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Froakie", "Water 1", "Water 1", GR_TYPICAL, ["Frogadier"]),
SpeciesInfo("Frogadier", "Water 1", "Water 1", GR_TYPICAL, ["Greninja"]),
SpeciesInfo("Greninja", "Water 1", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Bunnelby", "Field", "Field", GR_TYPICAL, ["Diggersby"]),
SpeciesInfo("Diggersby", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Fletchling", "Flying", "Flying", GR_TYPICAL, ["Fletchinder"]),
SpeciesInfo("Fletchinder", "Flying", "Flying", GR_TYPICAL, ["Talonflame"]),
SpeciesInfo("Talonflame", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Scatterbug", "Bug", "Bug", GR_TYPICAL, ["Spewpa"]),
SpeciesInfo("Spewpa", "Bug", "Bug", GR_TYPICAL, ["Vivillon"]),
SpeciesInfo("Vivillon", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Litleo", "Field", "Field", GR_TYPICAL, ["Pyroar"]),
SpeciesInfo("Pyroar", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Flabebe", "Fairy", "Fairy", GR_FEMALE_ONLY, ["Floette"]),
SpeciesInfo("Floette", "Fairy", "Fairy", GR_FEMALE_ONLY, ["Florges"]),
SpeciesInfo("Florges", "Fairy", "Fairy", GR_FEMALE_ONLY, []),
SpeciesInfo("Skiddo", "Field", "Field", GR_TYPICAL, ["Gogoat"]),
SpeciesInfo("Gogoat", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Pancham", "Field", "Human-Like", GR_TYPICAL, ["Pangoro"]),
SpeciesInfo("Pangoro", "Field", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Furfrou", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Espurr", "Field", "Field", GR_TYPICAL, ["Meowstic"]),
SpeciesInfo("Meowstic", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Honedge", "Mineral", "Mineral", GR_TYPICAL, ["Doublade"]),
SpeciesInfo("Doublade", "Mineral", "Mineral", GR_TYPICAL, ["Aegislash"]),
SpeciesInfo("Aegislash", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Spritzee", "Fairy", "Fairy", GR_TYPICAL, ["Aromatisse"]),
SpeciesInfo("Aromatisse", "Fairy", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Swirlix", "Fairy", "Fairy", GR_TYPICAL, ["Slurpuff"]),
SpeciesInfo("Slurpuff", "Fairy", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Inkay", "Water 1", "Water 2", GR_TYPICAL, ["Malamar"]),
SpeciesInfo("Malamar", "Water 1", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Binacle", "Water 3", "Water 3", GR_TYPICAL, ["Barbaracle"]),
SpeciesInfo("Barbaracle", "Water 3", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Skrelp", "Water 1", "Dragon", GR_TYPICAL, ["Dragalge"]),
SpeciesInfo("Dragalge", "Water 1", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Clauncher", "Water 1", "Water 3", GR_TYPICAL, ["Clawitzer"]),
SpeciesInfo("Clawitzer", "Water 1", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Helioptile", "Monster", "Dragon", GR_TYPICAL, ["Heliolisk"]),
SpeciesInfo("Heliolisk", "Monster", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Tyrunt", "Monster", "Dragon", GR_TYPICAL, ["Tyrantrum"]),
SpeciesInfo("Tyrantrum", "Monster", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Amaura", "Monster", "Monster", GR_TYPICAL, ["Aurorus"]),
SpeciesInfo("Aurorus", "Monster", "Monster", GR_TYPICAL, []),
SpeciesInfo("Hawlucha", "Human-Like", "Human-Like", GR_TYPICAL, []),
SpeciesInfo("Dedenne", "Field", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Carbink", "Fairy", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Goomy", "Dragon", "Dragon", GR_TYPICAL, ["Sliggoo"]),
SpeciesInfo("Sliggoo", "Dragon", "Dragon", GR_TYPICAL, ["Goodra"]),
SpeciesInfo("Goodra", "Dragon", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Klefki", "Mineral", "Mineral", GR_TYPICAL, []),
SpeciesInfo("Phantump", "Grass", "Amorphous", GR_TYPICAL, ["Trevenant"]),
SpeciesInfo("Trevenant", "Grass", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Pumpkaboo", "Amorphous", "Amorphous", GR_TYPICAL, ["Gourgeist"]),
SpeciesInfo("Gourgeist", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Bergmite", "Monster", "Monster", GR_TYPICAL, ["Avalugg"]),
SpeciesInfo("Avalugg", "Monster", "Monster", GR_TYPICAL, []),
SpeciesInfo("Noibat", "Flying", "Flying", GR_TYPICAL, ["Noivern"]),
SpeciesInfo("Noivern", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Xerneas", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Yveltal", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Zygarde", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Diancie", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Hoopa", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Volcanion", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Rowlet", "Flying", "Flying", GR_TYPICAL, ["Dartrix"]),
SpeciesInfo("Dartrix", "Flying", "Flying", GR_TYPICAL, ["Decidueye"]),
SpeciesInfo("Decidueye", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Litten", "Field", "Field", GR_TYPICAL, ["Torracat"]),
SpeciesInfo("Torracat", "Field", "Field", GR_TYPICAL, ["Incineroar"]),
SpeciesInfo("Incineroar", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Popplio", "Water 1", "Field", GR_TYPICAL, ["Brionne"]),
SpeciesInfo("Brionne", "Water 1", "Field", GR_TYPICAL, ["Primarina"]),
SpeciesInfo("Primarina", "Water 1", "Field", GR_TYPICAL, []),
SpeciesInfo("Pikipek", "Flying", "Flying", GR_TYPICAL, ["Trumbeak"]),
SpeciesInfo("Trumbeak", "Flying", "Flying", GR_TYPICAL, ["Toucannon"]),
SpeciesInfo("Toucannon", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Yungoos", "Field", "Field", GR_TYPICAL, ["Gumshoos"]),
SpeciesInfo("Gumshoos", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Grubbin", "Bug", "Bug", GR_TYPICAL, ["Charjabug"]),
SpeciesInfo("Charjabug", "Bug", "Bug", GR_TYPICAL, ["Vikavolt"]),
SpeciesInfo("Vikavolt", "Bug", "Bug", GR_TYPICAL, []),
SpeciesInfo("Crabrawler", "Water 3", "Water 3", GR_TYPICAL, ["Crabominable"]),
SpeciesInfo("Crabominable", "Water 3", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Oricorio", "Flying", "Flying", GR_TYPICAL, []),
SpeciesInfo("Cutiefly", "Bug", "Fairy", GR_TYPICAL, ["Ribombee"]),
SpeciesInfo("Ribombee", "Bug", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Rockruff", "Field", "Field", GR_TYPICAL, ["Lycanroc"]),
SpeciesInfo("Lycanroc", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Wishiwashi", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Mareanie", "Water 1", "Water 1", GR_TYPICAL, ["Toxapex"]),
SpeciesInfo("Toxapex", "Water 1", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Mudbray", "Field", "Field", GR_TYPICAL, ["Mudsdale"]),
SpeciesInfo("Mudsdale", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Dewpider", "Water 1", "Bug", GR_TYPICAL, ["Araquanid"]),
SpeciesInfo("Araquanid", "Water 1", "Bug", GR_TYPICAL, []),
SpeciesInfo("Fomantis", "Grass", "Grass", GR_TYPICAL, ["Lurantis"]),
SpeciesInfo("Lurantis", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Morelull", "Grass", "Grass", GR_TYPICAL, ["Shiinotic"]),
SpeciesInfo("Shiinotic", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Salandit", "Monster", "Dragon", GR_FEMALE_ONLY, ["Salazzle"]),
SpeciesInfo("Salazzle", "Monster", "Dragon", GR_FEMALE_ONLY, []),
SpeciesInfo("Stufful", "Field", "Field", GR_TYPICAL, ["Bewear"]),
SpeciesInfo("Bewear", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Bounsweet", "Grass", "Grass", GR_FEMALE_ONLY, ["Steenee"]),
SpeciesInfo("Steenee", "Grass", "Grass", GR_FEMALE_ONLY, ["Tsareena"]),
SpeciesInfo("Tsareena", "Grass", "Grass", GR_FEMALE_ONLY, []),
SpeciesInfo("Comfey", "Grass", "Grass", GR_TYPICAL, []),
SpeciesInfo("Oranguru", "Field", "Field", GR_TYPICAL, ["Passimian"]),
SpeciesInfo("Passimian", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Wimpod", "Bug", "Water 3", GR_TYPICAL, ["Golisopod"]),
SpeciesInfo("Golisopod", "Bug", "Water 3", GR_TYPICAL, []),
SpeciesInfo("Sandygast", "Amorphous", "Amorphous", GR_TYPICAL, ["Palossand"]),
SpeciesInfo("Palossand", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Pyukumuku", "Water 1", "Water 1", GR_TYPICAL, []),
SpeciesInfo("Type: Null", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, ["Silvally"]),
SpeciesInfo("Silvally", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Minior", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Komala", "Field", "Field", GR_TYPICAL, []),
SpeciesInfo("Turtonator", "Monster", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Togedemaru", "Field", "Fairy", GR_TYPICAL, []),
SpeciesInfo("Mimikyu", "Amorphous", "Amorphous", GR_TYPICAL, []),
SpeciesInfo("Bruxish", "Water 2", "Water 2", GR_TYPICAL, []),
SpeciesInfo("Drampa", "Monster", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Dhelmise", "Mineral", "Mineral", GR_UNKNOWN, []),
SpeciesInfo("Jangmo-o", "Dragon", "Dragon", GR_TYPICAL, ["Hakamo-o"]),
SpeciesInfo("Hakamo-o", "Dragon", "Dragon", GR_TYPICAL, ["Kommo-o"]),
SpeciesInfo("Kommo-o", "Dragon", "Dragon", GR_TYPICAL, []),
SpeciesInfo("Tapu Koko", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Tapu Lele", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Tapu Bulu", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Tapu Fini", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Cosmog", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, ["Cosmoem"]),
SpeciesInfo("Cosmoem", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, ["Solgaleo", "Lunala"]),
SpeciesInfo("Solgaleo", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Lunala", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Nihilego", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Buzzwole", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Pheromosa", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Xurkitree", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Celesteela", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Kartana", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Guzzlord", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Necrozma", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Magearna", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Marshadow", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Poipole", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, ["Naganadel"]),
SpeciesInfo("Naganadel", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Stakataka", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Blacephalon", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Zeraora", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, []),
SpeciesInfo("Meltan", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, ["Melmetal"]),
SpeciesInfo("Melmetal", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, [])
]
);