#include <string>
#include "core.cpp"

//baby pokemon are a unique case because they are in NED but they can evolve out of it
//the egg groups are for the pokemon it will evolve into
static std::string sBabyMons[] = {
	"Pichu",
	"Cleffa",
	"Igglybuff",
	"Togepi",
	"Tyrogue",
	"Smoochum",
	"Elekid",
	"Magby",
	"Azurill",
	"Wynaut",
	"Budew",
	"Chingling",
	"Bonsly",
	"Mime Jr.",
	"Happiny",
	"Munchlax",
	"Riolu",
	"Mantyke"
};

static std::string sFemaleOnlyMons[] = {
	"Nidoran F",
	"Chansey",
	"Kangaskhan",
	"Jynx",
	"Miltank",
	"Blissey",
	"Illumise",
	"Wormadam",
	"Vespiquen",
	"Froslass"
};

static std::string sMaleOnlyMons[] = {
	"Nidoran M",
	"Nidorino",
	"Nidoking",
	"Hitmonlee",
	"Hitmonchan",
	"Tauros",
	"Hitmontop",
	"Volbeat",
	"Mothim",
	"Gallade"
};

static std::string sUniversalTMs[] = {
	"Captivate",
	"Return",
	"Frustration",
	"Facade",
	"Swagger",
	"Natural Gift",
	"Endure",
	"Sleep Talk",
	"Attract",
	"Secret Power",
	"Rest",
	"Hidden Power",
	"Toxic",
	"Protect",
	"Double Team",
	"Substitute"//2025: Why was substitute missing!? If I discover something about this later, I really need to note it here
};

static std::string sTMsandHMs[] = {
	"Focus Punch",
	"Dragon Claw",
	"Water Pulse",
	"Calm Mind",
	"Roar",
	"Toxic",
	"Hail",
	"Bulk Up",
	"Bullet Seed",
	"Hidden Power",
	"Sunny Day",
	"Taunt",
	"Ice Beam",
	"Blizzard",
	"Hyper Beam",
	"Light Screen",
	"Protect",
	"Rain Dance",
	"Giga Drain",
	"Safeguard",
	"Frustration",
	"SolarBeam",
	"Iron Tail",
	"Thunderbolt",
	"Thunder",
	"Earthquake",
	"Return",
	"Dig",
	"Psychic",
	"Shadow Ball",
	"Brick Break",
	"Double Team",
	"Reflect",
	"Shock Wave",
	"Flamethrower",
	"Sludge Bomb",
	"Sandstorm",
	"Fire Blast",
	"Rock Tomb",
	"Aerial Ace",
	"Torment",
	"Facade",
	"Secret Power",
	"Rest",
	"Attract",
	"Thief",
	"Steel Wing",
	"Skill Swap",
	"Snatch",
	"Overheat",
	"Roost",
	"Focus Blast",
	"Energy Ball",
	"False Swipe",
	"Brine",
	"Fling",
	"Charge Beam",
	"Endure",
	"Dragon Pulse",
	"Drain Punch",
	"Will-O-Wisp",
	"Silver Wind",
	"Embargo",
	"Explosion",
	"Shadow Claw",
	"Payback",
	"Recycle",
	"Giga Impact",
	"Rock Polish",
	"Flash",
	"Stone Edge",
	"Avalanche",
	"Thunder Wave",
	"Gyro Ball",
	"Swords Dance",
	"Stealth Rock",
	"Psych Up",
	"Captivate",
	"Dark Pulse",
	"Rock Slide",
	"X-Scissor",
	"Sleep Talk",
	"Natural Gift",
	"Poison Jab",
	"Dream Eater",
	"Grass Knot",
	"Swagger",
	"Pluck",
	"U-turn",
	"Substitute",
	"Flash Cannon",
	"Trick Room",
	"Cut",
	"Fly",
	"Surf",
	"Strength",
	"Defog",
	"Whirlpool",
	"Rock Smash",
	"Waterfall",
	"Rock Climb"
};

//a list of pokemon who can come from eggs (not accounting for egg groups that forbid this)
static std::string sEggMons[] = {
	"Bulbasaur",
	"Charmander",
	"Squirtle",
	"Caterpie",
	"Weedle",
	"Pidgey",
	"Rattata",
	"Spearow",
	"Ekans",
	"Pichu",
	"Sandshrew",
	"Nidoran F",
	"Nidoran M",
	"Cleffa",
	"Vulpix",
	"Igglybuff",
	"Zubat",
	"Oddish",
	"Paras",
	"Venonat",
	"Diglett",
	"Meowth",
	"Psyduck",
	"Mankey",
	"Growlithe",
	"Poliwag",
	"Abra",
	"Machop",
	"Bellsprout",
	"Tentacool",
	"Geodude",
	"Ponyta",
	"Slowpoke",
	"Magnemite",
	"Farfetch'd",
	"Doduo",
	"Seel",
	"Grimer",
	"Shellder",
	"Gastly",
	"Onix",
	"Drowzee",
	"Krabby",
	"Voltorb",
	"Exeggcute",
	"Cubone",
	"Tyrogue",
	"Lickitung",
	"Koffing",
	"Rhyhorn",
	"Happiny",
	"Chansey",
	"Tangela",
	"Kangaskhan",
	"Horsea",
	"Goldeen",
	"Staryu",
	"Mime Jr.",
	"Mr. Mime",
	"Scyther",
	"Smoochum",
	"Elekid",
	"Magby",
	"Pinsir",
	"Tauros",
	"Magikarp",
	"Lapras",
	"Ditto",
	"Eevee",
	"Porygon",
	"Omanyte",
	"Kabuto",
	"Aerodactyl",
	"Munchlax",
	"Snorlax",
	"Articuno",
	"Zapdos",
	"Moltres",
	"Dratini",
	"Mewtwo",
	"Mew",
	"Chikorita",
	"Cyndaquil",
	"Totodile",
	"Sentret",
	"Hoothoot",
	"Ledyba",
	"Spinarak",
	"Chinchou",
	"Togepi",
	"Natu",
	"Mareep",
	"Azurill",
	"Marill",
	"Bonsly",
	"Sudowoodo",
	"Hoppip",
	"Aipom",
	"Sunkern",
	"Yanma",
	"Wooper",
	"Murkrow",
	"Misdreavus",
	"Unown",
	"Wynaut",
	"Wobbuffet",
	"Girafarig",
	"Pineco",
	"Dunsparce",
	"Gligar",
	"Snubbull",
	"Qwilfish",
	"Shuckle",
	"Heracross",
	"Sneasel",
	"Teddiursa",
	"Slugma",
	"Swinub",
	"Corsola",
	"Remoraid",
	"Delibird",
	"Mantyke",
	"Mantine",
	"Skarmory",
	"Houndour",
	"Phanpy",
	"Stantler",
	"Smeargle",
	"Miltank",
	"Raikou",
	"Entei",
	"Suicune",
	"Larvitar",
	"Lugia",
	"Ho-Oh",
	"Celebi",
	"Treecko",
	"Torchic",
	"Mudkip",
	"Poochyena",
	"Zigzagoon",
	"Wurmple",
	"Lotad",
	"Seedot",
	"Taillow",
	"Wingull",
	"Ralts",
	"Surskit",
	"Shroomish",
	"Slakoth",
	"Nincada",
	"Whismur",
	"Makuhita",
	"Nosepass",
	"Skitty",
	"Sableye",
	"Mawile",
	"Aron",
	"Meditite",
	"Electrike",
	"Plusle",
	"Minun",
	"Volbeat",
	"Illumise",
	"Budew",
	"Roselia",
	"Gulpin",
	"Carvanha",
	"Wailmer",
	"Numel",
	"Torkoal",
	"Spoink",
	"Spinda",
	"Trapinch",
	"Cacnea",
	"Swablu",
	"Zangoose",
	"Seviper",
	"Lunatone",
	"Solrock",
	"Barboach",
	"Corphish",
	"Baltoy",
	"Lileep",
	"Anorith",
	"Feebas",
	"Castform",
	"Kecleon",
	"Shuppet",
	"Duskull",
	"Tropius",
	"Chingling",
	"Chimecho",
	"Absol",
	"Snorunt",
	"Spheal",
	"Clamperl",
	"Relicanth",
	"Luvdisc",
	"Bagon",
	"Beldum",
	"Regirock",
	"Regice",
	"Registeel",
	"Latias",
	"Latios",
	"Kyogre",
	"Groudon",
	"Rayquaza",
	"Jirachi",
	"Deoxys",
	"Turtwig",
	"Chimchar",
	"Piplup",
	"Starly",
	"Bidoof",
	"Kricketot",
	"Shinx",
	"Cranidos",
	"Shieldon",
	"Burmy",
	"Combee",
	"Pachirisu",
	"Buizel",
	"Cherubi",
	"Shellos",
	"Drifloon",
	"Buneary",
	"Glameow",
	"Stunky",
	"Bronzor",
	"Chatot",
	"Spiritomb",
	"Gible",
	"Riolu",
	"Hippopotas",
	"Skorupi",
	"Croagunk",
	"Carnivine",
	"Finneon",
	"Snover",
	"Rotom",
	"Uxie",
	"Mesprit",
	"Azelf",
	"Dialga",
	"Palkia",
	"Heatran",
	"Regigigas",
	"Giratina",
	"Cresselia",
	"Phione",
	"Manaphy",
	"Darkrai",
	"Shaymin",
	"Arceus"
};

static SpeciesInfo sAllGroups[] = {
{"Bulbasaur", "Monster", "Grass", {"Ivysaur"}},
{"Ivysaur", "Monster", "Grass", {"Venusaur"}},
{"Venusaur", "Monster", "Grass", {}},
{"Charmander", "Monster", "Dragon", {"Charmeleon"}},
{"Charmeleon", "Monster", "Dragon", {"Charizard"}},
{"Charizard", "Monster", "Dragon", {}},
{"Squirtle", "Monster", "Water 1", {"Wartortle"}},
{"Wartortle", "Monster", "Water 1", {"Blastoise"}},
{"Blastoise", "Monster", "Water 1", {}},
{"Caterpie", "Bug", "Bug", {"Metapod"}},
{"Metapod", "Bug", "Bug", {"Butterfree"}},
{"Butterfree", "Bug", "Bug", {}},
{"Weedle", "Bug", "Bug", {"Kakuna"}},
{"Kakuna", "Bug", "Bug", {"Beedrill"}},
{"Beedrill", "Bug", "Bug", {}},
{"Pidgey", "Flying", "Flying", {"Pidgeotto"}},
{"Pidgeotto", "Flying", "Flying", {"Pidgeot"}},
{"Pidgeot", "Flying", "Flying", {}},
{"Rattata", "Field", "Field", {"Raticate"}},
{"Raticate", "Field", "Field", {}},
{"Spearow", "Flying", "Flying", {"Fearow"}},
{"Fearow", "Flying", "Flying", {}},
{"Ekans", "Field", "Dragon", {"Arbok"}},
{"Arbok", "Field", "Dragon", {}},
{"Pichu", "No Eggs Discovered", "No Eggs Discovered", {"Pikachu"}},
{"Pikachu", "Field", "Fairy", {"Raichu"}},
{"Raichu", "Field", "Fairy", {}},
{"Sandshrew", "Field", "Field", {"Sandslash"}},
{"Sandslash", "Field", "Field", {}},
{"Nidoran F", "Monster", "Field", {"Nidorina"}},
{"Nidorina", "No Eggs Discovered", "No Eggs Discovered", {"Nidoqueen"}},
{"Nidoqueen", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Nidoran M", "Monster", "Field", {"Nidorino"}},
{"Nidorino", "Monster", "Field", {"Nidoking"}},
{"Nidoking", "Monster", "Field", {}},
{"Cleffa", "No Eggs Discovered", "No Eggs Discovered", {"Clefairy"}},
{"Clefairy", "Fairy", "Fairy", {"Clefable"}},
{"Clefable", "Fairy", "Fairy", {}},
{"Vulpix", "Field", "Field", {"Ninetales"}},
{"Ninetales", "Field", "Field", {}},
{"Igglybuff", "No Eggs Discovered", "No Eggs Discovered", {"Jigglypuff"}},
{"Jigglypuff", "Fairy", "Fairy", {"Wigglytuff"}},
{"Wigglytuff", "Fairy", "Fairy", {}},
{"Zubat", "Flying", "Flying", {"Golbat"}},
{"Golbat", "Flying", "Flying", {"Crobat"}},
{"Crobat", "Flying", "Flying", {}},
{"Oddish", "Grass", "Grass", {"Gloom"}},
{"Gloom", "Grass", "Grass", {"Vileplume", "Bellossom"}},
{"Vileplume", "Grass", "Grass", {}},
{"Bellossom", "Grass", "Grass", {}},
{"Paras", "Bug", "Grass", {"Parasect"}},
{"Parasect", "Bug", "Grass", {}},
{"Venonat", "Bug", "Bug", {"Venomoth"}},
{"Venomoth", "Bug", "Bug", {}},
{"Diglett", "Field", "Field", {"Dugtrio"}},
{"Dugtrio", "Field", "Field", {}},
{"Meowth", "Field", "Field", {"Persian"}},
{"Persian", "Field", "Field", {}},
{"Psyduck", "Water 1", "Field", {"Golduck"}},
{"Golduck", "Water 1", "Field", {}},
{"Mankey", "Field", "Field", {"Primeape"}},
{"Primeape", "Field", "Field", {}},
{"Growlithe", "Field", "Field", {"Arcanine"}},
{"Arcanine", "Field", "Field", {}},
{"Poliwag", "Water 1", "Water 1", {"Poliwhirl"}},
{"Poliwhirl", "Water 1", "Water 1", {"Poliwrath", "Politoed"}},
{"Poliwrath", "Water 1", "Water 1", {}},
{"Politoed", "Water 1", "Water 1", {}},
{"Abra", "Human-Like", "Human-Like", {"Kadabra"}},
{"Kadabra", "Human-Like", "Human-Like", {"Alakazam"}},
{"Alakazam", "Human-Like", "Human-Like", {}},
{"Machop", "Human-Like", "Human-Like", {"Machoke"}},
{"Machoke", "Human-Like", "Human-Like", {"Machamp"}},
{"Machamp", "Human-Like", "Human-Like", {}},
{"Bellsprout", "Grass", "Grass", {"Weepinbell"}},
{"Weepinbell", "Grass", "Grass", {"Victreebel"}},
{"Victreebel", "Grass", "Grass", {}},
{"Tentacool", "Water 3", "Water 3", {"Tentacruel"}},
{"Tentacruel", "Water 3", "Water 3", {}},
{"Geodude", "Mineral", "Mineral", {"Graveler"}},
{"Graveler", "Mineral", "Mineral", {"Golem"}},
{"Golem", "Mineral", "Mineral", {}},
{"Ponyta", "Field", "Field", {"Rapidash"}},
{"Rapidash", "Field", "Field", {}},
{"Slowpoke", "Monster", "Water 1", {"Slowbro", "Slowking"}},
{"Slowbro", "Monster", "Water 1", {}},
{"Slowking", "Monster", "Water 1", {}},
{"Magnemite", "Mineral", "Mineral", {"Magneton"}},
{"Magneton", "Mineral", "Mineral", {"Magnezone"}},
{"Magnezone", "Mineral", "Mineral", {}},
{"Farfetch'd", "Flying", "Field", {}},
{"Doduo", "Flying", "Flying", {"Dodrio"}},
{"Dodrio", "Flying", "Flying", {}},
{"Seel", "Water 1", "Field", {"Dewgong"}},
{"Dewgong", "Water 1", "Field", {}},
{"Grimer", "Amorphous", "Amorphous", {"Muk"}},
{"Muk", "Amorphous", "Amorphous", {}},
{"Shellder", "Water 3", "Water 3", {"Cloyster"}},
{"Cloyster", "Water 3", "Water 3", {}},
{"Gastly", "Amorphous", "Amorphous", {"Haunter"}},
{"Haunter", "Amorphous", "Amorphous", {"Gengar"}},
{"Gengar", "Amorphous", "Amorphous", {}},
{"Onix", "Mineral", "Mineral", {"Steelix"}},
{"Steelix", "Mineral", "Mineral", {}},
{"Drowzee", "Human-Like", "Human-Like", {"Hypno"}},
{"Hypno", "Human-Like", "Human-Like", {}},
{"Krabby", "Water 3", "Water 3", {"Kingler"}},
{"Kingler", "Water 3", "Water 3", {}},
{"Voltorb", "Mineral", "Mineral", {"Electrode"}},
{"Electrode", "Mineral", "Mineral", {}},
{"Exeggcute", "Grass", "Grass", {"Exeggutor"}},
{"Exeggutor", "Grass", "Grass", {}},
{"Cubone", "Monster", "Monster", {"Marowak"}},
{"Marowak", "Monster", "Monster", {}},
{"Tyrogue", "No Eggs Discovered", "No Eggs Discovered", {"Hitmonlee", "Hitmonchan", "Hitmontop"}},
{"Hitmonlee", "Human-Like", "Human-Like", {}},
{"Hitmonchan", "Human-Like", "Human-Like", {}},
{"Hitmontop", "Human-Like", "Human-Like", {}},
{"Lickitung", "Monster", "Monster", {"Lickilicky"}},
{"Lickilicky", "Monster", "Monster", {}},
{"Koffing", "Amorphous", "Amorphous", {"Weezing"}},
{"Weezing", "Amorphous", "Amorphous", {}},
{"Rhyhorn", "Monster", "Field", {"Rhydon"}},
{"Rhydon", "Monster", "Field", {"Rhyperior"}},
{"Rhyperior", "Monster", "Field", {}},
{"Happiny", "No Eggs Discovered", "No Eggs Discovered", {"Chansey"}},
{"Chansey", "Fairy", "Fairy", {"Blissey"}},
{"Blissey", "Fairy", "Fairy", {}},
{"Tangela", "Grass", "Grass", {"Tangrowth"}},
{"Tangrowth", "Grass", "Grass", {}},
{"Kangaskhan", "Monster", "Monster", {}},
{"Horsea", "Water 1", "Dragon", {"Seadra"}},
{"Seadra", "Water 1", "Dragon", {"Kingdra"}},
{"Kingdra", "Water 1", "Dragon", {}},
{"Goldeen", "Water 2", "Water 2", {"Seaking"}},
{"Seaking", "Water 2", "Water 2", {}},
{"Staryu", "Water 3", "Water 3", {"Starmie"}},
{"Starmie", "Water 3", "Water 3", {}},
{"Mime Jr.", "No Eggs Discovered", "No Eggs Discovered", {"Mr. Mime"}},
{"Mr. Mime", "Human-Like", "Human-Like", {}},
{"Scyther", "Bug", "Bug", {"Scizor"}},
{"Scizor", "Bug", "Bug", {}},
{"Smoochum", "No Eggs Discovered", "No Eggs Discovered", {"Jynx"}},
{"Jynx", "Human-Like", "Human-Like", {}},
{"Elekid", "No Eggs Discovered", "No Eggs Discovered", {"Electabuzz"}},
{"Electabuzz", "Human-Like", "Human-Like", {"Electivire"}},
{"Electivire", "Human-Like", "Human-Like", {}},
{"Magby", "No Eggs Discovered", "No Eggs Discovered", {"Magmar"}},
{"Magmar", "Human-Like", "Human-Like", {"Magmortar"}},
{"Magmortar", "Human-Like", "Human-Like", {}},
{"Pinsir", "Bug", "Bug", {}},
{"Tauros", "Field", "Field", {}},
{"Magikarp", "Water 2", "Dragon", {"Gyarados"}},
{"Gyarados", "Water 2", "Dragon", {}},
{"Lapras", "Monster", "Water 1", {}},
{"Ditto", "Ditto", "Ditto", {}},
{"Eevee", "Field", "Field", {"Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon", "Leafeon", "Glaceon"}},//7 - Glaceon has to look 7 slots back to find Eevee
{"Vaporeon", "Field", "Field", {}},//6
{"Jolteon", "Field", "Field", {}},//5
{"Flareon", "Field", "Field", {}},//4
{"Espeon", "Field", "Field", {}},//3
{"Umbreon", "Field", "Field", {}},//2
{"Leafeon", "Field", "Field", {}},//1
{"Glaceon", "Field", "Field", {}},//0
{"Porygon", "Mineral", "Mineral", {"Porygon2"}},
{"Porygon2", "Mineral", "Mineral", {"Porygon-Z"}},
{"Porygon-Z", "Mineral", "Mineral", {}},
{"Omanyte", "Water 1", "Water 3", {"Omastar"}},
{"Omastar", "Water 1", "Water 3", {}},
{"Kabuto", "Water 1", "Water 3", {"Kabutops"}},
{"Kabutops", "Water 1", "Water 3", {}},
{"Aerodactyl", "Flying", "Flying", {}},
{"Munchlax", "No Eggs Discovered", "No Eggs Discovered", {"Snorlax"}},
{"Snorlax", "Monster", "Monster", {}},
{"Articuno", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Zapdos", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Moltres", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Dratini", "Water 1", "Dragon", {"Dragonair"}},
{"Dragonair", "Water 1", "Dragon", {"Dragonite"}},
{"Dragonite", "Water 1", "Dragon", {}},
{"Mewtwo", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Mew", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Chikorita", "Monster", "Grass", {"Bayleef"}},
{"Bayleef", "Monster", "Grass", {"Meganium"}},
{"Meganium", "Monster", "Grass", {}},
{"Cyndaquil", "Field", "Field", {"Quilava"}},
{"Quilava", "Field", "Field", {"Typhlosion"}},
{"Typhlosion", "Field", "Field", {}},
{"Totodile", "Monster", "Water 1", {"Croconaw"}},
{"Croconaw", "Monster", "Water 1", {"Feraligatr"}},
{"Feraligatr", "Monster", "Water 1", {}},
{"Sentret", "Field", "Field", {"Furret"}},
{"Furret", "Field", "Field", {}},
{"Hoothoot", "Flying", "Flying", {"Noctowl"}},
{"Noctowl", "Flying", "Flying", {}},
{"Ledyba", "Bug", "Bug", {"Ledian"}},
{"Ledian", "Bug", "Bug", {}},
{"Spinarak", "Bug", "Bug", {"Ariados"}},
{"Ariados", "Bug", "Bug", {}},
{"Chinchou", "Water 2", "Water 2", {"Lanturn"}},
{"Lanturn", "Water 2", "Water 2", {}},
{"Togepi", "No Eggs Discovered", "No Eggs Discovered", {"Togetic"}},
{"Togetic", "Flying", "Fairy", {"Togekiss"}},
{"Togekiss", "Flying", "Fairy", {}},
{"Natu", "Flying", "Flying", {"Xatu"}},
{"Xatu", "Flying", "Flying", {}},
{"Mareep", "Monster", "Field", {"Flaaffy"}},
{"Flaaffy", "Monster", "Field", {"Ampharos"}},
{"Ampharos", "Monster", "Field", {}},
{"Azurill", "No Eggs Discovered", "No Eggs Discovered", {"Marill"}},
{"Marill", "Water 1", "Fairy", {"Azumarill"}},
{"Azumarill", "Water 1", "Fairy", {}},
{"Bonsly", "No Eggs Discovered", "No Eggs Discovered", {"Sudowoodo"}},
{"Sudowoodo", "Mineral", "Mineral", {}},
{"Hoppip", "Fairy", "Grass", {"Skiploom"}},
{"Skiploom", "Fairy", "Grass", {"Jumpluff"}},
{"Jumpluff", "Fairy", "Grass", {}},
{"Aipom", "Field", "Field", {"Ambipom"}},
{"Ambipom", "Field", "Field", {}},
{"Sunkern", "Grass", "Grass", {"Sunflora"}},
{"Sunflora", "Grass", "Grass", {}},
{"Yanma", "Bug", "Bug", {"Yanmega"}},
{"Yanmega", "Bug", "Bug", {}},
{"Wooper", "Water 1", "Field", {"Quagsire"}},
{"Quagsire", "Water 1", "Field", {}},
{"Murkrow", "Flying", "Flying", {"Honchkrow"}},
{"Honchkrow", "Flying", "Flying", {}},
{"Misdreavus", "Amorphous", "Amorphous", {"Mismagius"}},
{"Mismagius", "Amorphous", "Amorphous", {}},
{"Unown", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Wynaut", "No Eggs Discovered", "No Eggs Discovered", {"Wobbuffet"}},
{"Wobbuffet", "Amorphous", "Amorphous", {}},
{"Girafarig", "Field", "Field", {}},
{"Pineco", "Bug", "Bug", {"Forretress"}},
{"Forretress", "Bug", "Bug", {}},
{"Dunsparce", "Field", "Field", {}},
{"Gligar", "Bug", "Bug", {"Gliscor"}},
{"Gliscor", "Bug", "Bug", {}},
{"Snubbull", "Field", "Fairy", {"Granbull"}},
{"Granbull", "Field", "Fairy", {}},
{"Qwilfish", "Water 2", "Water 2", {}},
{"Shuckle", "Bug", "Bug", {}},
{"Heracross", "Bug", "Bug", {}},
{"Sneasel", "Field", "Field", {"Weavile"}},
{"Weavile", "Field", "Field", {}},
{"Teddiursa", "Field", "Field", {"Ursaring"}},
{"Ursaring", "Field", "Field", {}},
{"Slugma", "Amorphous", "Amorphous", {"Magcargo"}},
{"Magcargo", "Amorphous", "Amorphous", {}},
{"Swinub", "Field", "Field", {"Piloswine"}},
{"Piloswine", "Field", "Field", {"Mamoswine"}},
{"Mamoswine", "Field", "Field", {}},
{"Corsola", "Water 1", "Water 3", {}},
{"Remoraid", "Water 1", "Water 2", {"Octillery"}},
{"Octillery", "Water 1", "Water 2", {}},
{"Delibird", "Water 1", "Field", {}},
{"Mantyke", "No Eggs Discovered", "No Eggs Discovered", {"Mantine"}},
{"Mantine", "Water 1", "Water 1", {}},
{"Skarmory", "Flying", "Flying", {}},
{"Houndour", "Field", "Field", {"Houndoom"}},
{"Houndoom", "Field", "Field", {}},
{"Phanpy", "Field", "Field", {"Donphan"}},
{"Donphan", "Field", "Field", {}},
{"Stantler", "Field", "Field", {}},
{"Smeargle", "Field", "Field", {}},
{"Miltank", "Field", "Field", {}},
{"Raikou", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Entei", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Suicune", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Larvitar", "Monster", "Monster", {"Pupitar"}},
{"Pupitar", "Monster", "Monster", {"Tyranitar"}},
{"Tyranitar", "Monster", "Monster", {}},
{"Lugia", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Ho-Oh", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Celebi", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Treecko", "Monster", "Dragon", {"Grovyle"}},
{"Grovyle", "Monster", "Dragon", {"Sceptile"}},
{"Sceptile", "Monster", "Dragon", {}},
{"Torchic", "Field", "Field", {"Combusken"}},
{"Combusken", "Field", "Field", {"Blaziken"}},
{"Blaziken", "Field", "Field", {}},
{"Mudkip", "Monster", "Water 1", {"Marshtomp"}},
{"Marshtomp", "Monster", "Water 1", {"Swampert"}},
{"Swampert", "Monster", "Water 1", {}},
{"Poochyena", "Field", "Field", {"Mightyena"}},
{"Mightyena", "Field", "Field", {}},
{"Zigzagoon", "Field", "Field", {"Linoone"}},
{"Linoone", "Field", "Field", {}},
{"Wurmple", "Bug", "Bug", {"Silcoon", "Cascoon"}},
{"Silcoon", "Bug", "Bug", {"Beautifly"}},
{"Beautifly", "Bug", "Bug", {}},
{"Cascoon", "Bug", "Bug", {"Dustox"}},
{"Dustox", "Bug", "Bug", {}},
{"Lotad", "Water 1", "Grass", {"Lombre"}},
{"Lombre", "Water 1", "Grass", {"Ludicolo"}},
{"Ludicolo", "Water 1", "Grass", {}},
{"Seedot", "Field", "Grass", {"Nuzleaf"}},
{"Nuzleaf", "Field", "Grass", {"Shiftry"}},
{"Shiftry", "Field", "Grass", {}},
{"Taillow", "Flying", "Flying", {"Swellow"}},
{"Swellow", "Flying", "Flying", {}},
{"Wingull", "Water 1", "Flying", {"Pelipper"}},
{"Pelipper", "Water 1", "Flying", {}},
{"Ralts", "Amorphous", "Amorphous", {"Kirlia"}},
{"Kirlia", "Amorphous", "Amorphous", {"Gardevoir", "Gallade"}},
{"Gardevoir", "Amorphous", "Amorphous", {}},
{"Gallade", "Amorphous", "Amorphous", {}},
{"Surskit", "Water 1", "Bug", {"Masquerain"}},
{"Masquerain", "Water 1", "Bug", {}},
{"Shroomish", "Fairy", "Grass", {"Breloom"}},
{"Breloom", "Fairy", "Grass", {}},
{"Slakoth", "Field", "Field", {"Vigoroth"}},
{"Vigoroth", "Field", "Field", {"Slaking"}},
{"Slaking", "Field", "Field", {}},
{"Nincada", "Bug", "Bug", {"Ninjask", "Shedinja"}},
{"Ninjask", "Bug", "Bug", {}},
{"Shedinja", "Mineral", "Mineral", {}},
{"Whismur", "Monster", "Field", {"Loudred"}},
{"Loudred", "Monster", "Field", {"Exploud"}},
{"Exploud", "Monster", "Field", {}},
{"Makuhita", "Human-Like", "Human-Like", {"Hariyama"}},
{"Hariyama", "Human-Like", "Human-Like", {}},
{"Nosepass", "Mineral", "Mineral", {"Probopass"}},
{"Probopass", "Mineral", "Mineral", {}},
{"Skitty", "Field", "Fairy", {"Delcatty"}},
{"Delcatty", "Field", "Fairy", {}},
{"Sableye", "Human-Like", "Human-Like", {}},
{"Mawile", "Field", "Fairy", {}},
{"Aron", "Monster", "Monster", {"Lairon"}},
{"Lairon", "Monster", "Monster", {"Aggron"}},
{"Aggron", "Monster", "Monster", {}},
{"Meditite", "Human-Like", "Human-Like", {"Medicham"}},
{"Medicham", "Human-Like", "Human-Like", {}},
{"Electrike", "Field", "Field", {"Manectric"}},
{"Manectric", "Field", "Field", {}},
{"Plusle", "Fairy", "Fairy", {}},
{"Minun", "Fairy", "Fairy", {}},
{"Volbeat", "Bug", "Human-Like", {}},
{"Illumise", "Bug", "Human-Like", {}},
{"Budew", "No Eggs Discovered", "No Eggs Discovered", {"Roselia"}},
{"Roselia", "Fairy", "Grass", {"Roserade"}},
{"Roserade", "Fairy", "Grass", {}},
{"Gulpin", "Amorphous", "Amorphous", {"Swalot"}},
{"Swalot", "Amorphous", "Amorphous", {}},
{"Carvanha", "Water 2", "Water 2", {"Sharpedo"}},
{"Sharpedo", "Water 2", "Water 2", {}},
{"Wailmer", "Field", "Water 2", {"Wailord"}},
{"Wailord", "Field", "Water 2", {}},
{"Numel", "Field", "Field", {"Camerupt"}},
{"Camerupt", "Field", "Field", {}},
{"Torkoal", "Field", "Field", {}},
{"Spoink", "Field", "Field", {"Grumpig"}},
{"Grumpig", "Field", "Field", {}},
{"Spinda", "Field", "Human-Like", {}},
{"Trapinch", "Bug", "Bug", {"Vibrava"}},
{"Vibrava", "Bug", "Bug", {"Flygon"}},
{"Flygon", "Bug", "Bug", {}},
{"Cacnea", "Grass", "Human-Like", {"Cacturne"}},
{"Cacturne", "Grass", "Human-Like", {}},
{"Swablu", "Flying", "Dragon", {"Altaria"}},
{"Altaria", "Flying", "Dragon", {}},
{"Zangoose", "Field", "Field", {}},
{"Seviper", "Field", "Dragon", {}},
{"Lunatone", "Mineral", "Mineral", {}},
{"Solrock", "Mineral", "Mineral", {}},
{"Barboach", "Water 2", "Water 2", {"Whiscash"}},
{"Whiscash", "Water 2", "Water 2", {}},
{"Corphish", "Water 1", "Water 3", {"Crawdaunt"}},
{"Crawdaunt", "Water 1", "Water 3", {}},
{"Baltoy", "Mineral", "Mineral", {"Claydol"}},
{"Claydol", "Mineral", "Mineral", {}},
{"Lileep", "Water 3", "Water 3", {"Cradily"}},
{"Cradily", "Water 3", "Water 3", {}},
{"Anorith", "Water 3", "Water 3", {"Armaldo"}},
{"Armaldo", "Water 3", "Water 3", {}},
{"Feebas", "Water 1", "Dragon", {"Milotic"}},
{"Milotic", "Water 1", "Dragon", {}},
{"Castform", "Fairy", "Amorphous", {}},
{"Kecleon", "Field", "Field", {}},
{"Shuppet", "Amorphous", "Amorphous", {"Banette"}},
{"Banette", "Amorphous", "Amorphous", {}},
{"Duskull", "Amorphous", "Amorphous", {"Dusclops"}},
{"Dusclops", "Amorphous", "Amorphous", {"Dusknoir"}},
{"Dusknoir", "Amorphous", "Amorphous", {}},
{"Tropius", "Monster", "Grass", {}},
{"Chingling", "No Eggs Discovered", "No Eggs Discovered", {"Chimecho"}},
{"Chimecho", "Amorphous", "Amorphous", {}},
{"Absol", "Field", "Field", {}},
{"Snorunt", "Fairy", "Mineral", {"Glalie", "Froslass"}},
{"Glalie", "Fairy", "Mineral", {}},
{"Froslass", "Fairy", "Mineral", {}},
{"Spheal", "Water 1", "Field", {"Sealeo"}},
{"Sealeo", "Water 1", "Field", {"Walrein"}},
{"Walrein", "Water 1", "Field", {}},
{"Clamperl", "Water 1", "Water 1", {"Huntail", "Gorebyss"}},
{"Huntail", "Water 1", "Water 1", {}},
{"Gorebyss", "Water 1", "Water 1", {}},
{"Relicanth", "Water 1", "Water 2", {}},
{"Luvdisc", "Water 2", "Water 2", {}},
{"Bagon", "Dragon", "Dragon", {"Shelgon"}},
{"Shelgon", "Dragon", "Dragon", {"Salamence"}},
{"Salamence", "Dragon", "Dragon", {}},
{"Beldum", "Mineral", "Mineral", {"Metang"}},
{"Metang", "Mineral", "Mineral", {"Metagross"}},
{"Metagross", "Mineral", "Mineral", {}},
{"Regirock", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Regice", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Registeel", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Latias", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Latios", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Kyogre", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Groudon", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Rayquaza", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Jirachi", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Deoxys", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Turtwig", "Monster", "Grass", {"Grotle"}},
{"Grotle", "Monster", "Grass", {"Torterra"}},
{"Torterra", "Monster", "Grass", {}},
{"Chimchar", "Field", "Human-Like", {"Monferno"}},
{"Monferno", "Field", "Human-Like", {"Infernape"}},
{"Infernape", "Field", "Human-Like", {}},
{"Piplup", "Water 1", "Field", {"Prinplup"}},
{"Prinplup", "Water 1", "Field", {"Empoleon"}},
{"Empoleon", "Water 1", "Field", {}},
{"Starly", "Flying", "Flying", {"Staravia"}},
{"Staravia", "Flying", "Flying", {"Staraptor"}},
{"Staraptor", "Flying", "Flying", {}},
{"Bidoof", "Water 1", "Field", {"Bibarel"}},
{"Bibarel", "Water 1", "Field", {}},
{"Kricketot", "Bug", "Bug", {"Kricketune"}},
{"Kricketune", "Bug", "Bug", {}},
{"Shinx", "Field", "Field", {"Luxio"}},
{"Luxio", "Field", "Field", {"Luxray"}},
{"Luxray", "Field", "Field", {}},
{"Cranidos", "Monster", "Monster", {"Rampardos"}},
{"Rampardos", "Monster", "Monster", {}},
{"Shieldon", "Monster", "Monster", {"Bastiodon"}},
{"Bastiodon", "Monster", "Monster", {}},
{"Burmy", "Bug", "Bug", {"Wormadam", "Mothim"}},
{"Wormadam", "Bug", "Bug", {}},
{"Mothim", "Bug", "Bug", {}},
{"Combee", "Bug", "Bug", {"Vespiquen"}},
{"Vespiquen", "Bug", "Bug", {}},
{"Pachirisu", "Field", "Fairy", {}},
{"Buizel", "Water 1", "Field", {"Floatzel"}},
{"Floatzel", "Water 1", "Field", {}},
{"Cherubi", "Fairy", "Grass", {"Cherrim"}},
{"Cherrim", "Fairy", "Grass", {}},
{"Shellos", "Water 1", "Amorphous", {"Gastrodon"}},
{"Gastrodon", "Water 1", "Amorphous", {}},
{"Drifloon", "Amorphous", "Amorphous", {"Drifblim"}},
{"Drifblim", "Amorphous", "Amorphous", {}},
{"Buneary", "Field", "Human-Like", {"Lopunny"}},
{"Lopunny", "Field", "Human-Like", {}},
{"Glameow", "Field", "Field", {"Purugly"}},
{"Purugly", "Field", "Field", {}},
{"Stunky", "Field", "Field", {"Skuntank"}},
{"Skuntank", "Field", "Field", {}},
{"Bronzor", "Mineral", "Mineral", {"Bronzong"}},
{"Bronzong", "Mineral", "Mineral", {}},
{"Chatot", "Flying", "Flying", {}},
{"Spiritomb", "Amorphous", "Amorphous", {}},
{"Gible", "Monster", "Dragon", {"Gabite"}},
{"Gabite", "Monster", "Dragon", {"Garchomp"}},
{"Garchomp", "Monster", "Dragon", {}},
{"Riolu", "No Eggs Discovered", "No Eggs Discovered", {"Lucario"}},
{"Lucario", "Field", "Human-Like", {}},
{"Hippopotas", "Field", "Field", {"Hippowdon"}},
{"Hippowdon", "Field", "Field", {}},
{"Skorupi", "Bug", "Water 3", {"Drapion"}},
{"Drapion", "Bug", "Water 3", {}},
{"Croagunk", "Human-Like", "Human-Like", {"Toxicroak"}},
{"Toxicroak", "Human-Like", "Human-Like", {}},
{"Carnivine", "Grass", "Grass", {}},
{"Finneon", "Water 2", "Water 2", {"Lumineon"}},
{"Lumineon", "Water 2", "Water 2", {}},
{"Snover", "Monster", "Grass", {"Abomasnow"}},
{"Abomasnow", "Monster", "Grass", {}},
{"Rotom", "Amorphous", "Amorphous", {}},
{"Uxie", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Mesprit", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Azelf", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Dialga", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Palkia", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Heatran", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Regigigas", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Giratina", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Cresselia", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Phione", "Water 1", "Fairy", {}},
{"Manaphy", "Water 1", "Fairy", {}},
{"Darkrai", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Shaymin", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Arceus", "No Eggs Discovered", "No Eggs Discovered", {}}
};