#ifndef DATA_GEN1
#define DATA_GEN1
#pragma once
#include "core.h"

extern Generation tGeneration1;
#endif
Generation tGeneration1 = {
GENERATION_1,
"====[[Generation I]]====",
//sBabyMons
{},
//sFemaleOnlyMons
{
"Nidoran F",
"Chansey",
"Kangaskhan",
"Jynx"
},
//sMaleOnlyMons
{
"Nidoran M",
"Nidorino",
"Nidoking",
"Hitmonlee",
"Hitmonchan",
"Tauros"
},
//sUniversalTMs
{
"Bide",
"Double Team",
"Rage",
"Rest",
"Toxic"
},
//sAllGroups
{
{"Bulbasaur", "Monster", "Grass", {"Ivysaur"}},
{"Ivysaur", "Monster", "Grass", {"Venusaur"}},
{"Venusaur", "Monster", "Grass", {}},
{"Charmander", "Monster", "Dragon", {"Charmeleon"}},
{"Charmeleon", "Monster", "Dragon", {"Charizard"}},
{"Charizard", "Monster", "Dragon", {}},
{"Squirtle", "Monster", "Water 1", {"Wartortle"}},
{"Wartortle", "Monster", "Water 1", {"Blastoise"}},
{"Blastoise", "Monster", "Water 1", {}},
{"Caterpie", "Bug", "Bug", {"Metapod"}},
{"Metapod", "Bug", "Bug", {"Butterfree"}},
{"Butterfree", "Bug", "Bug", {}},
{"Weedle", "Bug", "Bug", {"Kakuna"}},
{"Kakuna", "Bug", "Bug", {"Beedrill"}},
{"Beedrill", "Bug", "Bug", {}},
{"Pidgey", "Flying", "Flying", {"Pidgeotto"}},
{"Pidgeotto", "Flying", "Flying", {"Pidgeot"}},
{"Pidgeot", "Flying", "Flying", {}},
{"Rattata", "Field", "Field", {"Raticate"}},
{"Raticate", "Field", "Field", {}},
{"Spearow", "Flying", "Flying", {"Fearow"}},
{"Fearow", "Flying", "Flying", {}},
{"Ekans", "Field", "Dragon", {"Arbok"}},
{"Arbok", "Field", "Dragon", {}},
{"Pikachu", "Field", "Fairy", {"Raichu"}},
{"Raichu", "Field", "Fairy", {}},
{"Sandshrew", "Field", "Field", {"Sandslash"}},
{"Sandslash", "Field", "Field", {}},
{"Nidoran F", "Monster", "Field", {"Nidorina"}},
{"Nidorina", "No Eggs Discovered", "No Eggs Discovered", {"Nidoqueen"}},
{"Nidoqueen", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Nidoran M", "Monster", "Field", {"Nidorino"}},
{"Nidorino", "Monster", "Field", {"Nidoking"}},
{"Nidoking", "Monster", "Field", {}},
{"Clefairy", "Fairy", "Fairy", {"Clefable"}},
{"Clefable", "Fairy", "Fairy", {}},
{"Vulpix", "Field", "Field", {"Ninetales"}},
{"Ninetales", "Field", "Field", {}},
{"Jigglypuff", "Fairy", "Fairy", {"Wigglytuff"}},
{"Wigglytuff", "Fairy", "Fairy", {}},
{"Zubat", "Flying", "Flying", {"Golbat"}},
{"Golbat", "Flying", "Flying", {}},
{"Oddish", "Grass", "Grass", {"Gloom"}},
{"Gloom", "Grass", "Grass", {"Vileplume"}},
{"Vileplume", "Grass", "Grass", {}},
{"Paras", "Bug", "Grass", {"Parasect"}},
{"Parasect", "Bug", "Grass", {}},
{"Venonat", "Bug", "Bug", {"Venomoth"}},
{"Venomoth", "Bug", "Bug", {}},
{"Diglett", "Field", "Field", {"Dugtrio"}},
{"Dugtrio", "Field", "Field", {}},
{"Meowth", "Field", "Field", {"Persian"}},
{"Persian", "Field", "Field", {}},
{"Psyduck", "Water 1", "Field", {"Golduck"}},
{"Golduck", "Water 1", "Field", {}},
{"Mankey", "Field", "Field", {"Primeape"}},
{"Primeape", "Field", "Field", {}},
{"Growlithe", "Field", "Field", {"Arcanine"}},
{"Arcanine", "Field", "Field", {}},
{"Poliwag", "Water 1", "Water 1", {"Poliwhirl"}},
{"Poliwhirl", "Water 1", "Water 1", {"Poliwrath"}},
{"Poliwrath", "Water 1", "Water 1", {}},
{"Abra", "Human-Like", "Human-Like", {"Kadabra"}},
{"Kadabra", "Human-Like", "Human-Like", {"Alakazam"}},
{"Alakazam", "Human-Like", "Human-Like", {}},
{"Machop", "Human-Like", "Human-Like", {"Machoke"}},
{"Machoke", "Human-Like", "Human-Like", {"Machamp"}},
{"Machamp", "Human-Like", "Human-Like", {}},
{"Bellsprout", "Grass", "Grass", {"Weepinbell"}},
{"Weepinbell", "Grass", "Grass", {"Victreebel"}},
{"Victreebel", "Grass", "Grass", {}},
{"Tentacool", "Water 3", "Water 3", {"Tentacruel"}},
{"Tentacruel", "Water 3", "Water 3", {}},
{"Geodude", "Mineral", "Mineral", {"Graveler"}},
{"Graveler", "Mineral", "Mineral", {"Golem"}},
{"Golem", "Mineral", "Mineral", {}},
{"Ponyta", "Field", "Field", {"Rapidash"}},
{"Rapidash", "Field", "Field", {}},
{"Slowpoke", "Monster", "Water 1", {"Slowbro"}},
{"Slowbro", "Monster", "Water 1", {}},
{"Magnemite", "Mineral", "Mineral", {"Magneton"}},
{"Magneton", "Mineral", "Mineral", {}},
{"Farfetch'd", "Flying", "Field", {}},
{"Doduo", "Flying", "Flying", {"Dodrio"}},
{"Dodrio", "Flying", "Flying", {}},
{"Seel", "Water 1", "Field", {"Dewgong"}},
{"Dewgong", "Water 1", "Field", {}},
{"Grimer", "Amorphous", "Amorphous", {"Muk"}},
{"Muk", "Amorphous", "Amorphous", {}},
{"Shellder", "Water 3", "Water 3", {"Cloyster"}},
{"Cloyster", "Water 3", "Water 3", {}},
{"Gastly", "Amorphous", "Amorphous", {"Haunter"}},
{"Haunter", "Amorphous", "Amorphous", {"Gengar"}},
{"Gengar", "Amorphous", "Amorphous", {}},
{"Onix", "Mineral", "Mineral", {}},
{"Drowzee", "Human-Like", "Human-Like", {"Hypno"}},
{"Hypno", "Human-Like", "Human-Like", {}},
{"Krabby", "Water 3", "Water 3", {"Kingler"}},
{"Kingler", "Water 3", "Water 3", {}},
{"Voltorb", "Mineral", "Mineral", {"Electrode"}},
{"Electrode", "Mineral", "Mineral", {}},
{"Exeggcute", "Grass", "Grass", {"Exeggutor"}},
{"Exeggutor", "Grass", "Grass", {}},
{"Cubone", "Monster", "Monster", {"Marowak"}},
{"Marowak", "Monster", "Monster", {}},
{"Hitmonlee", "Human-Like", "Human-Like", {}},
{"Hitmonchan", "Human-Like", "Human-Like", {}},
{"Lickitung", "Monster", "Monster", {}},
{"Koffing", "Amorphous", "Amorphous", {"Weezing"}},
{"Weezing", "Amorphous", "Amorphous", {}},
{"Rhyhorn", "Monster", "Field", {"Rhydon"}},
{"Rhydon", "Monster", "Field", {}},
{"Chansey", "Fairy", "Fairy", {}},
{"Tangela", "Grass", "Grass", {}},
{"Kangaskhan", "Monster", "Monster", {}},
{"Horsea", "Water 1", "Dragon", {"Seadra"}},
{"Seadra", "Water 1", "Dragon", {}},
{"Goldeen", "Water 2", "Water 2", {"Seaking"}},
{"Seaking", "Water 2", "Water 2", {}},
{"Staryu", "Water 3", "Water 3", {"Starmie"}},
{"Starmie", "Water 3", "Water 3", {}},
{"Mr. Mime", "Human-Like", "Human-Like", {}},
{"Scyther", "Bug", "Bug", {}},
{"Jynx", "Human-Like", "Human-Like", {}},
{"Electabuzz", "Human-Like", "Human-Like", {}},
{"Magmar", "Human-Like", "Human-Like", {}},
{"Pinsir", "Bug", "Bug", {}},
{"Tauros", "Field", "Field", {}},
{"Magikarp", "Water 2", "Dragon", {"Gyarados"}},
{"Gyarados", "Water 2", "Dragon", {}},
{"Lapras", "Monster", "Water 1", {}},
{"Ditto", "Ditto", "Ditto", {}},
{"Eevee", "Field", "Field", {"Vaporeon", "Jolteon", "Flareon"}},
{"Vaporeon", "Field", "Field", {}},
{"Jolteon", "Field", "Field", {}},
{"Flareon", "Field", "Field", {}},
{"Porygon", "Mineral", "Mineral", {"Porygon2"}},
{"Omanyte", "Water 1", "Water 3", {"Omastar"}},
{"Omastar", "Water 1", "Water 3", {}},
{"Kabuto", "Water 1", "Water 3", {"Kabutops"}},
{"Kabutops", "Water 1", "Water 3", {}},
{"Aerodactyl", "Flying", "Flying", {}},
{"Snorlax", "Monster", "Monster", {}},
{"Articuno", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Zapdos", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Moltres", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Dratini", "Water 1", "Dragon", {"Dragonair"}},
{"Dragonair", "Water 1", "Dragon", {"Dragonite"}},
{"Dragonite", "Water 1", "Dragon", {}},
{"Mewtwo", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Mew", "No Eggs Discovered", "No Eggs Discovered", {}}
}
};