#ifndef DATA_GEN9
#define DATA_GEN9
#pragma once
#include "core.h"

extern Generation g_Generation9;
#endif
Generation g_Generation9 = {
"====[[Generation IX]]====",
GAME_SCARLET_VIOLET,
//UniversalTMs https://bulbapedia.bulbagarden.net/w/index.php?search=%22Every+Pok%C3%A9mon+can+learn+this+move+by%22&title=Special%3ASearch&go=Go
{
	"Endure",
	"Facade",
	"Protect",
	"Rest",
	"Sleep Talk",
	"Tera Blast"
},
//MonData https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_breeding_attributes https://bulbapedia.bulbagarden.net/wiki/List_of_cross-generational_evolutionary_lines
{
{"Bulbasaur", "Monster", "Grass", GR_TYPICAL, {"Ivysaur"}},
{"Ivysaur", "Monster", "Grass", GR_TYPICAL, {"Venusaur"}},
{"Venusaur", "Monster", "Grass", GR_TYPICAL, {}},
{"Charmander", "Monster", "Dragon", GR_TYPICAL, {"Charmeleon"}},
{"Charmeleon", "Monster", "Dragon", GR_TYPICAL, {"Charizard"}},
{"Charizard", "Monster", "Dragon", GR_TYPICAL, {}},
{"Squirtle", "Monster", "Water 1", GR_TYPICAL, {"Wartortle"}},
{"Wartortle", "Monster", "Water 1", GR_TYPICAL, {"Blastoise"}},
{"Blastoise", "Monster", "Water 1", GR_TYPICAL, {}},
{"Ekans", "Field", "Dragon", GR_TYPICAL, {"Arbok"}},
{"Arbok", "Field", "Dragon", GR_TYPICAL, {}},
{"Pichu", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Pikachu"}},
{"Pikachu", "Field", "Fairy", GR_TYPICAL, {"Raichu"}},
{"Raichu", "Field", "Fairy", GR_TYPICAL, {}},
{"Sandshrew", "Field", "Field", GR_TYPICAL, {"Sandslash"}},
{"Sandslash", "Field", "Field", GR_TYPICAL, {}},
{"Cleffa", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Clefairy"}},
{"Clefairy", "Fairy", "Fairy", GR_TYPICAL, {"Clefable"}},
{"Clefable", "Fairy", "Fairy", GR_TYPICAL, {}},
{"Vulpix", "Field", "Field", GR_TYPICAL, {"Ninetales"}},
{"Ninetales", "Field", "Field", GR_TYPICAL, {}},
{"Igglybuff", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Jigglypuff"}},
{"Jigglypuff", "Fairy", "Fairy", GR_TYPICAL, {"Wigglytuff"}},
{"Wigglytuff", "Fairy", "Fairy", GR_TYPICAL, {}},
{"Oddish", "Grass", "Grass", GR_TYPICAL, {"Gloom"}},
{"Gloom", "Grass", "Grass", GR_TYPICAL, {"Vileplume", "Bellossom"}},
{"Vileplume", "Grass", "Grass", GR_TYPICAL, {}},
{"Bellossom", "Grass", "Grass", GR_TYPICAL, {}},
{"Venonat", "Bug", "Bug", GR_TYPICAL, {"Venomoth"}},
{"Venomoth", "Bug", "Bug", GR_TYPICAL, {}},
{"Diglett", "Field", "Field", GR_TYPICAL, {"Dugtrio"}},
{"Dugtrio", "Field", "Field", GR_TYPICAL, {}},
{"Meowth", "Field", "Field", GR_TYPICAL, {"Persian"}},
{"Persian", "Field", "Field", GR_TYPICAL, {"Perrserker"}},
{"Perrserker", "Field", "Field", GR_TYPICAL, {}},
{"Psyduck", "Water 1", "Field", GR_TYPICAL, {"Golduck"}},
{"Golduck", "Water 1", "Field", GR_TYPICAL, {}},
{"Mankey", "Field", "Field", GR_TYPICAL, {"Primeape"}},
{"Primeape", "Field", "Field", GR_TYPICAL, {"Annihilape"}},
{"Annihilape", "Field", "Field", GR_TYPICAL, {}},
{"Growlithe", "Field", "Field", GR_TYPICAL, {"Arcanine"}},
{"Arcanine", "Field", "Field", GR_TYPICAL, {}},
{"Poliwag", "Water 1", "Water 1", GR_TYPICAL, {"Poliwhirl"}},
{"Poliwhirl", "Water 1", "Water 1", GR_TYPICAL, {"Poliwrath", "Politoed"}},
{"Poliwrath", "Water 1", "Water 1", GR_TYPICAL, {}},
{"Politoed", "Water 1", "Water 1", GR_TYPICAL, {}},
{"Bellsprout", "Grass", "Grass", GR_TYPICAL, {"Weepinbell"}},
{"Weepinbell", "Grass", "Grass", GR_TYPICAL, {"Victreebel"}},
{"Victreebel", "Grass", "Grass", GR_TYPICAL, {}},
{"Tentacool", "Water 3", "Water 3", GR_TYPICAL, {"Tentacruel"}},
{"Tentacruel", "Water 3", "Water 3", GR_TYPICAL, {}},
{"Geodude", "Mineral", "Mineral", GR_TYPICAL, {"Graveler"}},
{"Graveler", "Mineral", "Mineral", GR_TYPICAL, {"Golem"}},
{"Golem", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Slowpoke", "Monster", "Water 1", GR_TYPICAL, {"Slowbro", "Slowking"}},
{"Slowbro", "Monster", "Water 1", GR_TYPICAL, {}},
{"Slowking", "Monster", "Water 1", GR_TYPICAL, {}},
{"Magnemite", "Mineral", "Mineral", GR_UNKNOWN, {"Magneton"}},
{"Magneton", "Mineral", "Mineral", GR_UNKNOWN, {"Magnezone"}},
{"Magnezone", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Doduo", "Flying", "Flying", GR_TYPICAL, {"Dodrio"}},
{"Dodrio", "Flying", "Flying", GR_TYPICAL, {}},
{"Seel", "Water 1", "Field", GR_TYPICAL, {"Dewgong"}},
{"Dewgong", "Water 1", "Field", GR_TYPICAL, {}},
{"Grimer", "Amorphous", "Amorphous", GR_TYPICAL, {"Muk"}},
{"Muk", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Shellder", "Water 3", "Water 3", GR_TYPICAL, {"Cloyster"}},
{"Cloyster", "Water 3", "Water 3", GR_TYPICAL, {}},
{"Gastly", "Amorphous", "Amorphous", GR_TYPICAL, {"Haunter"}},
{"Haunter", "Amorphous", "Amorphous", GR_TYPICAL, {"Gengar"}},
{"Gengar", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Drowzee", "Human-Like", "Human-Like", GR_TYPICAL, {"Hypno"}},
{"Hypno", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Voltorb", "Mineral", "Mineral", GR_UNKNOWN, {"Electrode"}},
{"Electrode", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Exeggcute", "Grass", "Grass", GR_TYPICAL, {"Exeggutor"}},
{"Exeggutor", "Grass", "Grass", GR_TYPICAL, {}},
{"Tyrogue", "No Eggs Discovered", "No Eggs Discovered", GR_MALE_ONLY, {"Hitmonlee", "Hitmonchan", "Hitmontop"}},
{"Hitmonlee", "Human-Like", "Human-Like", GR_MALE_ONLY, {}},
{"Hitmonchan", "Human-Like", "Human-Like", GR_MALE_ONLY, {}},
{"Hitmontop", "Human-Like", "Human-Like", GR_MALE_ONLY, {}},
{"Koffing", "Amorphous", "Amorphous", GR_TYPICAL, {"Weezing"}},
{"Weezing", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Rhyhorn", "Monster", "Field", GR_TYPICAL, {"Rhydon"}},
{"Rhydon", "Monster", "Field", GR_TYPICAL, {"Rhyperior"}},
{"Rhyperior", "Monster", "Field", GR_TYPICAL, {}},
{"Happiny", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, {"Chansey"}},
{"Chansey", "Fairy", "Fairy", GR_FEMALE_ONLY, {"Blissey"}},
{"Blissey", "Fairy", "Fairy", GR_FEMALE_ONLY, {}},
{"Horsea", "Water 1", "Dragon", GR_TYPICAL, {"Seadra"}},
{"Seadra", "Water 1", "Dragon", GR_TYPICAL, {"Kingdra"}},
{"Kingdra", "Water 1", "Dragon", GR_TYPICAL, {}},
{"Scyther", "Bug", "Bug", GR_TYPICAL, {"Scizor", "Kleavor"}},
{"Scizor", "Bug", "Bug", GR_TYPICAL, {}},
{"Kleavor", "Bug", "Bug", GR_TYPICAL, {}},
{"Elekid", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Electabuzz"}},
{"Electabuzz", "Human-Like", "Human-Like", GR_TYPICAL, {"Electivire"}},
{"Electivire", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Magby", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Magmar"}},
{"Magmar", "Human-Like", "Human-Like", GR_TYPICAL, {"Magmortar"}},
{"Magmortar", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Tauros", "Field", "Field", GR_MALE_ONLY, {}},
{"Magikarp", "Water 2", "Dragon", GR_TYPICAL, {"Gyarados"}},
{"Gyarados", "Water 2", "Dragon", GR_TYPICAL, {}},
{"Lapras", "Monster", "Water 1", GR_TYPICAL, {}},
{"Ditto", "Ditto", "Ditto", GR_UNKNOWN, {}},
{"Eevee", "Field", "Field", GR_TYPICAL, {"Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon", "Leafeon", "Glaceon", "Sylveon"}},
{"Vaporeon", "Field", "Field", GR_TYPICAL, {}},
{"Jolteon", "Field", "Field", GR_TYPICAL, {}},
{"Flareon", "Field", "Field", GR_TYPICAL, {}},
{"Espeon", "Field", "Field", GR_TYPICAL, {}},
{"Umbreon", "Field", "Field", GR_TYPICAL, {}},
{"Leafeon", "Field", "Field", GR_TYPICAL, {}},
{"Glaceon", "Field", "Field", GR_TYPICAL, {}},
{"Sylveon", "Field", "Field", GR_TYPICAL, {}},
{"Porygon", "Mineral", "Mineral", GR_UNKNOWN, {"Porygon2"}},
{"Porygon2", "Mineral", "Mineral", GR_UNKNOWN, {"Porygon-Z"}},
{"Porygon-Z", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Munchlax", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Snorlax"}},
{"Snorlax", "Monster", "Monster", GR_TYPICAL, {}},
{"Articuno", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Zapdos", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Moltres", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Dratini", "Water 1", "Dragon", GR_TYPICAL, {"Dragonair"}},
{"Dragonair", "Water 1", "Dragon", GR_TYPICAL, {"Dragonite"}},
{"Dragonite", "Water 1", "Dragon", GR_TYPICAL, {}},
{"Mewtwo", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Mew", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Chikorita", "Monster", "Grass", GR_TYPICAL, {"Bayleef"}},
{"Bayleef", "Monster", "Grass", GR_TYPICAL, {"Meganium"}},
{"Meganium", "Monster", "Grass", GR_TYPICAL, {}},
{"Cyndaquil", "Field", "Field", GR_TYPICAL, {"Quilava"}},
{"Quilava", "Field", "Field", GR_TYPICAL, {"Typhlosion"}},
{"Typhlosion", "Field", "Field", GR_TYPICAL, {}},
{"Totodile", "Monster", "Water 1", GR_TYPICAL, {"Croconaw"}},
{"Croconaw", "Monster", "Water 1", GR_TYPICAL, {"Feraligatr"}},
{"Feraligatr", "Monster", "Water 1", GR_TYPICAL, {}},
{"Sentret", "Field", "Field", GR_TYPICAL, {"Furret"}},
{"Furret", "Field", "Field", GR_TYPICAL, {}},
{"Hoothoot", "Flying", "Flying", GR_TYPICAL, {"Noctowl"}},
{"Noctowl", "Flying", "Flying", GR_TYPICAL, {}},
{"Spinarak", "Bug", "Bug", GR_TYPICAL, {"Ariados"}},
{"Ariados", "Bug", "Bug", GR_TYPICAL, {}},
{"Chinchou", "Water 2", "Water 2", GR_TYPICAL, {"Lanturn"}},
{"Lanturn", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Mareep", "Monster", "Field", GR_TYPICAL, {"Flaaffy"}},
{"Flaaffy", "Monster", "Field", GR_TYPICAL, {"Ampharos"}},
{"Ampharos", "Monster", "Field", GR_TYPICAL, {}},
{"Azurill", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Marill"}},
{"Marill", "Water 1", "Fairy", GR_TYPICAL, {"Azumarill"}},
{"Azumarill", "Water 1", "Fairy", GR_TYPICAL, {}},
{"Bonsly", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Sudowoodo"}},
{"Sudowoodo", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Hoppip", "Fairy", "Grass", GR_TYPICAL, {"Skiploom"}},
{"Skiploom", "Fairy", "Grass", GR_TYPICAL, {"Jumpluff"}},
{"Jumpluff", "Fairy", "Grass", GR_TYPICAL, {}},
{"Aipom", "Field", "Field", GR_TYPICAL, {"Ambipom"}},
{"Ambipom", "Field", "Field", GR_TYPICAL, {}},
{"Sunkern", "Grass", "Grass", GR_TYPICAL, {"Sunflora"}},
{"Sunflora", "Grass", "Grass", GR_TYPICAL, {}},
{"Yanma", "Bug", "Bug", GR_TYPICAL, {"Yanmega"}},
{"Yanmega", "Bug", "Bug", GR_TYPICAL, {}},
{"Wooper", "Water 1", "Field", GR_TYPICAL, {"Quagsire", "Clodsire"}},
{"Quagsire", "Water 1", "Field", GR_TYPICAL, {}},
{"Clodsire", "Water 1", "Field", GR_TYPICAL, {}},
{"Murkrow", "Flying", "Flying", GR_TYPICAL, {"Honchkrow"}},
{"Honchkrow", "Flying", "Flying", GR_TYPICAL, {}},
{"Misdreavus", "Amorphous", "Amorphous", GR_TYPICAL, {"Mismagius"}},
{"Mismagius", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Girafarig", "Field", "Field", GR_TYPICAL, {"Farigiraf"}},
{"Farigiraf", "Field", "Field", GR_TYPICAL, {}},
{"Pineco", "Bug", "Bug", GR_TYPICAL, {"Forretress"}},
{"Forretress", "Bug", "Bug", GR_TYPICAL, {}},
{"Dunsparce", "Field", "Field", GR_TYPICAL, {"Dudunsparce"}},
{"Dudunsparce", "Field", "Field", GR_TYPICAL, {}},
{"Gligar", "Bug", "Bug", GR_TYPICAL, {"Gliscor"}},
{"Gliscor", "Bug", "Bug", GR_TYPICAL, {}},
{"Snubbull", "Field", "Fairy", GR_TYPICAL, {"Granbull"}},
{"Granbull", "Field", "Fairy", GR_TYPICAL, {}},
{"Qwilfish", "Water 2", "Water 2", GR_TYPICAL, {"Overqwil"}},
{"Overqwil", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Heracross", "Bug", "Bug", GR_TYPICAL, {}},
{"Sneasel", "Field", "Field", GR_TYPICAL, {"Weavile", "Sneasler"}},
{"Weavile", "Field", "Field", GR_TYPICAL, {}},
{"Sneasler", "Field", "Field", GR_TYPICAL, {}},
{"Teddiursa", "Field", "Field", GR_TYPICAL, {"Ursaring"}},
{"Ursaring", "Field", "Field", GR_TYPICAL, {"Ursaluna"}},
{"Ursaluna", "Field", "Field", GR_TYPICAL, {}},
{"Slugma", "Amorphous", "Amorphous", GR_TYPICAL, {"Magcargo"}},
{"Magcargo", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Swinub", "Field", "Field", GR_TYPICAL, {"Piloswine"}},
{"Piloswine", "Field", "Field", GR_TYPICAL, {"Mamoswine"}},
{"Mamoswine", "Field", "Field", GR_TYPICAL, {}},
{"Delibird", "Water 1", "Field", GR_TYPICAL, {}},
{"Skarmory", "Flying", "Flying", GR_TYPICAL, {}},
{"Houndour", "Field", "Field", GR_TYPICAL, {"Houndoom"}},
{"Houndoom", "Field", "Field", GR_TYPICAL, {}},
{"Phanpy", "Field", "Field", GR_TYPICAL, {"Donphan"}},
{"Donphan", "Field", "Field", GR_TYPICAL, {}},
{"Stantler", "Field", "Field", GR_TYPICAL, {"Wyrdeer"}},
{"Wyrdeer", "Field", "Field", GR_TYPICAL, {}},
{"Smeargle", "Field", "Field", GR_TYPICAL, {}},
{"Raikou", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Entei", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Suicune", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Larvitar", "Monster", "Monster", GR_TYPICAL, {"Pupitar"}},
{"Pupitar", "Monster", "Monster", GR_TYPICAL, {"Tyranitar"}},
{"Tyranitar", "Monster", "Monster", GR_TYPICAL, {}},
{"Lugia", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Ho-Oh", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Treecko", "Monster", "Dragon", GR_TYPICAL, {"Grovyle"}},
{"Grovyle", "Monster", "Dragon", GR_TYPICAL, {"Sceptile"}},
{"Sceptile", "Monster", "Dragon", GR_TYPICAL, {}},
{"Torchic", "Field", "Field", GR_TYPICAL, {"Combusken"}},
{"Combusken", "Field", "Field", GR_TYPICAL, {"Blaziken"}},
{"Blaziken", "Field", "Field", GR_TYPICAL, {}},
{"Mudkip", "Monster", "Water 1", GR_TYPICAL, {"Marshtomp"}},
{"Marshtomp", "Monster", "Water 1", GR_TYPICAL, {"Swampert"}},
{"Swampert", "Monster", "Water 1", GR_TYPICAL, {}},
{"Poochyena", "Field", "Field", GR_TYPICAL, {"Mightyena"}},
{"Mightyena", "Field", "Field", GR_TYPICAL, {}},
{"Lotad", "Water 1", "Grass", GR_TYPICAL, {"Lombre"}},
{"Lombre", "Water 1", "Grass", GR_TYPICAL, {"Ludicolo"}},
{"Ludicolo", "Water 1", "Grass", GR_TYPICAL, {}},
{"Seedot", "Field", "Grass", GR_TYPICAL, {"Nuzleaf"}},
{"Nuzleaf", "Field", "Grass", GR_TYPICAL, {"Shiftry"}},
{"Shiftry", "Field", "Grass", GR_TYPICAL, {}},
{"Wingull", "Water 1", "Flying", GR_TYPICAL, {"Pelipper"}},
{"Pelipper", "Water 1", "Flying", GR_TYPICAL, {}},
{"Ralts", "Human-Like", "Amorphous", GR_TYPICAL, {"Kirlia"}},
{"Kirlia", "Human-Like", "Amorphous", GR_MALE_ONLY, {"Gardevoir", "Gallade"}},
{"Gardevoir", "Human-Like", "Amorphous", GR_TYPICAL, {}},
{"Gallade", "Human-Like", "Amorphous", GR_MALE_ONLY, {}},
{"Surskit", "Water 1", "Bug", GR_TYPICAL, {"Masquerain"}},
{"Masquerain", "Water 1", "Bug", GR_TYPICAL, {}},
{"Shroomish", "Fairy", "Grass", GR_TYPICAL, {"Breloom"}},
{"Breloom", "Fairy", "Grass", GR_TYPICAL, {}},
{"Slakoth", "Field", "Field", GR_TYPICAL, {"Vigoroth"}},
{"Vigoroth", "Field", "Field", GR_TYPICAL, {"Slaking"}},
{"Slaking", "Field", "Field", GR_TYPICAL, {}},
{"Makuhita", "Human-Like", "Human-Like", GR_TYPICAL, {"Hariyama"}},
{"Hariyama", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Nosepass", "Mineral", "Mineral", GR_TYPICAL, {"Probopass"}},
{"Probopass", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Sableye", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Meditite", "Human-Like", "Human-Like", GR_TYPICAL, {"Medicham"}},
{"Medicham", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Plusle", "Fairy", "Fairy", GR_TYPICAL, {}},
{"Minun", "Fairy", "Fairy", GR_TYPICAL, {}},
{"Volbeat", "Bug", "Human-Like", GR_MALE_ONLY, {}},
{"Illumise", "Bug", "Human-Like", GR_FEMALE_ONLY, {}},
{"Gulpin", "Amorphous", "Amorphous", GR_TYPICAL, {"Swalot"}},
{"Swalot", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Numel", "Field", "Field", GR_TYPICAL, {"Camerupt"}},
{"Camerupt", "Field", "Field", GR_TYPICAL, {}},
{"Torkoal", "Field", "Field", GR_TYPICAL, {}},
{"Spoink", "Field", "Field", GR_TYPICAL, {"Grumpig"}},
{"Grumpig", "Field", "Field", GR_TYPICAL, {}},
{"Trapinch", "Bug", "Dragon", GR_TYPICAL, {"Vibrava"}},
{"Vibrava", "Bug", "Dragon", GR_TYPICAL, {"Flygon"}},
{"Flygon", "Bug", "Dragon", GR_TYPICAL, {}},
{"Cacnea", "Grass", "Human-Like", GR_TYPICAL, {"Cacturne"}},
{"Cacturne", "Grass", "Human-Like", GR_TYPICAL, {}},
{"Swablu", "Flying", "Dragon", GR_TYPICAL, {"Altaria"}},
{"Altaria", "Flying", "Dragon", GR_TYPICAL, {}},
{"Zangoose", "Field", "Field", GR_TYPICAL, {}},
{"Seviper", "Field", "Dragon", GR_TYPICAL, {}},
{"Barboach", "Water 2", "Water 2", GR_TYPICAL, {"Whiscash"}},
{"Whiscash", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Corphish", "Water 1", "Water 3", GR_TYPICAL, {"Crawdaunt"}},
{"Crawdaunt", "Water 1", "Water 3", GR_TYPICAL, {}},
{"Feebas", "Water 1", "Dragon", GR_TYPICAL, {"Milotic"}},
{"Milotic", "Water 1", "Dragon", GR_TYPICAL, {}},
{"Shuppet", "Amorphous", "Amorphous", GR_TYPICAL, {"Banette"}},
{"Banette", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Duskull", "Amorphous", "Amorphous", GR_TYPICAL, {"Dusclops"}},
{"Dusclops", "Amorphous", "Amorphous", GR_TYPICAL, {"Dusknoir"}},
{"Dusknoir", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Tropius", "Monster", "Grass", GR_TYPICAL, {}},
{"Chingling", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Chimecho"}},
{"Chimecho", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Snorunt", "Fairy", "Mineral", GR_FEMALE_ONLY, {"Glalie", "Froslass"}},
{"Glalie", "Fairy", "Mineral", GR_TYPICAL, {}},
{"Froslass", "Fairy", "Mineral", GR_FEMALE_ONLY, {}},
{"Luvdisc", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Bagon", "Dragon", "Dragon", GR_TYPICAL, {"Shelgon"}},
{"Shelgon", "Dragon", "Dragon", GR_TYPICAL, {"Salamence"}},
{"Salamence", "Dragon", "Dragon", GR_TYPICAL, {}},
{"Beldum", "Mineral", "Mineral", GR_UNKNOWN, {"Metang"}},
{"Metang", "Mineral", "Mineral", GR_UNKNOWN, {"Metagross"}},
{"Metagross", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Regirock", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Regice", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Registeel", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Latias", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, {}},
{"Latios", "No Eggs Discovered", "No Eggs Discovered", GR_MALE_ONLY, {}},
{"Kyogre", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Groudon", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Rayquaza", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Jirachi", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Deoxys", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Turtwig", "Monster", "Grass", GR_TYPICAL, {"Grotle"}},
{"Grotle", "Monster", "Grass", GR_TYPICAL, {"Torterra"}},
{"Torterra", "Monster", "Grass", GR_TYPICAL, {}},
{"Chimchar", "Field", "Human-Like", GR_TYPICAL, {"Monferno"}},
{"Monferno", "Field", "Human-Like", GR_TYPICAL, {"Infernape"}},
{"Infernape", "Field", "Human-Like", GR_TYPICAL, {}},
{"Piplup", "Water 1", "Field", GR_TYPICAL, {"Prinplup"}},
{"Prinplup", "Water 1", "Field", GR_TYPICAL, {"Empoleon"}},
{"Empoleon", "Water 1", "Field", GR_TYPICAL, {}},
{"Starly", "Flying", "Flying", GR_TYPICAL, {"Staravia"}},
{"Staravia", "Flying", "Flying", GR_TYPICAL, {"Staraptor"}},
{"Staraptor", "Flying", "Flying", GR_TYPICAL, {}},
{"Kricketot", "Bug", "Bug", GR_TYPICAL, {"Kricketune"}},
{"Kricketune", "Bug", "Bug", GR_TYPICAL, {}},
{"Shinx", "Field", "Field", GR_TYPICAL, {"Luxio"}},
{"Luxio", "Field", "Field", GR_TYPICAL, {"Luxray"}},
{"Luxray", "Field", "Field", GR_TYPICAL, {}},
{"Cranidos", "Monster", "Monster", GR_TYPICAL, {"Rampardos"}},
{"Rampardos", "Monster", "Monster", GR_TYPICAL, {}},
{"Shieldon", "Monster", "Monster", GR_TYPICAL, {"Bastiodon"}},
{"Bastiodon", "Monster", "Monster", GR_TYPICAL, {}},
{"Combee", "Bug", "Bug", GR_FEMALE_ONLY, {"Vespiquen"}},
{"Vespiquen", "Bug", "Bug", GR_FEMALE_ONLY, {}},
{"Pachirisu", "Field", "Fairy", GR_TYPICAL, {}},
{"Buizel", "Water 1", "Field", GR_TYPICAL, {"Floatzel"}},
{"Floatzel", "Water 1", "Field", GR_TYPICAL, {}},
{"Shellos", "Water 1", "Amorphous", GR_TYPICAL, {"Gastrodon"}},
{"Gastrodon", "Water 1", "Amorphous", GR_TYPICAL, {}},
{"Drifloon", "Amorphous", "Amorphous", GR_TYPICAL, {"Drifblim"}},
{"Drifblim", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Stunky", "Field", "Field", GR_TYPICAL, {"Skuntank"}},
{"Skuntank", "Field", "Field", GR_TYPICAL, {}},
{"Bronzor", "Mineral", "Mineral", GR_UNKNOWN, {"Bronzong"}},
{"Bronzong", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Spiritomb", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Gible", "Monster", "Dragon", GR_TYPICAL, {"Gabite"}},
{"Gabite", "Monster", "Dragon", GR_TYPICAL, {"Garchomp"}},
{"Garchomp", "Monster", "Dragon", GR_TYPICAL, {}},
{"Riolu", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Lucario"}},
{"Lucario", "Field", "Human-Like", GR_TYPICAL, {}},
{"Hippopotas", "Field", "Field", GR_TYPICAL, {"Hippowdon"}},
{"Hippowdon", "Field", "Field", GR_TYPICAL, {}},
{"Croagunk", "Human-Like", "Human-Like", GR_TYPICAL, {"Toxicroak"}},
{"Toxicroak", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Finneon", "Water 2", "Water 2", GR_TYPICAL, {"Lumineon"}},
{"Lumineon", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Snover", "Monster", "Grass", GR_TYPICAL, {"Abomasnow"}},
{"Abomasnow", "Monster", "Grass", GR_TYPICAL, {}},
{"Rotom", "Amorphous", "Amorphous", GR_UNKNOWN, {}},
{"Uxie", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Mesprit", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Azelf", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Dialga", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Palkia", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Heatran", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {}},
{"Regigigas", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Giratina", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Cresselia", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, {}},
{"Phione", "Water 1", "Fairy", GR_UNKNOWN, {}},
{"Manaphy", "Water 1", "Fairy", GR_UNKNOWN, {}},
{"Darkrai", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Shaymin", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Arceus", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Snivy", "Field", "Grass", GR_TYPICAL, {"Servine"}},
{"Servine", "Field", "Grass", GR_TYPICAL, {"Serperior"}},
{"Serperior", "Field", "Grass", GR_TYPICAL, {}},
{"Tepig", "Field", "Field", GR_TYPICAL, {"Pignite"}},
{"Pignite", "Field", "Field", GR_TYPICAL, {"Emboar"}},
{"Emboar", "Field", "Field", GR_TYPICAL, {}},
{"Oshawott", "Field", "Field", GR_TYPICAL, {"Dewott"}},
{"Dewott", "Field", "Field", GR_TYPICAL, {"Samurott"}},
{"Samurott", "Field", "Field", GR_TYPICAL, {}},
{"Blitzle", "Field", "Field", GR_TYPICAL, {"Zebstrika"}},
{"Zebstrika", "Field", "Field", GR_TYPICAL, {}},
{"Drilbur", "Field", "Field", GR_TYPICAL, {"Excadrill"}},
{"Excadrill", "Field", "Field", GR_TYPICAL, {}},
{"Timburr", "Human-Like", "Human-Like", GR_TYPICAL, {"Gurdurr"}},
{"Gurdurr", "Human-Like", "Human-Like", GR_TYPICAL, {"Conkeldurr"}},
{"Conkeldurr", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Sewaddle", "Bug", "Bug", GR_TYPICAL, {"Swadloon"}},
{"Swadloon", "Bug", "Bug", GR_TYPICAL, {"Leavanny"}},
{"Leavanny", "Bug", "Bug", GR_TYPICAL, {}},
{"Cottonee", "Grass", "Fairy", GR_TYPICAL, {"Whimsicott"}},
{"Whimsicott", "Grass", "Fairy", GR_TYPICAL, {}},
{"Petilil", "Grass", "Grass", GR_FEMALE_ONLY, {"Lilligant"}},
{"Lilligant", "Grass", "Grass", GR_FEMALE_ONLY, {}},
{"Basculin", "Water 2", "Water 2", GR_TYPICAL, {"Basculegion"}},
{"Basculegion", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Sandile", "Field", "Field", GR_TYPICAL, {"Krokorok"}},
{"Krokorok", "Field", "Field", GR_TYPICAL, {"Krookodile"}},
{"Krookodile", "Field", "Field", GR_TYPICAL, {}},
{"Scraggy", "Field", "Dragon", GR_TYPICAL, {"Scrafty"}},
{"Scrafty", "Field", "Dragon", GR_TYPICAL, {}},
{"Zorua", "Field", "Field", GR_TYPICAL, {"Zoroark"}},
{"Zoroark", "Field", "Field", GR_TYPICAL, {}},
{"Minccino", "Field", "Field", GR_TYPICAL, {"Cinccino"}},
{"Cinccino", "Field", "Field", GR_TYPICAL, {}},
{"Gothita", "Human-Like", "Human-Like", GR_TYPICAL, {"Gothorita"}},
{"Gothorita", "Human-Like", "Human-Like", GR_TYPICAL, {"Gothitelle"}},
{"Gothitelle", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Solosis", "Amorphous", "Amorphous", GR_TYPICAL, {"Duosion"}},
{"Duosion", "Amorphous", "Amorphous", GR_TYPICAL, {"Reuniclus"}},
{"Reuniclus", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Ducklett", "Water 1", "Flying", GR_TYPICAL, {"Swanna"}},
{"Swanna", "Water 1", "Flying", GR_TYPICAL, {}},
{"Deerling", "Field", "Field", GR_TYPICAL, {"Sawsbuck"}},
{"Sawsbuck", "Field", "Field", GR_TYPICAL, {}},
{"Foongus", "Grass", "Grass", GR_TYPICAL, {"Amoonguss"}},
{"Amoonguss", "Grass", "Grass", GR_TYPICAL, {}},
{"Alomomola", "Water 1", "Water 2", GR_TYPICAL, {}},
{"Joltik", "Bug", "Bug", GR_TYPICAL, {"Galvantula"}},
{"Galvantula", "Bug", "Bug", GR_TYPICAL, {}},
{"Tynamo", "Amorphous", "Amorphous", GR_TYPICAL, {"Eelektrik"}},
{"Eelektrik", "Amorphous", "Amorphous", GR_TYPICAL, {"Eelektross"}},
{"Eelektross", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Litwick", "Amorphous", "Amorphous", GR_TYPICAL, {"Lampent"}},
{"Lampent", "Amorphous", "Amorphous", GR_TYPICAL, {"Chandelure"}},
{"Chandelure", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Axew", "Monster", "Dragon", GR_TYPICAL, {"Fraxure"}},
{"Fraxure", "Monster", "Dragon", GR_TYPICAL, {"Haxorus"}},
{"Haxorus", "Monster", "Dragon", GR_TYPICAL, {}},
{"Cubchoo", "Field", "Field", GR_TYPICAL, {"Beartic"}},
{"Beartic", "Field", "Field", GR_TYPICAL, {}},
{"Cryogonal", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Mienfoo", "Field", "Human-Like", GR_TYPICAL, {"Mienshao"}},
{"Mienshao", "Field", "Human-Like", GR_TYPICAL, {}},
{"Golett", "Mineral", "Mineral", GR_UNKNOWN, {"Golurk"}},
{"Golurk", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Pawniard", "Human-Like", "Human-Like", GR_TYPICAL, {"Bisharp"}},
{"Bisharp", "Human-Like", "Human-Like", GR_TYPICAL, {"Kingambit"}},
{"Kingambit", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Rufflet", "Flying", "Flying", GR_MALE_ONLY, {"Braviary"}},
{"Braviary", "Flying", "Flying", GR_MALE_ONLY, {}},
{"Vullaby", "Flying", "Flying", GR_FEMALE_ONLY, {"Mandibuzz"}},
{"Mandibuzz", "Flying", "Flying", GR_FEMALE_ONLY, {}},
{"Deino", "Dragon", "Dragon", GR_TYPICAL, {"Zweilous"}},
{"Zweilous", "Dragon", "Dragon", GR_TYPICAL, {"Hydreigon"}},
{"Hydreigon", "Dragon", "Dragon", GR_TYPICAL, {}},
{"Larvesta", "Bug", "Bug", GR_TYPICAL, {"Volcarona"}},
{"Volcarona", "Bug", "Bug", GR_TYPICAL, {}},
{"Cobalion", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Terrakion", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Virizion", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Tornadus", "No Eggs Discovered", "No Eggs Discovered", GR_MALE_ONLY, {}},
{"Thundurus", "No Eggs Discovered", "No Eggs Discovered", GR_MALE_ONLY, {}},
{"Reshiram", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Zekrom", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Landorus", "No Eggs Discovered", "No Eggs Discovered", GR_MALE_ONLY, {}},
{"Kyurem", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Keldeo", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Meloetta", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Chespin", "Field", "Field", GR_TYPICAL, {"Quilladin"}},
{"Quilladin", "Field", "Field", GR_TYPICAL, {"Chesnaught"}},
{"Chesnaught", "Field", "Field", GR_TYPICAL, {}},
{"Fennekin", "Field", "Field", GR_TYPICAL, {"Braixen"}},
{"Braixen", "Field", "Field", GR_TYPICAL, {"Delphox"}},
{"Delphox", "Field", "Field", GR_TYPICAL, {}},
{"Froakie", "Water 1", "Water 1", GR_TYPICAL, {"Frogadier"}},
{"Frogadier", "Water 1", "Water 1", GR_TYPICAL, {"Greninja"}},
{"Greninja", "Water 1", "Water 1", GR_TYPICAL, {}},
{"Fletchling", "Flying", "Flying", GR_TYPICAL, {"Fletchinder"}},
{"Fletchinder", "Flying", "Flying", GR_TYPICAL, {"Talonflame"}},
{"Talonflame", "Flying", "Flying", GR_TYPICAL, {}},
{"Scatterbug", "Bug", "Bug", GR_TYPICAL, {"Spewpa"}},
{"Spewpa", "Bug", "Bug", GR_TYPICAL, {"Vivillon"}},
{"Vivillon", "Bug", "Bug", GR_TYPICAL, {}},
{"Litleo", "Field", "Field", GR_TYPICAL, {"Pyroar"}},
{"Pyroar", "Field", "Field", GR_TYPICAL, {}},
{"Flabebe", "Fairy", "Fairy", GR_FEMALE_ONLY, {"Floette"}},
{"Floette", "Fairy", "Fairy", GR_FEMALE_ONLY, {"Florges"}},
{"Florges", "Fairy", "Fairy", GR_FEMALE_ONLY, {}},
{"Skiddo", "Field", "Field", GR_TYPICAL, {"Gogoat"}},
{"Gogoat", "Field", "Field", GR_TYPICAL, {}},
{"Espurr", "Field", "Field", GR_TYPICAL, {"Meowstic"}},
{"Meowstic", "Field", "Field", GR_TYPICAL, {}},
{"Inkay", "Water 1", "Water 2", GR_TYPICAL, {"Malamar"}},
{"Malamar", "Water 1", "Water 2", GR_TYPICAL, {}},
{"Skrelp", "Water 1", "Dragon", GR_TYPICAL, {"Dragalge"}},
{"Dragalge", "Water 1", "Dragon", GR_TYPICAL, {}},
{"Clauncher", "Water 1", "Water 3", GR_TYPICAL, {"Clawitzer"}},
{"Clawitzer", "Water 1", "Water 3", GR_TYPICAL, {}},
{"Hawlucha", "Flying", "Human-Like", GR_TYPICAL, {}},
{"Dedenne", "Field", "Fairy", GR_TYPICAL, {}},
{"Carbink", "Fairy", "Mineral", GR_UNKNOWN, {}},
{"Goomy", "Dragon", "Dragon", GR_TYPICAL, {"Sliggoo"}},
{"Sliggoo", "Dragon", "Dragon", GR_TYPICAL, {"Goodra"}},
{"Goodra", "Dragon", "Dragon", GR_TYPICAL, {}},
{"Klefki", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Phantump", "Grass", "Amorphous", GR_TYPICAL, {"Trevenant"}},
{"Trevenant", "Grass", "Amorphous", GR_TYPICAL, {}},
{"Bergmite", "Monster", "Mineral", GR_TYPICAL, {"Avalugg"}},
{"Avalugg", "Monster", "Mineral", GR_TYPICAL, {}},
{"Noibat", "Flying", "Dragon", GR_TYPICAL, {"Noivern"}},
{"Noivern", "Flying", "Dragon", GR_TYPICAL, {}},
{"Diancie", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Hoopa", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Volcanion", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Rowlet", "Flying", "Flying", GR_TYPICAL, {"Dartrix"}},
{"Dartrix", "Flying", "Flying", GR_TYPICAL, {"Decidueye"}},
{"Decidueye", "Flying", "Flying", GR_TYPICAL, {}},
{"Litten", "Field", "Field", GR_TYPICAL, {"Torracat"}},
{"Torracat", "Field", "Field", GR_TYPICAL, {"Incineroar"}},
{"Incineroar", "Field", "Field", GR_TYPICAL, {}},
{"Popplio", "Water 1", "Field", GR_TYPICAL, {"Brionne"}},
{"Brionne", "Water 1", "Field", GR_TYPICAL, {"Primarina"}},
{"Primarina", "Water 1", "Field", GR_TYPICAL, {}},
{"Pikipek", "Flying", "Flying", GR_TYPICAL, {"Trumbeak"}},
{"Trumbeak", "Flying", "Flying", GR_TYPICAL, {"Toucannon"}},
{"Toucannon", "Flying", "Flying", GR_TYPICAL, {}},
{"Yungoos", "Field", "Field", GR_TYPICAL, {"Gumshoos"}},
{"Gumshoos", "Field", "Field", GR_TYPICAL, {}},
{"Grubbin", "Bug", "Bug", GR_TYPICAL, {"Charjabug"}},
{"Charjabug", "Bug", "Bug", GR_TYPICAL, {"Vikavolt"}},
{"Vikavolt", "Bug", "Bug", GR_TYPICAL, {}},
{"Crabrawler", "Water 3", "Water 3", GR_TYPICAL, {"Crabominable"}},
{"Crabominable", "Water 3", "Water 3", GR_TYPICAL, {}},
{"Oricorio", "Flying", "Flying", GR_TYPICAL, {}},
{"Cutiefly", "Bug", "Fairy", GR_TYPICAL, {"Ribombee"}},
{"Ribombee", "Bug", "Fairy", GR_TYPICAL, {}},
{"Rockruff", "Field", "Field", GR_TYPICAL, {"Lycanroc"}},
{"Lycanroc", "Field", "Field", GR_TYPICAL, {}},
{"Mareanie", "Water 1", "Water 1", GR_TYPICAL, {"Toxapex"}},
{"Toxapex", "Water 1", "Water 1", GR_TYPICAL, {}},
{"Mudbray", "Field", "Field", GR_TYPICAL, {"Mudsdale"}},
{"Mudsdale", "Field", "Field", GR_TYPICAL, {}},
{"Dewpider", "Water 1", "Bug", GR_TYPICAL, {"Araquanid"}},
{"Araquanid", "Water 1", "Bug", GR_TYPICAL, {}},
{"Fomantis", "Grass", "Grass", GR_TYPICAL, {"Lurantis"}},
{"Lurantis", "Grass", "Grass", GR_TYPICAL, {}},
{"Salandit", "Monster", "Dragon", GR_FEMALE_ONLY, {"Salazzle"}},
{"Salazzle", "Monster", "Dragon", GR_FEMALE_ONLY, {}},
{"Bounsweet", "Grass", "Grass", GR_FEMALE_ONLY, {"Steenee"}},
{"Steenee", "Grass", "Grass", GR_FEMALE_ONLY, {"Tsareena"}},
{"Tsareena", "Grass", "Grass", GR_FEMALE_ONLY, {}},
{"Comfey", "Grass", "Grass", GR_TYPICAL, {}},
{"Oranguru", "Field", "Field", GR_TYPICAL, {"Passimian"}},
{"Passimian", "Field", "Field", GR_TYPICAL, {}},
{"Sandygast", "Amorphous", "Amorphous", GR_TYPICAL, {"Palossand"}},
{"Palossand", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Minior", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Komala", "Field", "Field", GR_TYPICAL, {}},
{"Mimikyu", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Bruxish", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Jangmo-o", "Dragon", "Dragon", GR_TYPICAL, {"Hakamo-o"}},
{"Hakamo-o", "Dragon", "Dragon", GR_TYPICAL, {"Kommo-o"}},
{"Kommo-o", "Dragon", "Dragon", GR_TYPICAL, {}},
{"Cosmog", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {"Cosmoem"}},
{"Cosmoem", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {"Solgaleo", "Lunala"}},
{"Solgaleo", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Lunala", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Necrozma", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Magearna", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Grookey", "Field", "Grass", GR_TYPICAL, {"Thwackey"}},
{"Thwackey", "Field", "Grass", GR_TYPICAL, {"Rillaboom"}},
{"Rillaboom", "Field", "Grass", GR_TYPICAL, {}},
{"Scorbunny", "Field", "Human-Like", GR_TYPICAL, {}},
{"Raboot", "Field", "Human-Like", GR_TYPICAL, {"Cinderace"}},
{"Cinderace", "Field", "Human-Like", GR_TYPICAL, {"Sobble"}},
{"Sobble", "Water 1", "Field", GR_TYPICAL, {"Drizzile"}},
{"Drizzile", "Water 1", "Field", GR_TYPICAL, {"Inteleon"}},
{"Inteleon", "Water 1", "Field", GR_TYPICAL, {}},
{"Skwovet", "Field", "Field", GR_TYPICAL, {"Greedent"}},
{"Greedent", "Field", "Field", GR_TYPICAL, {}},
{"Rookidee", "Flying", "Flying", GR_TYPICAL, {"Corvisquire"}},
{"Corvisquire", "Flying", "Flying", GR_TYPICAL, {"Corviknight"}},
{"Corviknight", "Flying", "Flying", GR_TYPICAL, {}},
{"Chewtle", "Monster", "Water 1", GR_TYPICAL, {"Drednaw"}},
{"Drednaw", "Monster", "Water 1", GR_TYPICAL, {}},
{"Rolycoly", "Mineral", "Mineral", GR_TYPICAL, {"Carkol"}},
{"Carkol", "Mineral", "Mineral", GR_TYPICAL, {"Coalossal"}},
{"Coalossal", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Applin", "Grass", "Dragon", GR_TYPICAL, {"Flapple", "Appletun", "Dipplin"}},
{"Flapple", "Grass", "Dragon", GR_TYPICAL, {}},
{"Appletun", "Grass", "Dragon", GR_TYPICAL, {}},
{"Dipplin", "Grass", "Dragon", GR_TYPICAL, {"Hydrapple"}},
{"Hydrapple", "Grass", "Dragon", GR_TYPICAL, {}},
{"Silicobra", "Field", "Dragon", GR_TYPICAL, {"Sandaconda"}},
{"Sandaconda", "Field", "Dragon", GR_TYPICAL, {}},
{"Cramorant", "Water 1", "Flying", GR_TYPICAL, {}},
{"Arrokuda", "Water 2", "Water 2", GR_TYPICAL, {"Barraskewda"}},
{"Barraskewda", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Toxel", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Toxtricity"}},
{"Toxtricity", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Sinistea", "Mineral", "Amorphous", GR_UNKNOWN, {"Polteageist"}},
{"Polteageist", "Mineral", "Amorphous", GR_UNKNOWN, {}},
{"Hatenna", "Fairy", "Fairy", GR_FEMALE_ONLY, {"Hattrem"}},
{"Hattrem", "Fairy", "Fairy", GR_FEMALE_ONLY, {"Hatterene"}},
{"Hatterene", "Fairy", "Fairy", GR_FEMALE_ONLY, {}},
{"Impidimp", "Fairy", "Human-Like", GR_MALE_ONLY, {"Morgrem"}},
{"Morgrem", "Fairy", "Human-Like", GR_MALE_ONLY, {"Grimmsnarl"}},
{"Grimmsnarl", "Fairy", "Human-Like", GR_MALE_ONLY, {}},
{"Milcery", "Fairy", "Amorphous", GR_FEMALE_ONLY, {"Alcremie"}},
{"Alcremie", "Fairy", "Amorphous", GR_FEMALE_ONLY, {}},
{"Falinks", "Fairy", "Mineral", GR_UNKNOWN, {}},
{"Pincurchin", "Water 1", "Amorphous", GR_TYPICAL, {}},
{"Snom", "Bug", "Bug", GR_TYPICAL, {"Frosmoth"}},
{"Frosmoth", "Bug", "Bug", GR_TYPICAL, {}},
{"Stonjourner", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Eiscue", "Water 1", "Field", GR_TYPICAL, {}},
{"Indeedee", "Fairy", "Fairy", GR_TYPICAL, {}},
{"Morpeko", "Field", "Fairy", GR_TYPICAL, {}},
{"Cufant", "Field", "Mineral", GR_TYPICAL, {"Copperajah"}},
{"Copperajah", "Field", "Mineral", GR_TYPICAL, {}},
{"Duraludon", "Mineral", "Dragon", GR_TYPICAL, {"Archaludon"}},
{"Archaludon", "Mineral", "Dragon", GR_TYPICAL, {}},
{"Dreepy", "Amorphous", "Dragon", GR_TYPICAL, {"Drakloak"}},
{"Drakloak", "Amorphous", "Dragon", GR_TYPICAL, {"Dragapult"}},
{"Dragapult", "Amorphous", "Dragon", GR_TYPICAL, {}},
{"Zacian", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Zamazenta", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Eternatus", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Kubfu", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Urshifu"}},
{"Urshifu", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {}},
{"Zarude", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Regieleki", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Regidrago", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Glastrier", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Spectrier", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Calyrex", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Enamorus", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, {}},
{"Sprigatito", "Field", "Grass", GR_TYPICAL, {"Floragato"}},
{"Floragato", "Field", "Grass", GR_TYPICAL, {"Meowscarada"}},
{"Meowscarada", "Field", "Grass", GR_TYPICAL, {}},
{"Fuecoco", "Field", "Field", GR_TYPICAL, {"Crocalor"}},
{"Crocalor", "Field", "Field", GR_TYPICAL, {"Skeledirge"}},
{"Skeledirge", "Field", "Field", GR_TYPICAL, {}},
{"Quaxly", "Flying", "Water 1", GR_TYPICAL, {"Quaxwell"}},
{"Quaxwell", "Flying", "Water 1", GR_TYPICAL, {"Quaquaval"}},
{"Quaquaval", "Flying", "Water 1", GR_TYPICAL, {}},
{"Lechonk", "Field", "Field", GR_TYPICAL, {"Oinkologne"}},
{"Oinkologne", "Field", "Field", GR_TYPICAL, {}},
{"Tarountula", "Bug", "Bug", GR_TYPICAL, {"Spidops"}},
{"Spidops", "Bug", "Bug", GR_TYPICAL, {}},
{"Nymble", "Bug", "Bug", GR_TYPICAL, {"Lokix"}},
{"Lokix", "Bug", "Bug", GR_TYPICAL, {}},
{"Pawmi", "Field", "Field", GR_TYPICAL, {"Pawmo"}},
{"Pawmo", "Field", "Field", GR_TYPICAL, {"Pawmot"}},
{"Pawmot", "Field", "Field", GR_TYPICAL, {}},
{"Tandemaus", "Field", "Fairy", GR_UNKNOWN, {"Maushold"}},
{"Maushold", "Field", "Fairy", GR_UNKNOWN, {}},
{"Fidough", "Field", "Mineral", GR_TYPICAL, {"Dachsbun"}},
{"Dachsbun", "Field", "Mineral", GR_TYPICAL, {}},
{"Smoliv", "Grass", "Grass", GR_TYPICAL, {"Dolliv"}},
{"Dolliv", "Grass", "Grass", GR_TYPICAL, {"Arboliva"}},
{"Arboliva", "Grass", "Grass", GR_TYPICAL, {}},
{"Squawkabilly", "Flying", "Flying", GR_TYPICAL, {}},
{"Nacli", "Mineral", "Mineral", GR_TYPICAL, {"Naclstack"}},
{"Naclstack", "Mineral", "Mineral", GR_TYPICAL, {"Garganacl"}},
{"Garganacl", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Charcadet", "Human-Like", "Human-Like", GR_TYPICAL, {"Armarouge", "Ceruledge"}},
{"Armarouge", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Ceruledge", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Tadbulb", "Water 1", "Water 1", GR_TYPICAL, {"Bellibolt"}},
{"Bellibolt", "Water 1", "Water 1", GR_TYPICAL, {}},
{"Wattrel", "Water 1", "Flying", GR_TYPICAL, {"Kilowattrel"}},
{"Kilowattrel", "Water 1", "Flying", GR_TYPICAL, {}},
{"Maschiff", "Field", "Field", GR_TYPICAL, {"Mabosstiff"}},
{"Mabosstiff", "Field", "Field", GR_TYPICAL, {}},
{"Shroodle", "Field", "Field", GR_TYPICAL, {"Grafaiai"}},
{"Grafaiai", "Field", "Field", GR_TYPICAL, {}},
{"Bramblin", "Grass", "Grass", GR_TYPICAL, {"Brambleghast"}},
{"Brambleghast", "Grass", "Grass", GR_TYPICAL, {}},
{"Toedscool", "Grass", "Grass", GR_TYPICAL, {"Toedscruel"}},
{"Toedscruel", "Grass", "Grass", GR_TYPICAL, {}},
{"Klawf", "Water 3", "Water 3", GR_TYPICAL, {}},
{"Capsakid", "Grass", "Grass", GR_TYPICAL, {"Scovillain"}},
{"Scovillain", "Grass", "Grass", GR_TYPICAL, {}},
{"Rellor", "Bug", "Bug", GR_TYPICAL, {"Rabsca"}},
{"Rabsca", "Bug", "Bug", GR_TYPICAL, {}},
{"Flittle", "Flying", "Flying", GR_TYPICAL, {"Espathra"}},
{"Espathra", "Flying", "Flying", GR_TYPICAL, {}},
{"Tinkatink", "Fairy", "Fairy", GR_FEMALE_ONLY, {"Tinkatuff"}},
{"Tinkatuff", "Fairy", "Fairy", GR_FEMALE_ONLY, {"Tinkaton"}},
{"Tinkaton", "Fairy", "Fairy", GR_FEMALE_ONLY, {}},
{"Wiglett", "Water 3", "Water 3", GR_TYPICAL, {"Wugtrio"}},
{"Wugtrio", "Water 3", "Water 3", GR_TYPICAL, {}},
{"Bombirdier", "Flying", "Flying", GR_TYPICAL, {}},
{"Finizen", "Field", "Water 2", GR_TYPICAL, {"Palafin"}},
{"Palafin", "Field", "Water 2", GR_TYPICAL, {}},
{"Varoom", "Mineral", "Mineral", GR_TYPICAL, {"Revavroom"}},
{"Revavroom", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Cyclizar", "Field", "Field", GR_TYPICAL, {}},
{"Orthworm", "Field", "Field", GR_TYPICAL, {}},
{"Glimmet", "Mineral", "Mineral", GR_TYPICAL, {"Glimmora"}},
{"Glimmora", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Greavard", "Field", "Field", GR_TYPICAL, {"Houndstone"}},
{"Houndstone", "Field", "Field", GR_TYPICAL, {}},
{"Flamigo", "Flying", "Flying", GR_TYPICAL, {}},
{"Cetoddle", "Field", "Field", GR_TYPICAL, {"Cetitan"}},
{"Cetitan", "Field", "Field", GR_TYPICAL, {}},
{"Veluza", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Dondozo", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Tatsugiri", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Great Tusk", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Scream Tail", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Brute Bonnet", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Flutter Mane", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Slither Wing", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Sandy Shocks", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Iron Treads", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Iron Bundle", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Iron Hands", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Iron Jugulis", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Iron Moth", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Iron Thorns", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Frigibax", "Dragon", "Mineral", GR_TYPICAL, {"Arctibax"}},
{"Arctibax", "Dragon", "Mineral", GR_TYPICAL, {"Baxcalibur"}},
{"Baxcalibur", "Dragon", "Mineral", GR_TYPICAL, {}},
{"Gimmighoul", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {"Gholdengo"}},
{"Gholdengo", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Wo-Chien", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Chien-Pao", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Ting-Lu", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Chi-Yu", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Roaring Moon", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Iron Valiant", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Koraidon", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Miraidon", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Walking Wake", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Iron Leaves", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Poltchageist", "Mineral", "Amorphous", GR_UNKNOWN, {"Sinistcha"}},
{"Sinistcha", "Mineral", "Amorphous", GR_UNKNOWN, {}},
{"Okidogi", "No Eggs Discovered", "No Eggs Discovered", GR_MALE_ONLY, {}},
{"Munkidori", "No Eggs Discovered", "No Eggs Discovered", GR_MALE_ONLY, {}},
{"Fezandipiti", "No Eggs Discovered", "No Eggs Discovered", GR_MALE_ONLY, {}},
{"Ogerpon", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, {}},
{"Gouging Fire", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Raging Bolt", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Iron Boulder", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Iron Crown", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Terapagos", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {}},
{"Pecharunt", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}}
}
};