#ifndef DATA_GEN4
#define DATA_GEN4
#pragma once
#include "core.h"

extern Generation g_Generation4;
#endif
Generation g_Generation4 = {
"====[[Generation IV]]====",
//UniversalTMs
{
"Attract",
"Captivate",
"Double Team",
"Endure",
"Facade",
"Frustration",
"Hidden Power",
"Natural Gift",
"Protect",
"Rest",
"Return",
"Secret Power",
"Sleep Talk",
"Swagger",
"Toxic"
},
//MonData
{
{"Bulbasaur", "Monster", "Grass", GR_TYPICAL, {"Ivysaur"}},
{"Ivysaur", "Monster", "Grass", GR_TYPICAL, {"Venusaur"}},
{"Venusaur", "Monster", "Grass", GR_TYPICAL, {}},
{"Charmander", "Monster", "Dragon", GR_TYPICAL, {"Charmeleon"}},
{"Charmeleon", "Monster", "Dragon", GR_TYPICAL, {"Charizard"}},
{"Charizard", "Monster", "Dragon", GR_TYPICAL, {}},
{"Squirtle", "Monster", "Water 1", GR_TYPICAL, {"Wartortle"}},
{"Wartortle", "Monster", "Water 1", GR_TYPICAL, {"Blastoise"}},
{"Blastoise", "Monster", "Water 1", GR_TYPICAL, {}},
{"Caterpie", "Bug", "Bug", GR_TYPICAL, {"Metapod"}},
{"Metapod", "Bug", "Bug", GR_TYPICAL, {"Butterfree"}},
{"Butterfree", "Bug", "Bug", GR_TYPICAL, {}},
{"Weedle", "Bug", "Bug", GR_TYPICAL, {"Kakuna"}},
{"Kakuna", "Bug", "Bug", GR_TYPICAL, {"Beedrill"}},
{"Beedrill", "Bug", "Bug", GR_TYPICAL, {}},
{"Pidgey", "Flying", "Flying", GR_TYPICAL, {"Pidgeotto"}},
{"Pidgeotto", "Flying", "Flying", GR_TYPICAL, {"Pidgeot"}},
{"Pidgeot", "Flying", "Flying", GR_TYPICAL, {}},
{"Rattata", "Field", "Field", GR_TYPICAL, {"Raticate"}},
{"Raticate", "Field", "Field", GR_TYPICAL, {}},
{"Spearow", "Flying", "Flying", GR_TYPICAL, {"Fearow"}},
{"Fearow", "Flying", "Flying", GR_TYPICAL, {}},
{"Ekans", "Field", "Dragon", GR_TYPICAL, {"Arbok"}},
{"Arbok", "Field", "Dragon", GR_TYPICAL, {}},
{"Pichu", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Pikachu"}},
{"Pikachu", "Field", "Fairy", GR_TYPICAL, {"Raichu"}},
{"Raichu", "Field", "Fairy", GR_TYPICAL, {}},
{"Sandshrew", "Field", "Field", GR_TYPICAL, {"Sandslash"}},
{"Sandslash", "Field", "Field", GR_TYPICAL, {}},
{"Nidoran F", "Monster", "Field", GR_FEMALE_ONLY, {"Nidorina"}},
{"Nidorina", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, {"Nidoqueen"}},
{"Nidoqueen", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, {}},
{"Nidoran M", "Monster", "Field", GR_MALE_ONLY, {"Nidorino"}},
{"Nidorino", "Monster", "Field", GR_MALE_ONLY, {"Nidoking"}},
{"Nidoking", "Monster", "Field", GR_MALE_ONLY, {}},
{"Cleffa", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Clefairy"}},
{"Clefairy", "Fairy", "Fairy", GR_TYPICAL, {"Clefable"}},
{"Clefable", "Fairy", "Fairy", GR_TYPICAL, {}},
{"Vulpix", "Field", "Field", GR_TYPICAL, {"Ninetales"}},
{"Ninetales", "Field", "Field", GR_TYPICAL, {}},
{"Igglybuff", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Jigglypuff"}},
{"Jigglypuff", "Fairy", "Fairy", GR_TYPICAL, {"Wigglytuff"}},
{"Wigglytuff", "Fairy", "Fairy", GR_TYPICAL, {}},
{"Zubat", "Flying", "Flying", GR_TYPICAL, {"Golbat"}},
{"Golbat", "Flying", "Flying", GR_TYPICAL, {"Crobat"}},
{"Crobat", "Flying", "Flying", GR_TYPICAL, {}},
{"Oddish", "Grass", "Grass", GR_TYPICAL, {"Gloom"}},
{"Gloom", "Grass", "Grass", GR_TYPICAL, {"Vileplume", "Bellossom"}},
{"Vileplume", "Grass", "Grass", GR_TYPICAL, {}},
{"Bellossom", "Grass", "Grass", GR_TYPICAL, {}},
{"Paras", "Bug", "Grass", GR_TYPICAL, {"Parasect"}},
{"Parasect", "Bug", "Grass", GR_TYPICAL, {}},
{"Venonat", "Bug", "Bug", GR_TYPICAL, {"Venomoth"}},
{"Venomoth", "Bug", "Bug", GR_TYPICAL, {}},
{"Diglett", "Field", "Field", GR_TYPICAL, {"Dugtrio"}},
{"Dugtrio", "Field", "Field", GR_TYPICAL, {}},
{"Meowth", "Field", "Field", GR_TYPICAL, {"Persian"}},
{"Persian", "Field", "Field", GR_TYPICAL, {}},
{"Psyduck", "Water 1", "Field", GR_TYPICAL, {"Golduck"}},
{"Golduck", "Water 1", "Field", GR_TYPICAL, {}},
{"Mankey", "Field", "Field", GR_TYPICAL, {"Primeape"}},
{"Primeape", "Field", "Field", GR_TYPICAL, {}},
{"Growlithe", "Field", "Field", GR_TYPICAL, {"Arcanine"}},
{"Arcanine", "Field", "Field", GR_TYPICAL, {}},
{"Poliwag", "Water 1", "Water 1", GR_TYPICAL, {"Poliwhirl"}},
{"Poliwhirl", "Water 1", "Water 1", GR_TYPICAL, {"Poliwrath", "Politoed"}},
{"Poliwrath", "Water 1", "Water 1", GR_TYPICAL, {}},
{"Politoed", "Water 1", "Water 1", GR_TYPICAL, {}},
{"Abra", "Human-Like", "Human-Like", GR_TYPICAL, {"Kadabra"}},
{"Kadabra", "Human-Like", "Human-Like", GR_TYPICAL, {"Alakazam"}},
{"Alakazam", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Machop", "Human-Like", "Human-Like", GR_TYPICAL, {"Machoke"}},
{"Machoke", "Human-Like", "Human-Like", GR_TYPICAL, {"Machamp"}},
{"Machamp", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Bellsprout", "Grass", "Grass", GR_TYPICAL, {"Weepinbell"}},
{"Weepinbell", "Grass", "Grass", GR_TYPICAL, {"Victreebel"}},
{"Victreebel", "Grass", "Grass", GR_TYPICAL, {}},
{"Tentacool", "Water 3", "Water 3", GR_TYPICAL, {"Tentacruel"}},
{"Tentacruel", "Water 3", "Water 3", GR_TYPICAL, {}},
{"Geodude", "Mineral", "Mineral", GR_TYPICAL, {"Graveler"}},
{"Graveler", "Mineral", "Mineral", GR_TYPICAL, {"Golem"}},
{"Golem", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Ponyta", "Field", "Field", GR_TYPICAL, {"Rapidash"}},
{"Rapidash", "Field", "Field", GR_TYPICAL, {}},
{"Slowpoke", "Monster", "Water 1", GR_TYPICAL, {"Slowbro", "Slowking"}},
{"Slowbro", "Monster", "Water 1", GR_TYPICAL, {}},
{"Slowking", "Monster", "Water 1", GR_TYPICAL, {}},
{"Magnemite", "Mineral", "Mineral", GR_UNKNOWN, {"Magneton"}},
{"Magneton", "Mineral", "Mineral", GR_UNKNOWN, {"Magnezone"}},
{"Magnezone", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Farfetch'd", "Flying", "Field", GR_TYPICAL, {}},
{"Doduo", "Flying", "Flying", GR_TYPICAL, {"Dodrio"}},
{"Dodrio", "Flying", "Flying", GR_TYPICAL, {}},
{"Seel", "Water 1", "Field", GR_TYPICAL, {"Dewgong"}},
{"Dewgong", "Water 1", "Field", GR_TYPICAL, {}},
{"Grimer", "Amorphous", "Amorphous", GR_TYPICAL, {"Muk"}},
{"Muk", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Shellder", "Water 3", "Water 3", GR_TYPICAL, {"Cloyster"}},
{"Cloyster", "Water 3", "Water 3", GR_TYPICAL, {}},
{"Gastly", "Amorphous", "Amorphous", GR_TYPICAL, {"Haunter"}},
{"Haunter", "Amorphous", "Amorphous", GR_TYPICAL, {"Gengar"}},
{"Gengar", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Onix", "Mineral", "Mineral", GR_TYPICAL, {"Steelix"}},
{"Steelix", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Drowzee", "Human-Like", "Human-Like", GR_TYPICAL, {"Hypno"}},
{"Hypno", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Krabby", "Water 3", "Water 3", GR_TYPICAL, {"Kingler"}},
{"Kingler", "Water 3", "Water 3", GR_TYPICAL, {}},
{"Voltorb", "Mineral", "Mineral", GR_UNKNOWN, {"Electrode"}},
{"Electrode", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Exeggcute", "Grass", "Grass", GR_TYPICAL, {"Exeggutor"}},
{"Exeggutor", "Grass", "Grass", GR_TYPICAL, {}},
{"Cubone", "Monster", "Monster", GR_TYPICAL, {"Marowak"}},
{"Marowak", "Monster", "Monster", GR_TYPICAL, {}},
{"Tyrogue", "No Eggs Discovered", "No Eggs Discovered", GR_MALE_ONLY, {"Hitmonlee", "Hitmonchan", "Hitmontop"}},
{"Hitmonlee", "Human-Like", "Human-Like", GR_MALE_ONLY, {}},
{"Hitmonchan", "Human-Like", "Human-Like", GR_MALE_ONLY, {}},
{"Hitmontop", "Human-Like", "Human-Like", GR_MALE_ONLY, {}},
{"Lickitung", "Monster", "Monster", GR_TYPICAL, {"Lickilicky"}},
{"Lickilicky", "Monster", "Monster", GR_TYPICAL, {}},
{"Koffing", "Amorphous", "Amorphous", GR_TYPICAL, {"Weezing"}},
{"Weezing", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Rhyhorn", "Monster", "Field", GR_TYPICAL, {"Rhydon"}},
{"Rhydon", "Monster", "Field", GR_TYPICAL, {"Rhyperior"}},
{"Rhyperior", "Monster", "Field", GR_TYPICAL, {}},
{"Happiny", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, {"Chansey"}},
{"Chansey", "Fairy", "Fairy", GR_FEMALE_ONLY, {"Blissey"}},
{"Blissey", "Fairy", "Fairy", GR_FEMALE_ONLY, {}},
{"Tangela", "Grass", "Grass", GR_TYPICAL, {"Tangrowth"}},
{"Tangrowth", "Grass", "Grass", GR_TYPICAL, {}},
{"Kangaskhan", "Monster", "Monster", GR_FEMALE_ONLY, {}},
{"Horsea", "Water 1", "Dragon", GR_TYPICAL, {"Seadra"}},
{"Seadra", "Water 1", "Dragon", GR_TYPICAL, {"Kingdra"}},
{"Kingdra", "Water 1", "Dragon", GR_TYPICAL, {}},
{"Goldeen", "Water 2", "Water 2", GR_TYPICAL, {"Seaking"}},
{"Seaking", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Staryu", "Water 3", "Water 3", GR_UNKNOWN, {"Starmie"}},
{"Starmie", "Water 3", "Water 3", GR_UNKNOWN, {}},
{"Mime Jr.", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Mr. Mime"}},
{"Mr. Mime", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Scyther", "Bug", "Bug", GR_TYPICAL, {"Scizor"}},
{"Scizor", "Bug", "Bug", GR_TYPICAL, {}},
{"Smoochum", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, {"Jynx"}},
{"Jynx", "Human-Like", "Human-Like", GR_FEMALE_ONLY, {}},
{"Elekid", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Electabuzz"}},
{"Electabuzz", "Human-Like", "Human-Like", GR_TYPICAL, {"Electivire"}},
{"Electivire", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Magby", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Magmar"}},
{"Magmar", "Human-Like", "Human-Like", GR_TYPICAL, {"Magmortar"}},
{"Magmortar", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Pinsir", "Bug", "Bug", GR_TYPICAL, {}},
{"Tauros", "Field", "Field", GR_MALE_ONLY, {}},
{"Magikarp", "Water 2", "Dragon", GR_TYPICAL, {"Gyarados"}},
{"Gyarados", "Water 2", "Dragon", GR_TYPICAL, {}},
{"Lapras", "Monster", "Water 1", GR_TYPICAL, {}},
{"Ditto", "Ditto", "Ditto", GR_UNKNOWN, {}},
{"Eevee", "Field", "Field", GR_TYPICAL, {"Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon", "Leafeon", "Glaceon"}},//7 - Glaceon has to look 7 slots back to find Eevee
{"Vaporeon", "Field", "Field", GR_TYPICAL, {}},//6
{"Jolteon", "Field", "Field", GR_TYPICAL, {}},//5
{"Flareon", "Field", "Field", GR_TYPICAL, {}},//4
{"Espeon", "Field", "Field", GR_TYPICAL, {}},//3
{"Umbreon", "Field", "Field", GR_TYPICAL, {}},//2
{"Leafeon", "Field", "Field", GR_TYPICAL, {}},//1
{"Glaceon", "Field", "Field", GR_TYPICAL, {}},//0
{"Porygon", "Mineral", "Mineral", GR_UNKNOWN, {"Porygon2"}},
{"Porygon2", "Mineral", "Mineral", GR_UNKNOWN, {"Porygon-Z"}},
{"Porygon-Z", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Omanyte", "Water 1", "Water 3", GR_TYPICAL, {"Omastar"}},
{"Omastar", "Water 1", "Water 3", GR_TYPICAL, {}},
{"Kabuto", "Water 1", "Water 3", GR_TYPICAL, {"Kabutops"}},
{"Kabutops", "Water 1", "Water 3", GR_TYPICAL, {}},
{"Aerodactyl", "Flying", "Flying", GR_TYPICAL, {}},
{"Munchlax", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Snorlax"}},
{"Snorlax", "Monster", "Monster", GR_TYPICAL, {}},
{"Articuno", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Zapdos", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Moltres", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Dratini", "Water 1", "Dragon", GR_TYPICAL, {"Dragonair"}},
{"Dragonair", "Water 1", "Dragon", GR_TYPICAL, {"Dragonite"}},
{"Dragonite", "Water 1", "Dragon", GR_TYPICAL, {}},
{"Mewtwo", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Mew", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Chikorita", "Monster", "Grass", GR_TYPICAL, {"Bayleef"}},
{"Bayleef", "Monster", "Grass", GR_TYPICAL, {"Meganium"}},
{"Meganium", "Monster", "Grass", GR_TYPICAL, {}},
{"Cyndaquil", "Field", "Field", GR_TYPICAL, {"Quilava"}},
{"Quilava", "Field", "Field", GR_TYPICAL, {"Typhlosion"}},
{"Typhlosion", "Field", "Field", GR_TYPICAL, {}},
{"Totodile", "Monster", "Water 1", GR_TYPICAL, {"Croconaw"}},
{"Croconaw", "Monster", "Water 1", GR_TYPICAL, {"Feraligatr"}},
{"Feraligatr", "Monster", "Water 1", GR_TYPICAL, {}},
{"Sentret", "Field", "Field", GR_TYPICAL, {"Furret"}},
{"Furret", "Field", "Field", GR_TYPICAL, {}},
{"Hoothoot", "Flying", "Flying", GR_TYPICAL, {"Noctowl"}},
{"Noctowl", "Flying", "Flying", GR_TYPICAL, {}},
{"Ledyba", "Bug", "Bug", GR_TYPICAL, {"Ledian"}},
{"Ledian", "Bug", "Bug", GR_TYPICAL, {}},
{"Spinarak", "Bug", "Bug", GR_TYPICAL, {"Ariados"}},
{"Ariados", "Bug", "Bug", GR_TYPICAL, {}},
{"Chinchou", "Water 2", "Water 2", GR_TYPICAL, {"Lanturn"}},
{"Lanturn", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Togepi", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Togetic"}},
{"Togetic", "Flying", "Fairy", GR_TYPICAL, {"Togekiss"}},
{"Togekiss", "Flying", "Fairy", GR_TYPICAL, {}},
{"Natu", "Flying", "Flying", GR_TYPICAL, {"Xatu"}},
{"Xatu", "Flying", "Flying", GR_TYPICAL, {}},
{"Mareep", "Monster", "Field", GR_TYPICAL, {"Flaaffy"}},
{"Flaaffy", "Monster", "Field", GR_TYPICAL, {"Ampharos"}},
{"Ampharos", "Monster", "Field", GR_TYPICAL, {}},
{"Azurill", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Marill"}},
{"Marill", "Water 1", "Fairy", GR_TYPICAL, {"Azumarill"}},
{"Azumarill", "Water 1", "Fairy", GR_TYPICAL, {}},
{"Bonsly", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Sudowoodo"}},
{"Sudowoodo", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Hoppip", "Fairy", "Grass", GR_TYPICAL, {"Skiploom"}},
{"Skiploom", "Fairy", "Grass", GR_TYPICAL, {"Jumpluff"}},
{"Jumpluff", "Fairy", "Grass", GR_TYPICAL, {}},
{"Aipom", "Field", "Field", GR_TYPICAL, {"Ambipom"}},
{"Ambipom", "Field", "Field", GR_TYPICAL, {}},
{"Sunkern", "Grass", "Grass", GR_TYPICAL, {"Sunflora"}},
{"Sunflora", "Grass", "Grass", GR_TYPICAL, {}},
{"Yanma", "Bug", "Bug", GR_TYPICAL, {"Yanmega"}},
{"Yanmega", "Bug", "Bug", GR_TYPICAL, {}},
{"Wooper", "Water 1", "Field", GR_TYPICAL, {"Quagsire"}},
{"Quagsire", "Water 1", "Field", GR_TYPICAL, {}},
{"Murkrow", "Flying", "Flying", GR_TYPICAL, {"Honchkrow"}},
{"Honchkrow", "Flying", "Flying", GR_TYPICAL, {}},
{"Misdreavus", "Amorphous", "Amorphous", GR_TYPICAL, {"Mismagius"}},
{"Mismagius", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Unown", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Wynaut", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Wobbuffet"}},
{"Wobbuffet", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Girafarig", "Field", "Field", GR_TYPICAL, {}},
{"Pineco", "Bug", "Bug", GR_TYPICAL, {"Forretress"}},
{"Forretress", "Bug", "Bug", GR_TYPICAL, {}},
{"Dunsparce", "Field", "Field", GR_TYPICAL, {}},
{"Gligar", "Bug", "Bug", GR_TYPICAL, {"Gliscor"}},
{"Gliscor", "Bug", "Bug", GR_TYPICAL, {}},
{"Snubbull", "Field", "Fairy", GR_TYPICAL, {"Granbull"}},
{"Granbull", "Field", "Fairy", GR_TYPICAL, {}},
{"Qwilfish", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Shuckle", "Bug", "Bug", GR_TYPICAL, {}},
{"Heracross", "Bug", "Bug", GR_TYPICAL, {}},
{"Sneasel", "Field", "Field", GR_TYPICAL, {"Weavile"}},
{"Weavile", "Field", "Field", GR_TYPICAL, {}},
{"Teddiursa", "Field", "Field", GR_TYPICAL, {"Ursaring"}},
{"Ursaring", "Field", "Field", GR_TYPICAL, {}},
{"Slugma", "Amorphous", "Amorphous", GR_TYPICAL, {"Magcargo"}},
{"Magcargo", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Swinub", "Field", "Field", GR_TYPICAL, {"Piloswine"}},
{"Piloswine", "Field", "Field", GR_TYPICAL, {"Mamoswine"}},
{"Mamoswine", "Field", "Field", GR_TYPICAL, {}},
{"Corsola", "Water 1", "Water 3", GR_TYPICAL, {}},
{"Remoraid", "Water 1", "Water 2", GR_TYPICAL, {"Octillery"}},
{"Octillery", "Water 1", "Water 2", GR_TYPICAL, {}},
{"Delibird", "Water 1", "Field", GR_TYPICAL, {}},
{"Mantyke", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Mantine"}},
{"Mantine", "Water 1", "Water 1", GR_TYPICAL, {}},
{"Skarmory", "Flying", "Flying", GR_TYPICAL, {}},
{"Houndour", "Field", "Field", GR_TYPICAL, {"Houndoom"}},
{"Houndoom", "Field", "Field", GR_TYPICAL, {}},
{"Phanpy", "Field", "Field", GR_TYPICAL, {"Donphan"}},
{"Donphan", "Field", "Field", GR_TYPICAL, {}},
{"Stantler", "Field", "Field", GR_TYPICAL, {}},
{"Smeargle", "Field", "Field", GR_TYPICAL, {}},
{"Miltank", "Field", "Field", GR_FEMALE_ONLY, {}},
{"Raikou", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Entei", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Suicune", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Larvitar", "Monster", "Monster", GR_TYPICAL, {"Pupitar"}},
{"Pupitar", "Monster", "Monster", GR_TYPICAL, {"Tyranitar"}},
{"Tyranitar", "Monster", "Monster", GR_TYPICAL, {}},
{"Lugia", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Ho-Oh", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Celebi", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Treecko", "Monster", "Dragon", GR_TYPICAL, {"Grovyle"}},
{"Grovyle", "Monster", "Dragon", GR_TYPICAL, {"Sceptile"}},
{"Sceptile", "Monster", "Dragon", GR_TYPICAL, {}},
{"Torchic", "Field", "Field", GR_TYPICAL, {"Combusken"}},
{"Combusken", "Field", "Field", GR_TYPICAL, {"Blaziken"}},
{"Blaziken", "Field", "Field", GR_TYPICAL, {}},
{"Mudkip", "Monster", "Water 1", GR_TYPICAL, {"Marshtomp"}},
{"Marshtomp", "Monster", "Water 1", GR_TYPICAL, {"Swampert"}},
{"Swampert", "Monster", "Water 1", GR_TYPICAL, {}},
{"Poochyena", "Field", "Field", GR_TYPICAL, {"Mightyena"}},
{"Mightyena", "Field", "Field", GR_TYPICAL, {}},
{"Zigzagoon", "Field", "Field", GR_TYPICAL, {"Linoone"}},
{"Linoone", "Field", "Field", GR_TYPICAL, {}},
{"Wurmple", "Bug", "Bug", GR_TYPICAL, {"Silcoon", "Cascoon"}},
{"Silcoon", "Bug", "Bug", GR_TYPICAL, {"Beautifly"}},
{"Beautifly", "Bug", "Bug", GR_TYPICAL, {}},
{"Cascoon", "Bug", "Bug", GR_TYPICAL, {"Dustox"}},
{"Dustox", "Bug", "Bug", GR_TYPICAL, {}},
{"Lotad", "Water 1", "Grass", GR_TYPICAL, {"Lombre"}},
{"Lombre", "Water 1", "Grass", GR_TYPICAL, {"Ludicolo"}},
{"Ludicolo", "Water 1", "Grass", GR_TYPICAL, {}},
{"Seedot", "Field", "Grass", GR_TYPICAL, {"Nuzleaf"}},
{"Nuzleaf", "Field", "Grass", GR_TYPICAL, {"Shiftry"}},
{"Shiftry", "Field", "Grass", GR_TYPICAL, {}},
{"Taillow", "Flying", "Flying", GR_TYPICAL, {"Swellow"}},
{"Swellow", "Flying", "Flying", GR_TYPICAL, {}},
{"Wingull", "Water 1", "Flying", GR_TYPICAL, {"Pelipper"}},
{"Pelipper", "Water 1", "Flying", GR_TYPICAL, {}},
{"Ralts", "Amorphous", "Amorphous", GR_TYPICAL, {"Kirlia"}},
{"Kirlia", "Amorphous", "Amorphous", GR_MALE_ONLY, {"Gardevoir", "Gallade"}},
{"Gardevoir", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Gallade", "Amorphous", "Amorphous", GR_MALE_ONLY, {}},
{"Surskit", "Water 1", "Bug", GR_TYPICAL, {"Masquerain"}},
{"Masquerain", "Water 1", "Bug", GR_TYPICAL, {}},
{"Shroomish", "Fairy", "Grass", GR_TYPICAL, {"Breloom"}},
{"Breloom", "Fairy", "Grass", GR_TYPICAL, {}},
{"Slakoth", "Field", "Field", GR_TYPICAL, {"Vigoroth"}},
{"Vigoroth", "Field", "Field", GR_TYPICAL, {"Slaking"}},
{"Slaking", "Field", "Field", GR_TYPICAL, {}},
{"Nincada", "Bug", "Bug", GR_UNKNOWN, {"Ninjask", "Shedinja"}},
{"Ninjask", "Bug", "Bug", GR_TYPICAL, {"Shedinja"}},//a small hack: in this gen, shedinja will copy the moves ninjask learned at the time it evolved from nincada
{"Shedinja", "Bug", "Bug", GR_UNKNOWN, {}},
{"Whismur", "Monster", "Field", GR_TYPICAL, {"Loudred"}},
{"Loudred", "Monster", "Field", GR_TYPICAL, {"Exploud"}},
{"Exploud", "Monster", "Field", GR_TYPICAL, {}},
{"Makuhita", "Human-Like", "Human-Like", GR_TYPICAL, {"Hariyama"}},
{"Hariyama", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Nosepass", "Mineral", "Mineral", GR_TYPICAL, {"Probopass"}},
{"Probopass", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Skitty", "Field", "Fairy", GR_TYPICAL, {"Delcatty"}},
{"Delcatty", "Field", "Fairy", GR_TYPICAL, {}},
{"Sableye", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Mawile", "Field", "Fairy", GR_TYPICAL, {}},
{"Aron", "Monster", "Monster", GR_TYPICAL, {"Lairon"}},
{"Lairon", "Monster", "Monster", GR_TYPICAL, {"Aggron"}},
{"Aggron", "Monster", "Monster", GR_TYPICAL, {}},
{"Meditite", "Human-Like", "Human-Like", GR_TYPICAL, {"Medicham"}},
{"Medicham", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Electrike", "Field", "Field", GR_TYPICAL, {"Manectric"}},
{"Manectric", "Field", "Field", GR_TYPICAL, {}},
{"Plusle", "Fairy", "Fairy", GR_TYPICAL, {}},
{"Minun", "Fairy", "Fairy", GR_TYPICAL, {}},
{"Volbeat", "Bug", "Human-Like", GR_MALE_ONLY, {}},
{"Illumise", "Bug", "Human-Like", GR_FEMALE_ONLY, {}},
{"Budew", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Roselia"}},
{"Roselia", "Fairy", "Grass", GR_TYPICAL, {"Roserade"}},
{"Roserade", "Fairy", "Grass", GR_TYPICAL, {}},
{"Gulpin", "Amorphous", "Amorphous", GR_TYPICAL, {"Swalot"}},
{"Swalot", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Carvanha", "Water 2", "Water 2", GR_TYPICAL, {"Sharpedo"}},
{"Sharpedo", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Wailmer", "Field", "Water 2", GR_TYPICAL, {"Wailord"}},
{"Wailord", "Field", "Water 2", GR_TYPICAL, {}},
{"Numel", "Field", "Field", GR_TYPICAL, {"Camerupt"}},
{"Camerupt", "Field", "Field", GR_TYPICAL, {}},
{"Torkoal", "Field", "Field", GR_TYPICAL, {}},
{"Spoink", "Field", "Field", GR_TYPICAL, {"Grumpig"}},
{"Grumpig", "Field", "Field", GR_TYPICAL, {}},
{"Spinda", "Field", "Human-Like", GR_TYPICAL, {}},
{"Trapinch", "Bug", "Bug", GR_TYPICAL, {"Vibrava"}},
{"Vibrava", "Bug", "Bug", GR_TYPICAL, {"Flygon"}},
{"Flygon", "Bug", "Bug", GR_TYPICAL, {}},
{"Cacnea", "Grass", "Human-Like", GR_TYPICAL, {"Cacturne"}},
{"Cacturne", "Grass", "Human-Like", GR_TYPICAL, {}},
{"Swablu", "Flying", "Dragon", GR_TYPICAL, {"Altaria"}},
{"Altaria", "Flying", "Dragon", GR_TYPICAL, {}},
{"Zangoose", "Field", "Field", GR_TYPICAL, {}},
{"Seviper", "Field", "Dragon", GR_TYPICAL, {}},
{"Lunatone", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Solrock", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Barboach", "Water 2", "Water 2", GR_TYPICAL, {"Whiscash"}},
{"Whiscash", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Corphish", "Water 1", "Water 3", GR_TYPICAL, {"Crawdaunt"}},
{"Crawdaunt", "Water 1", "Water 3", GR_TYPICAL, {}},
{"Baltoy", "Mineral", "Mineral", GR_UNKNOWN, {"Claydol"}},
{"Claydol", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Lileep", "Water 3", "Water 3", GR_TYPICAL, {"Cradily"}},
{"Cradily", "Water 3", "Water 3", GR_TYPICAL, {}},
{"Anorith", "Water 3", "Water 3", GR_TYPICAL, {"Armaldo"}},
{"Armaldo", "Water 3", "Water 3", GR_TYPICAL, {}},
{"Feebas", "Water 1", "Dragon", GR_TYPICAL, {"Milotic"}},
{"Milotic", "Water 1", "Dragon", GR_TYPICAL, {}},
{"Castform", "Fairy", "Amorphous", GR_TYPICAL, {}},
{"Kecleon", "Field", "Field", GR_TYPICAL, {}},
{"Shuppet", "Amorphous", "Amorphous", GR_TYPICAL, {"Banette"}},
{"Banette", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Duskull", "Amorphous", "Amorphous", GR_TYPICAL, {"Dusclops"}},
{"Dusclops", "Amorphous", "Amorphous", GR_TYPICAL, {"Dusknoir"}},
{"Dusknoir", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Tropius", "Monster", "Grass", GR_TYPICAL, {}},
{"Chingling", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Chimecho"}},
{"Chimecho", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Absol", "Field", "Field", GR_TYPICAL, {}},
{"Snorunt", "Fairy", "Mineral", GR_FEMALE_ONLY, {"Glalie", "Froslass"}},
{"Glalie", "Fairy", "Mineral", GR_TYPICAL, {}},
{"Froslass", "Fairy", "Mineral", GR_FEMALE_ONLY, {}},
{"Spheal", "Water 1", "Field", GR_TYPICAL, {"Sealeo"}},
{"Sealeo", "Water 1", "Field", GR_TYPICAL, {"Walrein"}},
{"Walrein", "Water 1", "Field", GR_TYPICAL, {}},
{"Clamperl", "Water 1", "Water 1", GR_TYPICAL, {"Huntail", "Gorebyss"}},
{"Huntail", "Water 1", "Water 1", GR_TYPICAL, {}},
{"Gorebyss", "Water 1", "Water 1", GR_TYPICAL, {}},
{"Relicanth", "Water 1", "Water 2", GR_TYPICAL, {}},
{"Luvdisc", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Bagon", "Dragon", "Dragon", GR_TYPICAL, {"Shelgon"}},
{"Shelgon", "Dragon", "Dragon", GR_TYPICAL, {"Salamence"}},
{"Salamence", "Dragon", "Dragon", GR_TYPICAL, {}},
{"Beldum", "Mineral", "Mineral", GR_UNKNOWN, {"Metang"}},
{"Metang", "Mineral", "Mineral", GR_UNKNOWN, {"Metagross"}},
{"Metagross", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Regirock", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Regice", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Registeel", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Latias", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, {}},
{"Latios", "No Eggs Discovered", "No Eggs Discovered", GR_MALE_ONLY, {}},
{"Kyogre", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Groudon", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Rayquaza", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Jirachi", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Deoxys", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Turtwig", "Monster", "Grass", GR_TYPICAL, {"Grotle"}},
{"Grotle", "Monster", "Grass", GR_TYPICAL, {"Torterra"}},
{"Torterra", "Monster", "Grass", GR_TYPICAL, {}},
{"Chimchar", "Field", "Human-Like", GR_TYPICAL, {"Monferno"}},
{"Monferno", "Field", "Human-Like", GR_TYPICAL, {"Infernape"}},
{"Infernape", "Field", "Human-Like", GR_TYPICAL, {}},
{"Piplup", "Water 1", "Field", GR_TYPICAL, {"Prinplup"}},
{"Prinplup", "Water 1", "Field", GR_TYPICAL, {"Empoleon"}},
{"Empoleon", "Water 1", "Field", GR_TYPICAL, {}},
{"Starly", "Flying", "Flying", GR_TYPICAL, {"Staravia"}},
{"Staravia", "Flying", "Flying", GR_TYPICAL, {"Staraptor"}},
{"Staraptor", "Flying", "Flying", GR_TYPICAL, {}},
{"Bidoof", "Water 1", "Field", GR_TYPICAL, {"Bibarel"}},
{"Bibarel", "Water 1", "Field", GR_TYPICAL, {}},
{"Kricketot", "Bug", "Bug", GR_TYPICAL, {"Kricketune"}},
{"Kricketune", "Bug", "Bug", GR_TYPICAL, {}},
{"Shinx", "Field", "Field", GR_TYPICAL, {"Luxio"}},
{"Luxio", "Field", "Field", GR_TYPICAL, {"Luxray"}},
{"Luxray", "Field", "Field", GR_TYPICAL, {}},
{"Cranidos", "Monster", "Monster", GR_TYPICAL, {"Rampardos"}},
{"Rampardos", "Monster", "Monster", GR_TYPICAL, {}},
{"Shieldon", "Monster", "Monster", GR_TYPICAL, {"Bastiodon"}},
{"Bastiodon", "Monster", "Monster", GR_TYPICAL, {}},
{"Burmy", "Bug", "Bug", GR_MALE_ONLY, {"Wormadam", "Mothim"}},
{"Wormadam", "Bug", "Bug", GR_FEMALE_ONLY, {}},
{"Mothim", "Bug", "Bug", GR_MALE_ONLY, {}},
{"Combee", "Bug", "Bug", GR_FEMALE_ONLY, {"Vespiquen"}},
{"Vespiquen", "Bug", "Bug", GR_FEMALE_ONLY, {}},
{"Pachirisu", "Field", "Fairy", GR_TYPICAL, {}},
{"Buizel", "Water 1", "Field", GR_TYPICAL, {"Floatzel"}},
{"Floatzel", "Water 1", "Field", GR_TYPICAL, {}},
{"Cherubi", "Fairy", "Grass", GR_TYPICAL, {"Cherrim"}},
{"Cherrim", "Fairy", "Grass", GR_TYPICAL, {}},
{"Shellos", "Water 1", "Amorphous", GR_TYPICAL, {"Gastrodon"}},
{"Gastrodon", "Water 1", "Amorphous", GR_TYPICAL, {}},
{"Drifloon", "Amorphous", "Amorphous", GR_TYPICAL, {"Drifblim"}},
{"Drifblim", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Buneary", "Field", "Human-Like", GR_TYPICAL, {"Lopunny"}},
{"Lopunny", "Field", "Human-Like", GR_TYPICAL, {}},
{"Glameow", "Field", "Field", GR_TYPICAL, {"Purugly"}},
{"Purugly", "Field", "Field", GR_TYPICAL, {}},
{"Stunky", "Field", "Field", GR_TYPICAL, {"Skuntank"}},
{"Skuntank", "Field", "Field", GR_TYPICAL, {}},
{"Bronzor", "Mineral", "Mineral", GR_UNKNOWN, {"Bronzong"}},
{"Bronzong", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Chatot", "Flying", "Flying", GR_TYPICAL, {}},
{"Spiritomb", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Gible", "Monster", "Dragon", GR_TYPICAL, {"Gabite"}},
{"Gabite", "Monster", "Dragon", GR_TYPICAL, {"Garchomp"}},
{"Garchomp", "Monster", "Dragon", GR_TYPICAL, {}},
{"Riolu", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Lucario"}},
{"Lucario", "Field", "Human-Like", GR_TYPICAL, {}},
{"Hippopotas", "Field", "Field", GR_TYPICAL, {"Hippowdon"}},
{"Hippowdon", "Field", "Field", GR_TYPICAL, {}},
{"Skorupi", "Bug", "Water 3", GR_TYPICAL, {"Drapion"}},
{"Drapion", "Bug", "Water 3", GR_TYPICAL, {}},
{"Croagunk", "Human-Like", "Human-Like", GR_TYPICAL, {"Toxicroak"}},
{"Toxicroak", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Carnivine", "Grass", "Grass", GR_TYPICAL, {}},
{"Finneon", "Water 2", "Water 2", GR_TYPICAL, {"Lumineon"}},
{"Lumineon", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Snover", "Monster", "Grass", GR_TYPICAL, {"Abomasnow"}},
{"Abomasnow", "Monster", "Grass", GR_TYPICAL, {}},
{"Rotom", "Amorphous", "Amorphous", GR_UNKNOWN, {}},
{"Uxie", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Mesprit", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Azelf", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Dialga", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Palkia", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Heatran", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {}},
{"Regigigas", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Giratina", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Cresselia", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, {}},
{"Phione", "Water 1", "Fairy", GR_UNKNOWN, {}},
{"Manaphy", "Water 1", "Fairy", GR_UNKNOWN, {}},
{"Darkrai", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Shaymin", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Arceus", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}}
}
};