#ifndef DATA_GEN9
#define DATA_GEN9
#pragma once
#include "core.h"

extern Generation tGeneration9;
#endif
Generation tGeneration9 = {
GENERATION_9,
"====[[Generation IX]]====",
//sBabyMons https://bulbapedia.bulbagarden.net/wiki/Baby_Pok%C3%A9mon
{
"Pichu",
"Cleffa",
"Igglybuff",
"Togepi",
"Tyrogue",
"Smoochum",
"Elekid",
"Magby",
"Azurill",
"Wynaut",
"Budew",
"Chingling",
"Bonsly",
"Mime Jr.",
"Happiny",
"Munchlax",
"Riolu",
"Mantyke",
"Toxel"
},
//sFemaleOnlyMons https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_gender_ratio
{
"Nidoran F",
"Chansey",
"Kangaskhan",
"Jynx",
"Miltank",
"Blissey",
"Illumise",
"Wormadam",
"Vespiquen",
"Froslass",
"Petilil",
"Lilligant",
"Vullaby",
"Mandibuzz",
"Flabebe",
"Floette",
"Florges",
"Salazzle",
"Bounsweet",
"Steenee",
"Tsareena",
"Hatenna",
"Hattrem",
"Hatterene",
"Milcery",
"Alcremie",
"Tinkatink",
"Tinkatuff",
"Tinkaton"
},
//sMaleOnlyMons
{
"Nidoran M",
"Nidorino",
"Nidoking",
"Hitmonlee",
"Hitmonchan",
"Tauros",
"Hitmontop",
"Volbeat",
"Mothim",
"Gallade",
"Throh",
"Sawk",
"Rufflet",
"Braviary",
"Impidimp",
"Morgrem",
"Grimmsnarl",
"Ursaluna"
},
//sUniversalTMs https://bulbapedia.bulbagarden.net/w/index.php?search=%22Every+Pok%C3%A9mon+can+learn+this+move+by%22&title=Special%3ASearch&go=Go
{

},
//sAllGroups https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_breeding_attributes https://bulbapedia.bulbagarden.net/wiki/List_of_cross-generational_evolutionary_lines
{
{"Bulbasaur", "Monster", "Grass", {"Ivysaur"}},
{"Ivysaur", "Monster", "Grass", {"Venusaur"}},
{"Venusaur", "Monster", "Grass", {}},
{"Charmander", "Monster", "Dragon", {"Charmeleon"}},
{"Charmeleon", "Monster", "Dragon", {"Charizard"}},
{"Charizard", "Monster", "Dragon", {}},
{"Squirtle", "Monster", "Water 1", {"Wartortle"}},
{"Wartortle", "Monster", "Water 1", {"Blastoise"}},
{"Blastoise", "Monster", "Water 1", {}},
{"Ekans", "Field", "Dragon", {"Arbok"}},
{"Arbok", "Field", "Dragon", {}},
{"Pichu", "No Eggs Discovered", "No Eggs Discovered", {"Pikachu"}},
{"Pikachu", "Field", "Fairy", {"Raichu"}},
{"Raichu", "Field", "Fairy", {}},
{"Sandshrew", "Field", "Field", {"Sandslash"}},
{"Sandslash", "Field", "Field", {}},
{"Cleffa", "No Eggs Discovered", "No Eggs Discovered", {"Clefairy"}},
{"Clefairy", "Fairy", "Fairy", {"Clefable"}},
{"Clefable", "Fairy", "Fairy", {}},
{"Vulpix", "Field", "Field", {"Ninetales"}},
{"Ninetales", "Field", "Field", {}},
{"Igglybuff", "No Eggs Discovered", "No Eggs Discovered", {"Jigglypuff"}},
{"Jigglypuff", "Fairy", "Fairy", {"Wigglytuff"}},
{"Wigglytuff", "Fairy", "Fairy", {}},
{"Oddish", "Grass", "Grass", {"Gloom"}},
{"Gloom", "Grass", "Grass", {"Vileplume", "Bellossom"}},
{"Vileplume", "Grass", "Grass", {}},
{"Bellossom", "Grass", "Grass", {}},
{"Venonat", "Bug", "Bug", {"Venomoth"}},
{"Venomoth", "Bug", "Bug", {}},
{"Diglett", "Field", "Field", {"Dugtrio"}},
{"Dugtrio", "Field", "Field", {}},
{"Meowth", "Field", "Field", {"Persian"}},
{"Persian", "Field", "Field", {"Perrserker"}},
{"Perrserker", "Field", "Field", {}},
{"Psyduck", "Water 1", "Field", {"Golduck"}},
{"Golduck", "Water 1", "Field", {}},
{"Mankey", "Field", "Field", {"Primeape"}},
{"Primeape", "Field", "Field", {"Annihilape"}},
{"Annihilape", "Field", "Field", {}},
{"Growlithe", "Field", "Field", {"Arcanine"}},
{"Arcanine", "Field", "Field", {}},
{"Poliwag", "Water 1", "Water 1", {"Poliwhirl"}},
{"Poliwhirl", "Water 1", "Water 1", {"Poliwrath", "Politoed"}},
{"Poliwrath", "Water 1", "Water 1", {}},
{"Politoed", "Water 1", "Water 1", {}},
{"Bellsprout", "Grass", "Grass", {"Weepinbell"}},
{"Weepinbell", "Grass", "Grass", {"Victreebel"}},
{"Victreebel", "Grass", "Grass", {}},
{"Tentacool", "Water 3", "Water 3", {"Tentacruel"}},
{"Tentacruel", "Water 3", "Water 3", {}},
{"Geodude", "Mineral", "Mineral", {"Graveler"}},
{"Graveler", "Mineral", "Mineral", {"Golem"}},
{"Golem", "Mineral", "Mineral", {}},
{"Slowpoke", "Monster", "Water 1", {"Slowbro", "Slowking"}},
{"Slowbro", "Monster", "Water 1", {}},
{"Slowking", "Monster", "Water 1", {}},
{"Magnemite", "Mineral", "Mineral", {"Magneton"}},
{"Magneton", "Mineral", "Mineral", {"Magnezone"}},
{"Magnezone", "Mineral", "Mineral", {}},
{"Doduo", "Flying", "Flying", {"Dodrio"}},
{"Dodrio", "Flying", "Flying", {}},
{"Seel", "Water 1", "Field", {"Dewgong"}},
{"Dewgong", "Water 1", "Field", {}},
{"Grimer", "Amorphous", "Amorphous", {"Muk"}},
{"Muk", "Amorphous", "Amorphous", {}},
{"Shellder", "Water 3", "Water 3", {"Cloyster"}},
{"Cloyster", "Water 3", "Water 3", {}},
{"Gastly", "Amorphous", "Amorphous", {"Haunter"}},
{"Haunter", "Amorphous", "Amorphous", {"Gengar"}},
{"Gengar", "Amorphous", "Amorphous", {}},
{"Drowzee", "Human-Like", "Human-Like", {"Hypno"}},
{"Hypno", "Human-Like", "Human-Like", {}},
{"Voltorb", "Mineral", "Mineral", {"Electrode"}},
{"Electrode", "Mineral", "Mineral", {}},
{"Exeggcute", "Grass", "Grass", {"Exeggutor"}},
{"Exeggutor", "Grass", "Grass", {}},
{"Tyrogue", "No Eggs Discovered", "No Eggs Discovered", {"Hitmonlee", "Hitmonchan", "Hitmontop"}},
{"Hitmonlee", "Human-Like", "Human-Like", {}},
{"Hitmonchan", "Human-Like", "Human-Like", {}},
{"Hitmontop", "Human-Like", "Human-Like", {}},
{"Koffing", "Amorphous", "Amorphous", {"Weezing"}},
{"Weezing", "Amorphous", "Amorphous", {}},
{"Rhyhorn", "Monster", "Field", {"Rhydon"}},
{"Rhydon", "Monster", "Field", {"Rhyperior"}},
{"Rhyperior", "Monster", "Field", {}},
{"Happiny", "No Eggs Discovered", "No Eggs Discovered", {"Chansey"}},
{"Chansey", "Fairy", "Fairy", {"Blissey"}},
{"Blissey", "Fairy", "Fairy", {}},
{"Horsea", "Water 1", "Dragon", {"Seadra"}},
{"Seadra", "Water 1", "Dragon", {"Kingdra"}},
{"Kingdra", "Water 1", "Dragon", {}},
{"Scyther", "Bug", "Bug", {"Scizor", "Kleavor"}},
{"Scizor", "Bug", "Bug", {}},
{"Kleavor", "Bug", "Bug", {}},
{"Elekid", "No Eggs Discovered", "No Eggs Discovered", {"Electabuzz"}},
{"Electabuzz", "Human-Like", "Human-Like", {"Electivire"}},
{"Electivire", "Human-Like", "Human-Like", {}},
{"Magby", "No Eggs Discovered", "No Eggs Discovered", {"Magmar"}},
{"Magmar", "Human-Like", "Human-Like", {"Magmortar"}},
{"Magmortar", "Human-Like", "Human-Like", {}},
{"Tauros", "Field", "Field", {}},
{"Magikarp", "Water 2", "Dragon", {"Gyarados"}},
{"Gyarados", "Water 2", "Dragon", {}},
{"Lapras", "Monster", "Water 1", {}},
{"Ditto", "Ditto", "Ditto", {}},
{"Eevee", "Field", "Field", {"Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon", "Leafeon", "Glaceon", "Sylveon"}},
{"Vaporeon", "Field", "Field", {}},
{"Jolteon", "Field", "Field", {}},
{"Flareon", "Field", "Field", {}},
{"Espeon", "Field", "Field", {}},
{"Umbreon", "Field", "Field", {}},
{"Leafeon", "Field", "Field", {}},
{"Glaceon", "Field", "Field", {}},
{"Sylveon", "Field", "Field", {}},
{"Porygon", "Mineral", "Mineral", {"Porygon2"}},
{"Porygon2", "Mineral", "Mineral", {"Porygon-Z"}},
{"Porygon-Z", "Mineral", "Mineral", {}},
{"Munchlax", "No Eggs Discovered", "No Eggs Discovered", {"Snorlax"}},
{"Snorlax", "Monster", "Monster", {}},
{"Articuno", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Zapdos", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Moltres", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Dratini", "Water 1", "Dragon", {"Dragonair"}},
{"Dragonair", "Water 1", "Dragon", {"Dragonite"}},
{"Dragonite", "Water 1", "Dragon", {}},
{"Mewtwo", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Mew", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Chikorita", "Monster", "Grass", {"Bayleef"}},
{"Bayleef", "Monster", "Grass", {"Meganium"}},
{"Meganium", "Monster", "Grass", {}},
{"Cyndaquil", "Field", "Field", {"Quilava"}},
{"Quilava", "Field", "Field", {"Typhlosion"}},
{"Typhlosion", "Field", "Field", {}},
{"Totodile", "Monster", "Water 1", {"Croconaw"}},
{"Croconaw", "Monster", "Water 1", {"Feraligatr"}},
{"Feraligatr", "Monster", "Water 1", {}},
{"Sentret", "Field", "Field", {"Furret"}},
{"Furret", "Field", "Field", {}},
{"Hoothoot", "Flying", "Flying", {"Noctowl"}},
{"Noctowl", "Flying", "Flying", {}},
{"Spinarak", "Bug", "Bug", {"Ariados"}},
{"Ariados", "Bug", "Bug", {}},
{"Chinchou", "Water 2", "Water 2", {"Lanturn"}},
{"Lanturn", "Water 2", "Water 2", {}},
{"Mareep", "Monster", "Field", {"Flaaffy"}},
{"Flaaffy", "Monster", "Field", {"Ampharos"}},
{"Ampharos", "Monster", "Field", {}},
{"Azurill", "No Eggs Discovered", "No Eggs Discovered", {"Marill"}},
{"Marill", "Water 1", "Fairy", {"Azumarill"}},
{"Azumarill", "Water 1", "Fairy", {}},
{"Bonsly", "No Eggs Discovered", "No Eggs Discovered", {"Sudowoodo"}},
{"Sudowoodo", "Mineral", "Mineral", {}},
{"Hoppip", "Fairy", "Grass", {"Skiploom"}},
{"Skiploom", "Fairy", "Grass", {"Jumpluff"}},
{"Jumpluff", "Fairy", "Grass", {}},
{"Aipom", "Field", "Field", {"Ambipom"}},
{"Ambipom", "Field", "Field", {}},
{"Sunkern", "Grass", "Grass", {"Sunflora"}},
{"Sunflora", "Grass", "Grass", {}},
{"Yanma", "Bug", "Bug", {"Yanmega"}},
{"Yanmega", "Bug", "Bug", {}},
{"Wooper", "Water 1", "Field", {"Quagsire", "Clodsire"}},
{"Quagsire", "Water 1", "Field", {}},
{"Clodsire", "Water 1", "Field", {}},
{"Murkrow", "Flying", "Flying", {"Honchkrow"}},
{"Honchkrow", "Flying", "Flying", {}},
{"Misdreavus", "Amorphous", "Amorphous", {"Mismagius"}},
{"Mismagius", "Amorphous", "Amorphous", {}},
{"Girafarig", "Field", "Field", {"Farigiraf"}},
{"Farigiraf", "Field", "Field", {}},
{"Pineco", "Bug", "Bug", {"Forretress"}},
{"Forretress", "Bug", "Bug", {}},
{"Dunsparce", "Field", "Field", {"Dudunsparce"}},
{"Dudunsparce", "Field", "Field", {}},
{"Gligar", "Bug", "Bug", {"Gliscor"}},
{"Gliscor", "Bug", "Bug", {}},
{"Snubbull", "Field", "Fairy", {"Granbull"}},
{"Granbull", "Field", "Fairy", {}},
{"Qwilfish", "Water 2", "Water 2", {"Overqwil"}},
{"Overqwil", "Water 2", "Water 2", {}},
{"Heracross", "Bug", "Bug", {}},
{"Sneasel", "Field", "Field", {"Weavile", "Sneasler"}},
{"Weavile", "Field", "Field", {}},
{"Sneasler", "Field", "Field", {}},
{"Teddiursa", "Field", "Field", {"Ursaring"}},
{"Ursaring", "Field", "Field", {"Ursaluna"}},
{"Ursaluna", "Field", "Field", {}},
{"Slugma", "Amorphous", "Amorphous", {"Magcargo"}},
{"Magcargo", "Amorphous", "Amorphous", {}},
{"Swinub", "Field", "Field", {"Piloswine"}},
{"Piloswine", "Field", "Field", {"Mamoswine"}},
{"Mamoswine", "Field", "Field", {}},
{"Delibird", "Water 1", "Field", {}},
{"Skarmory", "Flying", "Flying", {}},
{"Houndour", "Field", "Field", {"Houndoom"}},
{"Houndoom", "Field", "Field", {}},
{"Phanpy", "Field", "Field", {"Donphan"}},
{"Donphan", "Field", "Field", {}},
{"Stantler", "Field", "Field", {"Wyrdeer"}},
{"Wyrdeer", "Field", "Field", {}},
{"Smeargle", "Field", "Field", {}},
{"Raikou", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Entei", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Suicune", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Larvitar", "Monster", "Monster", {"Pupitar"}},
{"Pupitar", "Monster", "Monster", {"Tyranitar"}},
{"Tyranitar", "Monster", "Monster", {}},
{"Lugia", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Ho-Oh", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Treecko", "Monster", "Dragon", {"Grovyle"}},
{"Grovyle", "Monster", "Dragon", {"Sceptile"}},
{"Sceptile", "Monster", "Dragon", {}},
{"Torchic", "Field", "Field", {"Combusken"}},
{"Combusken", "Field", "Field", {"Blaziken"}},
{"Blaziken", "Field", "Field", {}},
{"Mudkip", "Monster", "Water 1", {"Marshtomp"}},
{"Marshtomp", "Monster", "Water 1", {"Swampert"}},
{"Swampert", "Monster", "Water 1", {}},
{"Poochyena", "Field", "Field", {"Mightyena"}},
{"Mightyena", "Field", "Field", {}},
{"Lotad", "Water 1", "Grass", {"Lombre"}},
{"Lombre", "Water 1", "Grass", {"Ludicolo"}},
{"Ludicolo", "Water 1", "Grass", {}},
{"Seedot", "Field", "Grass", {"Nuzleaf"}},
{"Nuzleaf", "Field", "Grass", {"Shiftry"}},
{"Shiftry", "Field", "Grass", {}},
{"Wingull", "Water 1", "Flying", {"Pelipper"}},
{"Pelipper", "Water 1", "Flying", {}},
{"Ralts", "Human-Like", "Amorphous", {"Kirlia"}},
{"Kirlia", "Human-Like", "Amorphous", {"Gardevoir", "Gallade"}},
{"Gardevoir", "Human-Like", "Amorphous", {}},
{"Gallade", "Human-Like", "Amorphous", {}},
{"Surskit", "Water 1", "Bug", {"Masquerain"}},
{"Masquerain", "Water 1", "Bug", {}},
{"Shroomish", "Fairy", "Grass", {"Breloom"}},
{"Breloom", "Fairy", "Grass", {}},
{"Slakoth", "Field", "Field", {"Vigoroth"}},
{"Vigoroth", "Field", "Field", {"Slaking"}},
{"Slaking", "Field", "Field", {}},
{"Makuhita", "Human-Like", "Human-Like", {"Hariyama"}},
{"Hariyama", "Human-Like", "Human-Like", {}},
{"Nosepass", "Mineral", "Mineral", {"Probopass"}},
{"Probopass", "Mineral", "Mineral", {}},
{"Sableye", "Human-Like", "Human-Like", {}},
{"Meditite", "Human-Like", "Human-Like", {"Medicham"}},
{"Medicham", "Human-Like", "Human-Like", {}},
{"Plusle", "Fairy", "Fairy", {}},
{"Minun", "Fairy", "Fairy", {}},
{"Volbeat", "Bug", "Human-Like", {}},
{"Illumise", "Bug", "Human-Like", {}},
{"Gulpin", "Amorphous", "Amorphous", {"Swalot"}},
{"Swalot", "Amorphous", "Amorphous", {}},
{"Numel", "Field", "Field", {"Camerupt"}},
{"Camerupt", "Field", "Field", {}},
{"Torkoal", "Field", "Field", {}},
{"Spoink", "Field", "Field", {"Grumpig"}},
{"Grumpig", "Field", "Field", {}},
{"Trapinch", "Bug", "Dragon", {"Vibrava"}},
{"Vibrava", "Bug", "Dragon", {"Flygon"}},
{"Flygon", "Bug", "Dragon", {}},
{"Cacnea", "Grass", "Human-Like", {"Cacturne"}},
{"Cacturne", "Grass", "Human-Like", {}},
{"Swablu", "Flying", "Dragon", {"Altaria"}},
{"Altaria", "Flying", "Dragon", {}},
{"Zangoose", "Field", "Field", {}},
{"Seviper", "Field", "Dragon", {}},
{"Barboach", "Water 2", "Water 2", {"Whiscash"}},
{"Whiscash", "Water 2", "Water 2", {}},
{"Corphish", "Water 1", "Water 3", {"Crawdaunt"}},
{"Crawdaunt", "Water 1", "Water 3", {}},
{"Feebas", "Water 1", "Dragon", {"Milotic"}},
{"Milotic", "Water 1", "Dragon", {}},
{"Shuppet", "Amorphous", "Amorphous", {"Banette"}},
{"Banette", "Amorphous", "Amorphous", {}},
{"Duskull", "Amorphous", "Amorphous", {"Dusclops"}},
{"Dusclops", "Amorphous", "Amorphous", {"Dusknoir"}},
{"Dusknoir", "Amorphous", "Amorphous", {}},
{"Tropius", "Monster", "Grass", {}},
{"Chingling", "No Eggs Discovered", "No Eggs Discovered", {"Chimecho"}},
{"Chimecho", "Amorphous", "Amorphous", {}},
{"Snorunt", "Fairy", "Mineral", {"Glalie", "Froslass"}},
{"Glalie", "Fairy", "Mineral", {}},
{"Froslass", "Fairy", "Mineral", {}},
{"Luvdisc", "Water 2", "Water 2", {}},
{"Bagon", "Dragon", "Dragon", {"Shelgon"}},
{"Shelgon", "Dragon", "Dragon", {"Salamence"}},
{"Salamence", "Dragon", "Dragon", {}},
{"Beldum", "Mineral", "Mineral", {"Metang"}},
{"Metang", "Mineral", "Mineral", {"Metagross"}},
{"Metagross", "Mineral", "Mineral", {}},
{"Regirock", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Regice", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Registeel", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Latias", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Latios", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Kyogre", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Groudon", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Rayquaza", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Jirachi", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Deoxys", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Turtwig", "Monster", "Grass", {"Grotle"}},
{"Grotle", "Monster", "Grass", {"Torterra"}},
{"Torterra", "Monster", "Grass", {}},
{"Chimchar", "Field", "Human-Like", {"Monferno"}},
{"Monferno", "Field", "Human-Like", {"Infernape"}},
{"Infernape", "Field", "Human-Like", {}},
{"Piplup", "Water 1", "Field", {"Prinplup"}},
{"Prinplup", "Water 1", "Field", {"Empoleon"}},
{"Empoleon", "Water 1", "Field", {}},
{"Starly", "Flying", "Flying", {"Staravia"}},
{"Staravia", "Flying", "Flying", {"Staraptor"}},
{"Staraptor", "Flying", "Flying", {}},
{"Kricketot", "Bug", "Bug", {"Kricketune"}},
{"Kricketune", "Bug", "Bug", {}},
{"Shinx", "Field", "Field", {"Luxio"}},
{"Luxio", "Field", "Field", {"Luxray"}},
{"Luxray", "Field", "Field", {}},
{"Cranidos", "Monster", "Monster", {"Rampardos"}},
{"Rampardos", "Monster", "Monster", {}},
{"Shieldon", "Monster", "Monster", {"Bastiodon"}},
{"Bastiodon", "Monster", "Monster", {}},
{"Combee", "Bug", "Bug", {"Vespiquen"}},
{"Vespiquen", "Bug", "Bug", {}},
{"Pachirisu", "Field", "Fairy", {}},
{"Buizel", "Water 1", "Field", {"Floatzel"}},
{"Floatzel", "Water 1", "Field", {}},
{"Shellos", "Water 1", "Amorphous", {"Gastrodon"}},
{"Gastrodon", "Water 1", "Amorphous", {}},
{"Drifloon", "Amorphous", "Amorphous", {"Drifblim"}},
{"Drifblim", "Amorphous", "Amorphous", {}},
{"Stunky", "Field", "Field", {"Skuntank"}},
{"Skuntank", "Field", "Field", {}},
{"Bronzor", "Mineral", "Mineral", {"Bronzong"}},
{"Bronzong", "Mineral", "Mineral", {}},
{"Spiritomb", "Amorphous", "Amorphous", {}},
{"Gible", "Monster", "Dragon", {"Gabite"}},
{"Gabite", "Monster", "Dragon", {"Garchomp"}},
{"Garchomp", "Monster", "Dragon", {}},
{"Riolu", "No Eggs Discovered", "No Eggs Discovered", {"Lucario"}},
{"Lucario", "Field", "Human-Like", {}},
{"Hippopotas", "Field", "Field", {"Hippowdon"}},
{"Hippowdon", "Field", "Field", {}},
{"Croagunk", "Human-Like", "Human-Like", {"Toxicroak"}},
{"Toxicroak", "Human-Like", "Human-Like", {}},
{"Finneon", "Water 2", "Water 2", {"Lumineon"}},
{"Lumineon", "Water 2", "Water 2", {}},
{"Snover", "Monster", "Grass", {"Abomasnow"}},
{"Abomasnow", "Monster", "Grass", {}},
{"Rotom", "Amorphous", "Amorphous", {}},
{"Uxie", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Mesprit", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Azelf", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Dialga", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Palkia", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Heatran", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Regigigas", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Giratina", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Cresselia", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Phione", "Water 1", "Fairy", {}},
{"Manaphy", "Water 1", "Fairy", {}},
{"Darkrai", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Shaymin", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Arceus", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Snivy", "Field", "Grass", {"Servine"}},
{"Servine", "Field", "Grass", {"Serperior"}},
{"Serperior", "Field", "Grass", {}},
{"Tepig", "Field", "Field", {"Pignite"}},
{"Pignite", "Field", "Field", {"Emboar"}},
{"Emboar", "Field", "Field", {}},
{"Oshawott", "Field", "Field", {"Dewott"}},
{"Dewott", "Field", "Field", {"Samurott"}},
{"Samurott", "Field", "Field", {}},
{"Blitzle", "Field", "Field", {"Zebstrika"}},
{"Zebstrika", "Field", "Field", {}},
{"Drilbur", "Field", "Field", {"Excadrill"}},
{"Excadrill", "Field", "Field", {}},
{"Timburr", "Human-Like", "Human-Like", {"Gurdurr"}},
{"Gurdurr", "Human-Like", "Human-Like", {"Conkeldurr"}},
{"Conkeldurr", "Human-Like", "Human-Like", {}},
{"Sewaddle", "Bug", "Bug", {"Swadloon"}},
{"Swadloon", "Bug", "Bug", {"Leavanny"}},
{"Leavanny", "Bug", "Bug", {}},
{"Cottonee", "Grass", "Fairy", {"Whimsicott"}},
{"Whimsicott", "Grass", "Fairy", {}},
{"Petilil", "Grass", "Grass", {"Lilligant"}},
{"Lilligant", "Grass", "Grass", {}},
{"Basculin", "Water 2", "Water 2", {"Basculegion"}},
{"Basculegion", "Water 2", "Water 2", {}},
{"Sandile", "Field", "Field", {"Krokorok"}},
{"Krokorok", "Field", "Field", {"Krookodile"}},
{"Krookodile", "Field", "Field", {}},
{"Scraggy", "Field", "Dragon", {"Scrafty"}},
{"Scrafty", "Field", "Dragon", {}},
{"Zorua", "Field", "Field", {"Zoroark"}},
{"Zoroark", "Field", "Field", {}},
{"Minccino", "Field", "Field", {"Cinccino"}},
{"Cinccino", "Field", "Field", {}},
{"Gothita", "Human-Like", "Human-Like", {"Gothorita"}},
{"Gothorita", "Human-Like", "Human-Like", {"Gothitelle"}},
{"Gothitelle", "Human-Like", "Human-Like", {}},
{"Solosis", "Amorphous", "Amorphous", {"Duosion"}},
{"Duosion", "Amorphous", "Amorphous", {"Reuniclus"}},
{"Reuniclus", "Amorphous", "Amorphous", {}},
{"Ducklett", "Water 1", "Flying", {"Swanna"}},
{"Swanna", "Water 1", "Flying", {}},
{"Deerling", "Field", "Field", {"Sawsbuck"}},
{"Sawsbuck", "Field", "Field", {}},
{"Foongus", "Grass", "Grass", {"Amoonguss"}},
{"Amoonguss", "Grass", "Grass", {}},
{"Alomomola", "Water 1", "Water 2", {}},
{"Joltik", "Bug", "Bug", {"Galvantula"}},
{"Galvantula", "Bug", "Bug", {}},
{"Tynamo", "Amorphous", "Amorphous", {"Eelektrik"}},
{"Eelektrik", "Amorphous", "Amorphous", {"Eelektross"}},
{"Eelektross", "Amorphous", "Amorphous", {}},
{"Litwick", "Amorphous", "Amorphous", {"Lampent"}},
{"Lampent", "Amorphous", "Amorphous", {"Chandelure"}},
{"Chandelure", "Amorphous", "Amorphous", {}},
{"Axew", "Monster", "Dragon", {"Fraxure"}},
{"Fraxure", "Monster", "Dragon", {"Haxorus"}},
{"Haxorus", "Monster", "Dragon", {}},
{"Cubchoo", "Field", "Field", {"Beartic"}},
{"Beartic", "Field", "Field", {}},
{"Cryogonal", "Mineral", "Mineral", {}},
{"Mienfoo", "Field", "Human-Like", {"Mienshao"}},
{"Mienshao", "Field", "Human-Like", {}},
{"Golett", "Mineral", "Mineral", {"Golurk"}},
{"Golurk", "Mineral", "Mineral", {}},
{"Pawniard", "Human-Like", "Human-Like", {"Bisharp"}},
{"Bisharp", "Human-Like", "Human-Like", {"Kingambit"}},
{"Kingambit", "Human-Like", "Human-Like", {}},
{"Rufflet", "Flying", "Flying", {"Braviary"}},
{"Braviary", "Flying", "Flying", {}},
{"Vullaby", "Flying", "Flying", {"Mandibuzz"}},
{"Mandibuzz", "Flying", "Flying", {}},
{"Deino", "Dragon", "Dragon", {"Zweilous"}},
{"Zweilous", "Dragon", "Dragon", {"Hydreigon"}},
{"Hydreigon", "Dragon", "Dragon", {}},
{"Larvesta", "Bug", "Bug", {"Volcarona"}},
{"Volcarona", "Bug", "Bug", {}},
{"Cobalion", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Terrakion", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Virizion", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Tornadus", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Thundurus", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Reshiram", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Zekrom", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Landorus", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Kyurem", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Keldeo", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Meloetta", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Chespin", "Field", "Field", {"Quilladin"}},
{"Quilladin", "Field", "Field", {"Chesnaught"}},
{"Chesnaught", "Field", "Field", {}},
{"Fennekin", "Field", "Field", {"Braixen"}},
{"Braixen", "Field", "Field", {"Delphox"}},
{"Delphox", "Field", "Field", {}},
{"Froakie", "Water 1", "Water 1", {"Frogadier"}},
{"Frogadier", "Water 1", "Water 1", {"Greninja"}},
{"Greninja", "Water 1", "Water 1", {}},
{"Fletchling", "Flying", "Flying", {"Fletchinder"}},
{"Fletchinder", "Flying", "Flying", {"Talonflame"}},
{"Talonflame", "Flying", "Flying", {}},
{"Scatterbug", "Bug", "Bug", {"Spewpa"}},
{"Spewpa", "Bug", "Bug", {"Vivillon"}},
{"Vivillon", "Bug", "Bug", {}},
{"Litleo", "Field", "Field", {"Pyroar"}},
{"Pyroar", "Field", "Field", {}},
{"Flabebe", "Fairy", "Fairy", {"Floette"}},
{"Floette", "Fairy", "Fairy", {"Florges"}},
{"Florges", "Fairy", "Fairy", {}},
{"Skiddo", "Field", "Field", {"Gogoat"}},
{"Gogoat", "Field", "Field", {}},
{"Espurr", "Field", "Field", {"Meowstic"}},
{"Meowstic", "Field", "Field", {}},
{"Inkay", "Water 1", "Water 2", {"Malamar"}},
{"Malamar", "Water 1", "Water 2", {}},
{"Skrelp", "Water 1", "Dragon", {"Dragalge"}},
{"Dragalge", "Water 1", "Dragon", {}},
{"Clauncher", "Water 1", "Water 3", {"Clawitzer"}},
{"Clawitzer", "Water 1", "Water 3", {}},
{"Hawlucha", "Flying", "Human-Like", {}},
{"Dedenne", "Field", "Fairy", {}},
{"Carbink", "Fairy", "Mineral", {}},
{"Goomy", "Dragon", "Dragon", {"Sliggoo"}},
{"Sliggoo", "Dragon", "Dragon", {"Goodra"}},
{"Goodra", "Dragon", "Dragon", {}},
{"Klefki", "Mineral", "Mineral", {}},
{"Phantump", "Grass", "Amorphous", {"Trevenant"}},
{"Trevenant", "Grass", "Amorphous", {}},
{"Bergmite", "Monster", "Mineral", {"Avalugg"}},
{"Avalugg", "Monster", "Mineral", {}},
{"Noibat", "Flying", "Dragon", {"Noivern"}},
{"Noivern", "Flying", "Dragon", {}},
{"Diancie", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Hoopa", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Volcanion", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Rowlet", "Flying", "Flying", {"Dartrix"}},
{"Dartrix", "Flying", "Flying", {"Decidueye"}},
{"Decidueye", "Flying", "Flying", {}},
{"Litten", "Field", "Field", {"Torracat"}},
{"Torracat", "Field", "Field", {"Incineroar"}},
{"Incineroar", "Field", "Field", {}},
{"Popplio", "Water 1", "Field", {"Brionne"}},
{"Brionne", "Water 1", "Field", {"Primarina"}},
{"Primarina", "Water 1", "Field", {}},
{"Pikipek", "Flying", "Flying", {"Trumbeak"}},
{"Trumbeak", "Flying", "Flying", {"Toucannon"}},
{"Toucannon", "Flying", "Flying", {}},
{"Yungoos", "Field", "Field", {"Gumshoos"}},
{"Gumshoos", "Field", "Field", {}},
{"Grubbin", "Bug", "Bug", {"Charjabug"}},
{"Charjabug", "Bug", "Bug", {"Vikavolt"}},
{"Vikavolt", "Bug", "Bug", {}},
{"Crabrawler", "Water 3", "Water 3", {"Crabominable"}},
{"Crabominable", "Water 3", "Water 3", {}},
{"Oricorio", "Flying", "Flying", {}},
{"Cutiefly", "Bug", "Fairy", {"Ribombee"}},
{"Ribombee", "Bug", "Fairy", {}},
{"Rockruff", "Field", "Field", {"Lycanroc"}},
{"Lycanroc", "Field", "Field", {}},
{"Mareanie", "Water 1", "Water 1", {"Toxapex"}},
{"Toxapex", "Water 1", "Water 1", {}},
{"Mudbray", "Field", "Field", {"Mudsdale"}},
{"Mudsdale", "Field", "Field", {}},
{"Dewpider", "Water 1", "Bug", {"Araquanid"}},
{"Araquanid", "Water 1", "Bug", {}},
{"Fomantis", "Grass", "Grass", {"Lurantis"}},
{"Lurantis", "Grass", "Grass", {}},
{"Salandit", "Monster", "Dragon", {"Salazzle"}},
{"Salazzle", "Monster", "Dragon", {}},
{"Bounsweet", "Grass", "Grass", {"Steenee"}},
{"Steenee", "Grass", "Grass", {"Tsareena"}},
{"Tsareena", "Grass", "Grass", {}},
{"Comfey", "Grass", "Grass", {}},
{"Oranguru", "Field", "Field", {"Passimian"}},
{"Passimian", "Field", "Field", {}},
{"Sandygast", "Amorphous", "Amorphous", {"Palossand"}},
{"Palossand", "Amorphous", "Amorphous", {}},
{"Minior", "Mineral", "Mineral", {}},
{"Komala", "Field", "Field", {}},
{"Mimikyu", "Amorphous", "Amorphous", {}},
{"Bruxish", "Water 2", "Water 2", {}},
{"Jangmo-o", "Dragon", "Dragon", {"Hakamo-o"}},
{"Hakamo-o", "Dragon", "Dragon", {"Kommo-o"}},
{"Kommo-o", "Dragon", "Dragon", {}},
{"Cosmog", "No Eggs Discovered", "No Eggs Discovered", {"Cosmoem"}},
{"Cosmoem", "No Eggs Discovered", "No Eggs Discovered", {"Solgaleo", "Lunala"}},
{"Solgaleo", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Lunala", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Necrozma", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Magearna", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Grookey", "Field", "Grass", {"Thwackey"}},
{"Thwackey", "Field", "Grass", {"Rillaboom"}},
{"Rillaboom", "Field", "Grass", {}},
{"Scorbunny", "Field", "Human-Like", {}},
{"Raboot", "Field", "Human-Like", {"Cinderace"}},
{"Cinderace", "Field", "Human-Like", {"Sobble"}},
{"Sobble", "Water 1", "Field", {"Drizzile"}},
{"Drizzile", "Water 1", "Field", {"Inteleon"}},
{"Inteleon", "Water 1", "Field", {}},
{"Skwovet", "Field", "Field", {"Greedent"}},
{"Greedent", "Field", "Field", {}},
{"Rookidee", "Flying", "Flying", {"Corvisquire"}},
{"Corvisquire", "Flying", "Flying", {"Corviknight"}},
{"Corviknight", "Flying", "Flying", {}},
{"Chewtle", "Monster", "Water 1", {"Drednaw"}},
{"Drednaw", "Monster", "Water 1", {}},
{"Rolycoly", "Mineral", "Mineral", {"Carkol"}},
{"Carkol", "Mineral", "Mineral", {"Coalossal"}},
{"Coalossal", "Mineral", "Mineral", {}},
{"Applin", "Grass", "Dragon", {"Flapple", "Appletun", "Dipplin"}},
{"Flapple", "Grass", "Dragon", {}},
{"Appletun", "Grass", "Dragon", {}},
{"Dipplin", "Grass", "Dragon", {"Hydrapple"}},
{"Hydrapple", "Grass", "Dragon", {}},
{"Silicobra", "Field", "Dragon", {"Sandaconda"}},
{"Sandaconda", "Field", "Dragon", {}},
{"Cramorant", "Water 1", "Flying", {}},
{"Arrokuda", "Water 2", "Water 2", {"Barraskewda"}},
{"Barraskewda", "Water 2", "Water 2", {}},
{"Toxel", "No Eggs Discovered", "No Eggs Discovered", {"Toxtricity"}},
{"Toxtricity", "Human-Like", "Human-Like", {}},
{"Sinistea", "Mineral", "Amorphous", {"Polteageist"}},
{"Polteageist", "Mineral", "Amorphous", {}},
{"Hatenna", "Fairy", "Fairy", {"Hattrem"}},
{"Hattrem", "Fairy", "Fairy", {"Hatterene"}},
{"Hatterene", "Fairy", "Fairy", {}},
{"Impidimp", "Fairy", "Human-Like", {"Morgrem"}},
{"Morgrem", "Fairy", "Human-Like", {"Grimmsnarl"}},
{"Grimmsnarl", "Fairy", "Human-Like", {}},
{"Milcery", "Fairy", "Amorphous", {"Alcremie"}},
{"Alcremie", "Fairy", "Amorphous", {}},
{"Falinks", "Fairy", "Mineral", {}},
{"Pincurchin", "Water 1", "Amorphous", {}},
{"Snom", "Bug", "Bug", {"Frosmoth"}},
{"Frosmoth", "Bug", "Bug", {}},
{"Stonjourner", "Mineral", "Mineral", {}},
{"Eiscue", "Water 1", "Field", {}},
{"Indeedee", "Fairy", "Fairy", {}},
{"Morpeko", "Field", "Fairy", {}},
{"Cufant", "Field", "Mineral", {"Copperajah"}},
{"Copperajah", "Field", "Mineral", {}},
{"Duraludon", "Mineral", "Dragon", {"Archaludon"}},
{"Archaludon", "Mineral", "Dragon", {}},
{"Dreepy", "Amorphous", "Dragon", {"Drakloak"}},
{"Drakloak", "Amorphous", "Dragon", {"Dragapult"}},
{"Dragapult", "Amorphous", "Dragon", {}},
{"Zacian", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Zamazenta", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Eternatus", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Kubfu", "No Eggs Discovered", "No Eggs Discovered", {"Urshifu"}},
{"Urshifu", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Zarude", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Regieleki", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Regidrago", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Glastrier", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Spectrier", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Calyrex", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Enamorus", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Sprigatito", "Field", "Grass", {"Floragato"}},
{"Floragato", "Field", "Grass", {"Meowscarada"}},
{"Meowscarada", "Field", "Grass", {}},
{"Fuecoco", "Field", "Field", {"Crocalor"}},
{"Crocalor", "Field", "Field", {"Skeledirge"}},
{"Skeledirge", "Field", "Field", {}},
{"Quaxly", "Flying", "Water 1", {"Quaxwell"}},
{"Quaxwell", "Flying", "Water 1", {"Quaquaval"}},
{"Quaquaval", "Flying", "Water 1", {}},
{"Lechonk", "Field", "Field", {"Oinkologne"}},
{"Oinkologne", "Field", "Field", {}},
{"Tarountula", "Bug", "Bug", {"Spidops"}},
{"Spidops", "Bug", "Bug", {}},
{"Nymble", "Bug", "Bug", {"Lokix"}},
{"Lokix", "Bug", "Bug", {}},
{"Pawmi", "Field", "Field", {"Pawmo"}},
{"Pawmo", "Field", "Field", {"Pawmot"}},
{"Pawmot", "Field", "Field", {}},
{"Tandemaus", "Field", "Fairy", {"Maushold"}},
{"Maushold", "Field", "Fairy", {}},
{"Fidough", "Field", "Mineral", {"Dachsbun"}},
{"Dachsbun", "Field", "Mineral", {}},
{"Smoliv", "Grass", "Grass", {"Dolliv"}},
{"Dolliv", "Grass", "Grass", {"Arboliva"}},
{"Arboliva", "Grass", "Grass", {}},
{"Squawkabilly", "Flying", "Flying", {}},
{"Nacli", "Mineral", "Mineral", {"Naclstack"}},
{"Naclstack", "Mineral", "Mineral", {"Garganacl"}},
{"Garganacl", "Mineral", "Mineral", {}},
{"Charcadet", "Human-Like", "Human-Like", {"Armarouge", "Ceruledge"}},
{"Armarouge", "Human-Like", "Human-Like", {}},
{"Ceruledge", "Human-Like", "Human-Like", {}},
{"Tadbulb", "Water 1", "Water 1", {"Bellibolt"}},
{"Bellibolt", "Water 1", "Water 1", {}},
{"Wattrel", "Water 1", "Flying", {"Kilowattrel"}},
{"Kilowattrel", "Water 1", "Flying", {}},
{"Maschiff", "Field", "Field", {"Mabosstiff"}},
{"Mabosstiff", "Field", "Field", {}},
{"Shroodle", "Field", "Field", {"Grafaiai"}},
{"Grafaiai", "Field", "Field", {}},
{"Bramblin", "Grass", "Grass", {"Brambleghast"}},
{"Brambleghast", "Grass", "Grass", {}},
{"Toedscool", "Grass", "Grass", {"Toedscruel"}},
{"Toedscruel", "Grass", "Grass", {}},
{"Klawf", "Water 3", "Water 3", {}},
{"Capsakid", "Grass", "Grass", {"Scovillain"}},
{"Scovillain", "Grass", "Grass", {}},
{"Rellor", "Bug", "Bug", {"Rabsca"}},
{"Rabsca", "Bug", "Bug", {}},
{"Flittle", "Flying", "Flying", {"Espathra"}},
{"Espathra", "Flying", "Flying", {}},
{"Tinkatink", "Fairy", "Fairy", {"Tinkatuff"}},
{"Tinkatuff", "Fairy", "Fairy", {"Tinkaton"}},
{"Tinkaton", "Fairy", "Fairy", {}},
{"Wiglett", "Water 3", "Water 3", {"Wugtrio"}},
{"Wugtrio", "Water 3", "Water 3", {}},
{"Bombirdier", "Flying", "Flying", {}},
{"Finizen", "Field", "Water 2", {"Palafin"}},
{"Palafin", "Field", "Water 2", {}},
{"Varoom", "Mineral", "Mineral", {"Revavroom"}},
{"Revavroom", "Mineral", "Mineral", {}},
{"Cyclizar", "Field", "Field", {}},
{"Orthworm", "Field", "Field", {}},
{"Glimmet", "Mineral", "Mineral", {"Glimmora"}},
{"Glimmora", "Mineral", "Mineral", {}},
{"Greavard", "Field", "Field", {"Houndstone"}},
{"Houndstone", "Field", "Field", {}},
{"Flamigo", "Flying", "Flying", {}},
{"Cetoddle", "Field", "Field", {"Cetitan"}},
{"Cetitan", "Field", "Field", {}},
{"Veluza", "Water 2", "Water 2", {}},
{"Dondozo", "Water 2", "Water 2", {}},
{"Tatsugiri", "Water 2", "Water 2", {}},
{"Great Tusk", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Scream Tail", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Brute Bonnet", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Flutter Mane", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Slither Wing", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Sandy Shocks", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Iron Treads", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Iron Bundle", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Iron Hands", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Iron Jugulis", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Iron Moth", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Iron Thorns", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Frigibax", "Dragon", "Mineral", {"Arctibax"}},
{"Arctibax", "Dragon", "Mineral", {"Baxcalibur"}},
{"Baxcalibur", "Dragon", "Mineral", {}},
{"Gimmighoul", "No Eggs Discovered", "No Eggs Discovered", {"Gholdengo"}},
{"Gholdengo", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Wo-Chien", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Chien-Pao", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Ting-Lu", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Chi-Yu", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Roaring Moon", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Iron Valiant", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Koraidon", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Miraidon", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Walking Wake", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Iron Leaves", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Poltchageist", "Mineral", "Amorphous", {"Sinistcha"}},
{"Sinistcha", "Mineral", "Amorphous", {}},
{"Okidogi", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Munkidori", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Fezandipiti", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Ogerpon", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Gouging Fire", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Raging Bolt", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Iron Boulder", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Iron Crown", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Terapagos", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Pecharunt", "No Eggs Discovered", "No Eggs Discovered", {}}
}
};