#ifndef DATA_GEN2
#define DATA_GEN2
#pragma once
#include "core.h"

extern Generation tGeneration2;
#endif
Generation tGeneration2 = {
GENERATION_2,
"====[[Generation II]]====",
//sUniversalTMs
{
"Attract",
"Double Team",
"Endure",
"Frustration",
"Hidden Power",
"Protect",
"Rest",
"Return",
"Sleep Talk",
"Snore",
"Swagger",
"Toxic"
},
//sAllGroups
{
{"Bulbasaur", "Monster", "Grass", GR_TYPICAL, {"Ivysaur"}},
{"Ivysaur", "Monster", "Grass", GR_TYPICAL, {"Venusaur"}},
{"Venusaur", "Monster", "Grass", GR_TYPICAL, {}},
{"Charmander", "Monster", "Dragon", GR_TYPICAL, {"Charmeleon"}},
{"Charmeleon", "Monster", "Dragon", GR_TYPICAL, {"Charizard"}},
{"Charizard", "Monster", "Dragon", GR_TYPICAL, {}},
{"Squirtle", "Monster", "Water 1", GR_TYPICAL, {"Wartortle"}},
{"Wartortle", "Monster", "Water 1", GR_TYPICAL, {"Blastoise"}},
{"Blastoise", "Monster", "Water 1", GR_TYPICAL, {}},
{"Caterpie", "Bug", "Bug", GR_TYPICAL, {"Metapod"}},
{"Metapod", "Bug", "Bug", GR_TYPICAL, {"Butterfree"}},
{"Butterfree", "Bug", "Bug", GR_TYPICAL, {}},
{"Weedle", "Bug", "Bug", GR_TYPICAL, {"Kakuna"}},
{"Kakuna", "Bug", "Bug", GR_TYPICAL, {"Beedrill"}},
{"Beedrill", "Bug", "Bug", GR_TYPICAL, {}},
{"Pidgey", "Flying", "Flying", GR_TYPICAL, {"Pidgeotto"}},
{"Pidgeotto", "Flying", "Flying", GR_TYPICAL, {"Pidgeot"}},
{"Pidgeot", "Flying", "Flying", GR_TYPICAL, {}},
{"Rattata", "Field", "Field", GR_TYPICAL, {"Raticate"}},
{"Raticate", "Field", "Field", GR_TYPICAL, {}},
{"Spearow", "Flying", "Flying", GR_TYPICAL, {"Fearow"}},
{"Fearow", "Flying", "Flying", GR_TYPICAL, {}},
{"Ekans", "Field", "Dragon", GR_TYPICAL, {"Arbok"}},
{"Arbok", "Field", "Dragon", GR_TYPICAL, {}},
{"Pichu", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Pikachu"}},
{"Pikachu", "Field", "Fairy", GR_TYPICAL, {"Raichu"}},
{"Raichu", "Field", "Fairy", GR_TYPICAL, {}},
{"Sandshrew", "Field", "Field", GR_TYPICAL, {"Sandslash"}},
{"Sandslash", "Field", "Field", GR_TYPICAL, {}},
{"Nidoran F", "Monster", "Field", GR_FEMALE_ONLY, {"Nidorina"}},
{"Nidorina", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, {"Nidoqueen"}},
{"Nidoqueen", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, {}},
{"Nidoran M", "Monster", "Field", GR_MALE_ONLY, {"Nidorino"}},
{"Nidorino", "Monster", "Field", GR_MALE_ONLY, {"Nidoking"}},
{"Nidoking", "Monster", "Field", GR_MALE_ONLY, {}},
{"Cleffa", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Clefairy"}},
{"Clefairy", "Fairy", "Fairy", GR_TYPICAL, {"Clefable"}},
{"Clefable", "Fairy", "Fairy", GR_TYPICAL, {}},
{"Vulpix", "Field", "Field", GR_TYPICAL, {"Ninetales"}},
{"Ninetales", "Field", "Field", GR_TYPICAL, {}},
{"Igglybuff", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Jigglypuff"}},
{"Jigglypuff", "Fairy", "Fairy", GR_TYPICAL, {"Wigglytuff"}},
{"Wigglytuff", "Fairy", "Fairy", GR_TYPICAL, {}},
{"Zubat", "Flying", "Flying", GR_TYPICAL, {"Golbat"}},
{"Golbat", "Flying", "Flying", GR_TYPICAL, {"Crobat"}},
{"Crobat", "Flying", "Flying", GR_TYPICAL, {}},
{"Oddish", "Grass", "Grass", GR_TYPICAL, {"Gloom"}},
{"Gloom", "Grass", "Grass", GR_TYPICAL, {"Vileplume", "Bellossom"}},
{"Vileplume", "Grass", "Grass", GR_TYPICAL, {}},
{"Bellossom", "Grass", "Grass", GR_TYPICAL, {}},
{"Paras", "Bug", "Grass", GR_TYPICAL, {"Parasect"}},
{"Parasect", "Bug", "Grass", GR_TYPICAL, {}},
{"Venonat", "Bug", "Bug", GR_TYPICAL, {"Venomoth"}},
{"Venomoth", "Bug", "Bug", GR_TYPICAL, {}},
{"Diglett", "Field", "Field", GR_TYPICAL, {"Dugtrio"}},
{"Dugtrio", "Field", "Field", GR_TYPICAL, {}},
{"Meowth", "Field", "Field", GR_TYPICAL, {"Persian"}},
{"Persian", "Field", "Field", GR_TYPICAL, {}},
{"Psyduck", "Water 1", "Field", GR_TYPICAL, {"Golduck"}},
{"Golduck", "Water 1", "Field", GR_TYPICAL, {}},
{"Mankey", "Field", "Field", GR_TYPICAL, {"Primeape"}},
{"Primeape", "Field", "Field", GR_TYPICAL, {}},
{"Growlithe", "Field", "Field", GR_TYPICAL, {"Arcanine"}},
{"Arcanine", "Field", "Field", GR_TYPICAL, {}},
{"Poliwag", "Water 1", "Water 1", GR_TYPICAL, {"Poliwhirl"}},
{"Poliwhirl", "Water 1", "Water 1", GR_TYPICAL, {"Poliwrath", "Politoed"}},
{"Poliwrath", "Water 1", "Water 1", GR_TYPICAL, {}},
{"Politoed", "Water 1", "Water 1", GR_TYPICAL, {}},
{"Abra", "Human-Like", "Human-Like", GR_TYPICAL, {"Kadabra"}},
{"Kadabra", "Human-Like", "Human-Like", GR_TYPICAL, {"Alakazam"}},
{"Alakazam", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Machop", "Human-Like", "Human-Like", GR_TYPICAL, {"Machoke"}},
{"Machoke", "Human-Like", "Human-Like", GR_TYPICAL, {"Machamp"}},
{"Machamp", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Bellsprout", "Grass", "Grass", GR_TYPICAL, {"Weepinbell"}},
{"Weepinbell", "Grass", "Grass", GR_TYPICAL, {"Victreebel"}},
{"Victreebel", "Grass", "Grass", GR_TYPICAL, {}},
{"Tentacool", "Water 3", "Water 3", GR_TYPICAL, {"Tentacruel"}},
{"Tentacruel", "Water 3", "Water 3", GR_TYPICAL, {}},
{"Geodude", "Mineral", "Mineral", GR_TYPICAL, {"Graveler"}},
{"Graveler", "Mineral", "Mineral", GR_TYPICAL, {"Golem"}},
{"Golem", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Ponyta", "Field", "Field", GR_TYPICAL, {"Rapidash"}},
{"Rapidash", "Field", "Field", GR_TYPICAL, {}},
{"Slowpoke", "Monster", "Water 1", GR_TYPICAL, {"Slowbro", "Slowking"}},
{"Slowbro", "Monster", "Water 1", GR_TYPICAL, {}},
{"Slowking", "Monster", "Water 1", GR_TYPICAL, {}},
{"Magnemite", "Mineral", "Mineral", GR_UNKNOWN, {"Magneton"}},
{"Magneton", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Farfetch'd", "Flying", "Field", GR_TYPICAL, {}},
{"Doduo", "Flying", "Flying", GR_TYPICAL, {"Dodrio"}},
{"Dodrio", "Flying", "Flying", GR_TYPICAL, {}},
{"Seel", "Water 1", "Field", GR_TYPICAL, {"Dewgong"}},
{"Dewgong", "Water 1", "Field", GR_TYPICAL, {}},
{"Grimer", "Amorphous", "Amorphous", GR_TYPICAL, {"Muk"}},
{"Muk", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Shellder", "Water 3", "Water 3", GR_TYPICAL, {"Cloyster"}},
{"Cloyster", "Water 3", "Water 3", GR_TYPICAL, {}},
{"Gastly", "Amorphous", "Amorphous", GR_TYPICAL, {"Haunter"}},
{"Haunter", "Amorphous", "Amorphous", GR_TYPICAL, {"Gengar"}},
{"Gengar", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Onix", "Mineral", "Mineral", GR_TYPICAL, {"Steelix"}},
{"Steelix", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Drowzee", "Human-Like", "Human-Like", GR_TYPICAL, {"Hypno"}},
{"Hypno", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Krabby", "Water 3", "Water 3", GR_TYPICAL, {"Kingler"}},
{"Kingler", "Water 3", "Water 3", GR_TYPICAL, {}},
{"Voltorb", "Mineral", "Mineral", GR_UNKNOWN, {"Electrode"}},
{"Electrode", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Exeggcute", "Grass", "Grass", GR_TYPICAL, {"Exeggutor"}},
{"Exeggutor", "Grass", "Grass", GR_TYPICAL, {}},
{"Cubone", "Monster", "Monster", GR_TYPICAL, {"Marowak"}},
{"Marowak", "Monster", "Monster", GR_TYPICAL, {}},
{"Tyrogue", "No Eggs Discovered", "No Eggs Discovered", GR_MALE_ONLY, {"Hitmonlee", "Hitmonchan", "Hitmontop"}},
{"Hitmonlee", "Human-Like", "Human-Like", GR_MALE_ONLY, {}},
{"Hitmonchan", "Human-Like", "Human-Like", GR_MALE_ONLY, {}},
{"Hitmontop", "Human-Like", "Human-Like", GR_MALE_ONLY, {}},
{"Lickitung", "Monster", "Monster", GR_TYPICAL, {}},
{"Koffing", "Amorphous", "Amorphous", GR_TYPICAL, {"Weezing"}},
{"Weezing", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Rhyhorn", "Monster", "Field", GR_TYPICAL, {"Rhydon"}},
{"Rhydon", "Monster", "Field", GR_TYPICAL, {}},
{"Chansey", "Fairy", "Fairy", GR_FEMALE_ONLY, {"Blissey"}},
{"Blissey", "Fairy", "Fairy", GR_FEMALE_ONLY, {}},
{"Tangela", "Grass", "Grass", GR_TYPICAL, {}},
{"Kangaskhan", "Monster", "Monster", GR_FEMALE_ONLY, {}},
{"Horsea", "Water 1", "Dragon", GR_TYPICAL, {"Seadra"}},
{"Seadra", "Water 1", "Dragon", GR_TYPICAL, {"Kingdra"}},
{"Kingdra", "Water 1", "Dragon", GR_TYPICAL, {}},
{"Goldeen", "Water 2", "Water 2", GR_TYPICAL, {"Seaking"}},
{"Seaking", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Staryu", "Water 3", "Water 3", GR_UNKNOWN, {"Starmie"}},
{"Starmie", "Water 3", "Water 3", GR_UNKNOWN, {}},
{"Mr. Mime", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Scyther", "Bug", "Bug", GR_TYPICAL, {"Scizor"}},
{"Scizor", "Bug", "Bug", GR_TYPICAL, {}},
{"Smoochum", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, {"Jynx"}},
{"Jynx", "Human-Like", "Human-Like", GR_FEMALE_ONLY, {}},
{"Elekid", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Electabuzz"}},
{"Electabuzz", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Magby", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Magmar"}},
{"Magmar", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Pinsir", "Bug", "Bug", GR_TYPICAL, {}},
{"Tauros", "Field", "Field", GR_MALE_ONLY, {}},
{"Magikarp", "Water 2", "Dragon", GR_TYPICAL, {"Gyarados"}},
{"Gyarados", "Water 2", "Dragon", GR_TYPICAL, {}},
{"Lapras", "Monster", "Water 1", GR_TYPICAL, {}},
{"Ditto", "Ditto", "Ditto", GR_UNKNOWN, {}},
{"Eevee", "Field", "Field", GR_TYPICAL, {"Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon"}},
{"Vaporeon", "Field", "Field", GR_TYPICAL, {}},
{"Jolteon", "Field", "Field", GR_TYPICAL, {}},
{"Flareon", "Field", "Field", GR_TYPICAL, {}},
{"Espeon", "Field", "Field", GR_TYPICAL, {}},
{"Umbreon", "Field", "Field", GR_TYPICAL, {}},
{"Porygon", "Mineral", "Mineral", GR_UNKNOWN, {"Porygon2"}},
{"Porygon2", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Omanyte", "Water 1", "Water 3", GR_TYPICAL, {"Omastar"}},
{"Omastar", "Water 1", "Water 3", GR_TYPICAL, {}},
{"Kabuto", "Water 1", "Water 3", GR_TYPICAL, {"Kabutops"}},
{"Kabutops", "Water 1", "Water 3", GR_TYPICAL, {}},
{"Aerodactyl", "Flying", "Flying", GR_TYPICAL, {}},
{"Snorlax", "Monster", "Monster", GR_TYPICAL, {}},
{"Articuno", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Zapdos", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Moltres", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Dratini", "Water 1", "Dragon", GR_TYPICAL, {"Dragonair"}},
{"Dragonair", "Water 1", "Dragon", GR_TYPICAL, {"Dragonite"}},
{"Dragonite", "Water 1", "Dragon", GR_TYPICAL, {}},
{"Mewtwo", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Mew", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Chikorita", "Monster", "Grass", GR_TYPICAL, {"Bayleef"}},
{"Bayleef", "Monster", "Grass", GR_TYPICAL, {"Meganium"}},
{"Meganium", "Monster", "Grass", GR_TYPICAL, {}},
{"Cyndaquil", "Field", "Field", GR_TYPICAL, {"Quilava"}},
{"Quilava", "Field", "Field", GR_TYPICAL, {"Typhlosion"}},
{"Typhlosion", "Field", "Field", GR_TYPICAL, {}},
{"Totodile", "Monster", "Water 1", GR_TYPICAL, {"Croconaw"}},
{"Croconaw", "Monster", "Water 1", GR_TYPICAL, {"Feraligatr"}},
{"Feraligatr", "Monster", "Water 1", GR_TYPICAL, {}},
{"Sentret", "Field", "Field", GR_TYPICAL, {"Furret"}},
{"Furret", "Field", "Field", GR_TYPICAL, {}},
{"Hoothoot", "Flying", "Flying", GR_TYPICAL, {"Noctowl"}},
{"Noctowl", "Flying", "Flying", GR_TYPICAL, {}},
{"Ledyba", "Bug", "Bug", GR_TYPICAL, {"Ledian"}},
{"Ledian", "Bug", "Bug", GR_TYPICAL, {}},
{"Spinarak", "Bug", "Bug", GR_TYPICAL, {"Ariados"}},
{"Ariados", "Bug", "Bug", GR_TYPICAL, {}},
{"Chinchou", "Water 2", "Water 2", GR_TYPICAL, {"Lanturn"}},
{"Lanturn", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Togepi", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Togetic"}},
{"Togetic", "Flying", "Fairy", GR_TYPICAL, {}},
{"Natu", "Flying", "Flying", GR_TYPICAL, {"Xatu"}},
{"Xatu", "Flying", "Flying", GR_TYPICAL, {}},
{"Mareep", "Monster", "Field", GR_TYPICAL, {"Flaaffy"}},
{"Flaaffy", "Monster", "Field", GR_TYPICAL, {"Ampharos"}},
{"Ampharos", "Monster", "Field", GR_TYPICAL, {}},
{"Marill", "Water 1", "Fairy", GR_TYPICAL, {"Azumarill"}},
{"Azumarill", "Water 1", "Fairy", GR_TYPICAL, {}},
{"Sudowoodo", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Hoppip", "Fairy", "Grass", GR_TYPICAL, {"Skiploom"}},
{"Skiploom", "Fairy", "Grass", GR_TYPICAL, {"Jumpluff"}},
{"Jumpluff", "Fairy", "Grass", GR_TYPICAL, {}},
{"Aipom", "Field", "Field", GR_TYPICAL, {}},
{"Sunkern", "Grass", "Grass", GR_TYPICAL, {"Sunflora"}},
{"Sunflora", "Grass", "Grass", GR_TYPICAL, {}},
{"Yanma", "Bug", "Bug", GR_TYPICAL, {}},
{"Wooper", "Water 1", "Field", GR_TYPICAL, {"Quagsire"}},
{"Quagsire", "Water 1", "Field", GR_TYPICAL, {}},
{"Murkrow", "Flying", "Flying", GR_TYPICAL, {}},
{"Misdreavus", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Unown", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Wobbuffet", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Girafarig", "Field", "Field", GR_TYPICAL, {}},
{"Pineco", "Bug", "Bug", GR_TYPICAL, {"Forretress"}},
{"Forretress", "Bug", "Bug", GR_TYPICAL, {}},
{"Dunsparce", "Field", "Field", GR_TYPICAL, {}},
{"Gligar", "Bug", "Bug", GR_TYPICAL, {}},
{"Snubbull", "Field", "Fairy", GR_TYPICAL, {"Granbull"}},
{"Granbull", "Field", "Fairy", GR_TYPICAL, {}},
{"Qwilfish", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Shuckle", "Bug", "Bug", GR_TYPICAL, {}},
{"Heracross", "Bug", "Bug", GR_TYPICAL, {}},
{"Sneasel", "Field", "Field", GR_TYPICAL, {}},
{"Teddiursa", "Field", "Field", GR_TYPICAL, {"Ursaring"}},
{"Ursaring", "Field", "Field", GR_TYPICAL, {}},
{"Slugma", "Amorphous", "Amorphous", GR_TYPICAL, {"Magcargo"}},
{"Magcargo", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Swinub", "Field", "Field", GR_TYPICAL, {"Piloswine"}},
{"Piloswine", "Field", "Field", GR_TYPICAL, {}},
{"Corsola", "Water 1", "Water 3", GR_TYPICAL, {}},
{"Remoraid", "Water 1", "Water 2", GR_TYPICAL, {"Octillery"}},
{"Octillery", "Water 1", "Water 2", GR_TYPICAL, {}},
{"Delibird", "Water 1", "Field", GR_TYPICAL, {}},
{"Mantine", "Water 1", "Water 1", GR_TYPICAL, {}},
{"Skarmory", "Flying", "Flying", GR_TYPICAL, {}},
{"Houndour", "Field", "Field", GR_TYPICAL, {"Houndoom"}},
{"Houndoom", "Field", "Field", GR_TYPICAL, {}},
{"Phanpy", "Field", "Field", GR_TYPICAL, {"Donphan"}},
{"Donphan", "Field", "Field", GR_TYPICAL, {}},
{"Stantler", "Field", "Field", GR_TYPICAL, {}},
{"Smeargle", "Field", "Field", GR_TYPICAL, {}},
{"Miltank", "Field", "Field", GR_FEMALE_ONLY, {}},
{"Raikou", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Entei", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Suicune", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Larvitar", "Monster", "Monster", GR_TYPICAL, {"Pupitar"}},
{"Pupitar", "Monster", "Monster", GR_TYPICAL, {"Tyranitar"}},
{"Tyranitar", "Monster", "Monster", GR_TYPICAL, {}},
{"Lugia", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Ho-Oh", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Celebi", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}}
}
};