#ifndef DATA_GEN2
#define DATA_GEN2
#pragma once
#include "core.h"

extern Generation tGeneration2;
#endif
Generation tGeneration2 = {
2,
"====[[Generation II]]====",
//sBabyMons
{
"Pichu",
"Cleffa",
"Igglybuff",
"Togepi",
"Tyrogue",
"Smoochum",
"Elekid",
"Magby"
},
//sFemaleOnlyMons
{
"Nidoran F",
"Chansey",
"Kangaskhan",
"Jynx",
"Miltank",
"Blissey"
},
//sMaleOnlyMons
{
"Nidoran M",
"Nidorino",
"Nidoking",
"Hitmonlee",
"Hitmonchan",
"Tauros",
"Hitmontop"
},
//sUniversalTMs
{
"Return",
"Frustration",
"Swagger",
"Endure",
"Sleep Talk",
"Attract",
"Rest",
"Hidden Power",
"Toxic",
"Protect",
"Double Team",
"Substitute"
},
//sTMsandHMs
{
"Dynamic Punch",
"Headbutt",
"Curse",
"Rollout",
"Roar",
"Toxic",
"Zap Cannon",
"Rock Smash",
"Psych Up",
"Hidden Power",
"Sunny Day",
"Sweet Scent",
"Snore",
"Blizzard",
"Hyper Beam",
"Icy Wind",
"Protect",
"Rain Dance",
"Giga Drain",
"Endure",
"Frustration",
"Solar Beam",
"Iron Tail",
"Dragon Breath",
"Thunder",
"Earthquake",
"Return",
"Dig",
"Psychic",
"Shadow Ball",
"Mud-Slap",
"Double Team",
"Ice Punch",
"Swagger",
"Sleep Talk",
"Sludge Bomb",
"Sandstorm",
"Fire Blast",
"Swift",
"Defense Curl",
"Thunder Punch",
"Dream Eater",
"Detect",
"Rest",
"Attract",
"Thief",
"Steel Wing",
"Fire Punch",
"Fury Cutter",
"Nightmare",
"Cut",
"Fly",
"Surf",
"Strength",
"Flash",
"Whirlpool",
"Waterfall"
},
//sAllGroups
{
{"Bulbasaur", "Monster", "Grass", {"Ivysaur"}},
{"Ivysaur", "Monster", "Grass", {"Venusaur"}},
{"Venusaur", "Monster", "Grass", {}},
{"Charmander", "Monster", "Dragon", {"Charmeleon"}},
{"Charmeleon", "Monster", "Dragon", {"Charizard"}},
{"Charizard", "Monster", "Dragon", {}},
{"Squirtle", "Monster", "Water 1", {"Wartortle"}},
{"Wartortle", "Monster", "Water 1", {"Blastoise"}},
{"Blastoise", "Monster", "Water 1", {}},
{"Caterpie", "Bug", "Bug", {"Metapod"}},
{"Metapod", "Bug", "Bug", {"Butterfree"}},
{"Butterfree", "Bug", "Bug", {}},
{"Weedle", "Bug", "Bug", {"Kakuna"}},
{"Kakuna", "Bug", "Bug", {"Beedrill"}},
{"Beedrill", "Bug", "Bug", {}},
{"Pidgey", "Flying", "Flying", {"Pidgeotto"}},
{"Pidgeotto", "Flying", "Flying", {"Pidgeot"}},
{"Pidgeot", "Flying", "Flying", {}},
{"Rattata", "Field", "Field", {"Raticate"}},
{"Raticate", "Field", "Field", {}},
{"Spearow", "Flying", "Flying", {"Fearow"}},
{"Fearow", "Flying", "Flying", {}},
{"Ekans", "Field", "Dragon", {"Arbok"}},
{"Arbok", "Field", "Dragon", {}},
{"Pichu", "No Eggs Discovered", "No Eggs Discovered", {"Pikachu"}},
{"Pikachu", "Field", "Fairy", {"Raichu"}},
{"Raichu", "Field", "Fairy", {}},
{"Sandshrew", "Field", "Field", {"Sandslash"}},
{"Sandslash", "Field", "Field", {}},
{"Nidoran F", "Monster", "Field", {"Nidorina"}},
{"Nidorina", "No Eggs Discovered", "No Eggs Discovered", {"Nidoqueen"}},
{"Nidoqueen", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Nidoran M", "Monster", "Field", {"Nidorino"}},
{"Nidorino", "Monster", "Field", {"Nidoking"}},
{"Nidoking", "Monster", "Field", {}},
{"Cleffa", "No Eggs Discovered", "No Eggs Discovered", {"Clefairy"}},
{"Clefairy", "Fairy", "Fairy", {"Clefable"}},
{"Clefable", "Fairy", "Fairy", {}},
{"Vulpix", "Field", "Field", {"Ninetales"}},
{"Ninetales", "Field", "Field", {}},
{"Igglybuff", "No Eggs Discovered", "No Eggs Discovered", {"Jigglypuff"}},
{"Jigglypuff", "Fairy", "Fairy", {"Wigglytuff"}},
{"Wigglytuff", "Fairy", "Fairy", {}},
{"Zubat", "Flying", "Flying", {"Golbat"}},
{"Golbat", "Flying", "Flying", {"Crobat"}},
{"Crobat", "Flying", "Flying", {}},
{"Oddish", "Grass", "Grass", {"Gloom"}},
{"Gloom", "Grass", "Grass", {"Vileplume", "Bellossom"}},
{"Vileplume", "Grass", "Grass", {}},
{"Bellossom", "Grass", "Grass", {}},
{"Paras", "Bug", "Grass", {"Parasect"}},
{"Parasect", "Bug", "Grass", {}},
{"Venonat", "Bug", "Bug", {"Venomoth"}},
{"Venomoth", "Bug", "Bug", {}},
{"Diglett", "Field", "Field", {"Dugtrio"}},
{"Dugtrio", "Field", "Field", {}},
{"Meowth", "Field", "Field", {"Persian"}},
{"Persian", "Field", "Field", {}},
{"Psyduck", "Water 1", "Field", {"Golduck"}},
{"Golduck", "Water 1", "Field", {}},
{"Mankey", "Field", "Field", {"Primeape"}},
{"Primeape", "Field", "Field", {}},
{"Growlithe", "Field", "Field", {"Arcanine"}},
{"Arcanine", "Field", "Field", {}},
{"Poliwag", "Water 1", "Water 1", {"Poliwhirl"}},
{"Poliwhirl", "Water 1", "Water 1", {"Poliwrath", "Politoed"}},
{"Poliwrath", "Water 1", "Water 1", {}},
{"Politoed", "Water 1", "Water 1", {}},
{"Abra", "Human-Like", "Human-Like", {"Kadabra"}},
{"Kadabra", "Human-Like", "Human-Like", {"Alakazam"}},
{"Alakazam", "Human-Like", "Human-Like", {}},
{"Machop", "Human-Like", "Human-Like", {"Machoke"}},
{"Machoke", "Human-Like", "Human-Like", {"Machamp"}},
{"Machamp", "Human-Like", "Human-Like", {}},
{"Bellsprout", "Grass", "Grass", {"Weepinbell"}},
{"Weepinbell", "Grass", "Grass", {"Victreebel"}},
{"Victreebel", "Grass", "Grass", {}},
{"Tentacool", "Water 3", "Water 3", {"Tentacruel"}},
{"Tentacruel", "Water 3", "Water 3", {}},
{"Geodude", "Mineral", "Mineral", {"Graveler"}},
{"Graveler", "Mineral", "Mineral", {"Golem"}},
{"Golem", "Mineral", "Mineral", {}},
{"Ponyta", "Field", "Field", {"Rapidash"}},
{"Rapidash", "Field", "Field", {}},
{"Slowpoke", "Monster", "Water 1", {"Slowbro", "Slowking"}},
{"Slowbro", "Monster", "Water 1", {}},
{"Slowking", "Monster", "Water 1", {}},
{"Magnemite", "Mineral", "Mineral", {"Magneton"}},
{"Magneton", "Mineral", "Mineral", {}},
{"Farfetch'd", "Flying", "Field", {}},
{"Doduo", "Flying", "Flying", {"Dodrio"}},
{"Dodrio", "Flying", "Flying", {}},
{"Seel", "Water 1", "Field", {"Dewgong"}},
{"Dewgong", "Water 1", "Field", {}},
{"Grimer", "Amorphous", "Amorphous", {"Muk"}},
{"Muk", "Amorphous", "Amorphous", {}},
{"Shellder", "Water 3", "Water 3", {"Cloyster"}},
{"Cloyster", "Water 3", "Water 3", {}},
{"Gastly", "Amorphous", "Amorphous", {"Haunter"}},
{"Haunter", "Amorphous", "Amorphous", {"Gengar"}},
{"Gengar", "Amorphous", "Amorphous", {}},
{"Onix", "Mineral", "Mineral", {"Steelix"}},
{"Steelix", "Mineral", "Mineral", {}},
{"Drowzee", "Human-Like", "Human-Like", {"Hypno"}},
{"Hypno", "Human-Like", "Human-Like", {}},
{"Krabby", "Water 3", "Water 3", {"Kingler"}},
{"Kingler", "Water 3", "Water 3", {}},
{"Voltorb", "Mineral", "Mineral", {"Electrode"}},
{"Electrode", "Mineral", "Mineral", {}},
{"Exeggcute", "Grass", "Grass", {"Exeggutor"}},
{"Exeggutor", "Grass", "Grass", {}},
{"Cubone", "Monster", "Monster", {"Marowak"}},
{"Marowak", "Monster", "Monster", {}},
{"Tyrogue", "No Eggs Discovered", "No Eggs Discovered", {"Hitmonlee", "Hitmonchan", "Hitmontop"}},
{"Hitmonlee", "Human-Like", "Human-Like", {}},
{"Hitmonchan", "Human-Like", "Human-Like", {}},
{"Hitmontop", "Human-Like", "Human-Like", {}},
{"Lickitung", "Monster", "Monster", {}},
{"Koffing", "Amorphous", "Amorphous", {"Weezing"}},
{"Weezing", "Amorphous", "Amorphous", {}},
{"Rhyhorn", "Monster", "Field", {"Rhydon"}},
{"Rhydon", "Monster", "Field", {}},
{"Chansey", "Fairy", "Fairy", {"Blissey"}},
{"Blissey", "Fairy", "Fairy", {}},
{"Tangela", "Grass", "Grass", {}},
{"Kangaskhan", "Monster", "Monster", {}},
{"Horsea", "Water 1", "Dragon", {"Seadra"}},
{"Seadra", "Water 1", "Dragon", {"Kingdra"}},
{"Kingdra", "Water 1", "Dragon", {}},
{"Goldeen", "Water 2", "Water 2", {"Seaking"}},
{"Seaking", "Water 2", "Water 2", {}},
{"Staryu", "Water 3", "Water 3", {"Starmie"}},
{"Starmie", "Water 3", "Water 3", {}},
{"Mr. Mime", "Human-Like", "Human-Like", {}},
{"Scyther", "Bug", "Bug", {"Scizor"}},
{"Scizor", "Bug", "Bug", {}},
{"Smoochum", "No Eggs Discovered", "No Eggs Discovered", {"Jynx"}},
{"Jynx", "Human-Like", "Human-Like", {}},
{"Elekid", "No Eggs Discovered", "No Eggs Discovered", {"Electabuzz"}},
{"Electabuzz", "Human-Like", "Human-Like", {}},
{"Magby", "No Eggs Discovered", "No Eggs Discovered", {"Magmar"}},
{"Magmar", "Human-Like", "Human-Like", {}},
{"Pinsir", "Bug", "Bug", {}},
{"Tauros", "Field", "Field", {}},
{"Magikarp", "Water 2", "Dragon", {"Gyarados"}},
{"Gyarados", "Water 2", "Dragon", {}},
{"Lapras", "Monster", "Water 1", {}},
{"Ditto", "Ditto", "Ditto", {}},
{"Eevee", "Field", "Field", {"Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon"}},
{"Vaporeon", "Field", "Field", {}},
{"Jolteon", "Field", "Field", {}},
{"Flareon", "Field", "Field", {}},
{"Espeon", "Field", "Field", {}},
{"Umbreon", "Field", "Field", {}},
{"Porygon", "Mineral", "Mineral", {"Porygon2"}},
{"Porygon2", "Mineral", "Mineral", {}},
{"Omanyte", "Water 1", "Water 3", {"Omastar"}},
{"Omastar", "Water 1", "Water 3", {}},
{"Kabuto", "Water 1", "Water 3", {"Kabutops"}},
{"Kabutops", "Water 1", "Water 3", {}},
{"Aerodactyl", "Flying", "Flying", {}},
{"Snorlax", "Monster", "Monster", {}},
{"Articuno", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Zapdos", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Moltres", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Dratini", "Water 1", "Dragon", {"Dragonair"}},
{"Dragonair", "Water 1", "Dragon", {"Dragonite"}},
{"Dragonite", "Water 1", "Dragon", {}},
{"Mewtwo", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Mew", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Chikorita", "Monster", "Grass", {"Bayleef"}},
{"Bayleef", "Monster", "Grass", {"Meganium"}},
{"Meganium", "Monster", "Grass", {}},
{"Cyndaquil", "Field", "Field", {"Quilava"}},
{"Quilava", "Field", "Field", {"Typhlosion"}},
{"Typhlosion", "Field", "Field", {}},
{"Totodile", "Monster", "Water 1", {"Croconaw"}},
{"Croconaw", "Monster", "Water 1", {"Feraligatr"}},
{"Feraligatr", "Monster", "Water 1", {}},
{"Sentret", "Field", "Field", {"Furret"}},
{"Furret", "Field", "Field", {}},
{"Hoothoot", "Flying", "Flying", {"Noctowl"}},
{"Noctowl", "Flying", "Flying", {}},
{"Ledyba", "Bug", "Bug", {"Ledian"}},
{"Ledian", "Bug", "Bug", {}},
{"Spinarak", "Bug", "Bug", {"Ariados"}},
{"Ariados", "Bug", "Bug", {}},
{"Chinchou", "Water 2", "Water 2", {"Lanturn"}},
{"Lanturn", "Water 2", "Water 2", {}},
{"Togepi", "No Eggs Discovered", "No Eggs Discovered", {"Togetic"}},
{"Togetic", "Flying", "Fairy", {}},
{"Natu", "Flying", "Flying", {"Xatu"}},
{"Xatu", "Flying", "Flying", {}},
{"Mareep", "Monster", "Field", {"Flaaffy"}},
{"Flaaffy", "Monster", "Field", {"Ampharos"}},
{"Ampharos", "Monster", "Field", {}},
{"Marill", "Water 1", "Fairy", {"Azumarill"}},
{"Azumarill", "Water 1", "Fairy", {}},
{"Sudowoodo", "Mineral", "Mineral", {}},
{"Hoppip", "Fairy", "Grass", {"Skiploom"}},
{"Skiploom", "Fairy", "Grass", {"Jumpluff"}},
{"Jumpluff", "Fairy", "Grass", {}},
{"Aipom", "Field", "Field", {}},
{"Sunkern", "Grass", "Grass", {"Sunflora"}},
{"Sunflora", "Grass", "Grass", {}},
{"Yanma", "Bug", "Bug", {}},
{"Wooper", "Water 1", "Field", {"Quagsire"}},
{"Quagsire", "Water 1", "Field", {}},
{"Murkrow", "Flying", "Flying", {}},
{"Misdreavus", "Amorphous", "Amorphous", {}},
{"Unown", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Wobbuffet", "Amorphous", "Amorphous", {}},
{"Girafarig", "Field", "Field", {}},
{"Pineco", "Bug", "Bug", {"Forretress"}},
{"Forretress", "Bug", "Bug", {}},
{"Dunsparce", "Field", "Field", {}},
{"Gligar", "Bug", "Bug", {}},
{"Snubbull", "Field", "Fairy", {"Granbull"}},
{"Granbull", "Field", "Fairy", {}},
{"Qwilfish", "Water 2", "Water 2", {}},
{"Shuckle", "Bug", "Bug", {}},
{"Heracross", "Bug", "Bug", {}},
{"Sneasel", "Field", "Field", {}},
{"Teddiursa", "Field", "Field", {"Ursaring"}},
{"Ursaring", "Field", "Field", {}},
{"Slugma", "Amorphous", "Amorphous", {"Magcargo"}},
{"Magcargo", "Amorphous", "Amorphous", {}},
{"Swinub", "Field", "Field", {"Piloswine"}},
{"Piloswine", "Field", "Field", {}},
{"Corsola", "Water 1", "Water 3", {}},
{"Remoraid", "Water 1", "Water 2", {"Octillery"}},
{"Octillery", "Water 1", "Water 2", {}},
{"Delibird", "Water 1", "Field", {}},
{"Mantine", "Water 1", "Water 1", {}},
{"Skarmory", "Flying", "Flying", {}},
{"Houndour", "Field", "Field", {"Houndoom"}},
{"Houndoom", "Field", "Field", {}},
{"Phanpy", "Field", "Field", {"Donphan"}},
{"Donphan", "Field", "Field", {}},
{"Stantler", "Field", "Field", {}},
{"Smeargle", "Field", "Field", {}},
{"Miltank", "Field", "Field", {}},
{"Raikou", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Entei", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Suicune", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Larvitar", "Monster", "Monster", {"Pupitar"}},
{"Pupitar", "Monster", "Monster", {"Tyranitar"}},
{"Tyranitar", "Monster", "Monster", {}},
{"Lugia", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Ho-Oh", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Celebi", "No Eggs Discovered", "No Eggs Discovered", {}}
}
};