#ifndef DATA_GEN8
#define DATA_GEN8
#pragma once
#include "core.h"

extern Generation g_Generation8;
#endif
Generation g_Generation8 = {
"====[[Generation VIII]]====",
//UniversalTMs https://bulbapedia.bulbagarden.net/w/index.php?search=%22Every+Pok%C3%A9mon+can+learn+this+move+by%22&title=Special%3ASearch&go=Go
{
"Attract",
"Endure",
"Facade",
"Protect",
"Rest",
"Round",
"Sleep Talk",
"Snore"
},
//MonData https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_breeding_attributes https://bulbapedia.bulbagarden.net/wiki/List_of_cross-generational_evolutionary_lines
{
{"Bulbasaur", "Monster", "Grass", GR_TYPICAL, {"Ivysaur"}},
{"Ivysaur", "Monster", "Grass", GR_TYPICAL, {"Venusaur"}},
{"Venusaur", "Monster", "Grass", GR_TYPICAL, {}},
{"Charmander", "Monster", "Dragon", GR_TYPICAL, {"Charmeleon"}},
{"Charmeleon", "Monster", "Dragon", GR_TYPICAL, {"Charizard"}},
{"Charizard", "Monster", "Dragon", GR_TYPICAL, {}},
{"Squirtle", "Monster", "Water 1", GR_TYPICAL, {"Wartortle"}},
{"Wartortle", "Monster", "Water 1", GR_TYPICAL, {"Blastoise"}},
{"Blastoise", "Monster", "Water 1", GR_TYPICAL, {}},
{"Caterpie", "Bug", "Bug", GR_TYPICAL, {"Metapod"}},
{"Metapod", "Bug", "Bug", GR_TYPICAL, {"Butterfree"}},
{"Butterfree", "Bug", "Bug", GR_TYPICAL, {}},
{"Pichu", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Pikachu"}},
{"Pikachu", "Field", "Fairy", GR_TYPICAL, {"Raichu"}},
{"Raichu", "Field", "Fairy", GR_TYPICAL, {}},
{"Sandshrew", "Field", "Field", GR_TYPICAL, {"Sandslash"}},
{"Sandslash", "Field", "Field", GR_TYPICAL, {}},
{"Nidoran F", "Monster", "Field", GR_FEMALE_ONLY, {"Nidorina"}},
{"Nidorina", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, {"Nidoqueen"}},
{"Nidoqueen", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, {}},
{"Nidoran M", "Monster", "Field", GR_MALE_ONLY, {"Nidorino"}},
{"Nidorino", "Monster", "Field", GR_MALE_ONLY, {"Nidoking"}},
{"Nidoking", "Monster", "Field", GR_MALE_ONLY, {}},
{"Cleffa", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Clefairy"}},
{"Clefairy", "Fairy", "Fairy", GR_TYPICAL, {"Clefable"}},
{"Clefable", "Fairy", "Fairy", GR_TYPICAL, {}},
{"Vulpix", "Field", "Field", GR_TYPICAL, {"Ninetales"}},
{"Ninetales", "Field", "Field", GR_TYPICAL, {}},
{"Igglybuff", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Jigglypuff"}},
{"Jigglypuff", "Fairy", "Fairy", GR_TYPICAL, {"Wigglytuff"}},
{"Wigglytuff", "Fairy", "Fairy", GR_TYPICAL, {}},
{"Zubat", "Flying", "Flying", GR_TYPICAL, {"Golbat"}},
{"Golbat", "Flying", "Flying", GR_TYPICAL, {"Crobat"}},
{"Crobat", "Flying", "Flying", GR_TYPICAL, {}},
{"Oddish", "Grass", "Grass", GR_TYPICAL, {"Gloom"}},
{"Gloom", "Grass", "Grass", GR_TYPICAL, {"Vileplume", "Bellossom"}},
{"Vileplume", "Grass", "Grass", GR_TYPICAL, {}},
{"Bellossom", "Grass", "Grass", GR_TYPICAL, {}},
{"Diglett", "Field", "Field", GR_TYPICAL, {"Dugtrio"}},
{"Dugtrio", "Field", "Field", GR_TYPICAL, {}},
{"Meowth", "Field", "Field", GR_TYPICAL, {"Persian", "Perrserker"}},
{"Persian", "Field", "Field", GR_TYPICAL, {}},
{"Perrserker", "Field", "Field", GR_TYPICAL, {}},
{"Psyduck", "Water 1", "Field", GR_TYPICAL, {"Golduck"}},
{"Golduck", "Water 1", "Field", GR_TYPICAL, {}},
{"Growlithe", "Field", "Field", GR_TYPICAL, {"Arcanine"}},
{"Arcanine", "Field", "Field", GR_TYPICAL, {}},
{"Poliwag", "Water 1", "Water 1", GR_TYPICAL, {"Poliwhirl"}},
{"Poliwhirl", "Water 1", "Water 1", GR_TYPICAL, {"Poliwrath", "Politoed"}},
{"Poliwrath", "Water 1", "Water 1", GR_TYPICAL, {}},
{"Politoed", "Water 1", "Water 1", GR_TYPICAL, {}},
{"Abra", "Human-Like", "Human-Like", GR_TYPICAL, {"Kadabra"}},
{"Kadabra", "Human-Like", "Human-Like", GR_TYPICAL, {"Alakazam"}},
{"Alakazam", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Machop", "Human-Like", "Human-Like", GR_TYPICAL, {"Machoke"}},
{"Machoke", "Human-Like", "Human-Like", GR_TYPICAL, {"Machamp"}},
{"Machamp", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Tentacool", "Water 3", "Water 3", GR_TYPICAL, {"Tentacruel"}},
{"Tentacruel", "Water 3", "Water 3", GR_TYPICAL, {}},
{"Ponyta", "Field", "Field", GR_TYPICAL, {"Rapidash"}},
{"Rapidash", "Field", "Field", GR_TYPICAL, {}},
{"Slowpoke", "Monster", "Water 1", GR_TYPICAL, {"Slowbro", "Slowking"}},
{"Slowbro", "Monster", "Water 1", GR_TYPICAL, {}},
{"Slowking", "Monster", "Water 1", GR_TYPICAL, {}},
{"Magnemite", "Mineral", "Mineral", GR_UNKNOWN, {"Magneton"}},
{"Magneton", "Mineral", "Mineral", GR_UNKNOWN, {"Magnezone"}},
{"Magnezone", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Farfetch'd", "Flying", "Field", GR_TYPICAL, {"Sirfetch'd"}},
{"Sirfetch'd", "Flying", "Field", GR_TYPICAL, {}},
{"Shellder", "Water 3", "Water 3", GR_TYPICAL, {"Cloyster"}},
{"Cloyster", "Water 3", "Water 3", GR_TYPICAL, {}},
{"Gastly", "Amorphous", "Amorphous", GR_TYPICAL, {"Haunter"}},
{"Haunter", "Amorphous", "Amorphous", GR_TYPICAL, {"Gengar"}},
{"Gengar", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Onix", "Mineral", "Mineral", GR_TYPICAL, {"Steelix"}},
{"Steelix", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Krabby", "Water 3", "Water 3", GR_TYPICAL, {"Kingler"}},
{"Kingler", "Water 3", "Water 3", GR_TYPICAL, {}},
{"Exeggcute", "Grass", "Grass", GR_TYPICAL, {"Exeggutor"}},
{"Exeggutor", "Grass", "Grass", GR_TYPICAL, {}},
{"Cubone", "Monster", "Monster", GR_TYPICAL, {"Marowak"}},
{"Marowak", "Monster", "Monster", GR_TYPICAL, {}},
{"Tyrogue", "No Eggs Discovered", "No Eggs Discovered", GR_MALE_ONLY, {"Hitmonlee", "Hitmonchan", "Hitmontop"}},
{"Hitmonlee", "Human-Like", "Human-Like", GR_MALE_ONLY, {}},
{"Hitmonchan", "Human-Like", "Human-Like", GR_MALE_ONLY, {}},
{"Hitmontop", "Human-Like", "Human-Like", GR_MALE_ONLY, {}},
{"Lickitung", "Monster", "Monster", GR_TYPICAL, {"Lickilicky"}},
{"Lickilicky", "Monster", "Monster", GR_TYPICAL, {}},
{"Koffing", "Amorphous", "Amorphous", GR_TYPICAL, {"Weezing"}},
{"Weezing", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Rhyhorn", "Monster", "Field", GR_TYPICAL, {"Rhydon"}},
{"Rhydon", "Monster", "Field", GR_TYPICAL, {"Rhyperior"}},
{"Rhyperior", "Monster", "Field", GR_TYPICAL, {}},
{"Happiny", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, {"Chansey"}},
{"Chansey", "Fairy", "Fairy", GR_FEMALE_ONLY, {"Blissey"}},
{"Blissey", "Fairy", "Fairy", GR_FEMALE_ONLY, {}},
{"Tangela", "Grass", "Grass", GR_TYPICAL, {"Tangrowth"}},
{"Tangrowth", "Grass", "Grass", GR_TYPICAL, {}},
{"Kangaskhan", "Monster", "Monster", GR_FEMALE_ONLY, {}},
{"Horsea", "Water 1", "Dragon", GR_TYPICAL, {"Seadra"}},
{"Seadra", "Water 1", "Dragon", GR_TYPICAL, {"Kingdra"}},
{"Kingdra", "Water 1", "Dragon", GR_TYPICAL, {}},
{"Goldeen", "Water 2", "Water 2", GR_TYPICAL, {"Seaking"}},
{"Seaking", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Staryu", "Water 3", "Water 3", GR_UNKNOWN, {"Starmie"}},
{"Starmie", "Water 3", "Water 3", GR_UNKNOWN, {}},
{"Mime Jr.", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Mr. Mime"}},
{"Mr. Mime", "Human-Like", "Human-Like", GR_TYPICAL, {"Mr. Rime"}},
{"Mr. Rime", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Scyther", "Bug", "Bug", GR_TYPICAL, {"Scizor"}},
{"Scizor", "Bug", "Bug", GR_TYPICAL, {}},
{"Smoochum", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, {"Jynx"}},
{"Jynx", "Human-Like", "Human-Like", GR_FEMALE_ONLY, {}},
{"Elekid", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Electabuzz"}},
{"Electabuzz", "Human-Like", "Human-Like", GR_TYPICAL, {"Electivire"}},
{"Electivire", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Magby", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Magmar"}},
{"Magmar", "Human-Like", "Human-Like", GR_TYPICAL, {"Magmortar"}},
{"Magmortar", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Pinsir", "Bug", "Bug", GR_TYPICAL, {}},
{"Tauros", "Field", "Field", GR_MALE_ONLY, {}},
{"Magikarp", "Water 2", "Dragon", GR_TYPICAL, {"Gyarados"}},
{"Gyarados", "Water 2", "Dragon", GR_TYPICAL, {}},
{"Lapras", "Monster", "Water 1", GR_TYPICAL, {}},
{"Ditto", "Ditto", "Ditto", GR_UNKNOWN, {}},
{"Eevee", "Field", "Field", GR_TYPICAL, {"Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon", "Leafeon", "Glaceon", "Sylveon"}},
{"Vaporeon", "Field", "Field", GR_TYPICAL, {}},
{"Jolteon", "Field", "Field", GR_TYPICAL, {}},
{"Flareon", "Field", "Field", GR_TYPICAL, {}},
{"Espeon", "Field", "Field", GR_TYPICAL, {}},
{"Umbreon", "Field", "Field", GR_TYPICAL, {}},
{"Leafeon", "Field", "Field", GR_TYPICAL, {}},
{"Glaceon", "Field", "Field", GR_TYPICAL, {}},
{"Sylveon", "Field", "Field", GR_TYPICAL, {}},
{"Porygon", "Mineral", "Mineral", GR_UNKNOWN, {"Porygon2"}},
{"Porygon2", "Mineral", "Mineral", GR_UNKNOWN, {"Porygon-Z"}},
{"Porygon-Z", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Omanyte", "Water 1", "Water 3", GR_TYPICAL, {"Omastar"}},
{"Omastar", "Water 1", "Water 3", GR_TYPICAL, {}},
{"Kabuto", "Water 1", "Water 3", GR_TYPICAL, {"Kabutops"}},
{"Kabutops", "Water 1", "Water 3", GR_TYPICAL, {}},
{"Aerodactyl", "Flying", "Flying", GR_TYPICAL, {}},
{"Munchlax", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Snorlax"}},
{"Snorlax", "Monster", "Monster", GR_TYPICAL, {}},
{"Articuno", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Zapdos", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Moltres", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Dratini", "Water 1", "Dragon", GR_TYPICAL, {"Dragonair"}},
{"Dragonair", "Water 1", "Dragon", GR_TYPICAL, {"Dragonite"}},
{"Dragonite", "Water 1", "Dragon", GR_TYPICAL, {}},
{"Mewtwo", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Mew", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Hoothoot", "Flying", "Flying", GR_TYPICAL, {"Noctowl"}},
{"Noctowl", "Flying", "Flying", GR_TYPICAL, {}},
{"Chinchou", "Water 2", "Water 2", GR_TYPICAL, {"Lanturn"}},
{"Lanturn", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Togepi", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Togetic"}},
{"Togetic", "Flying", "Fairy", GR_TYPICAL, {"Togekiss"}},
{"Togekiss", "Flying", "Fairy", GR_TYPICAL, {}},
{"Natu", "Flying", "Flying", GR_TYPICAL, {"Xatu"}},
{"Xatu", "Flying", "Flying", GR_TYPICAL, {}},
{"Azurill", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Marill"}},
{"Marill", "Water 1", "Fairy", GR_TYPICAL, {"Azumarill"}},
{"Azumarill", "Water 1", "Fairy", GR_TYPICAL, {}},
{"Bonsly", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Sudowoodo"}},
{"Sudowoodo", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Wooper", "Water 1", "Field", GR_TYPICAL, {"Quagsire"}},
{"Quagsire", "Water 1", "Field", GR_TYPICAL, {}},
{"Wynaut", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Wobbuffet"}},
{"Wobbuffet", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Dunsparce", "Field", "Field", GR_TYPICAL, {}},
{"Qwilfish", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Shuckle", "Bug", "Bug", GR_TYPICAL, {}},
{"Heracross", "Bug", "Bug", GR_TYPICAL, {}},
{"Sneasel", "Field", "Field", GR_TYPICAL, {"Weavile"}},
{"Weavile", "Field", "Field", GR_TYPICAL, {}},
{"Swinub", "Field", "Field", GR_TYPICAL, {"Piloswine"}},
{"Piloswine", "Field", "Field", GR_TYPICAL, {"Mamoswine"}},
{"Mamoswine", "Field", "Field", GR_TYPICAL, {}},
{"Corsola", "Water 1", "Water 3", GR_TYPICAL, {"Cursola"}},
{"Cursola", "Water 1", "Water 3", GR_TYPICAL, {}},
{"Remoraid", "Water 1", "Water 2", GR_TYPICAL, {"Octillery"}},
{"Octillery", "Water 1", "Water 2", GR_TYPICAL, {}},
{"Delibird", "Water 1", "Field", GR_TYPICAL, {}},
{"Mantyke", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Mantine"}},
{"Mantine", "Water 1", "Water 1", GR_TYPICAL, {}},
{"Skarmory", "Flying", "Flying", GR_TYPICAL, {}},
{"Miltank", "Field", "Field", GR_FEMALE_ONLY, {}},
{"Raikou", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Entei", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Suicune", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Larvitar", "Monster", "Monster", GR_TYPICAL, {"Pupitar"}},
{"Pupitar", "Monster", "Monster", GR_TYPICAL, {"Tyranitar"}},
{"Tyranitar", "Monster", "Monster", GR_TYPICAL, {}},
{"Lugia", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Ho-Oh", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Celebi", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Treecko", "Monster", "Dragon", GR_TYPICAL, {"Grovyle"}},
{"Grovyle", "Monster", "Dragon", GR_TYPICAL, {"Sceptile"}},
{"Sceptile", "Monster", "Dragon", GR_TYPICAL, {}},
{"Torchic", "Field", "Field", GR_TYPICAL, {"Combusken"}},
{"Combusken", "Field", "Field", GR_TYPICAL, {"Blaziken"}},
{"Blaziken", "Field", "Field", GR_TYPICAL, {}},
{"Mudkip", "Monster", "Water 1", GR_TYPICAL, {"Marshtomp"}},
{"Marshtomp", "Monster", "Water 1", GR_TYPICAL, {"Swampert"}},
{"Swampert", "Monster", "Water 1", GR_TYPICAL, {}},
{"Zigzagoon", "Field", "Field", GR_TYPICAL, {"Linoone"}},
{"Linoone", "Field", "Field", GR_TYPICAL, {"Obstagoon"}},
{"Obstagoon", "Field", "Field", GR_TYPICAL, {}},
{"Lotad", "Water 1", "Grass", GR_TYPICAL, {"Lombre"}},
{"Lombre", "Water 1", "Grass", GR_TYPICAL, {"Ludicolo"}},
{"Ludicolo", "Water 1", "Grass", GR_TYPICAL, {}},
{"Seedot", "Field", "Grass", GR_TYPICAL, {"Nuzleaf"}},
{"Nuzleaf", "Field", "Grass", GR_TYPICAL, {"Shiftry"}},
{"Shiftry", "Field", "Grass", GR_TYPICAL, {}},
{"Wingull", "Water 1", "Flying", GR_TYPICAL, {"Pelipper"}},
{"Pelipper", "Water 1", "Flying", GR_TYPICAL, {}},
{"Ralts", "Human-Like", "Amorphous", GR_TYPICAL, {"Kirlia"}},
{"Kirlia", "Human-Like", "Amorphous", GR_MALE_ONLY, {"Gardevoir", "Gallade"}},
{"Gardevoir", "Human-Like", "Amorphous", GR_TYPICAL, {}},
{"Gallade", "Human-Like", "Amorphous", GR_MALE_ONLY, {}},
{"Nincada", "Bug", "Bug", GR_UNKNOWN, {"Ninjask", "Shedinja"}},
{"Ninjask", "Bug", "Bug", GR_TYPICAL, {}},
{"Shedinja", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Whismur", "Monster", "Field", GR_TYPICAL, {"Loudred"}},
{"Loudred", "Monster", "Field", GR_TYPICAL, {"Exploud"}},
{"Exploud", "Monster", "Field", GR_TYPICAL, {}},
{"Sableye", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Mawile", "Field", "Fairy", GR_TYPICAL, {}},
{"Aron", "Monster", "Monster", GR_TYPICAL, {"Lairon"}},
{"Lairon", "Monster", "Monster", GR_TYPICAL, {"Aggron"}},
{"Aggron", "Monster", "Monster", GR_TYPICAL, {}},
{"Electrike", "Field", "Field", GR_TYPICAL, {"Manectric"}},
{"Manectric", "Field", "Field", GR_TYPICAL, {}},
{"Budew", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Roselia"}},
{"Roselia", "Fairy", "Grass", GR_TYPICAL, {"Roserade"}},
{"Roserade", "Fairy", "Grass", GR_TYPICAL, {}},
{"Carvanha", "Water 2", "Water 2", GR_TYPICAL, {"Sharpedo"}},
{"Sharpedo", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Wailmer", "Field", "Water 2", GR_TYPICAL, {"Wailord"}},
{"Wailord", "Field", "Water 2", GR_TYPICAL, {}},
{"Torkoal", "Field", "Field", GR_TYPICAL, {}},
{"Trapinch", "Bug", "Dragon", GR_TYPICAL, {"Vibrava"}},
{"Vibrava", "Bug", "Dragon", GR_TYPICAL, {"Flygon"}},
{"Flygon", "Bug", "Dragon", GR_TYPICAL, {}},
{"Swablu", "Flying", "Dragon", GR_TYPICAL, {"Altaria"}},
{"Altaria", "Flying", "Dragon", GR_TYPICAL, {}},
{"Lunatone", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Solrock", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Barboach", "Water 2", "Water 2", GR_TYPICAL, {"Whiscash"}},
{"Whiscash", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Corphish", "Water 1", "Water 3", GR_TYPICAL, {"Crawdaunt"}},
{"Crawdaunt", "Water 1", "Water 3", GR_TYPICAL, {}},
{"Baltoy", "Mineral", "Mineral", GR_UNKNOWN, {"Claydol"}},
{"Claydol", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Lileep", "Water 3", "Water 3", GR_TYPICAL, {"Cradily"}},
{"Cradily", "Water 3", "Water 3", GR_TYPICAL, {}},
{"Anorith", "Water 3", "Water 3", GR_TYPICAL, {"Armaldo"}},
{"Armaldo", "Water 3", "Water 3", GR_TYPICAL, {}},
{"Feebas", "Water 1", "Dragon", GR_TYPICAL, {"Milotic"}},
{"Milotic", "Water 1", "Dragon", GR_TYPICAL, {}},
{"Duskull", "Amorphous", "Amorphous", GR_TYPICAL, {"Dusclops"}},
{"Dusclops", "Amorphous", "Amorphous", GR_TYPICAL, {"Dusknoir"}},
{"Dusknoir", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Absol", "Field", "Field", GR_TYPICAL, {}},
{"Snorunt", "Fairy", "Mineral", GR_FEMALE_ONLY, {"Glalie", "Froslass"}},
{"Glalie", "Fairy", "Mineral", GR_TYPICAL, {}},
{"Froslass", "Fairy", "Mineral", GR_FEMALE_ONLY, {}},
{"Spheal", "Water 1", "Field", GR_TYPICAL, {"Sealeo"}},
{"Sealeo", "Water 1", "Field", GR_TYPICAL, {"Walrein"}},
{"Walrein", "Water 1", "Field", GR_TYPICAL, {}},
{"Relicanth", "Water 1", "Water 2", GR_TYPICAL, {}},
{"Bagon", "Dragon", "Dragon", GR_TYPICAL, {"Shelgon"}},
{"Shelgon", "Dragon", "Dragon", GR_TYPICAL, {"Salamence"}},
{"Salamence", "Dragon", "Dragon", GR_TYPICAL, {}},
{"Beldum", "Mineral", "Mineral", GR_UNKNOWN, {"Metang"}},
{"Metang", "Mineral", "Mineral", GR_UNKNOWN, {"Metagross"}},
{"Metagross", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Regirock", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Regice", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Registeel", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Latias", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, {}},
{"Latios", "No Eggs Discovered", "No Eggs Discovered", GR_MALE_ONLY, {}},
{"Kyogre", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Groudon", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Rayquaza", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Jirachi", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Shinx", "Field", "Field", GR_TYPICAL, {"Luxio"}},
{"Luxio", "Field", "Field", GR_TYPICAL, {"Luxray"}},
{"Luxray", "Field", "Field", GR_TYPICAL, {}},
{"Combee", "Bug", "Bug", GR_FEMALE_ONLY, {"Vespiquen"}},
{"Vespiquen", "Bug", "Bug", GR_FEMALE_ONLY, {}},
{"Cherubi", "Fairy", "Grass", GR_TYPICAL, {"Cherrim"}},
{"Cherrim", "Fairy", "Grass", GR_TYPICAL, {}},
{"Shellos", "Water 1", "Amorphous", GR_TYPICAL, {"Gastrodon"}},
{"Gastrodon", "Water 1", "Amorphous", GR_TYPICAL, {}},
{"Drifloon", "Amorphous", "Amorphous", GR_TYPICAL, {"Drifblim"}},
{"Drifblim", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Buneary", "Field", "Human-Like", GR_TYPICAL, {"Lopunny"}},
{"Lopunny", "Field", "Human-Like", GR_TYPICAL, {}},
{"Stunky", "Field", "Field", GR_TYPICAL, {"Skuntank"}},
{"Skuntank", "Field", "Field", GR_TYPICAL, {}},
{"Bronzor", "Mineral", "Mineral", GR_UNKNOWN, {"Bronzong"}},
{"Bronzong", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Spiritomb", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Gible", "Monster", "Dragon", GR_TYPICAL, {"Gabite"}},
{"Gabite", "Monster", "Dragon", GR_TYPICAL, {"Garchomp"}},
{"Garchomp", "Monster", "Dragon", GR_TYPICAL, {}},
{"Riolu", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Lucario"}},
{"Lucario", "Field", "Human-Like", GR_TYPICAL, {}},
{"Hippopotas", "Field", "Field", GR_TYPICAL, {"Hippowdon"}},
{"Hippowdon", "Field", "Field", GR_TYPICAL, {}},
{"Skorupi", "Bug", "Water 3", GR_TYPICAL, {"Drapion"}},
{"Drapion", "Bug", "Water 3", GR_TYPICAL, {}},
{"Croagunk", "Human-Like", "Human-Like", GR_TYPICAL, {"Toxicroak"}},
{"Toxicroak", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Snover", "Monster", "Grass", GR_TYPICAL, {"Abomasnow"}},
{"Abomasnow", "Monster", "Grass", GR_TYPICAL, {}},
{"Rotom", "Amorphous", "Amorphous", GR_UNKNOWN, {}},
{"Uxie", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Mesprit", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Azelf", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Dialga", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Palkia", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Heatran", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {}},
{"Regigigas", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Giratina", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Cresselia", "No Eggs Discovered", "No Eggs Discovered", GR_FEMALE_ONLY, {}},
{"Victini", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Lillipup", "Field", "Field", GR_TYPICAL, {"Herdier"}},
{"Herdier", "Field", "Field", GR_TYPICAL, {"Stoutland"}},
{"Stoutland", "Field", "Field", GR_TYPICAL, {}},
{"Purrloin", "Field", "Field", GR_TYPICAL, {"Liepard"}},
{"Liepard", "Field", "Field", GR_TYPICAL, {}},
{"Munna", "Field", "Field", GR_TYPICAL, {"Musharna"}},
{"Musharna", "Field", "Field", GR_TYPICAL, {}},
{"Pidove", "Flying", "Flying", GR_TYPICAL, {"Tranquill"}},
{"Tranquill", "Flying", "Flying", GR_TYPICAL, {"Unfezant"}},
{"Unfezant", "Flying", "Flying", GR_TYPICAL, {}},
{"Roggenrola", "Mineral", "Mineral", GR_TYPICAL, {"Boldore"}},
{"Boldore", "Mineral", "Mineral", GR_TYPICAL, {"Gigalith"}},
{"Gigalith", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Woobat", "Field", "Flying", GR_TYPICAL, {"Swoobat"}},
{"Swoobat", "Field", "Flying", GR_TYPICAL, {}},
{"Drilbur", "Field", "Field", GR_TYPICAL, {"Excadrill"}},
{"Excadrill", "Field", "Field", GR_TYPICAL, {}},
{"Audino", "Fairy", "Fairy", GR_TYPICAL, {}},
{"Timburr", "Human-Like", "Human-Like", GR_TYPICAL, {"Gurdurr"}},
{"Gurdurr", "Human-Like", "Human-Like", GR_TYPICAL, {"Conkeldurr"}},
{"Conkeldurr", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Tympole", "Water 1", "Water 1", GR_TYPICAL, {"Palpitoad"}},
{"Palpitoad", "Water 1", "Water 1", GR_TYPICAL, {"Seismitoad"}},
{"Seismitoad", "Water 1", "Water 1", GR_TYPICAL, {}},
{"Throh", "Human-Like", "Human-Like", GR_MALE_ONLY, {}},
{"Sawk", "Human-Like", "Human-Like", GR_MALE_ONLY, {}},
{"Venipede", "Bug", "Bug", GR_TYPICAL, {"Whirlipede"}},
{"Whirlipede", "Bug", "Bug", GR_TYPICAL, {"Scolipede"}},
{"Scolipede", "Bug", "Bug", GR_TYPICAL, {}},
{"Cottonee", "Grass", "Fairy", GR_TYPICAL, {}},
{"Whimsicott", "Grass", "Fairy", GR_FEMALE_ONLY, {"Petilil"}},
{"Petilil", "Grass", "Grass", GR_FEMALE_ONLY, {"Lilligant"}},
{"Lilligant", "Grass", "Grass", GR_FEMALE_ONLY, {}},
{"Basculin", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Sandile", "Field", "Field", GR_TYPICAL, {"Krokorok"}},
{"Krokorok", "Field", "Field", GR_TYPICAL, {"Krookodile"}},
{"Krookodile", "Field", "Field", GR_TYPICAL, {}},
{"Darumaka", "Field", "Field", GR_TYPICAL, {"Darmanitan"}},
{"Darmanitan", "Field", "Field", GR_TYPICAL, {}},
{"Maractus", "Grass", "Grass", GR_TYPICAL, {}},
{"Dwebble", "Bug", "Mineral", GR_TYPICAL, {"Crustle"}},
{"Crustle", "Bug", "Mineral", GR_TYPICAL, {}},
{"Scraggy", "Field", "Dragon", GR_TYPICAL, {"Scrafty"}},
{"Scrafty", "Field", "Dragon", GR_TYPICAL, {}},
{"Sigilyph", "Flying", "Flying", GR_TYPICAL, {}},
{"Yamask", "Mineral", "Amorphous", GR_TYPICAL, {"Cofagrigus", "Runerigus"}},
{"Cofagrigus", "Mineral", "Amorphous", GR_TYPICAL, {}},
{"Runerigus", "Mineral", "Amorphous", GR_TYPICAL, {}},
{"Tirtouga", "Water 1", "Water 3", GR_TYPICAL, {"Carracosta"}},
{"Carracosta", "Water 1", "Water 3", GR_TYPICAL, {}},
{"Archen", "Flying", "Water 3", GR_TYPICAL, {"Archeops"}},
{"Archeops", "Flying", "Water 3", GR_TYPICAL, {}},
{"Trubbish", "Mineral", "Mineral", GR_TYPICAL, {"Garbodor"}},
{"Garbodor", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Zorua", "Field", "Field", GR_TYPICAL, {"Zoroark"}},
{"Zoroark", "Field", "Field", GR_TYPICAL, {}},
{"Minccino", "Field", "Field", GR_TYPICAL, {"Cinccino"}},
{"Cinccino", "Field", "Field", GR_TYPICAL, {}},
{"Gothita", "Human-Like", "Human-Like", GR_TYPICAL, {"Gothorita"}},
{"Gothorita", "Human-Like", "Human-Like", GR_TYPICAL, {"Gothitelle"}},
{"Gothitelle", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Solosis", "Amorphous", "Amorphous", GR_TYPICAL, {"Duosion"}},
{"Duosion", "Amorphous", "Amorphous", GR_TYPICAL, {"Reuniclus"}},
{"Reuniclus", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Vanillite", "Mineral", "Mineral", GR_TYPICAL, {"Vanillish"}},
{"Vanillish", "Mineral", "Mineral", GR_TYPICAL, {"Vanilluxe"}},
{"Vanilluxe", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Emolga", "Field", "Field", GR_TYPICAL, {}},
{"Karrablast", "Bug", "Bug", GR_TYPICAL, {"Escavalier"}},
{"Escavalier", "Bug", "Bug", GR_TYPICAL, {}},
{"Foongus", "Grass", "Grass", GR_TYPICAL, {"Amoonguss"}},
{"Amoonguss", "Grass", "Grass", GR_TYPICAL, {}},
{"Frillish", "Amorphous", "Amorphous", GR_TYPICAL, {"Jellicent"}},
{"Jellicent", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Joltik", "Bug", "Bug", GR_TYPICAL, {"Galvantula"}},
{"Galvantula", "Bug", "Bug", GR_TYPICAL, {}},
{"Ferroseed", "Grass", "Mineral", GR_TYPICAL, {"Ferrothorn"}},
{"Ferrothorn", "Grass", "Mineral", GR_TYPICAL, {}},
{"Klink", "Mineral", "Mineral", GR_UNKNOWN, {"Klang"}},
{"Klang", "Mineral", "Mineral", GR_UNKNOWN, {"Klinklang"}},
{"Klinklang", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Elgyem", "Human-Like", "Human-Like", GR_TYPICAL, {"Beheeyem"}},
{"Beheeyem", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Litwick", "Amorphous", "Amorphous", GR_TYPICAL, {"Lampent"}},
{"Lampent", "Amorphous", "Amorphous", GR_TYPICAL, {"Chandelure"}},
{"Chandelure", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Axew", "Monster", "Dragon", GR_TYPICAL, {"Fraxure"}},
{"Fraxure", "Monster", "Dragon", GR_TYPICAL, {"Haxorus"}},
{"Haxorus", "Monster", "Dragon", GR_TYPICAL, {}},
{"Cubchoo", "Field", "Field", GR_TYPICAL, {"Beartic"}},
{"Beartic", "Field", "Field", GR_TYPICAL, {}},
{"Cryogonal", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Shelmet", "Bug", "Bug", GR_TYPICAL, {"Accelgor"}},
{"Accelgor", "Bug", "Bug", GR_TYPICAL, {}},
{"Stunfisk", "Water 1", "Amorphous", GR_TYPICAL, {}},
{"Mienfoo", "Field", "Human-Like", GR_TYPICAL, {"Mienshao"}},
{"Mienshao", "Field", "Human-Like", GR_TYPICAL, {}},
{"Druddigon", "Dragon", "Monster", GR_TYPICAL, {}},
{"Golett", "Mineral", "Mineral", GR_UNKNOWN, {"Golurk"}},
{"Golurk", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Pawniard", "Human-Like", "Human-Like", GR_TYPICAL, {"Bisharp"}},
{"Bisharp", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Bouffalant", "Field", "Field", GR_TYPICAL, {}},
{"Rufflet", "Flying", "Flying", GR_MALE_ONLY, {"Braviary"}},
{"Braviary", "Flying", "Flying", GR_MALE_ONLY, {}},
{"Vullaby", "Flying", "Flying", GR_FEMALE_ONLY, {"Mandibuzz"}},
{"Mandibuzz", "Flying", "Flying", GR_FEMALE_ONLY, {}},
{"Heatmor", "Field", "Field", GR_TYPICAL, {}},
{"Durant", "Bug", "Bug", GR_TYPICAL, {}},
{"Deino", "Dragon", "Dragon", GR_TYPICAL, {"Zweilous"}},
{"Zweilous", "Dragon", "Dragon", GR_TYPICAL, {"Hydreigon"}},
{"Hydreigon", "Dragon", "Dragon", GR_TYPICAL, {}},
{"Larvesta", "Bug", "Bug", GR_TYPICAL, {"Volcarona"}},
{"Volcarona", "Bug", "Bug", GR_TYPICAL, {}},
{"Cobalion", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Terrakion", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Virizion", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Tornadus", "No Eggs Discovered", "No Eggs Discovered", GR_MALE_ONLY, {}},
{"Thundurus", "No Eggs Discovered", "No Eggs Discovered", GR_MALE_ONLY, {}},
{"Reshiram", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Zekrom", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Landorus", "No Eggs Discovered", "No Eggs Discovered", GR_MALE_ONLY, {}},
{"Kyurem", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Keldeo", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Genesect", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Bunnelby", "Field", "Field", GR_TYPICAL, {"Diggersby"}},
{"Diggersby", "Field", "Field", GR_TYPICAL, {}},
{"Fletchling", "Flying", "Flying", GR_TYPICAL, {"Fletchinder"}},
{"Fletchinder", "Flying", "Flying", GR_TYPICAL, {"Talonflame"}},
{"Talonflame", "Flying", "Flying", GR_TYPICAL, {}},
{"Pancham", "Field", "Human-Like", GR_TYPICAL, {"Pangoro"}},
{"Pangoro", "Field", "Human-Like", GR_TYPICAL, {}},
{"Espurr", "Field", "Field", GR_TYPICAL, {"Meowstic"}},
{"Meowstic", "Field", "Field", GR_TYPICAL, {}},
{"Honedge", "Mineral", "Mineral", GR_TYPICAL, {"Doublade"}},
{"Doublade", "Mineral", "Mineral", GR_TYPICAL, {"Aegislash"}},
{"Aegislash", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Spritzee", "Fairy", "Fairy", GR_TYPICAL, {"Aromatisse"}},
{"Aromatisse", "Fairy", "Fairy", GR_TYPICAL, {}},
{"Swirlix", "Fairy", "Fairy", GR_TYPICAL, {"Slurpuff"}},
{"Slurpuff", "Fairy", "Fairy", GR_TYPICAL, {}},
{"Inkay", "Water 1", "Water 2", GR_TYPICAL, {"Malamar"}},
{"Malamar", "Water 1", "Water 2", GR_TYPICAL, {}},
{"Binacle", "Water 3", "Water 3", GR_TYPICAL, {"Barbaracle"}},
{"Barbaracle", "Water 3", "Water 3", GR_TYPICAL, {}},
{"Skrelp", "Water 1", "Dragon", GR_TYPICAL, {"Dragalge"}},
{"Dragalge", "Water 1", "Dragon", GR_TYPICAL, {}},
{"Clauncher", "Water 1", "Water 3", GR_TYPICAL, {"Clawitzer"}},
{"Clawitzer", "Water 1", "Water 3", GR_TYPICAL, {}},
{"Helioptile", "Monster", "Dragon", GR_TYPICAL, {"Heliolisk"}},
{"Heliolisk", "Monster", "Dragon", GR_TYPICAL, {}},
{"Tyrunt", "Monster", "Dragon", GR_TYPICAL, {"Tyrantrum"}},
{"Tyrantrum", "Monster", "Dragon", GR_TYPICAL, {}},
{"Amaura", "Monster", "Monster", GR_TYPICAL, {"Aurorus"}},
{"Aurorus", "Monster", "Monster", GR_TYPICAL, {}},
{"Hawlucha", "Flying", "Human-Like", GR_TYPICAL, {}},
{"Dedenne", "Field", "Fairy", GR_TYPICAL, {}},
{"Carbink", "Fairy", "Mineral", GR_UNKNOWN, {}},
{"Goomy", "Dragon", "Dragon", GR_TYPICAL, {"Sliggoo"}},
{"Sliggoo", "Dragon", "Dragon", GR_TYPICAL, {"Goodra"}},
{"Goodra", "Dragon", "Dragon", GR_TYPICAL, {}},
{"Klefki", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Phantump", "Grass", "Amorphous", GR_TYPICAL, {"Trevenant"}},
{"Trevenant", "Grass", "Amorphous", GR_TYPICAL, {}},
{"Pumpkaboo", "Amorphous", "Amorphous", GR_TYPICAL, {"Gourgeist"}},
{"Gourgeist", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Bergmite", "Monster", "Mineral", GR_TYPICAL, {"Avalugg"}},
{"Avalugg", "Monster", "Mineral", GR_TYPICAL, {}},
{"Noibat", "Flying", "Dragon", GR_TYPICAL, {"Noivern"}},
{"Noivern", "Flying", "Dragon", GR_TYPICAL, {}},
{"Xerneas", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Yveltal", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Zygarde", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Diancie", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Volcanion", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Rowlet", "Flying", "Flying", GR_TYPICAL, {"Dartrix"}},
{"Dartrix", "Flying", "Flying", GR_TYPICAL, {"Decidueye"}},
{"Decidueye", "Flying", "Flying", GR_TYPICAL, {}},
{"Litten", "Field", "Field", GR_TYPICAL, {"Torracat"}},
{"Torracat", "Field", "Field", GR_TYPICAL, {"Incineroar"}},
{"Incineroar", "Field", "Field", GR_TYPICAL, {}},
{"Popplio", "Water 1", "Field", GR_TYPICAL, {"Brionne"}},
{"Brionne", "Water 1", "Field", GR_TYPICAL, {"Primarina"}},
{"Primarina", "Water 1", "Field", GR_TYPICAL, {}},
{"Grubbin", "Bug", "Bug", GR_TYPICAL, {"Charjabug"}},
{"Charjabug", "Bug", "Bug", GR_TYPICAL, {"Vikavolt"}},
{"Vikavolt", "Bug", "Bug", GR_TYPICAL, {}},
{"Cutiefly", "Bug", "Fairy", GR_TYPICAL, {"Ribombee"}},
{"Ribombee", "Bug", "Fairy", GR_TYPICAL, {}},
{"Rockruff", "Field", "Field", GR_TYPICAL, {"Lycanroc"}},
{"Lycanroc", "Field", "Field", GR_TYPICAL, {}},
{"Wishiwashi", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Mareanie", "Water 1", "Water 1", GR_TYPICAL, {"Toxapex"}},
{"Toxapex", "Water 1", "Water 1", GR_TYPICAL, {}},
{"Mudbray", "Field", "Field", GR_TYPICAL, {"Mudsdale"}},
{"Mudsdale", "Field", "Field", GR_TYPICAL, {}},
{"Dewpider", "Water 1", "Bug", GR_TYPICAL, {"Araquanid"}},
{"Araquanid", "Water 1", "Bug", GR_TYPICAL, {}},
{"Fomantis", "Grass", "Grass", GR_TYPICAL, {"Lurantis"}},
{"Lurantis", "Grass", "Grass", GR_TYPICAL, {}},
{"Morelull", "Grass", "Grass", GR_TYPICAL, {"Shiinotic"}},
{"Shiinotic", "Grass", "Grass", GR_TYPICAL, {}},
{"Salandit", "Monster", "Dragon", GR_FEMALE_ONLY, {"Salazzle"}},
{"Salazzle", "Monster", "Dragon", GR_FEMALE_ONLY, {}},
{"Stufful", "Field", "Field", GR_TYPICAL, {"Bewear"}},
{"Bewear", "Field", "Field", GR_TYPICAL, {}},
{"Bounsweet", "Grass", "Grass", GR_FEMALE_ONLY, {"Steenee"}},
{"Steenee", "Grass", "Grass", GR_FEMALE_ONLY, {"Tsareena"}},
{"Tsareena", "Grass", "Grass", GR_FEMALE_ONLY, {}},
{"Comfey", "Grass", "Grass", GR_TYPICAL, {}},
{"Oranguru", "Field", "Field", GR_TYPICAL, {"Passimian"}},
{"Passimian", "Field", "Field", GR_TYPICAL, {}},
{"Wimpod", "Bug", "Water 3", GR_TYPICAL, {"Golisopod"}},
{"Golisopod", "Bug", "Water 3", GR_TYPICAL, {}},
{"Sandygast", "Amorphous", "Amorphous", GR_TYPICAL, {"Palossand"}},
{"Palossand", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Pyukumuku", "Water 1", "Water 1", GR_TYPICAL, {}},
{"Type: Null", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {"Silvally"}},
{"Silvally", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Turtonator", "Monster", "Dragon", GR_TYPICAL, {}},
{"Togedemaru", "Field", "Fairy", GR_TYPICAL, {}},
{"Mimikyu", "Amorphous", "Amorphous", GR_TYPICAL, {}},
{"Drampa", "Monster", "Dragon", GR_TYPICAL, {}},
{"Dhelmise", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Jangmo-o", "Dragon", "Dragon", GR_TYPICAL, {"Hakamo-o"}},
{"Hakamo-o", "Dragon", "Dragon", GR_TYPICAL, {"Kommo-o"}},
{"Kommo-o", "Dragon", "Dragon", GR_TYPICAL, {}},
{"Tapu Koko", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Tapu Lele", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Tapu Bulu", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Tapu Fini", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Cosmog", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {"Cosmoem"}},
{"Cosmoem", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {"Solgaleo", "Lunala"}},
{"Solgaleo", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Lunala", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Nihilego", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Buzzwole", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Pheromosa", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Xurkitree", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Celesteela", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Kartana", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Guzzlord", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Necrozma", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Magearna", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Marshadow", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Poipole", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {"Naganadel"}},
{"Naganadel", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Stakataka", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Blacephalon", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Zeraora", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Meltan", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {"Melmetal"}},
{"Melmetal", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Grookey", "Field", "Grass", GR_TYPICAL, {"Thwackey"}},
{"Thwackey", "Field", "Grass", GR_TYPICAL, {"Rillaboom"}},
{"Rillaboom", "Field", "Grass", GR_TYPICAL, {}},
{"Scorbunny", "Field", "Human-Like", GR_TYPICAL, {"Raboot"}},
{"Raboot", "Field", "Human-Like", GR_TYPICAL, {"Cinderace"}},
{"Cinderace", "Field", "Human-Like", GR_TYPICAL, {}},
{"Sobble", "Water 1", "Field", GR_TYPICAL, {"Drizzile"}},
{"Drizzile", "Water 1", "Field", GR_TYPICAL, {"Inteleon"}},
{"Inteleon", "Water 1", "Field", GR_TYPICAL, {}},
{"Skwovet", "Field", "Field", GR_TYPICAL, {"Greedent"}},
{"Greedent", "Field", "Field", GR_TYPICAL, {}},
{"Rookidee", "Flying", "Flying", GR_TYPICAL, {"Corvisquire"}},
{"Corvisquire", "Flying", "Flying", GR_TYPICAL, {"Corviknight"}},
{"Corviknight", "Flying", "Flying", GR_TYPICAL, {}},
{"Blipbug", "Bug", "Bug", GR_TYPICAL, {"Dottler"}},
{"Dottler", "Bug", "Bug", GR_TYPICAL, {"Orbeetle"}},
{"Orbeetle", "Bug", "Bug", GR_TYPICAL, {}},
{"Nickit", "Field", "Field", GR_TYPICAL, {"Thievul"}},
{"Thievul", "Field", "Field", GR_TYPICAL, {}},
{"Gossifleur", "Grass", "Grass", GR_TYPICAL, {"Eldegoss"}},
{"Eldegoss", "Grass", "Grass", GR_TYPICAL, {}},
{"Wooloo", "Field", "Field", GR_TYPICAL, {"Dubwool"}},
{"Dubwool", "Field", "Field", GR_TYPICAL, {}},
{"Chewtle", "Monster", "Water 1", GR_TYPICAL, {"Drednaw"}},
{"Drednaw", "Monster", "Water 1", GR_TYPICAL, {}},
{"Yamper", "Field", "Field", GR_TYPICAL, {"Boltund"}},
{"Boltund", "Field", "Field", GR_TYPICAL, {}},
{"Rolycoly", "Mineral", "Mineral", GR_TYPICAL, {"Carkol"}},
{"Carkol", "Mineral", "Mineral", GR_TYPICAL, {"Coalossal"}},
{"Coalossal", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Applin", "Grass", "Dragon", GR_TYPICAL, {"Flapple", "Appletun"}},
{"Flapple", "Grass", "Dragon", GR_TYPICAL, {}},
{"Appletun", "Grass", "Dragon", GR_TYPICAL, {}},
{"Silicobra", "Field", "Dragon", GR_TYPICAL, {"Sandaconda"}},
{"Sandaconda", "Field", "Dragon", GR_TYPICAL, {}},
{"Cramorant", "Water 1", "Flying", GR_TYPICAL, {}},
{"Arrokuda", "Water 2", "Water 2", GR_TYPICAL, {"Barraskewda"}},
{"Barraskewda", "Water 2", "Water 2", GR_TYPICAL, {}},
{"Toxel", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Toxtricity"}},
{"Toxtricity", "Human-Like", "Human-Like", GR_TYPICAL, {}},
{"Sizzlipede", "Bug", "Bug", GR_TYPICAL, {"Centiskorch"}},
{"Centiskorch", "Bug", "Bug", GR_TYPICAL, {}},
{"Clobbopus", "Water 1", "Human-Like", GR_TYPICAL, {"Grapploct"}},
{"Grapploct", "Water 1", "Human-Like", GR_TYPICAL, {}},
{"Sinistea", "Mineral", "Amorphous", GR_UNKNOWN, {"Polteageist"}},
{"Polteageist", "Mineral", "Amorphous", GR_UNKNOWN, {}},
{"Hatenna", "Fairy", "Fairy", GR_FEMALE_ONLY, {"Hattrem"}},
{"Hattrem", "Fairy", "Fairy", GR_FEMALE_ONLY, {"Hatterene"}},
{"Hatterene", "Fairy", "Fairy", GR_FEMALE_ONLY, {}},
{"Impidimp", "Fairy", "Human-Like", GR_MALE_ONLY, {"Morgrem"}},
{"Morgrem", "Fairy", "Human-Like", GR_MALE_ONLY, {"Grimmsnarl"}},
{"Grimmsnarl", "Fairy", "Human-Like", GR_MALE_ONLY, {}},
{"Milcery", "Fairy", "Amorphous", GR_FEMALE_ONLY, {"Alcremie"}},
{"Alcremie", "Fairy", "Amorphous", GR_FEMALE_ONLY, {}},
{"Falinks", "Fairy", "Mineral", GR_UNKNOWN, {}},
{"Pincurchin", "Water 1", "Amorphous", GR_TYPICAL, {}},
{"Snom", "Bug", "Bug", GR_TYPICAL, {"Frosmoth"}},
{"Frosmoth", "Bug", "Bug", GR_TYPICAL, {}},
{"Stonjourner", "Mineral", "Mineral", GR_TYPICAL, {}},
{"Eiscue", "Water 1", "Field", GR_TYPICAL, {}},
{"Indeedee", "Fairy", "Fairy", GR_TYPICAL, {}},
{"Morpeko", "Field", "Fairy", GR_TYPICAL, {}},
{"Cufant", "Field", "Mineral", GR_TYPICAL, {"Copperajah"}},
{"Copperajah", "Field", "Mineral", GR_TYPICAL, {}},
{"Dracozolt", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Arctozolt", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Dracovish", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Arctovish", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Duraludon", "Mineral", "Dragon", GR_TYPICAL, {}},
{"Dreepy", "Amorphous", "Dragon", GR_TYPICAL, {"Drakloak"}},
{"Drakloak", "Amorphous", "Dragon", GR_TYPICAL, {"Dragapult"}},
{"Dragapult", "Amorphous", "Dragon", GR_TYPICAL, {}},
{"Zacian", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Zamazenta", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Eternatus", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Kubfu", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {"Urshifu"}},
{"Urshifu", "No Eggs Discovered", "No Eggs Discovered", GR_TYPICAL, {}},
{"Zarude", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Regieleki", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Regidrago", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Glastrier", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Spectrier", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Calyrex", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}}
}
};