#ifndef DATA_GEN1
#define DATA_GEN1
#pragma once
#include "core.h"

extern Generation g_Generation1;
#endif
Generation g_Generation1 = {
"====[[Generation I]]====",
//UniversalTMs
{
"Bide",
"Double Team",
"Rage",
"Rest",
"Toxic"
},
//MonData
{
{"Bulbasaur", "Monster", "Grass", GR_UNKNOWN, {"Ivysaur"}},
{"Ivysaur", "Monster", "Grass", GR_UNKNOWN, {"Venusaur"}},
{"Venusaur", "Monster", "Grass", GR_UNKNOWN, {}},
{"Charmander", "Monster", "Dragon", GR_UNKNOWN, {"Charmeleon"}},
{"Charmeleon", "Monster", "Dragon", GR_UNKNOWN, {"Charizard"}},
{"Charizard", "Monster", "Dragon", GR_UNKNOWN, {}},
{"Squirtle", "Monster", "Water 1", GR_UNKNOWN, {"Wartortle"}},
{"Wartortle", "Monster", "Water 1", GR_UNKNOWN, {"Blastoise"}},
{"Blastoise", "Monster", "Water 1", GR_UNKNOWN, {}},
{"Caterpie", "Bug", "Bug", GR_UNKNOWN, {"Metapod"}},
{"Metapod", "Bug", "Bug", GR_UNKNOWN, {"Butterfree"}},
{"Butterfree", "Bug", "Bug", GR_UNKNOWN, {}},
{"Weedle", "Bug", "Bug", GR_UNKNOWN, {"Kakuna"}},
{"Kakuna", "Bug", "Bug", GR_UNKNOWN, {"Beedrill"}},
{"Beedrill", "Bug", "Bug", GR_UNKNOWN, {}},
{"Pidgey", "Flying", "Flying", GR_UNKNOWN, {"Pidgeotto"}},
{"Pidgeotto", "Flying", "Flying", GR_UNKNOWN, {"Pidgeot"}},
{"Pidgeot", "Flying", "Flying", GR_UNKNOWN, {}},
{"Rattata", "Field", "Field", GR_UNKNOWN, {"Raticate"}},
{"Raticate", "Field", "Field", GR_UNKNOWN, {}},
{"Spearow", "Flying", "Flying", GR_UNKNOWN, {"Fearow"}},
{"Fearow", "Flying", "Flying", GR_UNKNOWN, {}},
{"Ekans", "Field", "Dragon", GR_UNKNOWN, {"Arbok"}},
{"Arbok", "Field", "Dragon", GR_UNKNOWN, {}},
{"Pikachu", "Field", "Fairy", GR_UNKNOWN, {"Raichu"}},
{"Raichu", "Field", "Fairy", GR_UNKNOWN, {}},
{"Sandshrew", "Field", "Field", GR_UNKNOWN, {"Sandslash"}},
{"Sandslash", "Field", "Field", GR_UNKNOWN, {}},
{"Nidoran F", "Monster", "Field", GR_UNKNOWN, {"Nidorina"}},
{"Nidorina", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {"Nidoqueen"}},
{"Nidoqueen", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Nidoran M", "Monster", "Field", GR_UNKNOWN, {"Nidorino"}},
{"Nidorino", "Monster", "Field", GR_UNKNOWN, {"Nidoking"}},
{"Nidoking", "Monster", "Field", GR_UNKNOWN, {}},
{"Clefairy", "Fairy", "Fairy", GR_UNKNOWN, {"Clefable"}},
{"Clefable", "Fairy", "Fairy", GR_UNKNOWN, {}},
{"Vulpix", "Field", "Field", GR_UNKNOWN, {"Ninetales"}},
{"Ninetales", "Field", "Field", GR_UNKNOWN, {}},
{"Jigglypuff", "Fairy", "Fairy", GR_UNKNOWN, {"Wigglytuff"}},
{"Wigglytuff", "Fairy", "Fairy", GR_UNKNOWN, {}},
{"Zubat", "Flying", "Flying", GR_UNKNOWN, {"Golbat"}},
{"Golbat", "Flying", "Flying", GR_UNKNOWN, {}},
{"Oddish", "Grass", "Grass", GR_UNKNOWN, {"Gloom"}},
{"Gloom", "Grass", "Grass", GR_UNKNOWN, {"Vileplume"}},
{"Vileplume", "Grass", "Grass", GR_UNKNOWN, {}},
{"Paras", "Bug", "Grass", GR_UNKNOWN, {"Parasect"}},
{"Parasect", "Bug", "Grass", GR_UNKNOWN, {}},
{"Venonat", "Bug", "Bug", GR_UNKNOWN, {"Venomoth"}},
{"Venomoth", "Bug", "Bug", GR_UNKNOWN, {}},
{"Diglett", "Field", "Field", GR_UNKNOWN, {"Dugtrio"}},
{"Dugtrio", "Field", "Field", GR_UNKNOWN, {}},
{"Meowth", "Field", "Field", GR_UNKNOWN, {"Persian"}},
{"Persian", "Field", "Field", GR_UNKNOWN, {}},
{"Psyduck", "Water 1", "Field", GR_UNKNOWN, {"Golduck"}},
{"Golduck", "Water 1", "Field", GR_UNKNOWN, {}},
{"Mankey", "Field", "Field", GR_UNKNOWN, {"Primeape"}},
{"Primeape", "Field", "Field", GR_UNKNOWN, {}},
{"Growlithe", "Field", "Field", GR_UNKNOWN, {"Arcanine"}},
{"Arcanine", "Field", "Field", GR_UNKNOWN, {}},
{"Poliwag", "Water 1", "Water 1", GR_UNKNOWN, {"Poliwhirl"}},
{"Poliwhirl", "Water 1", "Water 1", GR_UNKNOWN, {"Poliwrath"}},
{"Poliwrath", "Water 1", "Water 1", GR_UNKNOWN, {}},
{"Abra", "Human-Like", "Human-Like", GR_UNKNOWN, {"Kadabra"}},
{"Kadabra", "Human-Like", "Human-Like", GR_UNKNOWN, {"Alakazam"}},
{"Alakazam", "Human-Like", "Human-Like", GR_UNKNOWN, {}},
{"Machop", "Human-Like", "Human-Like", GR_UNKNOWN, {"Machoke"}},
{"Machoke", "Human-Like", "Human-Like", GR_UNKNOWN, {"Machamp"}},
{"Machamp", "Human-Like", "Human-Like", GR_UNKNOWN, {}},
{"Bellsprout", "Grass", "Grass", GR_UNKNOWN, {"Weepinbell"}},
{"Weepinbell", "Grass", "Grass", GR_UNKNOWN, {"Victreebel"}},
{"Victreebel", "Grass", "Grass", GR_UNKNOWN, {}},
{"Tentacool", "Water 3", "Water 3", GR_UNKNOWN, {"Tentacruel"}},
{"Tentacruel", "Water 3", "Water 3", GR_UNKNOWN, {}},
{"Geodude", "Mineral", "Mineral", GR_UNKNOWN, {"Graveler"}},
{"Graveler", "Mineral", "Mineral", GR_UNKNOWN, {"Golem"}},
{"Golem", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Ponyta", "Field", "Field", GR_UNKNOWN, {"Rapidash"}},
{"Rapidash", "Field", "Field", GR_UNKNOWN, {}},
{"Slowpoke", "Monster", "Water 1", GR_UNKNOWN, {"Slowbro"}},
{"Slowbro", "Monster", "Water 1", GR_UNKNOWN, {}},
{"Magnemite", "Mineral", "Mineral", GR_UNKNOWN, {"Magneton"}},
{"Magneton", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Farfetch'd", "Flying", "Field", GR_UNKNOWN, {}},
{"Doduo", "Flying", "Flying", GR_UNKNOWN, {"Dodrio"}},
{"Dodrio", "Flying", "Flying", GR_UNKNOWN, {}},
{"Seel", "Water 1", "Field", GR_UNKNOWN, {"Dewgong"}},
{"Dewgong", "Water 1", "Field", GR_UNKNOWN, {}},
{"Grimer", "Amorphous", "Amorphous", GR_UNKNOWN, {"Muk"}},
{"Muk", "Amorphous", "Amorphous", GR_UNKNOWN, {}},
{"Shellder", "Water 3", "Water 3", GR_UNKNOWN, {"Cloyster"}},
{"Cloyster", "Water 3", "Water 3", GR_UNKNOWN, {}},
{"Gastly", "Amorphous", "Amorphous", GR_UNKNOWN, {"Haunter"}},
{"Haunter", "Amorphous", "Amorphous", GR_UNKNOWN, {"Gengar"}},
{"Gengar", "Amorphous", "Amorphous", GR_UNKNOWN, {}},
{"Onix", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Drowzee", "Human-Like", "Human-Like", GR_UNKNOWN, {"Hypno"}},
{"Hypno", "Human-Like", "Human-Like", GR_UNKNOWN, {}},
{"Krabby", "Water 3", "Water 3", GR_UNKNOWN, {"Kingler"}},
{"Kingler", "Water 3", "Water 3", GR_UNKNOWN, {}},
{"Voltorb", "Mineral", "Mineral", GR_UNKNOWN, {"Electrode"}},
{"Electrode", "Mineral", "Mineral", GR_UNKNOWN, {}},
{"Exeggcute", "Grass", "Grass", GR_UNKNOWN, {"Exeggutor"}},
{"Exeggutor", "Grass", "Grass", GR_UNKNOWN, {}},
{"Cubone", "Monster", "Monster", GR_UNKNOWN, {"Marowak"}},
{"Marowak", "Monster", "Monster", GR_UNKNOWN, {}},
{"Hitmonlee", "Human-Like", "Human-Like", GR_UNKNOWN, {}},
{"Hitmonchan", "Human-Like", "Human-Like", GR_UNKNOWN, {}},
{"Lickitung", "Monster", "Monster", GR_UNKNOWN, {}},
{"Koffing", "Amorphous", "Amorphous", GR_UNKNOWN, {"Weezing"}},
{"Weezing", "Amorphous", "Amorphous", GR_UNKNOWN, {}},
{"Rhyhorn", "Monster", "Field", GR_UNKNOWN, {"Rhydon"}},
{"Rhydon", "Monster", "Field", GR_UNKNOWN, {}},
{"Chansey", "Fairy", "Fairy", GR_UNKNOWN, {}},
{"Tangela", "Grass", "Grass", GR_UNKNOWN, {}},
{"Kangaskhan", "Monster", "Monster", GR_UNKNOWN, {}},
{"Horsea", "Water 1", "Dragon", GR_UNKNOWN, {"Seadra"}},
{"Seadra", "Water 1", "Dragon", GR_UNKNOWN, {}},
{"Goldeen", "Water 2", "Water 2", GR_UNKNOWN, {"Seaking"}},
{"Seaking", "Water 2", "Water 2", GR_UNKNOWN, {}},
{"Staryu", "Water 3", "Water 3", GR_UNKNOWN, {"Starmie"}},
{"Starmie", "Water 3", "Water 3", GR_UNKNOWN, {}},
{"Mr. Mime", "Human-Like", "Human-Like", GR_UNKNOWN, {}},
{"Scyther", "Bug", "Bug", GR_UNKNOWN, {}},
{"Jynx", "Human-Like", "Human-Like", GR_UNKNOWN, {}},
{"Electabuzz", "Human-Like", "Human-Like", GR_UNKNOWN, {}},
{"Magmar", "Human-Like", "Human-Like", GR_UNKNOWN, {}},
{"Pinsir", "Bug", "Bug", GR_UNKNOWN, {}},
{"Tauros", "Field", "Field", GR_UNKNOWN, {}},
{"Magikarp", "Water 2", "Dragon", GR_UNKNOWN, {"Gyarados"}},
{"Gyarados", "Water 2", "Dragon", GR_UNKNOWN, {}},
{"Lapras", "Monster", "Water 1", GR_UNKNOWN, {}},
{"Ditto", "Ditto", "Ditto", GR_UNKNOWN, {}},
{"Eevee", "Field", "Field", GR_UNKNOWN, {"Vaporeon", "Jolteon", "Flareon"}},
{"Vaporeon", "Field", "Field", GR_UNKNOWN, {}},
{"Jolteon", "Field", "Field", GR_UNKNOWN, {}},
{"Flareon", "Field", "Field", GR_UNKNOWN, {}},
{"Porygon", "Mineral", "Mineral", GR_UNKNOWN, {"Porygon2"}},
{"Omanyte", "Water 1", "Water 3", GR_UNKNOWN, {"Omastar"}},
{"Omastar", "Water 1", "Water 3", GR_UNKNOWN, {}},
{"Kabuto", "Water 1", "Water 3", GR_UNKNOWN, {"Kabutops"}},
{"Kabutops", "Water 1", "Water 3", GR_UNKNOWN, {}},
{"Aerodactyl", "Flying", "Flying", GR_UNKNOWN, {}},
{"Snorlax", "Monster", "Monster", GR_UNKNOWN, {}},
{"Articuno", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Zapdos", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Moltres", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Dratini", "Water 1", "Dragon", GR_UNKNOWN, {"Dragonair"}},
{"Dragonair", "Water 1", "Dragon", GR_UNKNOWN, {"Dragonite"}},
{"Dragonite", "Water 1", "Dragon", GR_UNKNOWN, {}},
{"Mewtwo", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}},
{"Mew", "No Eggs Discovered", "No Eggs Discovered", GR_UNKNOWN, {}}
}
};