#ifndef DATA_GEN8
#define DATA_GEN8
#pragma once
#include "core.h"

extern Generation tGeneration8;
#endif
Generation tGeneration8 = {
GENERATION_8,
"====[[Generation VIII]]====",
//sBabyMons https://bulbapedia.bulbagarden.net/wiki/Baby_Pok%C3%A9mon
{
"Pichu",
"Cleffa",
"Igglybuff",
"Togepi",
"Tyrogue",
"Smoochum",
"Elekid",
"Magby",
"Azurill",
"Wynaut",
"Budew",
"Chingling",
"Bonsly",
"Mime Jr.",
"Happiny",
"Munchlax",
"Riolu",
"Mantyke",
"Toxel"
},
//sFemaleOnlyMons https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_gender_ratio
{
"Nidoran F",
"Chansey",
"Kangaskhan",
"Jynx",
"Miltank",
"Blissey",
"Illumise",
"Wormadam",
"Vespiquen",
"Froslass",
"Petilil",
"Lilligant",
"Vullaby",
"Mandibuzz",
"Flabebe",
"Floette",
"Florges",
"Salazzle",
"Bounsweet",
"Steenee",
"Tsareena",
"Hatenna",
"Hattrem",
"Hatterene",
"Milcery",
"Alcremie"
},
//sMaleOnlyMons
{
"Nidoran M",
"Nidorino",
"Nidoking",
"Hitmonlee",
"Hitmonchan",
"Tauros",
"Hitmontop",
"Volbeat",
"Mothim",
"Gallade",
"Throh",
"Sawk",
"Rufflet",
"Braviary",
"Impidimp",
"Morgrem",
"Grimmsnarl"
},
//sUniversalTMs https://bulbapedia.bulbagarden.net/w/index.php?search=%22Every+Pok%C3%A9mon+can+learn+this+move+by%22&title=Special%3ASearch&go=Go
{
"Attract",
"Endure",
"Facade",
"Protect",
"Rest",
"Round",
"Sleep Talk",
"Snore",
},
//sAllGroups https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_breeding_attributes https://bulbapedia.bulbagarden.net/wiki/List_of_cross-generational_evolutionary_lines
{
{"Bulbasaur", "Monster", "Grass", {"Ivysaur"}},
{"Ivysaur", "Monster", "Grass", {"Venusaur"}},
{"Venusaur", "Monster", "Grass", {}},
{"Charmander", "Monster", "Dragon", {"Charmeleon"}},
{"Charmeleon", "Monster", "Dragon", {"Charizard"}},
{"Charizard", "Monster", "Dragon", {}},
{"Squirtle", "Monster", "Water 1", {"Wartortle"}},
{"Wartortle", "Monster", "Water 1", {"Blastoise"}},
{"Blastoise", "Monster", "Water 1", {}},
{"Caterpie", "Bug", "Bug", {"Metapod"}},
{"Metapod", "Bug", "Bug", {"Butterfree"}},
{"Butterfree", "Bug", "Bug", {}},
{"Weedle", "Bug", "Bug", {"Kakuna"}},
{"Kakuna", "Bug", "Bug", {"Beedrill"}},
{"Beedrill", "Bug", "Bug", {}},
{"Pidgey", "Flying", "Flying", {"Pidgeotto"}},
{"Pidgeotto", "Flying", "Flying", {"Pidgeot"}},
{"Pidgeot", "Flying", "Flying", {}},
{"Rattata", "Field", "Field", {"Raticate"}},
{"Raticate", "Field", "Field", {}},
{"Spearow", "Flying", "Flying", {"Fearow"}},
{"Fearow", "Flying", "Flying", {}},
{"Ekans", "Field", "Dragon", {"Arbok"}},
{"Arbok", "Field", "Dragon", {}},
{"Pichu", "No Eggs Discovered", "No Eggs Discovered", {"Pikachu"}},
{"Pikachu", "Field", "Fairy", {"Raichu"}},
{"Raichu", "Field", "Fairy", {}},
{"Sandshrew", "Field", "Field", {"Sandslash"}},
{"Sandslash", "Field", "Field", {}},
{"Nidoran F", "Monster", "Field", {"Nidorina"}},
{"Nidorina", "No Eggs Discovered", "No Eggs Discovered", {"Nidoqueen"}},
{"Nidoqueen", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Nidoran M", "Monster", "Field", {"Nidorino"}},
{"Nidorino", "Monster", "Field", {"Nidoking"}},
{"Nidoking", "Monster", "Field", {}},
{"Cleffa", "No Eggs Discovered", "No Eggs Discovered", {"Clefairy"}},
{"Clefairy", "Fairy", "Fairy", {"Clefable"}},
{"Clefable", "Fairy", "Fairy", {}},
{"Vulpix", "Field", "Field", {"Ninetales"}},
{"Ninetales", "Field", "Field", {}},
{"Igglybuff", "No Eggs Discovered", "No Eggs Discovered", {"Jigglypuff"}},
{"Jigglypuff", "Fairy", "Fairy", {"Wigglytuff"}},
{"Wigglytuff", "Fairy", "Fairy", {}},
{"Zubat", "Flying", "Flying", {"Golbat"}},
{"Golbat", "Flying", "Flying", {"Crobat"}},
{"Crobat", "Flying", "Flying", {}},
{"Oddish", "Grass", "Grass", {"Gloom"}},
{"Gloom", "Grass", "Grass", {"Vileplume", "Bellossom"}},
{"Vileplume", "Grass", "Grass", {}},
{"Bellossom", "Grass", "Grass", {}},
{"Paras", "Bug", "Grass", {"Parasect"}},
{"Parasect", "Bug", "Grass", {}},
{"Venonat", "Bug", "Bug", {"Venomoth"}},
{"Venomoth", "Bug", "Bug", {}},
{"Diglett", "Field", "Field", {"Dugtrio"}},
{"Dugtrio", "Field", "Field", {}},
{"Meowth", "Field", "Field", {"Persian", "Perrserker"}},
{"Persian", "Field", "Field", {}},
{"Perrserker", "Field", "Field", {}},
{"Psyduck", "Water 1", "Field", {"Golduck"}},
{"Golduck", "Water 1", "Field", {}},
{"Mankey", "Field", "Field", {"Primeape"}},
{"Primeape", "Field", "Field", {}},
{"Growlithe", "Field", "Field", {"Arcanine"}},
{"Arcanine", "Field", "Field", {}},
{"Poliwag", "Water 1", "Water 1", {"Poliwhirl"}},
{"Poliwhirl", "Water 1", "Water 1", {"Poliwrath", "Politoed"}},
{"Poliwrath", "Water 1", "Water 1", {}},
{"Politoed", "Water 1", "Water 1", {}},
{"Abra", "Human-Like", "Human-Like", {"Kadabra"}},
{"Kadabra", "Human-Like", "Human-Like", {"Alakazam"}},
{"Alakazam", "Human-Like", "Human-Like", {}},
{"Machop", "Human-Like", "Human-Like", {"Machoke"}},
{"Machoke", "Human-Like", "Human-Like", {"Machamp"}},
{"Machamp", "Human-Like", "Human-Like", {}},
{"Bellsprout", "Grass", "Grass", {"Weepinbell"}},
{"Weepinbell", "Grass", "Grass", {"Victreebel"}},
{"Victreebel", "Grass", "Grass", {}},
{"Tentacool", "Water 3", "Water 3", {"Tentacruel"}},
{"Tentacruel", "Water 3", "Water 3", {}},
{"Geodude", "Mineral", "Mineral", {"Graveler"}},
{"Graveler", "Mineral", "Mineral", {"Golem"}},
{"Golem", "Mineral", "Mineral", {}},
{"Ponyta", "Field", "Field", {"Rapidash"}},
{"Rapidash", "Field", "Field", {}},
{"Slowpoke", "Monster", "Water 1", {"Slowbro", "Slowking"}},
{"Slowbro", "Monster", "Water 1", {}},
{"Slowking", "Monster", "Water 1", {}},
{"Magnemite", "Mineral", "Mineral", {"Magneton"}},
{"Magneton", "Mineral", "Mineral", {"Magnezone"}},
{"Magnezone", "Mineral", "Mineral", {}},
{"Farfetch'd", "Flying", "Field", {"Sirfetch'd"}},
{"Sirfetch'd", "Flying", "Field", {}},
{"Doduo", "Flying", "Flying", {"Dodrio"}},
{"Dodrio", "Flying", "Flying", {}},
{"Seel", "Water 1", "Field", {"Dewgong"}},
{"Dewgong", "Water 1", "Field", {}},
{"Grimer", "Amorphous", "Amorphous", {"Muk"}},
{"Muk", "Amorphous", "Amorphous", {}},
{"Shellder", "Water 3", "Water 3", {"Cloyster"}},
{"Cloyster", "Water 3", "Water 3", {}},
{"Gastly", "Amorphous", "Amorphous", {"Haunter"}},
{"Haunter", "Amorphous", "Amorphous", {"Gengar"}},
{"Gengar", "Amorphous", "Amorphous", {}},
{"Onix", "Mineral", "Mineral", {"Steelix"}},
{"Steelix", "Mineral", "Mineral", {}},
{"Drowzee", "Human-Like", "Human-Like", {"Hypno"}},
{"Hypno", "Human-Like", "Human-Like", {}},
{"Krabby", "Water 3", "Water 3", {"Kingler"}},
{"Kingler", "Water 3", "Water 3", {}},
{"Voltorb", "Mineral", "Mineral", {"Electrode"}},
{"Electrode", "Mineral", "Mineral", {}},
{"Exeggcute", "Grass", "Grass", {"Exeggutor"}},
{"Exeggutor", "Grass", "Grass", {}},
{"Cubone", "Monster", "Monster", {"Marowak"}},
{"Marowak", "Monster", "Monster", {}},
{"Tyrogue", "No Eggs Discovered", "No Eggs Discovered", {"Hitmonlee", "Hitmonchan", "Hitmontop"}},
{"Hitmonlee", "Human-Like", "Human-Like", {}},
{"Hitmonchan", "Human-Like", "Human-Like", {}},
{"Hitmontop", "Human-Like", "Human-Like", {}},
{"Lickitung", "Monster", "Monster", {"Lickilicky"}},
{"Lickilicky", "Monster", "Monster", {}},
{"Koffing", "Amorphous", "Amorphous", {"Weezing"}},
{"Weezing", "Amorphous", "Amorphous", {}},
{"Rhyhorn", "Monster", "Field", {"Rhydon"}},
{"Rhydon", "Monster", "Field", {"Rhyperior"}},
{"Rhyperior", "Monster", "Field", {}},
{"Happiny", "No Eggs Discovered", "No Eggs Discovered", {"Chansey"}},
{"Chansey", "Fairy", "Fairy", {"Blissey"}},
{"Blissey", "Fairy", "Fairy", {}},
{"Tangela", "Grass", "Grass", {"Tangrowth"}},
{"Tangrowth", "Grass", "Grass", {}},
{"Kangaskhan", "Monster", "Monster", {}},
{"Horsea", "Water 1", "Dragon", {"Seadra"}},
{"Seadra", "Water 1", "Dragon", {"Kingdra"}},
{"Kingdra", "Water 1", "Dragon", {}},
{"Goldeen", "Water 2", "Water 2", {"Seaking"}},
{"Seaking", "Water 2", "Water 2", {}},
{"Staryu", "Water 3", "Water 3", {"Starmie"}},
{"Starmie", "Water 3", "Water 3", {}},
{"Mime Jr.", "No Eggs Discovered", "No Eggs Discovered", {"Mr. Mime"}},
{"Mr. Mime", "Human-Like", "Human-Like", {"Mr. Rime"}},
{"Mr. Rime", "Human-Like", "Human-Like", {}},
{"Scyther", "Bug", "Bug", {"Scizor", "Kleavor"}},
{"Scizor", "Bug", "Bug", {}},
{"Kleavor", "Bug", "Bug", {}},
{"Smoochum", "No Eggs Discovered", "No Eggs Discovered", {"Jynx"}},
{"Jynx", "Human-Like", "Human-Like", {}},
{"Elekid", "No Eggs Discovered", "No Eggs Discovered", {"Electabuzz"}},
{"Electabuzz", "Human-Like", "Human-Like", {"Electivire"}},
{"Electivire", "Human-Like", "Human-Like", {}},
{"Magby", "No Eggs Discovered", "No Eggs Discovered", {"Magmar"}},
{"Magmar", "Human-Like", "Human-Like", {"Magmortar"}},
{"Magmortar", "Human-Like", "Human-Like", {}},
{"Pinsir", "Bug", "Bug", {}},
{"Tauros", "Field", "Field", {}},
{"Magikarp", "Water 2", "Dragon", {"Gyarados"}},
{"Gyarados", "Water 2", "Dragon", {}},
{"Lapras", "Monster", "Water 1", {}},
{"Ditto", "Ditto", "Ditto", {}},
{"Eevee", "Field", "Field", {"Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon", "Leafeon", "Glaceon", "Sylveon"}},
{"Vaporeon", "Field", "Field", {}},
{"Jolteon", "Field", "Field", {}},
{"Flareon", "Field", "Field", {}},
{"Espeon", "Field", "Field", {}},
{"Umbreon", "Field", "Field", {}},
{"Leafeon", "Field", "Field", {}},
{"Glaceon", "Field", "Field", {}},
{"Sylveon", "Field", "Field", {}},
{"Porygon", "Mineral", "Mineral", {"Porygon2"}},
{"Porygon2", "Mineral", "Mineral", {"Porygon-Z"}},
{"Porygon-Z", "Mineral", "Mineral", {}},
{"Omanyte", "Water 1", "Water 3", {"Omastar"}},
{"Omastar", "Water 1", "Water 3", {}},
{"Kabuto", "Water 1", "Water 3", {"Kabutops"}},
{"Kabutops", "Water 1", "Water 3", {}},
{"Aerodactyl", "Flying", "Flying", {}},
{"Munchlax", "No Eggs Discovered", "No Eggs Discovered", {"Snorlax"}},
{"Snorlax", "Monster", "Monster", {}},
{"Articuno", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Zapdos", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Moltres", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Dratini", "Water 1", "Dragon", {"Dragonair"}},
{"Dragonair", "Water 1", "Dragon", {"Dragonite"}},
{"Dragonite", "Water 1", "Dragon", {}},
{"Mewtwo", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Mew", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Chikorita", "Monster", "Grass", {"Bayleef"}},
{"Bayleef", "Monster", "Grass", {"Meganium"}},
{"Meganium", "Monster", "Grass", {}},
{"Cyndaquil", "Field", "Field", {"Quilava"}},
{"Quilava", "Field", "Field", {"Typhlosion"}},
{"Typhlosion", "Field", "Field", {}},
{"Totodile", "Monster", "Water 1", {"Croconaw"}},
{"Croconaw", "Monster", "Water 1", {"Feraligatr"}},
{"Feraligatr", "Monster", "Water 1", {}},
{"Sentret", "Field", "Field", {"Furret"}},
{"Furret", "Field", "Field", {}},
{"Hoothoot", "Flying", "Flying", {"Noctowl"}},
{"Noctowl", "Flying", "Flying", {}},
{"Ledyba", "Bug", "Bug", {"Ledian"}},
{"Ledian", "Bug", "Bug", {}},
{"Spinarak", "Bug", "Bug", {"Ariados"}},
{"Ariados", "Bug", "Bug", {}},
{"Chinchou", "Water 2", "Water 2", {"Lanturn"}},
{"Lanturn", "Water 2", "Water 2", {}},
{"Togepi", "No Eggs Discovered", "No Eggs Discovered", {"Togetic"}},
{"Togetic", "Flying", "Fairy", {"Togekiss"}},
{"Togekiss", "Flying", "Fairy", {}},
{"Natu", "Flying", "Flying", {"Xatu"}},
{"Xatu", "Flying", "Flying", {}},
{"Mareep", "Monster", "Field", {"Flaaffy"}},
{"Flaaffy", "Monster", "Field", {"Ampharos"}},
{"Ampharos", "Monster", "Field", {}},
{"Azurill", "No Eggs Discovered", "No Eggs Discovered", {"Marill"}},
{"Marill", "Water 1", "Fairy", {"Azumarill"}},
{"Azumarill", "Water 1", "Fairy", {}},
{"Bonsly", "No Eggs Discovered", "No Eggs Discovered", {"Sudowoodo"}},
{"Sudowoodo", "Mineral", "Mineral", {}},
{"Hoppip", "Fairy", "Grass", {"Skiploom"}},
{"Skiploom", "Fairy", "Grass", {"Jumpluff"}},
{"Jumpluff", "Fairy", "Grass", {}},
{"Aipom", "Field", "Field", {"Ambipom"}},
{"Ambipom", "Field", "Field", {}},
{"Sunkern", "Grass", "Grass", {"Sunflora"}},
{"Sunflora", "Grass", "Grass", {}},
{"Yanma", "Bug", "Bug", {"Yanmega"}},
{"Yanmega", "Bug", "Bug", {}},
{"Wooper", "Water 1", "Field", {"Quagsire"}},
{"Quagsire", "Water 1", "Field", {}},
{"Murkrow", "Flying", "Flying", {"Honchkrow"}},
{"Honchkrow", "Flying", "Flying", {}},
{"Misdreavus", "Amorphous", "Amorphous", {"Mismagius"}},
{"Mismagius", "Amorphous", "Amorphous", {}},
{"Unown", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Wynaut", "No Eggs Discovered", "No Eggs Discovered", {"Wobbuffet"}},
{"Wobbuffet", "Amorphous", "Amorphous", {}},
{"Girafarig", "Field", "Field", {}},
{"Pineco", "Bug", "Bug", {"Forretress"}},
{"Forretress", "Bug", "Bug", {}},
{"Dunsparce", "Field", "Field", {}},
{"Gligar", "Bug", "Bug", {"Gliscor"}},
{"Gliscor", "Bug", "Bug", {}},
{"Snubbull", "Field", "Fairy", {"Granbull"}},
{"Granbull", "Field", "Fairy", {}},
{"Qwilfish", "Water 2", "Water 2", {"Overqwil"}},
{"Overqwil", "Water 2", "Water 2", {}},
{"Shuckle", "Bug", "Bug", {}},
{"Heracross", "Bug", "Bug", {}},
{"Sneasel", "Field", "Field", {"Weavile", "Sneasler"}},
{"Weavile", "Field", "Field", {}},
{"Sneasler", "Field", "Field", {}},
{"Teddiursa", "Field", "Field", {"Ursaring"}},
{"Ursaring", "Field", "Field", {"Ursaluna"}},
{"Ursaluna", "Field", "Field", {}},
{"Slugma", "Amorphous", "Amorphous", {"Magcargo"}},
{"Magcargo", "Amorphous", "Amorphous", {}},
{"Swinub", "Field", "Field", {"Piloswine"}},
{"Piloswine", "Field", "Field", {"Mamoswine"}},
{"Mamoswine", "Field", "Field", {}},
{"Corsola", "Water 1", "Water 3", {"Cursola"}},
{"Cursola", "Water 1", "Water 3", {}},
{"Remoraid", "Water 1", "Water 2", {"Octillery"}},
{"Octillery", "Water 1", "Water 2", {}},
{"Delibird", "Water 1", "Field", {}},
{"Mantyke", "No Eggs Discovered", "No Eggs Discovered", {"Mantine"}},
{"Mantine", "Water 1", "Water 1", {}},
{"Skarmory", "Flying", "Flying", {}},
{"Houndour", "Field", "Field", {"Houndoom"}},
{"Houndoom", "Field", "Field", {}},
{"Phanpy", "Field", "Field", {"Donphan"}},
{"Donphan", "Field", "Field", {}},
{"Stantler", "Field", "Field", {"Wyrdeer"}},
{"Wyrdeer", "Field", "Field", {}},
{"Smeargle", "Field", "Field", {}},
{"Miltank", "Field", "Field", {}},
{"Raikou", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Entei", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Suicune", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Larvitar", "Monster", "Monster", {"Pupitar"}},
{"Pupitar", "Monster", "Monster", {"Tyranitar"}},
{"Tyranitar", "Monster", "Monster", {}},
{"Lugia", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Ho-Oh", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Celebi", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Treecko", "Monster", "Dragon", {"Grovyle"}},
{"Grovyle", "Monster", "Dragon", {"Sceptile"}},
{"Sceptile", "Monster", "Dragon", {}},
{"Torchic", "Field", "Field", {"Combusken"}},
{"Combusken", "Field", "Field", {"Blaziken"}},
{"Blaziken", "Field", "Field", {}},
{"Mudkip", "Monster", "Water 1", {"Marshtomp"}},
{"Marshtomp", "Monster", "Water 1", {"Swampert"}},
{"Swampert", "Monster", "Water 1", {}},
{"Poochyena", "Field", "Field", {"Mightyena"}},
{"Mightyena", "Field", "Field", {}},
{"Zigzagoon", "Field", "Field", {"Linoone"}},
{"Linoone", "Field", "Field", {"Obstagoon"}},
{"Obstagoon", "Field", "Field", {}},
{"Wurmple", "Bug", "Bug", {"Silcoon", "Cascoon"}},
{"Silcoon", "Bug", "Bug", {"Beautifly"}},
{"Beautifly", "Bug", "Bug", {}},
{"Cascoon", "Bug", "Bug", {"Dustox"}},
{"Dustox", "Bug", "Bug", {}},
{"Lotad", "Water 1", "Grass", {"Lombre"}},
{"Lombre", "Water 1", "Grass", {"Ludicolo"}},
{"Ludicolo", "Water 1", "Grass", {}},
{"Seedot", "Field", "Grass", {"Nuzleaf"}},
{"Nuzleaf", "Field", "Grass", {"Shiftry"}},
{"Shiftry", "Field", "Grass", {}},
{"Taillow", "Flying", "Flying", {"Swellow"}},
{"Swellow", "Flying", "Flying", {}},
{"Wingull", "Water 1", "Flying", {"Pelipper"}},
{"Pelipper", "Water 1", "Flying", {}},
{"Ralts", "Human-Like", "Amorphous", {"Kirlia"}},
{"Kirlia", "Human-Like", "Amorphous", {"Gardevoir", "Gallade"}},
{"Gardevoir", "Human-Like", "Amorphous", {}},
{"Gallade", "Human-Like", "Amorphous", {}},
{"Surskit", "Water 1", "Bug", {"Masquerain"}},
{"Masquerain", "Water 1", "Bug", {}},
{"Shroomish", "Fairy", "Grass", {"Breloom"}},
{"Breloom", "Fairy", "Grass", {}},
{"Slakoth", "Field", "Field", {"Vigoroth"}},
{"Vigoroth", "Field", "Field", {"Slaking"}},
{"Slaking", "Field", "Field", {}},
{"Nincada", "Bug", "Bug", {"Ninjask", "Shedinja"}},
{"Ninjask", "Bug", "Bug", {}},
{"Shedinja", "Mineral", "Mineral", {}},
{"Whismur", "Monster", "Field", {"Loudred"}},
{"Loudred", "Monster", "Field", {"Exploud"}},
{"Exploud", "Monster", "Field", {}},
{"Makuhita", "Human-Like", "Human-Like", {"Hariyama"}},
{"Hariyama", "Human-Like", "Human-Like", {}},
{"Nosepass", "Mineral", "Mineral", {"Probopass"}},
{"Probopass", "Mineral", "Mineral", {}},
{"Skitty", "Field", "Fairy", {"Delcatty"}},
{"Delcatty", "Field", "Fairy", {}},
{"Sableye", "Human-Like", "Human-Like", {}},
{"Mawile", "Field", "Fairy", {}},
{"Aron", "Monster", "Monster", {"Lairon"}},
{"Lairon", "Monster", "Monster", {"Aggron"}},
{"Aggron", "Monster", "Monster", {}},
{"Meditite", "Human-Like", "Human-Like", {"Medicham"}},
{"Medicham", "Human-Like", "Human-Like", {}},
{"Electrike", "Field", "Field", {"Manectric"}},
{"Manectric", "Field", "Field", {}},
{"Plusle", "Fairy", "Fairy", {}},
{"Minun", "Fairy", "Fairy", {}},
{"Volbeat", "Bug", "Human-Like", {}},
{"Illumise", "Bug", "Human-Like", {}},
{"Budew", "No Eggs Discovered", "No Eggs Discovered", {"Roselia"}},
{"Roselia", "Fairy", "Grass", {"Roserade"}},
{"Roserade", "Fairy", "Grass", {}},
{"Gulpin", "Amorphous", "Amorphous", {"Swalot"}},
{"Swalot", "Amorphous", "Amorphous", {}},
{"Carvanha", "Water 2", "Water 2", {"Sharpedo"}},
{"Sharpedo", "Water 2", "Water 2", {}},
{"Wailmer", "Field", "Water 2", {"Wailord"}},
{"Wailord", "Field", "Water 2", {}},
{"Numel", "Field", "Field", {"Camerupt"}},
{"Camerupt", "Field", "Field", {}},
{"Torkoal", "Field", "Field", {}},
{"Spoink", "Field", "Field", {"Grumpig"}},
{"Grumpig", "Field", "Field", {}},
{"Spinda", "Field", "Human-Like", {}},
{"Trapinch", "Bug", "Dragon", {"Vibrava"}},
{"Vibrava", "Bug", "Dragon", {"Flygon"}},
{"Flygon", "Bug", "Dragon", {}},
{"Cacnea", "Grass", "Human-Like", {"Cacturne"}},
{"Cacturne", "Grass", "Human-Like", {}},
{"Swablu", "Flying", "Dragon", {"Altaria"}},
{"Altaria", "Flying", "Dragon", {}},
{"Zangoose", "Field", "Field", {}},
{"Seviper", "Field", "Dragon", {}},
{"Lunatone", "Mineral", "Mineral", {}},
{"Solrock", "Mineral", "Mineral", {}},
{"Barboach", "Water 2", "Water 2", {"Whiscash"}},
{"Whiscash", "Water 2", "Water 2", {}},
{"Corphish", "Water 1", "Water 3", {"Crawdaunt"}},
{"Crawdaunt", "Water 1", "Water 3", {}},
{"Baltoy", "Mineral", "Mineral", {"Claydol"}},
{"Claydol", "Mineral", "Mineral", {}},
{"Lileep", "Water 3", "Water 3", {"Cradily"}},
{"Cradily", "Water 3", "Water 3", {}},
{"Anorith", "Water 3", "Water 3", {"Armaldo"}},
{"Armaldo", "Water 3", "Water 3", {}},
{"Feebas", "Water 1", "Dragon", {"Milotic"}},
{"Milotic", "Water 1", "Dragon", {}},
{"Castform", "Fairy", "Amorphous", {}},
{"Kecleon", "Field", "Field", {}},
{"Shuppet", "Amorphous", "Amorphous", {"Banette"}},
{"Banette", "Amorphous", "Amorphous", {}},
{"Duskull", "Amorphous", "Amorphous", {"Dusclops"}},
{"Dusclops", "Amorphous", "Amorphous", {"Dusknoir"}},
{"Dusknoir", "Amorphous", "Amorphous", {}},
{"Tropius", "Monster", "Grass", {}},
{"Chingling", "No Eggs Discovered", "No Eggs Discovered", {"Chimecho"}},
{"Chimecho", "Amorphous", "Amorphous", {}},
{"Absol", "Field", "Field", {}},
{"Snorunt", "Fairy", "Mineral", {"Glalie", "Froslass"}},
{"Glalie", "Fairy", "Mineral", {}},
{"Froslass", "Fairy", "Mineral", {}},
{"Spheal", "Water 1", "Field", {"Sealeo"}},
{"Sealeo", "Water 1", "Field", {"Walrein"}},
{"Walrein", "Water 1", "Field", {}},
{"Clamperl", "Water 1", "Water 1", {"Huntail", "Gorebyss"}},
{"Huntail", "Water 1", "Water 1", {}},
{"Gorebyss", "Water 1", "Water 1", {}},
{"Relicanth", "Water 1", "Water 2", {}},
{"Luvdisc", "Water 2", "Water 2", {}},
{"Bagon", "Dragon", "Dragon", {"Shelgon"}},
{"Shelgon", "Dragon", "Dragon", {"Salamence"}},
{"Salamence", "Dragon", "Dragon", {}},
{"Beldum", "Mineral", "Mineral", {"Metang"}},
{"Metang", "Mineral", "Mineral", {"Metagross"}},
{"Metagross", "Mineral", "Mineral", {}},
{"Regirock", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Regice", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Registeel", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Latias", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Latios", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Kyogre", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Groudon", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Rayquaza", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Jirachi", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Deoxys", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Turtwig", "Monster", "Grass", {"Grotle"}},
{"Grotle", "Monster", "Grass", {"Torterra"}},
{"Torterra", "Monster", "Grass", {}},
{"Chimchar", "Field", "Human-Like", {"Monferno"}},
{"Monferno", "Field", "Human-Like", {"Infernape"}},
{"Infernape", "Field", "Human-Like", {}},
{"Piplup", "Water 1", "Field", {"Prinplup"}},
{"Prinplup", "Water 1", "Field", {"Empoleon"}},
{"Empoleon", "Water 1", "Field", {}},
{"Starly", "Flying", "Flying", {"Staravia"}},
{"Staravia", "Flying", "Flying", {"Staraptor"}},
{"Staraptor", "Flying", "Flying", {}},
{"Bidoof", "Water 1", "Field", {"Bibarel"}},
{"Bibarel", "Water 1", "Field", {}},
{"Kricketot", "Bug", "Bug", {"Kricketune"}},
{"Kricketune", "Bug", "Bug", {}},
{"Shinx", "Field", "Field", {"Luxio"}},
{"Luxio", "Field", "Field", {"Luxray"}},
{"Luxray", "Field", "Field", {}},
{"Cranidos", "Monster", "Monster", {"Rampardos"}},
{"Rampardos", "Monster", "Monster", {}},
{"Shieldon", "Monster", "Monster", {"Bastiodon"}},
{"Bastiodon", "Monster", "Monster", {}},
{"Burmy", "Bug", "Bug", {"Wormadam", "Mothim"}},
{"Wormadam", "Bug", "Bug", {}},
{"Mothim", "Bug", "Bug", {}},
{"Combee", "Bug", "Bug", {"Vespiquen"}},
{"Vespiquen", "Bug", "Bug", {}},
{"Pachirisu", "Field", "Fairy", {}},
{"Buizel", "Water 1", "Field", {"Floatzel"}},
{"Floatzel", "Water 1", "Field", {}},
{"Cherubi", "Fairy", "Grass", {"Cherrim"}},
{"Cherrim", "Fairy", "Grass", {}},
{"Shellos", "Water 1", "Amorphous", {"Gastrodon"}},
{"Gastrodon", "Water 1", "Amorphous", {}},
{"Drifloon", "Amorphous", "Amorphous", {"Drifblim"}},
{"Drifblim", "Amorphous", "Amorphous", {}},
{"Buneary", "Field", "Human-Like", {"Lopunny"}},
{"Lopunny", "Field", "Human-Like", {}},
{"Glameow", "Field", "Field", {"Purugly"}},
{"Purugly", "Field", "Field", {}},
{"Stunky", "Field", "Field", {"Skuntank"}},
{"Skuntank", "Field", "Field", {}},
{"Bronzor", "Mineral", "Mineral", {"Bronzong"}},
{"Bronzong", "Mineral", "Mineral", {}},
{"Chatot", "Flying", "Flying", {}},
{"Spiritomb", "Amorphous", "Amorphous", {}},
{"Gible", "Monster", "Dragon", {"Gabite"}},
{"Gabite", "Monster", "Dragon", {"Garchomp"}},
{"Garchomp", "Monster", "Dragon", {}},
{"Riolu", "No Eggs Discovered", "No Eggs Discovered", {"Lucario"}},
{"Lucario", "Field", "Human-Like", {}},
{"Hippopotas", "Field", "Field", {"Hippowdon"}},
{"Hippowdon", "Field", "Field", {}},
{"Skorupi", "Bug", "Water 3", {"Drapion"}},
{"Drapion", "Bug", "Water 3", {}},
{"Croagunk", "Human-Like", "Human-Like", {"Toxicroak"}},
{"Toxicroak", "Human-Like", "Human-Like", {}},
{"Carnivine", "Grass", "Grass", {}},
{"Finneon", "Water 2", "Water 2", {"Lumineon"}},
{"Lumineon", "Water 2", "Water 2", {}},
{"Snover", "Monster", "Grass", {"Abomasnow"}},
{"Abomasnow", "Monster", "Grass", {}},
{"Rotom", "Amorphous", "Amorphous", {}},
{"Uxie", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Mesprit", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Azelf", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Dialga", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Palkia", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Heatran", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Regigigas", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Giratina", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Cresselia", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Phione", "Water 1", "Fairy", {}},
{"Manaphy", "Water 1", "Fairy", {}},
{"Darkrai", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Shaymin", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Arceus", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Victini", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Snivy", "Field", "Grass", {}},
{"Servine", "Field", "Grass", {"Servine"}},
{"Serperior", "Field", "Grass", {"Serperior"}},
{"Tepig", "Field", "Field", {"Pignite"}},
{"Pignite", "Field", "Field", {"Emboar"}},
{"Emboar", "Field", "Field", {}},
{"Oshawott", "Field", "Field", {"Dewott"}},
{"Dewott", "Field", "Field", {"Samurott"}},
{"Samurott", "Field", "Field", {}},
{"Patrat", "Field", "Field", {"Watchog"}},
{"Watchog", "Field", "Field", {}},
{"Lillipup", "Field", "Field", {"Herdier"}},
{"Herdier", "Field", "Field", {"Stoutland"}},
{"Stoutland", "Field", "Field", {}},
{"Purrloin", "Field", "Field", {"Liepard"}},
{"Liepard", "Field", "Field", {}},
{"Pansage", "Field", "Field", {"Simisage"}},
{"Simisage", "Field", "Field", {}},
{"Pansear", "Field", "Field", {"Simisear"}},
{"Simisear", "Field", "Field", {}},
{"Panpour", "Field", "Field", {"Simipour"}},
{"Simipour", "Field", "Field", {}},
{"Munna", "Field", "Field", {"Musharna"}},
{"Musharna", "Field", "Field", {}},
{"Pidove", "Flying", "Flying", {"Tranquill"}},
{"Tranquill", "Flying", "Flying", {"Unfezant"}},
{"Unfezant", "Flying", "Flying", {}},
{"Blitzle", "Field", "Field", {"Zebstrika"}},
{"Zebstrika", "Field", "Field", {}},
{"Roggenrola", "Mineral", "Mineral", {"Boldore"}},
{"Boldore", "Mineral", "Mineral", {"Gigalith"}},
{"Gigalith", "Mineral", "Mineral", {}},
{"Woobat", "Field", "Flying", {"Swoobat"}},
{"Swoobat", "Field", "Flying", {}},
{"Drilbur", "Field", "Field", {"Excadrill"}},
{"Excadrill", "Field", "Field", {}},
{"Audino", "Fairy", "Fairy", {}},
{"Timburr", "Human-Like", "Human-Like", {"Gurdurr"}},
{"Gurdurr", "Human-Like", "Human-Like", {"Conkeldurr"}},
{"Conkeldurr", "Human-Like", "Human-Like", {}},
{"Tympole", "Water 1", "Water 1", {"Palpitoad"}},
{"Palpitoad", "Water 1", "Water 1", {"Seismitoad"}},
{"Seismitoad", "Water 1", "Water 1", {}},
{"Throh", "Human-Like", "Human-Like", {}},
{"Sawk", "Human-Like", "Human-Like", {}},
{"Sewaddle", "Bug", "Bug", {"Swadloon"}},
{"Swadloon", "Bug", "Bug", {"Leavanny"}},
{"Leavanny", "Bug", "Bug", {}},
{"Venipede", "Bug", "Bug", {"Whirlipede"}},
{"Whirlipede", "Bug", "Bug", {"Scolipede"}},
{"Scolipede", "Bug", "Bug", {}},
{"Cottonee", "Grass", "Fairy", {}},
{"Whimsicott", "Grass", "Fairy", {"Petilil"}},
{"Petilil", "Grass", "Grass", {"Lilligant"}},
{"Lilligant", "Grass", "Grass", {}},
{"Basculin", "Water 2", "Water 2", {"Basculegion"}},
{"Basculegion", "Water 2", "Water 2", {}},
{"Sandile", "Field", "Field", {"Krokorok"}},
{"Krokorok", "Field", "Field", {"Krookodile"}},
{"Krookodile", "Field", "Field", {}},
{"Darumaka", "Field", "Field", {"Darmanitan"}},
{"Darmanitan", "Field", "Field", {}},
{"Maractus", "Grass", "Grass", {}},
{"Dwebble", "Bug", "Mineral", {"Crustle"}},
{"Crustle", "Bug", "Mineral", {}},
{"Scraggy", "Field", "Dragon", {"Scrafty"}},
{"Scrafty", "Field", "Dragon", {}},
{"Sigilyph", "Flying", "Flying", {}},
{"Yamask", "Mineral", "Amorphous", {"Cofagrigus", "Runerigus"}},
{"Cofagrigus", "Mineral", "Amorphous", {}},
{"Runerigus", "Mineral", "Amorphous", {}},
{"Tirtouga", "Water 1", "Water 3", {"Carracosta"}},
{"Carracosta", "Water 1", "Water 3", {}},
{"Archen", "Flying", "Water 3", {"Archeops"}},
{"Archeops", "Flying", "Water 3", {}},
{"Trubbish", "Mineral", "Mineral", {"Garbodor"}},
{"Garbodor", "Mineral", "Mineral", {}},
{"Zorua", "Field", "Field", {"Zoroark"}},
{"Zoroark", "Field", "Field", {}},
{"Minccino", "Field", "Field", {"Cinccino"}},
{"Cinccino", "Field", "Field", {}},
{"Gothita", "Human-Like", "Human-Like", {"Gothorita"}},
{"Gothorita", "Human-Like", "Human-Like", {"Gothitelle"}},
{"Gothitelle", "Human-Like", "Human-Like", {}},
{"Solosis", "Amorphous", "Amorphous", {"Duosion"}},
{"Duosion", "Amorphous", "Amorphous", {"Reuniclus"}},
{"Reuniclus", "Amorphous", "Amorphous", {}},
{"Ducklett", "Water 1", "Flying", {"Swanna"}},
{"Swanna", "Water 1", "Flying", {}},
{"Vanillite", "Mineral", "Mineral", {"Vanillish"}},
{"Vanillish", "Mineral", "Mineral", {"Vanilluxe"}},
{"Vanilluxe", "Mineral", "Mineral", {}},
{"Deerling", "Field", "Field", {"Sawsbuck"}},
{"Sawsbuck", "Field", "Field", {}},
{"Emolga", "Field", "Field", {}},
{"Karrablast", "Bug", "Bug", {"Escavalier"}},
{"Escavalier", "Bug", "Bug", {}},
{"Foongus", "Grass", "Grass", {"Amoonguss"}},
{"Amoonguss", "Grass", "Grass", {}},
{"Frillish", "Amorphous", "Amorphous", {"Jellicent"}},
{"Jellicent", "Amorphous", "Amorphous", {}},
{"Alomomola", "Water 1", "Water 2", {}},
{"Joltik", "Bug", "Bug", {"Galvantula"}},
{"Galvantula", "Bug", "Bug", {}},
{"Ferroseed", "Grass", "Mineral", {"Ferrothorn"}},
{"Ferrothorn", "Grass", "Mineral", {}},
{"Klink", "Mineral", "Mineral", {"Klang"}},
{"Klang", "Mineral", "Mineral", {"Klinklang"}},
{"Klinklang", "Mineral", "Mineral", {}},
{"Tynamo", "Amorphous", "Amorphous", {"Eelektrik"}},
{"Eelektrik", "Amorphous", "Amorphous", {"Eelektross"}},
{"Eelektross", "Amorphous", "Amorphous", {}},
{"Elgyem", "Human-Like", "Human-Like", {"Beheeyem"}},
{"Beheeyem", "Human-Like", "Human-Like", {}},
{"Litwick", "Amorphous", "Amorphous", {"Lampent"}},
{"Lampent", "Amorphous", "Amorphous", {"Chandelure"}},
{"Chandelure", "Amorphous", "Amorphous", {}},
{"Axew", "Monster", "Dragon", {"Fraxure"}},
{"Fraxure", "Monster", "Dragon", {"Haxorus"}},
{"Haxorus", "Monster", "Dragon", {}},
{"Cubchoo", "Field", "Field", {"Beartic"}},
{"Beartic", "Field", "Field", {}},
{"Cryogonal", "Mineral", "Mineral", {}},
{"Shelmet", "Bug", "Bug", {"Accelgor"}},
{"Accelgor", "Bug", "Bug", {}},
{"Stunfisk", "Water 1", "Amorphous", {}},
{"Mienfoo", "Field", "Human-Like", {"Mienshao"}},
{"Mienshao", "Field", "Human-Like", {}},
{"Druddigon", "Dragon", "Monster", {}},
{"Golett", "Mineral", "Mineral", {"Golurk"}},
{"Golurk", "Mineral", "Mineral", {}},
{"Pawniard", "Human-Like", "Human-Like", {"Bisharp"}},
{"Bisharp", "Human-Like", "Human-Like", {}},
{"Bouffalant", "Field", "Field", {}},
{"Rufflet", "Flying", "Flying", {"Braviary"}},
{"Braviary", "Flying", "Flying", {}},
{"Vullaby", "Flying", "Flying", {"Mandibuzz"}},
{"Mandibuzz", "Flying", "Flying", {}},
{"Heatmor", "Field", "Field", {}},
{"Durant", "Bug", "Bug", {}},
{"Deino", "Dragon", "Dragon", {"Zweilous"}},
{"Zweilous", "Dragon", "Dragon", {"Hydreigon"}},
{"Hydreigon", "Dragon", "Dragon", {}},
{"Larvesta", "Bug", "Bug", {"Volcarona"}},
{"Volcarona", "Bug", "Bug", {}},
{"Cobalion", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Terrakion", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Virizion", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Tornadus", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Thundurus", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Reshiram", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Zekrom", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Landorus", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Kyurem", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Keldeo", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Meloetta", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Genesect", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Chespin", "Field", "Field", {"Quilladin"}},
{"Quilladin", "Field", "Field", {"Chesnaught"}},
{"Chesnaught", "Field", "Field", {}},
{"Fennekin", "Field", "Field", {"Braixen"}},
{"Braixen", "Field", "Field", {"Delphox"}},
{"Delphox", "Field", "Field", {}},
{"Froakie", "Water 1", "Water 1", {"Frogadier"}},
{"Frogadier", "Water 1", "Water 1", {"Greninja"}},
{"Greninja", "Water 1", "Water 1", {}},
{"Bunnelby", "Field", "Field", {"Diggersby"}},
{"Diggersby", "Field", "Field", {}},
{"Fletchling", "Flying", "Flying", {"Fletchinder"}},
{"Fletchinder", "Flying", "Flying", {"Talonflame"}},
{"Talonflame", "Flying", "Flying", {}},
{"Scatterbug", "Bug", "Bug", {"Spewpa"}},
{"Spewpa", "Bug", "Bug", {"Vivillon"}},
{"Vivillon", "Bug", "Bug", {}},
{"Litleo", "Field", "Field", {"Pyroar"}},
{"Pyroar", "Field", "Field", {}},
{"Flabebe", "Fairy", "Fairy", {"Floette"}},
{"Floette", "Fairy", "Fairy", {"Florges"}},
{"Florges", "Fairy", "Fairy", {}},
{"Skiddo", "Field", "Field", {"Gogoat"}},
{"Gogoat", "Field", "Field", {}},
{"Pancham", "Field", "Human-Like", {"Pangoro"}},
{"Pangoro", "Field", "Human-Like", {}},
{"Furfrou", "Field", "Field", {}},
{"Espurr", "Field", "Field", {"Meowstic"}},
{"Meowstic", "Field", "Field", {}},
{"Honedge", "Mineral", "Mineral", {"Doublade"}},
{"Doublade", "Mineral", "Mineral", {"Aegislash"}},
{"Aegislash", "Mineral", "Mineral", {}},
{"Spritzee", "Fairy", "Fairy", {"Aromatisse"}},
{"Aromatisse", "Fairy", "Fairy", {}},
{"Swirlix", "Fairy", "Fairy", {"Slurpuff"}},
{"Slurpuff", "Fairy", "Fairy", {}},
{"Inkay", "Water 1", "Water 2", {"Malamar"}},
{"Malamar", "Water 1", "Water 2", {}},
{"Binacle", "Water 3", "Water 3", {"Barbaracle"}},
{"Barbaracle", "Water 3", "Water 3", {}},
{"Skrelp", "Water 1", "Dragon", {"Dragalge"}},
{"Dragalge", "Water 1", "Dragon", {}},
{"Clauncher", "Water 1", "Water 3", {"Clawitzer"}},
{"Clawitzer", "Water 1", "Water 3", {}},
{"Helioptile", "Monster", "Dragon", {"Heliolisk"}},
{"Heliolisk", "Monster", "Dragon", {}},
{"Tyrunt", "Monster", "Dragon", {"Tyrantrum"}},
{"Tyrantrum", "Monster", "Dragon", {}},
{"Amaura", "Monster", "Monster", {"Aurorus"}},
{"Aurorus", "Monster", "Monster", {}},
{"Hawlucha", "Flying", "Human-Like", {}},
{"Dedenne", "Field", "Fairy", {}},
{"Carbink", "Fairy", "Mineral", {}},
{"Goomy", "Dragon", "Dragon", {"Sliggoo"}},
{"Sliggoo", "Dragon", "Dragon", {"Goodra"}},
{"Goodra", "Dragon", "Dragon", {}},
{"Klefki", "Mineral", "Mineral", {}},
{"Phantump", "Grass", "Amorphous", {"Trevenant"}},
{"Trevenant", "Grass", "Amorphous", {}},
{"Pumpkaboo", "Amorphous", "Amorphous", {"Gourgeist"}},
{"Gourgeist", "Amorphous", "Amorphous", {}},
{"Bergmite", "Monster", "Mineral", {"Avalugg"}},
{"Avalugg", "Monster", "Mineral", {}},
{"Noibat", "Flying", "Dragon", {"Noivern"}},
{"Noivern", "Flying", "Dragon", {}},
{"Xerneas", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Yveltal", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Zygarde", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Diancie", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Hoopa", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Volcanion", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Rowlet", "Flying", "Flying", {"Dartrix"}},
{"Dartrix", "Flying", "Flying", {"Decidueye"}},
{"Decidueye", "Flying", "Flying", {}},
{"Litten", "Field", "Field", {"Torracat"}},
{"Torracat", "Field", "Field", {"Incineroar"}},
{"Incineroar", "Field", "Field", {}},
{"Popplio", "Water 1", "Field", {"Brionne"}},
{"Brionne", "Water 1", "Field", {"Primarina"}},
{"Primarina", "Water 1", "Field", {}},
{"Pikipek", "Flying", "Flying", {"Trumbeak"}},
{"Trumbeak", "Flying", "Flying", {"Toucannon"}},
{"Toucannon", "Flying", "Flying", {}},
{"Yungoos", "Field", "Field", {"Gumshoos"}},
{"Gumshoos", "Field", "Field", {}},
{"Grubbin", "Bug", "Bug", {"Charjabug"}},
{"Charjabug", "Bug", "Bug", {"Vikavolt"}},
{"Vikavolt", "Bug", "Bug", {}},
{"Crabrawler", "Water 3", "Water 3", {"Crabominable"}},
{"Crabominable", "Water 3", "Water 3", {}},
{"Oricorio", "Flying", "Flying", {}},
{"Cutiefly", "Bug", "Fairy", {"Ribombee"}},
{"Ribombee", "Bug", "Fairy", {}},
{"Rockruff", "Field", "Field", {"Lycanroc"}},
{"Lycanroc", "Field", "Field", {}},
{"Wishiwashi", "Water 2", "Water 2", {}},
{"Mareanie", "Water 1", "Water 1", {"Toxapex"}},
{"Toxapex", "Water 1", "Water 1", {}},
{"Mudbray", "Field", "Field", {"Mudsdale"}},
{"Mudsdale", "Field", "Field", {}},
{"Dewpider", "Water 1", "Bug", {"Araquanid"}},
{"Araquanid", "Water 1", "Bug", {}},
{"Fomantis", "Grass", "Grass", {"Lurantis"}},
{"Lurantis", "Grass", "Grass", {}},
{"Morelull", "Grass", "Grass", {"Shiinotic"}},
{"Shiinotic", "Grass", "Grass", {}},
{"Salandit", "Monster", "Dragon", {"Salazzle"}},
{"Salazzle", "Monster", "Dragon", {}},
{"Stufful", "Field", "Field", {"Bewear"}},
{"Bewear", "Field", "Field", {}},
{"Bounsweet", "Grass", "Grass", {"Steenee"}},
{"Steenee", "Grass", "Grass", {"Tsareena"}},
{"Tsareena", "Grass", "Grass", {}},
{"Comfey", "Grass", "Grass", {}},
{"Oranguru", "Field", "Field", {"Passimian"}},
{"Passimian", "Field", "Field", {}},
{"Wimpod", "Bug", "Water 3", {"Golisopod"}},
{"Golisopod", "Bug", "Water 3", {}},
{"Sandygast", "Amorphous", "Amorphous", {"Palossand"}},
{"Palossand", "Amorphous", "Amorphous", {}},
{"Pyukumuku", "Water 1", "Water 1", {}},
{"Type: Null", "No Eggs Discovered", "No Eggs Discovered", {"Silvally"}},
{"Silvally", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Minior", "Mineral", "Mineral", {}},
{"Komala", "Field", "Field", {}},
{"Turtonator", "Monster", "Dragon", {}},
{"Togedemaru", "Field", "Fairy", {}},
{"Mimikyu", "Amorphous", "Amorphous", {}},
{"Bruxish", "Water 2", "Water 2", {}},
{"Drampa", "Monster", "Dragon", {}},
{"Dhelmise", "Mineral", "Mineral", {}},
{"Jangmo-o", "Dragon", "Dragon", {"Hakamo-o"}},
{"Hakamo-o", "Dragon", "Dragon", {"Kommo-o"}},
{"Kommo-o", "Dragon", "Dragon", {}},
{"Tapu Koko", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Tapu Lele", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Tapu Bulu", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Tapu Fini", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Cosmog", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Cosmoem", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Solgaleo", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Lunala", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Nihilego", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Buzzwole", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Pheromosa", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Xurkitree", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Celesteela", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Kartana", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Guzzlord", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Necrozma", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Magearna", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Marshadow", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Poipole", "No Eggs Discovered", "No Eggs Discovered", {"Naganadel"}},
{"Naganadel", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Stakataka", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Blacephalon", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Zeraora", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Grookey", "Field", "Grass", {"Thwackey"}},
{"Thwackey", "Field", "Grass", {"Rillaboom"}},
{"Rillaboom", "Field", "Grass", {}},
{"Scorbunny", "Field", "Human-Like", {"Raboot"}},
{"Raboot", "Field", "Human-Like", {"Cinderace"}},
{"Cinderace", "Field", "Human-Like", {}},
{"Sobble", "Water 1", "Field", {"Drizzile"}},
{"Drizzile", "Water 1", "Field", {"Inteleon"}},
{"Inteleon", "Water 1", "Field", {}},
{"Skwovet", "Field", "Field", {"Greedent"}},
{"Greedent", "Field", "Field", {}},
{"Rookidee", "Flying", "Flying", {"Corvisquire"}},
{"Corvisquire", "Flying", "Flying", {"Corviknight"}},
{"Corviknight", "Flying", "Flying", {}},
{"Blipbug", "Bug", "Bug", {"Dottler"}},
{"Dottler", "Bug", "Bug", {"Orbeetle"}},
{"Orbeetle", "Bug", "Bug", {}},
{"Nickit", "Field", "Field", {"Thievul"}},
{"Thievul", "Field", "Field", {}},
{"Gossifleur", "Grass", "Grass", {"Eldegoss"}},
{"Eldegoss", "Grass", "Grass", {}},
{"Wooloo", "Field", "Field", {"Dubwool"}},
{"Dubwool", "Field", "Field", {}},
{"Chewtle", "Monster", "Water 1", {"Drednaw"}},
{"Drednaw", "Monster", "Water 1", {}},
{"Yamper", "Field", "Field", {"Boltund"}},
{"Boltund", "Field", "Field", {}},
{"Rolycoly", "Mineral", "Mineral", {"Carkol"}},
{"Carkol", "Mineral", "Mineral", {"Coalossal"}},
{"Coalossal", "Mineral", "Mineral", {}},
{"Applin", "Grass", "Dragon", {"Flapple", "Appletun"}},
{"Flapple", "Grass", "Dragon", {}},
{"Appletun", "Grass", "Dragon", {}},
{"Silicobra", "Field", "Dragon", {"Sandaconda"}},
{"Sandaconda", "Field", "Dragon", {}},
{"Cramorant", "Water 1", "Flying", {}},
{"Arrokuda", "Water 2", "Water 2", {"Barraskewda"}},
{"Barraskewda", "Water 2", "Water 2", {}},
{"Toxel", "No Eggs Discovered", "No Eggs Discovered", {"Toxtricity"}},
{"Toxtricity", "Human-Like", "Human-Like", {}},
{"Sizzlipede", "Bug", "Bug", {"Centiskorch"}},
{"Centiskorch", "Bug", "Bug", {}},
{"Clobbopus", "Water 1", "Human-Like", {"Grapploct"}},
{"Grapploct", "Water 1", "Human-Like", {}},
{"Sinistea", "Mineral", "Amorphous", {"Polteageist"}},
{"Polteageist", "Mineral", "Amorphous", {}},
{"Hatenna", "Fairy", "Fairy", {"Hattrem"}},
{"Hattrem", "Fairy", "Fairy", {"Hatterene"}},
{"Hatterene", "Fairy", "Fairy", {}},
{"Impidimp", "Fairy", "Human-Like", {"Morgrem"}},
{"Morgrem", "Fairy", "Human-Like", {"Grimmsnarl"}},
{"Grimmsnarl", "Fairy", "Human-Like", {}},
{"Milcery", "Fairy", "Amorphous", {"Alcremie"}},
{"Alcremie", "Fairy", "Amorphous", {}},
{"Falinks", "Fairy", "Mineral", {}},
{"Pincurchin", "Water 1", "Amorphous", {}},
{"Snom", "Bug", "Bug", {"Frosmoth"}},
{"Frosmoth", "Bug", "Bug", {}},
{"Stonjourner", "Mineral", "Mineral", {}},
{"Eiscue", "Water 1", "Field", {}},
{"Indeedee", "Fairy", "Fairy", {}},
{"Morpeko", "Field", "Fairy", {}},
{"Cufant", "Field", "Mineral", {"Copperajah"}},
{"Copperajah", "Field", "Mineral", {}},
{"Dracozolt", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Arctozolt", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Dracovish", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Arctovish", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Duraludon", "Mineral", "Dragon", {}},
{"Dreepy", "Amorphous", "Dragon", {"Drakloak"}},
{"Drakloak", "Amorphous", "Dragon", {"Dragapult"}},
{"Dragapult", "Amorphous", "Dragon", {}},
{"Zacian", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Zamazenta", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Eternatus", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Kubfu", "No Eggs Discovered", "No Eggs Discovered", {"Urshifu"}},
{"Urshifu", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Zarude", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Regieleki", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Regidrago", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Glastrier", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Spectrier", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Calyrex", "No Eggs Discovered", "No Eggs Discovered", {}},
{"Enamorus", "No Eggs Discovered", "No Eggs Discovered", {}}
}
};